// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/feedback/statusIndicator/StatusIndicator.vue
<script lang="ts">
import type { StatusTone } from '../../../foundation/utils';

export interface StatusIndicatorProps {
  /** The semantic status tone. */
  tone?: StatusTone;

  /**
   * The bold first-line label (e.g. "All systems normal"). Rich content → the
   * `label` slot. Required in React; optional here so the slot form is usable —
   * supply one or the other.
   */
  label?: string;

  /** The smaller secondary line (e.g. "Updated 2m ago"). Rich content → the `description` slot. */
  description?: string;

  /** The optional pulsing ring for "live" indication. */
  hasPulse?: boolean;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useSlots, useTemplateRef } from 'vue';
import { cn, StatusTone as StatusToneToken } from '../../../foundation/utils';

const TONE: Record<StatusTone, string> = {
  success: 'bg-success',
  warning: 'bg-warning',
  destructive: 'bg-destructive',
  info: 'bg-info',
  neutral: 'bg-muted-foreground',
};

/**
 * Two-line status indicator — colored dot + bold label + smaller helper.
 * Use on monitoring / status pages. For an inline single-line indicator use
 * `display/Status`.
 */
defineOptions({ name: 'StatusIndicator', inheritAttrs: false });

const props = withDefaults(defineProps<StatusIndicatorProps>(), { tone: StatusToneToken.Success });

const attrs = useAttrs();
const slots = useSlots();
const el = useTemplateRef<HTMLDivElement>('el');

const hasDescription = computed(() => Boolean(props.description) || Boolean(slots.description));

const dotClasses = computed(() => cn('inline-block h-2.5 w-2.5 rounded-full', TONE[props.tone]));

const pulseClasses = computed(() =>
  cn('absolute inset-0 inline-block rounded-full opacity-75 animate-ping', TONE[props.tone]),
);

const classes = computed(() =>
  cn('flex items-start gap-3', attrs.class as string | undefined),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <div ref="el" v-bind="rest" :class="classes">
    <span class="relative mt-1 inline-flex">
      <span :class="dotClasses" />
      <span v-if="props.hasPulse" :class="pulseClasses" />
    </span>
    <div class="min-w-0 flex-1">
      <div class="text-sm font-medium text-foreground">
        <slot name="label">{{ props.label }}</slot>
      </div>
      <div v-if="hasDescription" class="text-xs text-muted-foreground">
        <slot name="description">{{ props.description }}</slot>
      </div>
    </div>
  </div>
</template>

// src/presentation/feedback/statusIndicator/StatusIndicator.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from 'react';
import { cn, StatusTone } from '../../../foundation/utils';

export interface StatusIndicatorProps extends Omit<ComponentPropsWithoutRef<'div'>, 'title'> {
  /** The semantic status tone. */
  tone?: StatusTone;

  /** The bold first-line label (e.g. "All systems normal"). */
  label: ReactNode;

  /** The smaller secondary line (e.g. "Updated 2m ago"). */
  description?: ReactNode;

  /** The optional pulsing ring for "live" indication. */
  hasPulse?: boolean;
}

const TONE: Record<StatusTone, string> = {
  success: 'bg-success',
  warning: 'bg-warning',
  destructive: 'bg-destructive',
  info: 'bg-info',
  neutral: 'bg-muted-foreground',
};

/**
 * Two-line status indicator — colored dot + bold label + smaller helper.
 * Use on monitoring / status pages. For an inline single-line indicator use
 * `display/Status`.
 */
export const StatusIndicator = forwardRef<HTMLDivElement, StatusIndicatorProps>(
  ({ tone = StatusTone.Success, label, description, hasPulse, className, ...props }, ref) => (
    <div
      ref={ref}
      className={cn('flex items-start gap-3', className)}
      {...props}
    >
      <span className="relative mt-1 inline-flex">
        <span className={cn('inline-block h-2.5 w-2.5 rounded-full', TONE[tone])} />
        {hasPulse && (
          <span
            className={cn(
              'absolute inset-0 inline-block rounded-full opacity-75 animate-ping',
              TONE[tone],
            )}
          />
        )}
      </span>
      <div className="min-w-0 flex-1">
        <div className="text-sm font-medium text-foreground">{label}</div>
        {description && <div className="text-xs text-muted-foreground">{description}</div>}
      </div>
    </div>
  ),
);
StatusIndicator.displayName = 'StatusIndicator';
