// src/feedback/tour/Tour.tsx
import {
  useCallback,
  useEffect,
  useId,
  useState,
  type ReactNode,
  type RefObject,
} from 'react';
import { cn } from '../../utils';
import { useControlled } from '../../hooks';
import { Announce, Portal } from '../../primitives';

export interface TourStep {
  target: string | RefObject<HTMLElement>;
  title?: ReactNode;
  body?: ReactNode;
  placement?: 'top' | 'right' | 'bottom' | 'left';
}

export interface TourProps {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  steps: TourStep[];
  currentStep?: number;
  defaultCurrentStep?: number;
  onStepChange?: (i: number) => void;
  onComplete?: () => void;
  onSkip?: () => void;
  padding?: number;
}

interface Rect {
  top: number;
  left: number;
  width: number;
  height: number;
}

function rectFromTarget(target: TourStep['target']): Rect | null {
  let el: HTMLElement | null = null;
  if (typeof target === 'string') {
    el = document.querySelector(target);
  } else {
    el = target.current;
  }
  if (!el) return null;
  const r = el.getBoundingClientRect();
  return { top: r.top, left: r.left, width: r.width, height: r.height };
}

function placementCoords(rect: Rect, placement: NonNullable<TourStep['placement']>, gap = 12) {
  switch (placement) {
    case 'top':
      return { top: rect.top - gap, left: rect.left + rect.width / 2, transform: 'translate(-50%, -100%)' };
    case 'right':
      return { top: rect.top + rect.height / 2, left: rect.left + rect.width + gap, transform: 'translate(0, -50%)' };
    case 'bottom':
      return { top: rect.top + rect.height + gap, left: rect.left + rect.width / 2, transform: 'translate(-50%, 0)' };
    case 'left':
      return { top: rect.top + rect.height / 2, left: rect.left - gap, transform: 'translate(-100%, -50%)' };
  }
}

/**
 * Multi-step product tour. Renders an SVG mask with a cutout around each
 * step's target + a floating tooltip with Next / Prev / Skip / Done.
 */
export function Tour({
  open: openProp,
  defaultOpen = false,
  onOpenChange,
  steps,
  currentStep: currentStepProp,
  defaultCurrentStep = 0,
  onStepChange,
  onComplete,
  onSkip,
  padding = 8,
}: TourProps) {
  const [open, setOpen] = useControlled({
    controlled: openProp,
    default: defaultOpen,
    onChange: onOpenChange,
  });
  const [currentStep, setCurrentStep] = useControlled({
    controlled: currentStepProp,
    default: defaultCurrentStep,
    onChange: onStepChange,
  });

  const [rect, setRect] = useState<Rect | null>(null);
  const titleId = useId();
  const descId = useId();

  const step = steps[currentStep];

  // Update rect when step changes / window scrolls / resizes.
  useEffect(() => {
    if (!open || !step) return;

    const update = () => {
      const r = rectFromTarget(step.target);
      setRect(r);
    };
    // Defer to next frame so the target can mount / scroll into view.
    const handle = requestAnimationFrame(update);

    window.addEventListener('resize', update, { passive: true });
    window.addEventListener('scroll', update, { passive: true, capture: true });
    return () => {
      cancelAnimationFrame(handle);
      window.removeEventListener('resize', update);
      window.removeEventListener('scroll', update, true);
    };
  }, [open, step]);

  // Escape handling.
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        setOpen(false);
        onSkip?.();
      }
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, setOpen, onSkip]);

  const goNext = useCallback(() => {
    if (currentStep >= steps.length - 1) {
      setOpen(false);
      onComplete?.();
    } else {
      setCurrentStep(currentStep + 1);
    }
  }, [currentStep, steps.length, setOpen, setCurrentStep, onComplete]);

  const goPrev = useCallback(() => {
    if (currentStep > 0) setCurrentStep(currentStep - 1);
  }, [currentStep, setCurrentStep]);

  const skip = useCallback(() => {
    setOpen(false);
    onSkip?.();
  }, [setOpen, onSkip]);

  if (!open || !step) return null;

  const placement = step.placement ?? 'bottom';
  const tooltipCoords = rect ? placementCoords(rect, placement) : null;
  const cutoutPadding = padding;

  return (
    <Portal>
      {/* SVG mask backdrop with cutout around target */}
      <svg
        aria-hidden="true"
        className="pointer-events-auto fixed inset-0 z-50 h-full w-full"
        xmlns="http://www.w3.org/2000/svg"
      >
        <defs>
          <mask id="tour-mask">
            <rect width="100%" height="100%" fill="white" />
            {rect && (
              <rect
                x={rect.left - cutoutPadding}
                y={rect.top - cutoutPadding}
                width={rect.width + cutoutPadding * 2}
                height={rect.height + cutoutPadding * 2}
                rx={6}
                fill="black"
              />
            )}
          </mask>
        </defs>
        <rect
          width="100%"
          height="100%"
          fill="rgba(0,0,0,0.55)"
          mask="url(#tour-mask)"
        />
      </svg>

      {/* Tooltip */}
      {tooltipCoords && (
        <div
          role="dialog"
          aria-modal="false"
          aria-labelledby={titleId}
          aria-describedby={descId}
          style={{
            position: 'fixed',
            top: tooltipCoords.top,
            left: tooltipCoords.left,
            transform: tooltipCoords.transform,
            zIndex: 60,
          }}
          className={cn(
            'w-72 rounded-md border border-border bg-popover p-4 text-popover-foreground shadow-lg outline-none animate-in fade-in-0 zoom-in-95',
          )}
        >
          {step.title && (
            <div id={titleId} className="text-sm font-semibold">
              {step.title}
            </div>
          )}
          {step.body && (
            <div id={descId} className={cn('text-sm text-muted-foreground', step.title && 'mt-1.5')}>
              {step.body}
            </div>
          )}
          <div className="mt-3 flex items-center justify-between gap-3">
            <span className="text-xs text-muted-foreground">
              {currentStep + 1} / {steps.length}
            </span>
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={skip}
                className="text-xs text-muted-foreground hover:text-foreground"
              >
                Skip
              </button>
              {currentStep > 0 && (
                <button
                  type="button"
                  onClick={goPrev}
                  className="inline-flex h-7 items-center rounded-md border border-border bg-background px-2.5 text-xs font-medium hover:bg-muted"
                >
                  Back
                </button>
              )}
              <button
                type="button"
                onClick={goNext}
                className="inline-flex h-7 items-center rounded-md bg-primary px-2.5 text-xs font-medium text-primary-foreground hover:bg-primary/90"
              >
                {currentStep >= steps.length - 1 ? 'Done' : 'Next'}
              </button>
            </div>
          </div>
        </div>
      )}

      <Announce politeness="polite">
        {step.title
          ? `Step ${currentStep + 1} of ${steps.length}: ${typeof step.title === 'string' ? step.title : ''}`
          : ''}
      </Announce>
    </Portal>
  );
}

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/feedback/tour/Tour.vue
<script lang="ts">
import type { Ref } from 'vue';

/** Defines the side a Tour tooltip is placed on, relative to its target. */
export const Placement = {
  /** Refers to placement above the target. */
  Top: 'top',
  /** Refers to placement to the right of the target. */
  Right: 'right',
  /** Refers to placement below the target. */
  Bottom: 'bottom',
  /** Refers to placement to the left of the target. */
  Left: 'left',
} as const;

export type Placement = (typeof Placement)[keyof typeof Placement];

export interface TourStep {
  /** A CSS selector, or a template ref holding the element to spotlight. */
  target: string | Ref<HTMLElement | null>;
  title?: string;
  body?: string;
  placement?: Placement;
}

export interface TourProps {
  isOpen?: boolean;
  defaultOpen?: boolean;
  steps: ReadonlyArray<TourStep>;
  currentStep?: number;
  defaultCurrentStep?: number;
  padding?: number;
}
</script>

<script setup lang="ts">
import { computed, ref, shallowRef, watch } from 'vue';
import { cn, Key } from '../../../foundation/utils';
import { useControlled, useId, useReducedMotion } from '../../../foundation/hooks';
import { Announce, Portal, Presence } from '../../../foundation/primitives';

interface Rect {
  top: number;
  left: number;
  width: number;
  height: number;
}

function rectFromTarget(target: TourStep['target']): Rect | null {
  const el = typeof target === 'string' ? document.querySelector<HTMLElement>(target) : target.value;
  if (!el) return null;
  const r = el.getBoundingClientRect();
  return { top: r.top, left: r.left, width: r.width, height: r.height };
}

function placementCoords(rect: Rect, placement: NonNullable<TourStep['placement']>, gap = 12) {
  switch (placement) {
    case Placement.Top:
      return { top: rect.top - gap, left: rect.left + rect.width / 2, transform: 'translate(-50%, -100%)' };
    case Placement.Right:
      return { top: rect.top + rect.height / 2, left: rect.left + rect.width + gap, transform: 'translate(0, -50%)' };
    case Placement.Bottom:
      return { top: rect.top + rect.height + gap, left: rect.left + rect.width / 2, transform: 'translate(-50%, 0)' };
    case Placement.Left:
      return { top: rect.top + rect.height / 2, left: rect.left - gap, transform: 'translate(-100%, -50%)' };
  }
}

/**
 * Multi-step product tour. Renders an SVG mask with a cutout around each
 * step's target + a floating tooltip with Next / Prev / Skip / Done.
 *
 * `TourStep.title` / `.body` narrow React's `ReactNode` to `string`: steps are
 * plain data passed as a prop, not slot content, and the announcement already
 * required a string.
 */
defineOptions({ name: 'Tour', inheritAttrs: false });

const props = withDefaults(defineProps<TourProps>(), {
  defaultOpen: false,
  defaultCurrentStep: 0,
  padding: 8,
});

const emit = defineEmits<{
  /** Replaces React's `onOpenChange`. */
  'open-change': [open: boolean];
  /** Replaces React's `onStepChange`. */
  'step-change': [index: number];
  /** Replaces React's `onComplete`. Fires when Done is pressed on the last step. */
  complete: [];
  /** Replaces React's `onSkip`. Fires on Skip and on Escape. */
  skip: [];
}>();

const openCtl = useControlled<boolean>({
  controlled: () => props.isOpen,
  default: () => props.defaultOpen,
  onChange: (value) => emit('open-change', value),
});
const stepCtl = useControlled<number>({
  controlled: () => props.currentStep,
  default: () => props.defaultCurrentStep,
  onChange: (value) => emit('step-change', value),
});

const open = computed(() => openCtl.value.value);
const stepIndex = computed(() => stepCtl.value.value);

const rect = shallowRef<Rect | null>(null);
const titleId = useId('tour-title');
const descId = useId('tour-desc');
const maskId = useId('tour-mask');
const reducedMotion = useReducedMotion();

const step = computed(() => props.steps[stepIndex.value]);

/* Keep the Portal (scrim + tooltip) mounted while the pop-out plays — the
   component hard-unmounts on `!open`, which would kill the exit. Opening
   flips this true synchronously; closing defers the unmount until the
   tooltip's exit animation ends (`@animationend` below). Under reduced
   motion no animation fires, so drop it on the next frame instead. */
const mounted = ref(open.value);
watch(
  [open, reducedMotion],
  ([isOpen, isReduced], _previous, onCleanup) => {
    if (isOpen) {
      mounted.value = true;
      return;
    }
    if (!isReduced) return;
    const raf = requestAnimationFrame(() => {
      mounted.value = false;
    });
    onCleanup(() => cancelAnimationFrame(raf));
  },
  { immediate: true, flush: 'post' },
);

// Update rect when step changes / window scrolls / resizes.
watch(
  [open, step],
  ([isOpen, currentStepValue], _previous, onCleanup) => {
    if (!isOpen || !currentStepValue) return;

    const update = () => {
      rect.value = rectFromTarget(currentStepValue.target);
    };
    // Defer to next frame so the target can mount / scroll into view.
    const handle = requestAnimationFrame(update);

    window.addEventListener('resize', update, { passive: true });
    window.addEventListener('scroll', update, { passive: true, capture: true });
    onCleanup(() => {
      cancelAnimationFrame(handle);
      window.removeEventListener('resize', update);
      window.removeEventListener('scroll', update, true);
    });
  },
  { immediate: true, flush: 'post' },
);

// Escape handling.
watch(
  open,
  (isOpen, _previous, onCleanup) => {
    if (!isOpen) return;
    const onKey = (event: KeyboardEvent) => {
      if (event.key === Key.Escape) {
        event.preventDefault();
        openCtl.setValue(false);
        emit('skip');
      }
    };
    document.addEventListener('keydown', onKey);
    onCleanup(() => document.removeEventListener('keydown', onKey));
  },
  { immediate: true, flush: 'post' },
);

const goNext = () => {
  if (stepIndex.value >= props.steps.length - 1) {
    openCtl.setValue(false);
    emit('complete');
  } else {
    stepCtl.setValue(stepIndex.value + 1);
  }
};

const goPrev = () => {
  if (stepIndex.value > 0) stepCtl.setValue(stepIndex.value - 1);
};

const skip = () => {
  openCtl.setValue(false);
  emit('skip');
};

const placement = computed(() => step.value?.placement ?? Placement.Bottom);

const tooltipCoords = computed(() =>
  rect.value ? placementCoords(rect.value, placement.value) : null,
);

/** Vue does not auto-suffix numeric style values with `px` the way React does. */
const tooltipStyle = computed(() => {
  const coords = tooltipCoords.value;
  if (!coords) return undefined;
  return {
    position: 'fixed' as const,
    top: `${coords.top}px`,
    left: `${coords.left}px`,
    transform: coords.transform,
  };
});

const announcement = computed(() =>
  step.value?.title
    ? `Step ${stepIndex.value + 1} of ${props.steps.length}: ${step.value.title}`
    : '',
);

const bodyClasses = computed(() =>
  cn('text-sm text-muted-foreground', step.value?.title && 'mt-1.5'),
);

/**
 * `Presence` clones `data-state` onto this node, so the pop (fade + slight
 * scale) runs gated on that state. `motion-safe` so reduced-motion users get
 * no movement.
 */
const tooltipClasses = cn(
  'z-popover w-72 rounded-md border border-border bg-popover p-4 text-popover-foreground shadow-lg outline-none',
  'motion-safe:data-[state=open]:animate-(--animate-pop-in)',
  'motion-safe:data-[state=closed]:animate-(--animate-pop-out)',
  'motion-reduce:animate-none',
);

/** Drops the Portal once the exit animation completes. */
const onTooltipAnimationEnd = () => {
  if (!open.value) mounted.value = false;
};
</script>

<template>
  <Portal v-if="mounted && step">
    <!-- SVG mask backdrop with cutout around target. Skipped while the
         target is unresolvable so a bare scrim never blocks the page.
         Gated on `open` (not `mounted`) so the scrim clears immediately on
         close while the tooltip plays its pop-out before unmount. -->
    <svg
      v-if="open && rect"
      aria-hidden="true"
      class="pointer-events-auto fixed inset-0 z-modal h-full w-full"
      xmlns="http://www.w3.org/2000/svg"
    >
      <defs>
        <mask :id="maskId">
          <rect width="100%" height="100%" fill="white" />
          <rect
            :x="rect.left - props.padding"
            :y="rect.top - props.padding"
            :width="rect.width + props.padding * 2"
            :height="rect.height + props.padding * 2"
            :rx="6"
            fill="black"
          />
        </mask>
      </defs>
      <rect width="100%" height="100%" fill="rgba(0,0,0,0.55)" :mask="`url(#${maskId})`" />
    </svg>

    <!-- Tooltip — wrapped in `Presence` so its pop-out plays before the
         component unmounts. `Presence` clones `data-state` ("open" | "closed")
         onto the panel, so the pop tokens run gated on that state; the exit's
         `@animationend` drops `mounted`. -->
    <Presence v-if="tooltipCoords" :is-present="open">
      <div
        role="dialog"
        aria-modal="false"
        :aria-labelledby="titleId"
        :aria-describedby="descId"
        :style="tooltipStyle"
        :class="tooltipClasses"
        @animationend="onTooltipAnimationEnd"
      >
        <div v-if="step.title" :id="titleId" class="text-sm font-semibold">{{ step.title }}</div>
        <div v-if="step.body" :id="descId" :class="bodyClasses">{{ step.body }}</div>
        <div class="mt-3 flex items-center justify-between gap-3">
          <span class="text-xs text-muted-foreground">
            {{ stepIndex + 1 }} / {{ props.steps.length }}
          </span>
          <div class="flex items-center gap-2">
            <button
              type="button"
              class="text-xs text-muted-foreground hover:text-foreground"
              @click="skip"
            >
              Skip
            </button>
            <button
              v-if="stepIndex > 0"
              type="button"
              class="inline-flex h-7 items-center rounded-md border border-border bg-background px-2.5 text-xs font-medium hover:bg-muted"
              @click="goPrev"
            >
              Back
            </button>
            <button
              type="button"
              class="inline-flex h-7 items-center rounded-md bg-primary px-2.5 text-xs font-medium text-primary-foreground hover:bg-primary/90"
              @click="goNext"
            >
              {{ stepIndex >= props.steps.length - 1 ? 'Done' : 'Next' }}
            </button>
          </div>
        </div>
      </div>
    </Presence>

    <Announce politeness="polite">{{ announcement }}</Announce>
  </Portal>
</template>
