// src/presentation/forms/colorArea/ColorArea.tsx
import {
  forwardRef,
  useCallback,
  useRef,
  type CSSProperties,
  type HTMLAttributes,
  type KeyboardEvent,
  type PointerEvent as ReactPointerEvent,
} from 'react';
import { cn, composeRefs } from '../../../foundation/utils';
import { useControlled } from '../../../foundation/hooks';
import { clamp01, hsvToHex } from '../ColorExtensions';

export interface ColorAreaChange {
  saturation: number;
  value: number;
}

export interface ColorAreaProps
  extends Omit<HTMLAttributes<HTMLDivElement>, 'onChange' | 'defaultValue'> {
  hue?: number;
  saturation?: number;
  defaultSaturation?: number;
  value?: number;
  defaultValue?: number;
  onValueChange?: (next: ColorAreaChange) => void;
  step?: number;
  isDisabled?: boolean;
  'aria-label'?: string;
}

export const ColorArea = forwardRef<HTMLDivElement, ColorAreaProps>(function ColorArea(
  {
    hue = 0,
    saturation,
    defaultSaturation,
    value,
    defaultValue,
    onValueChange,
    step = 0.01,
    isDisabled = false,
    className,
    'aria-label': ariaLabel = 'Saturation and value',
    ...rest
  },
  forwardedRef,
) {
  const [s, setS] = useControlled<number>({
    controlled: saturation,
    default: defaultSaturation ?? 1,
  });
  const [v, setV] = useControlled<number>({
    controlled: value,
    default: defaultValue ?? 1,
  });

  const trackRef = useRef<HTMLDivElement | null>(null);

  const emit = useCallback(
    (nextS: number, nextV: number) => {
      const cs = clamp01(nextS);
      const cv = clamp01(nextV);
      setS(cs);
      setV(cv);
      onValueChange?.({ saturation: cs, value: cv });
    },
    [onValueChange, setS, setV],
  );

  const updateFromClient = useCallback(
    (clientX: number, clientY: number) => {
      const track = trackRef.current;
      if (!track) return;
      const rect = track.getBoundingClientRect();
      const xRatio = clamp01((clientX - rect.left) / rect.width);
      const yRatio = clamp01((clientY - rect.top) / rect.height);
      emit(xRatio, 1 - yRatio);
    },
    [emit],
  );

  const handlePointerDown = useCallback(
    (e: ReactPointerEvent<HTMLDivElement>) => {
      if (isDisabled) return;
      e.preventDefault();
      (e.target as Element).setPointerCapture?.(e.pointerId);
      updateFromClient(e.clientX, e.clientY);
    },
    [isDisabled, updateFromClient],
  );

  const handlePointerMove = useCallback(
    (e: ReactPointerEvent<HTMLDivElement>) => {
      if (isDisabled || e.buttons !== 1) return;
      updateFromClient(e.clientX, e.clientY);
    },
    [isDisabled, updateFromClient],
  );

  const handleKeyDown = useCallback(
    (e: KeyboardEvent<HTMLDivElement>) => {
      if (isDisabled) return;
      const big = step * 10;
      let nextS = s;
      let nextV = v;
      switch (e.key) {
        case 'ArrowRight':
          nextS = s + step;
          break;
        case 'ArrowLeft':
          nextS = s - step;
          break;
        case 'ArrowUp':
          nextV = v + step;
          break;
        case 'ArrowDown':
          nextV = v - step;
          break;
        case 'PageUp':
          nextV = v + big;
          break;
        case 'PageDown':
          nextV = v - big;
          break;
        case 'Home':
          nextS = 0;
          nextV = 1;
          break;
        case 'End':
          nextS = 1;
          nextV = 0;
          break;
        default:
          return;
      }
      e.preventDefault();
      emit(nextS, nextV);
    },
    [isDisabled, emit, s, step, v],
  );

  const baseColor = `hsl(${hue}, 100%, 50%)`;
  const trackStyle: CSSProperties = {
    backgroundImage: `linear-gradient(to bottom, transparent, #000), linear-gradient(to right, #fff, transparent)`,
    backgroundColor: baseColor,
  };

  const thumbColor = hsvToHex({ h: hue, s, v });
  const thumbStyle: CSSProperties = {
    left: `${s * 100}%`,
    top: `${(1 - v) * 100}%`,
    backgroundColor: thumbColor,
  };

  return (
    <div
      ref={composeRefs(forwardedRef, trackRef)}
      role="slider"
      tabIndex={isDisabled ? -1 : 0}
      aria-label={ariaLabel}
      aria-valuetext={`saturation ${(s * 100).toFixed(0)}%, value ${(v * 100).toFixed(0)}%`}
      aria-disabled={isDisabled || undefined}
      data-disabled={isDisabled ? '' : undefined}
      onPointerDown={handlePointerDown}
      onPointerMove={handlePointerMove}
      onKeyDown={handleKeyDown}
      style={trackStyle}
      className={cn(
        'relative aspect-square w-full select-none rounded-md border border-border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
        isDisabled && 'pointer-events-none opacity-50',
        className,
      )}
      {...rest}
    >
      <div
        aria-hidden="true"
        style={thumbStyle}
        className="absolute h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white shadow-md ring-1 ring-black/20"
      />
    </div>
  );
});

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/forms/colorArea/ColorArea.vue
<script lang="ts">
/** The saturation / value pair a `ColorArea` commits. */
export interface ColorAreaChange {
  saturation: number;
  value: number;
}

export interface ColorAreaProps {
  /** The hue the square is tinted with (0–360). */
  hue?: number;

  /** The saturation, controlled (0–1). The `v-model:saturation` binding target. */
  saturation?: number;

  /** The initial saturation when uncontrolled. */
  defaultSaturation?: number;

  /** The brightness/value, controlled (0–1). The `v-model:value` binding target. */
  value?: number;

  /** The initial value when uncontrolled. */
  defaultValue?: number;

  /** The arrow-key increment. `PageUp`/`PageDown` move ten steps. */
  step?: number;

  /** The disabled state. Falls back to the surrounding form control's `isDisabled`. */
  isDisabled?: boolean;

  /** The control's id. Auto-filled from `FormControl` context when omitted. */
  id?: string;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef, type StyleValue } from 'vue';
import type { ClassValue } from 'clsx';
import { cn } from '../../../foundation/utils';
import { useControlled } from '../../../foundation/hooks';
import { useFormControl } from '../../../foundation/primitives';
import { clamp01, hsvToHex } from '../ColorExtensions';

/**
 * Two-axis saturation / value square. Pointer-draggable and fully keyboard
 * operable as an ARIA `slider`.
 */
/* `inheritAttrs: false` so `class` folds into the component's own `cn()` call — plain fallthrough
   appends outside it and loses tailwind-merge conflict resolution. */
defineOptions({ name: 'ColorArea', inheritAttrs: false });

const props = withDefaults(defineProps<ColorAreaProps>(), {
  hue: 0,
  step: 0.01,
  /* Explicit `undefined` default: the flag falls back to the form control context, and Vue
     casts an absent `boolean` prop to `false` — which would shadow the context. */
  isDisabled: undefined,
});

const emit = defineEmits<{
  /** The `v-model:saturation` half. */
  'update:saturation': [value: number];
  /** The `v-model:value` half. */
  'update:value': [value: number];
  /**
   * Replaces React's `onValueChange`. Carries BOTH axes in one payload, as the React
   * original did — the two `update:*` emits above are the Vue `v-model` idiom beside it.
   */
  'value-change': [next: ColorAreaChange];
}>();

const attrs = useAttrs();

const saturationControlled = useControlled<number>({
  controlled: () => props.saturation,
  default: () => props.defaultSaturation ?? 1,
});
const valueControlled = useControlled<number>({
  controlled: () => props.value,
  default: () => props.defaultValue ?? 1,
});

const s = saturationControlled.value;
const v = valueControlled.value;

/* Inherits id/disabled/invalid/labelling from a surrounding <Field>; explicit props win. */
const ctx = useFormControl();
const disabled = computed(() => props.isDisabled ?? ctx?.isDisabled ?? false);

/* Never a declared prop — a declared `'aria-label'` would arrive as `props.ariaLabel` and
   stop reaching the DOM. It is read off the attrs so it can be relocated onto the track. */
const ariaLabel = computed(() => attrs['aria-label'] as string | undefined);

/* Names the area from the Field label when present; an explicit aria-label always wins. */
const labelledBy = computed(() => (!ariaLabel.value ? ctx?.labelledBy : undefined));

const track = useTemplateRef<HTMLDivElement>('track');

function commit(nextS: number, nextV: number): void {
  const cs = clamp01(nextS);
  const cv = clamp01(nextV);
  saturationControlled.setValue(cs);
  valueControlled.setValue(cv);
  emit('update:saturation', cs);
  emit('update:value', cv);
  emit('value-change', { saturation: cs, value: cv });
}

/* `getBoundingClientRect` is safe unguarded — pointer handlers never run on the server. */
function updateFromClient(clientX: number, clientY: number): void {
  const node = track.value;
  if (!node) return;
  const rect = node.getBoundingClientRect();
  const xRatio = clamp01((clientX - rect.left) / rect.width);
  const yRatio = clamp01((clientY - rect.top) / rect.height);
  commit(xRatio, 1 - yRatio);
}

function onPointerdown(event: PointerEvent): void {
  if (event.defaultPrevented) return;
  if (disabled.value) return;
  event.preventDefault();
  (event.target as Element).setPointerCapture?.(event.pointerId);
  updateFromClient(event.clientX, event.clientY);
}

function onPointermove(event: PointerEvent): void {
  if (event.defaultPrevented) return;
  if (disabled.value || event.buttons !== 1) return;
  updateFromClient(event.clientX, event.clientY);
}

function onKeydown(event: KeyboardEvent): void {
  if (event.defaultPrevented) return;
  if (disabled.value) return;
  const big = props.step * 10;
  let nextS = s.value;
  let nextV = v.value;
  switch (event.key) {
    case 'ArrowRight':
      nextS = s.value + props.step;
      break;
    case 'ArrowLeft':
      nextS = s.value - props.step;
      break;
    case 'ArrowUp':
      nextV = v.value + props.step;
      break;
    case 'ArrowDown':
      nextV = v.value - props.step;
      break;
    case 'PageUp':
      nextV = v.value + big;
      break;
    case 'PageDown':
      nextV = v.value - big;
      break;
    case 'Home':
      nextS = 0;
      nextV = 1;
      break;
    case 'End':
      nextS = 1;
      nextV = 0;
      break;
    default:
      return;
  }
  event.preventDefault();
  commit(nextS, nextV);
}

const trackStyle = computed<StyleValue>(() => [
  attrs.style as StyleValue,
  {
    backgroundImage: 'linear-gradient(to bottom, transparent, #000), linear-gradient(to right, #fff, transparent)',
    backgroundColor: `hsl(${props.hue}, 100%, 50%)`,
  },
]);

const thumbStyle = computed<StyleValue>(() => ({
  left: `${s.value * 100}%`,
  top: `${(1 - v.value) * 100}%`,
  backgroundColor: hsvToHex({ h: props.hue, s: s.value, v: v.value }),
}));

const controlId = computed(() => props.id ?? ctx?.id);
const finalAriaLabel = computed(() => ariaLabel.value ?? (labelledBy.value ? undefined : 'Saturation and value'));
const valueText = computed(() => `saturation ${(s.value * 100).toFixed(0)}%, value ${(v.value * 100).toFixed(0)}%`);
const isInvalid = computed(() => ctx?.isInvalid || undefined);
const describedBy = computed(() => ctx?.describedBy);

const OWNED_ATTRS: ReadonlySet<string> = new Set(['class', 'style', 'aria-label']);
const passthroughAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))),
);

const rootClass = computed(() =>
  cn(
    'relative aspect-square w-full select-none rounded-md border border-border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
    disabled.value && 'pointer-events-none opacity-50',
    attrs.class as ClassValue,
  ),
);

/** The rendered element — the Vue stand-in for the React original's forwarded ref. */
defineExpose({ el: track });
</script>

<template>
  <div
    ref="track"
    role="slider"
    :id="controlId"
    :tabindex="disabled ? -1 : 0"
    :aria-label="finalAriaLabel"
    :aria-labelledby="labelledBy"
    :aria-valuetext="valueText"
    :aria-invalid="isInvalid"
    :aria-describedby="describedBy"
    :aria-disabled="disabled || undefined"
    :data-disabled="disabled ? '' : undefined"
    :style="trackStyle"
    :class="rootClass"
    v-bind="passthroughAttrs"
    @pointerdown="onPointerdown"
    @pointermove="onPointermove"
    @keydown="onKeydown"
  >
    <div
      aria-hidden="true"
      :style="thumbStyle"
      class="absolute h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white shadow-md ring-1 ring-black/20"
    />
  </div>
</template>
