// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/layout/pullToRefresh/PullToRefresh.vue
<script lang="ts">
export interface PullToRefreshProps {
  onRefresh: () => Promise<void> | void;
  threshold?: number;
  maxPull?: number;
  isDisabled?: boolean;
}
</script>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, useAttrs, useTemplateRef, watch } from 'vue';
import { cn } from '../../../foundation/utils';
import { Announce, Politeness } from '../../../foundation/primitives';
import Spinner from '../../feedback/spinner/Spinner.vue';

/**
 * Pull-to-refresh wrapper. Listen to pointer drag at scrollTop=0; once past
 * `threshold`, fire `onRefresh`. Visual indicator: spinner that scales in as
 * the user pulls.
 */
defineOptions({ name: 'PullToRefresh', inheritAttrs: false });

/** The scrollable content — React's required `children`. */
defineSlots<{ default(): unknown }>();

const props = withDefaults(defineProps<PullToRefreshProps>(), {
  threshold: 60,
  maxPull: 120,
  isDisabled: false,
});

const attrs = useAttrs();
const el = useTemplateRef<HTMLDivElement>('el');

const startY = ref<number | null>(null);
const pull = ref(0);
const refreshing = ref(false);

const reached = computed(() => pull.value >= props.threshold);

function onPointerDown(e: PointerEvent): void {
  if (props.isDisabled || refreshing.value) return;
  const node = el.value;
  if (!node || node.scrollTop > 0) return;
  startY.value = e.clientY;
}

function onPointerMove(e: PointerEvent): void {
  if (startY.value == null) return;
  // Pointer was released outside the container — abandon the gesture.
  if (e.buttons === 0) {
    startY.value = null;
    pull.value = 0;
    return;
  }
  const dy = e.clientY - startY.value;
  if (dy < 0) {
    pull.value = 0;
    return;
  }
  // Resistance: sub-linear growth past threshold.
  const eased = dy < props.threshold ? dy : props.threshold + (dy - props.threshold) * 0.4;
  pull.value = Math.min(props.maxPull, eased);
}

async function onPointerUp(): Promise<void> {
  if (startY.value == null) return;
  const didReach = pull.value >= props.threshold;
  startY.value = null;
  if (didReach) {
    refreshing.value = true;
    pull.value = props.threshold;
    try {
      await props.onRefresh();
    } finally {
      refreshing.value = false;
      pull.value = 0;
    }
  } else {
    pull.value = 0;
  }
}

// Touch: native vertical pan fires pointercancel and kills the gesture.
// preventDefault touchmove only mid-pull (scrollTop 0, moving down); normal scroll stays native.
function onTouchMove(e: TouchEvent): void {
  const node = el.value;
  if (!node || startY.value == null || !e.cancelable) return;
  if (node.scrollTop > 0) return;
  const touch = e.touches[0];
  if (!touch) return;
  if (touch.clientY - startY.value > 0) e.preventDefault();
}

onMounted(() => {
  el.value?.addEventListener('touchmove', onTouchMove, { passive: false });
});

onBeforeUnmount(() => {
  el.value?.removeEventListener('touchmove', onTouchMove);
});

// Releasing the pointer outside the container must still finish the gesture.
watch(pull, (value, _previous, onCleanup) => {
  if (value === 0) return;
  const finish = (): void => {
    void onPointerUp();
  };
  window.addEventListener('pointerup', finish);
  window.addEventListener('pointercancel', finish);
  onCleanup(() => {
    window.removeEventListener('pointerup', finish);
    window.removeEventListener('pointercancel', finish);
  });
});

const classes = computed(() =>
  cn('relative h-full overflow-y-auto', attrs.class as string | undefined),
);

/**
 * Vue does not append `px` to a numeric `:style` value the way React does, so
 * every length below is spelled out.
 */
const indicatorStyle = computed(() => ({
  height: `${pull.value}px`,
  transition: startY.value == null ? 'height 200ms ease-out' : 'none',
}));

const contentStyle = computed(() => ({
  transform: `translateY(${pull.value}px)`,
  transition: startY.value == null ? 'transform 200ms ease-out' : 'none',
}));

const spinnerScaleStyle = computed(() => ({
  transform: `scale(${Math.min(1, pull.value / props.threshold)})`,
}));

const spinnerWrapClasses = computed(() =>
  cn('transition-opacity', refreshing.value || reached.value ? 'opacity-100' : 'opacity-60'),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <div
    ref="el"
    v-bind="rest"
    :class="classes"
    @pointerdown="onPointerDown"
    @pointermove="onPointerMove"
    @pointerup="onPointerUp"
    @pointercancel="onPointerUp"
  >
    <div
      aria-hidden="true"
      class="pointer-events-none absolute inset-x-0 top-0 z-raised flex items-center justify-center"
      :style="indicatorStyle"
    >
      <div v-if="pull > 8" :class="spinnerWrapClasses" :style="spinnerScaleStyle">
        <Spinner size="md" :tone="reached ? 'brand' : 'default'" />
      </div>
    </div>

    <div :style="contentStyle"><slot /></div>

    <Announce :politeness="Politeness.Polite">{{ refreshing ? 'Refreshing' : '' }}</Announce>
  </div>
</template>

// src/layout/pullToRefresh/PullToRefresh.tsx
import {
  forwardRef,
  useRef,
  useState,
  type HTMLAttributes,
  type PointerEvent as ReactPointerEvent,
  type ReactNode,
} from 'react';
import { cn } from '../../utils';
import { Announce } from '../../primitives';
import { Spinner } from '../../feedback/spinner';

export interface PullToRefreshProps extends HTMLAttributes<HTMLDivElement> {
  onRefresh: () => Promise<void> | void;
  threshold?: number;
  maxPull?: number;
  disabled?: boolean;
  children: ReactNode;
}

/**
 * Pull-to-refresh wrapper. Listen to pointer drag at scrollTop=0; once past
 * `threshold`, fire `onRefresh`. Visual indicator: spinner that scales in as
 * the user pulls.
 */
export const PullToRefresh = forwardRef<HTMLDivElement, PullToRefreshProps>(
  function PullToRefresh(
    { onRefresh, threshold = 60, maxPull = 120, disabled, className, children, ...rest },
    forwardedRef,
  ) {
    const containerRef = useRef<HTMLDivElement | null>(null);
    const startYRef = useRef<number | null>(null);
    const [pull, setPull] = useState(0);
    const [refreshing, setRefreshing] = useState(false);

    const onPointerDown = (e: ReactPointerEvent<HTMLDivElement>) => {
      if (disabled || refreshing) return;
      const el = containerRef.current;
      if (!el || el.scrollTop > 0) return;
      startYRef.current = e.clientY;
    };

    const onPointerMove = (e: ReactPointerEvent<HTMLDivElement>) => {
      if (startYRef.current == null) return;
      const dy = e.clientY - startYRef.current;
      if (dy < 0) {
        setPull(0);
        return;
      }
      // Resistance: sub-linear growth past threshold.
      const eased = dy < threshold ? dy : threshold + (dy - threshold) * 0.4;
      setPull(Math.min(maxPull, eased));
    };

    const onPointerUp = async () => {
      if (startYRef.current == null) return;
      const reached = pull >= threshold;
      startYRef.current = null;
      if (reached) {
        setRefreshing(true);
        setPull(threshold);
        try {
          await onRefresh();
        } finally {
          setRefreshing(false);
          setPull(0);
        }
      } else {
        setPull(0);
      }
    };

    const reached = pull >= threshold;

    return (
      <div
        ref={(el) => {
          containerRef.current = el;
          if (typeof forwardedRef === 'function') forwardedRef(el);
          else if (forwardedRef) (forwardedRef as React.MutableRefObject<HTMLDivElement | null>).current = el;
        }}
        onPointerDown={onPointerDown}
        onPointerMove={onPointerMove}
        onPointerUp={onPointerUp}
        onPointerCancel={onPointerUp}
        className={cn('relative h-full overflow-y-auto', className)}
        style={{ touchAction: 'pan-y' }}
        {...rest}
      >
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-x-0 top-0 z-10 flex items-center justify-center"
          style={{
            height: pull,
            transition: startYRef.current == null ? 'height 200ms ease-out' : 'none',
          }}
        >
          {pull > 8 && (
            <div
              className={cn(
                'transition-opacity',
                refreshing ? 'opacity-100' : reached ? 'opacity-100' : 'opacity-60',
              )}
              style={{ transform: `scale(${Math.min(1, pull / threshold)})` }}
            >
              <Spinner size="md" tone={reached ? 'brand' : 'default'} />
            </div>
          )}
        </div>
        <div
          style={{
            transform: `translateY(${pull}px)`,
            transition: startYRef.current == null ? 'transform 200ms ease-out' : 'none',
          }}
        >
          {children}
        </div>
        <Announce politeness="polite">
          {refreshing ? 'Refreshing' : ''}
        </Announce>
      </div>
    );
  },
);
