// src/display/scheduleView/ScheduleView.tsx
import { forwardRef, useMemo, type HTMLAttributes, type ReactNode } from 'react';
import { Temporal } from '@js-temporal/polyfill';
import { cn } from '../../utils';
import { formatZonedTime, minutesBetween, nowZoned, zonedAtHour } from '../../forms/DateExtensions';

// ScheduleView models bookings as absolute instants (a wall-clock time in a
// specific zone) — `Temporal.ZonedDateTime`, the peer of .NET `DateTimeOffset`.
// The single-day header projects down to the day's calendar date; the
// intra-day slot geometry does its math on `ZonedDateTime` (`.hour`, `.add`,
// `until`) via the shared, Temporal-based `DateExtensions`.

export interface ScheduleResource {
  id: string;
  label: ReactNode;
  color?: string;
}

export interface ScheduleBooking {
  id: string;
  resourceId: string;
  start: Temporal.ZonedDateTime;
  end: Temporal.ZonedDateTime;
  label?: ReactNode;
  color?: string;
}

export interface ScheduleViewProps extends HTMLAttributes<HTMLDivElement> {
  resources: ScheduleResource[];
  bookings: ScheduleBooking[];
  /** The day to render; its calendar date + time zone anchor the grid. */
  date?: Temporal.ZonedDateTime;
  hourRange?: [number, number];
  slotMinutes?: number;
  onBookingClick?: (booking: ScheduleBooking) => void;
  onSlotClick?: (resourceId: string, time: Temporal.ZonedDateTime) => void;
  renderBooking?: (booking: ScheduleBooking) => ReactNode;
}

/**
 * Multi-resource single-day schedule. Resources × hours grid; bookings
 * positioned absolutely within each row's timeline by minute offset.
 */
export const ScheduleView = forwardRef<HTMLDivElement, ScheduleViewProps>(function ScheduleView(
  {
    resources,
    bookings,
    date = nowZoned(),
    hourRange = [8, 20],
    slotMinutes = 30,
    onBookingClick,
    onSlotClick,
    renderBooking,
    className,
    ...rest
  },
  ref,
) {
  const [startHour, endHour] = hourRange;
  const totalMinutes = (endHour - startHour) * 60;
  const slotCount = Math.ceil(totalMinutes / slotMinutes);
  const dayStart = useMemo(
    () => zonedAtHour(date.toPlainDate(), startHour, date.timeZoneId),
    [date, startHour],
  );

  const bookingsByResource = useMemo(() => {
    const map = new Map<string, ScheduleBooking[]>();
    for (const b of bookings) {
      const list = map.get(b.resourceId);
      if (list) list.push(b);
      else map.set(b.resourceId, [b]);
    }
    return map;
  }, [bookings]);

  return (
    <div
      ref={ref}
      role="grid"
      aria-label="Schedule"
      className={cn(
        'overflow-auto rounded-md border border-border bg-card text-sm shadow-sm',
        className,
      )}
      {...rest}
    >
      {/* Hour header */}
      <div className="sticky top-0 z-raised flex border-b border-border bg-muted/40">
        <div className="w-32 shrink-0 border-r border-border px-3 py-2 text-xs font-medium text-muted-foreground">
          {date.toLocaleString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })}
        </div>
        <div className="flex-1 grid" style={{ gridTemplateColumns: `repeat(${endHour - startHour}, 1fr)` }}>
          {Array.from({ length: endHour - startHour }, (_, i) => (
            <div key={i} className="border-l border-border px-2 py-1 text-xs text-muted-foreground tabular-nums">
              {String((startHour + i) % 24).padStart(2, '0')}:00
            </div>
          ))}
        </div>
      </div>
      {/* Rows */}
      {resources.map((resource) => {
        const items = bookingsByResource.get(resource.id) ?? [];
        return (
          <div key={resource.id} role="row" className="flex border-b border-border last:border-b-0">
            <div className="w-32 shrink-0 border-r border-border bg-muted/20 px-3 py-2 text-xs font-medium">
              {resource.label}
            </div>
            <div className="relative flex-1" style={{ height: 56 }}>
              {/* Vertical hour gridlines */}
              <div
                aria-hidden="true"
                className="absolute inset-0 grid pointer-events-none"
                style={{ gridTemplateColumns: `repeat(${endHour - startHour}, 1fr)` }}
              >
                {Array.from({ length: endHour - startHour }, (_, i) => (
                  <div key={i} className="border-l border-border" />
                ))}
              </div>
              {/* Slot click overlay */}
              {onSlotClick && (
                <div
                  className="absolute inset-0 grid"
                  style={{ gridTemplateColumns: `repeat(${slotCount}, 1fr)` }}
                >
                  {Array.from({ length: slotCount }, (_, i) => {
                    const slotTime = dayStart.add({ minutes: i * slotMinutes });
                    return (
                      <button
                        key={i}
                        type="button"
                        aria-label={`Empty slot at ${formatZonedTime(slotTime)}`}
                        onClick={() => onSlotClick(resource.id, slotTime)}
                        className="hover:bg-primary-soft/30"
                      />
                    );
                  })}
                </div>
              )}
              {/* Bookings */}
              {items.map((booking) => {
                const offsetMin = Math.max(0, minutesBetween(dayStart, booking.start));
                const durMin = Math.max(15, minutesBetween(booking.start, booking.end));
                const left = (offsetMin / totalMinutes) * 100;
                const width = (durMin / totalMinutes) * 100;
                const color = booking.color ?? resource.color;
                return (
                  <button
                    key={booking.id}
                    type="button"
                    role="button"
                    aria-label={`${resource.label} ${formatZonedTime(booking.start)} – ${formatZonedTime(booking.end)}: ${booking.label ?? ''}`}
                    onClick={(e) => {
                      e.stopPropagation();
                      onBookingClick?.(booking);
                    }}
                    style={{
                      left: `${left}%`,
                      width: `${width}%`,
                      top: 4,
                      bottom: 4,
                      background: color,
                    }}
                    className={cn(
                      'absolute overflow-hidden rounded-md border border-border/60 px-2 py-1 text-left text-xs font-medium transition-colors hover:brightness-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
                      !color && 'bg-primary-soft text-primary-soft-foreground',
                    )}
                  >
                    {renderBooking ? (
                      renderBooking(booking)
                    ) : (
                      <>
                        <div className="truncate">{booking.label ?? booking.id}</div>
                        <div className="text-[10px] opacity-70 tabular-nums">
                          {formatZonedTime(booking.start)}
                          {' – '}
                          {formatZonedTime(booking.end)}
                        </div>
                      </>
                    )}
                  </button>
                );
              })}
            </div>
          </div>
        );
      })}
    </div>
  );
});

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/scheduleView/ScheduleView.vue
<script lang="ts">
import type { Temporal } from 'temporal-polyfill';

// ScheduleView models bookings as absolute instants (a wall-clock time in a
// specific zone) — `Temporal.ZonedDateTime`, the peer of .NET `DateTimeOffset`.
// The single-day header projects down to the day's calendar date; the
// intra-day slot geometry does its math on `ZonedDateTime` (`.hour`, `.add`,
// `until`) via the shared, Temporal-based `DateExtensions`.

export interface ScheduleResource {
  id: string;
  /** The row label. React took a `ReactNode`; richer content goes through the `resource` slot. */
  label: string | number;
  color?: string;
}

export interface ScheduleBooking {
  id: string;
  resourceId: string;
  start: Temporal.ZonedDateTime;
  end: Temporal.ZonedDateTime;
  /** The booking label. React took a `ReactNode`; richer content goes through the `booking` slot. */
  label?: string | number;
  color?: string;
}

export interface ScheduleViewProps {
  resources: ReadonlyArray<ScheduleResource>;
  bookings: ReadonlyArray<ScheduleBooking>;
  /** The day to render; its calendar date + time zone anchor the grid. */
  date?: Temporal.ZonedDateTime;
  hourRange?: [number, number];
  slotMinutes?: number;
  /**
   * Handles a click on an empty slot.
   *
   * Kept a PROP rather than an emit: its presence is what renders the slot overlay at
   * all, and Vue strips a declared emit's listener out of `useAttrs()` — an emit could
   * never be detected, so the overlay would either always or never render.
   */
  onSlotClick?: (resourceId: string, time: Temporal.ZonedDateTime) => void;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef, type StyleValue } from 'vue';
import type { ClassValue } from 'clsx';
import { cn } from '../../../foundation/utils';
import {
  formatZonedTime,
  minutesBetween,
  nowZoned,
  zonedAtHour,
} from '../../forms/DateExtensions';

/**
 * Multi-resource single-day schedule. Resources × hours grid; bookings
 * positioned absolutely within each row's timeline by minute offset.
 */
/* `inheritAttrs: false` so `class` folds into the component's own `cn()` call — plain fallthrough
   appends outside it and loses tailwind-merge conflict resolution. */
defineOptions({ name: 'ScheduleView', inheritAttrs: false });

const props = withDefaults(defineProps<ScheduleViewProps>(), {
  hourRange: () => [8, 20],
  slotMinutes: 30,
});

const emit = defineEmits<{
  /** Fires when a booking is clicked. Replaces React's `onBookingClick`. */
  'booking-click': [booking: ScheduleBooking];
}>();

/** Replaces React's `renderBooking` render prop, and lifts `label` to rich content. */
defineSlots<{
  /** Overrides a resource row's label. Falls back to `resource.label`. */
  resource?(props: { resource: ScheduleResource }): unknown;
  /** Overrides a booking's body. Falls back to the label + time range. */
  booking?(props: { booking: ScheduleBooking }): unknown;
}>();

const attrs = useAttrs();

/* `nowZoned()` reads the host time zone through `Temporal.Now` — universal, not a browser
   global, so it is safe as a computed default on the server. */
const day = computed(() => props.date ?? nowZoned());

const startHour = computed(() => props.hourRange[0]);
const endHour = computed(() => props.hourRange[1]);
const hourCount = computed(() => endHour.value - startHour.value);
const totalMinutes = computed(() => hourCount.value * 60);
const slotCount = computed(() => Math.ceil(totalMinutes.value / props.slotMinutes));

const dayStart = computed(() =>
  zonedAtHour(day.value.toPlainDate(), startHour.value, day.value.timeZoneId),
);

const bookingsByResource = computed(() => {
  const map = new Map<string, Array<ScheduleBooking>>();
  for (const b of props.bookings) {
    const list = map.get(b.resourceId);
    if (list) list.push(b);
    else map.set(b.resourceId, [b]);
  }
  return map;
});

function bookingsFor(resourceId: string): Array<ScheduleBooking> {
  return bookingsByResource.value.get(resourceId) ?? [];
}

const dayLabel = computed(() =>
  day.value.toLocaleString(undefined, { weekday: 'short', month: 'short', day: 'numeric' }),
);

const hourColumns = computed<StyleValue>(() => ({
  gridTemplateColumns: `repeat(${hourCount.value}, 1fr)`,
}));

const slotColumns = computed<StyleValue>(() => ({
  gridTemplateColumns: `repeat(${slotCount.value}, 1fr)`,
}));

function hourLabel(index: number): string {
  return `${String((startHour.value + index) % 24).padStart(2, '0')}:00`;
}

function slotTime(index: number): Temporal.ZonedDateTime {
  return dayStart.value.add({ minutes: index * props.slotMinutes });
}

function slotLabel(index: number): string {
  return `Empty slot at ${formatZonedTime(slotTime(index))}`;
}

function onSlot(resourceId: string, index: number): void {
  props.onSlotClick?.(resourceId, slotTime(index));
}

function onBooking(event: MouseEvent, booking: ScheduleBooking): void {
  event.stopPropagation();
  emit('booking-click', booking);
}

function bookingLabel(resource: ScheduleResource, booking: ScheduleBooking): string {
  return `${resource.label} ${formatZonedTime(booking.start)} – ${formatZonedTime(booking.end)}: ${booking.label ?? ''}`;
}

/* Numeric CSS lengths are spelled with their unit — React's style object auto-appended `px`,
   Vue's does not, so a bare `56` would be dropped as an invalid declaration. */
function bookingStyle(resource: ScheduleResource, booking: ScheduleBooking): StyleValue {
  const offsetMin = Math.max(0, minutesBetween(dayStart.value, booking.start));
  const durMin = Math.max(15, minutesBetween(booking.start, booking.end));
  return {
    left: `${(offsetMin / totalMinutes.value) * 100}%`,
    width: `${(durMin / totalMinutes.value) * 100}%`,
    top: '4px',
    bottom: '4px',
    background: booking.color ?? resource.color,
  };
}

function bookingClass(resource: ScheduleResource, booking: ScheduleBooking): string {
  const color = booking.color ?? resource.color;
  return cn(
    'absolute overflow-hidden rounded-md border border-border/60 px-2 py-1 text-left text-xs font-medium transition-colors hover:brightness-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
    !color && 'bg-primary-soft text-primary-soft-foreground',
  );
}

const ROW_STYLE: StyleValue = { height: '56px' };

const OWNED_ATTRS: ReadonlySet<string> = new Set(['class']);
const passthroughAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))),
);

const rootClass = computed(() =>
  cn(
    'overflow-auto rounded-md border border-border bg-card text-sm shadow-sm',
    attrs.class as ClassValue,
  ),
);

const root = useTemplateRef<HTMLDivElement>('root');

/** The rendered element — the Vue stand-in for the React original's forwarded ref. */
defineExpose({ el: root });
</script>

<template>
  <!-- Timeline layout, no 2D keyboard nav — ARIA grid (grid > row > gridcell)
       would be a lie; group + labeled slot/booking buttons is honest. -->
  <div
    ref="root"
    role="group"
    aria-label="Schedule"
    :class="rootClass"
    v-bind="passthroughAttrs"
  >
    <!-- Hour header -->
    <div class="sticky top-0 z-raised flex border-b border-border bg-muted/40">
      <div
        class="w-32 shrink-0 border-r border-border px-3 py-2 text-xs font-medium text-muted-foreground"
      >
        {{ dayLabel }}
      </div>
      <div class="flex-1 grid" :style="hourColumns">
        <div
          v-for="i in hourCount"
          :key="i"
          class="border-l border-border px-2 py-1 text-xs text-muted-foreground tabular-nums"
        >
          {{ hourLabel(i - 1) }}
        </div>
      </div>
    </div>
    <!-- Rows -->
    <div
      v-for="resource in resources"
      :key="resource.id"
      class="flex border-b border-border last:border-b-0"
    >
      <div
        class="w-32 shrink-0 border-r border-border bg-muted/20 px-3 py-2 text-xs font-medium"
      >
        <slot name="resource" :resource="resource">{{ resource.label }}</slot>
      </div>
      <div class="relative flex-1" :style="ROW_STYLE">
        <!-- Vertical hour gridlines -->
        <div aria-hidden="true" class="absolute inset-0 grid pointer-events-none" :style="hourColumns">
          <div v-for="i in hourCount" :key="i" class="border-l border-border" />
        </div>
        <!-- Slot click overlay -->
        <div v-if="onSlotClick" class="absolute inset-0 grid" :style="slotColumns">
          <button
            v-for="i in slotCount"
            :key="i"
            type="button"
            :aria-label="slotLabel(i - 1)"
            class="hover:bg-primary-soft/30"
            @click="onSlot(resource.id, i - 1)"
          />
        </div>
        <!-- Bookings -->
        <button
          v-for="booking in bookingsFor(resource.id)"
          :key="booking.id"
          type="button"
          :aria-label="bookingLabel(resource, booking)"
          :style="bookingStyle(resource, booking)"
          :class="bookingClass(resource, booking)"
          @click="onBooking($event, booking)"
        >
          <slot name="booking" :booking="booking">
            <div class="truncate">{{ booking.label ?? booking.id }}</div>
            <div class="text-[10px] opacity-70 tabular-nums">
              {{ formatZonedTime(booking.start) }}
              {{ ' – ' }}
              {{ formatZonedTime(booking.end) }}
            </div>
          </slot>
        </button>
      </div>
    </div>
  </div>
</template>
