// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/feedback/loadingOverlay/LoadingOverlay.vue
<script lang="ts">
import type { Size } from '../../../foundation/utils';
import type { SpinnerTone } from '../spinner/Spinner.variants';

export interface LoadingOverlayProps {
  /** The mount state. Default `true`. */
  isOpen?: boolean;

  /** The caption under the spinner. Default `"Loading…"`. Rich content → the `label` slot. */
  label?: string;

  /** The inline-positioning toggle — positions the scrim absolutely inside the parent (parent must be `position: relative`). */
  isInline?: boolean;

  /** The backdrop-blur toggle. */
  hasBlur?: boolean;

  /** The spinner diameter step. Default `lg`. */
  spinnerSize?: Size;

  /** The spinner color tone. Default `brand`. */
  spinnerTone?: SpinnerTone;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useSlots, useTemplateRef } from 'vue';
import { cn, Size as SizeToken } from '../../../foundation/utils';
import { Presence } from '../../../foundation/primitives';
import Backdrop from '../../overlays/backdrop/Backdrop.vue';
import Spinner from '../spinner/Spinner.vue';
import { SpinnerTone as SpinnerToneToken } from '../spinner/Spinner.variants';

/**
 * Scrim + centered spinner — blocks interaction with a region during a long task.
 * `isInline` scopes the scrim to a `position: relative` parent; default covers the
 * viewport via `Backdrop`.
 *
 * React split the scrim into a `forwardRef` `LoadingScrim` so the two branches
 * could share it and `Presence` had a spreadable node to clone. Vue's `Presence`
 * clones whatever single element it is given, so the two branches collapse into
 * one `<div>` whose position/elevation classes switch on `isInline` — same DOM,
 * one component fewer.
 */
defineOptions({ name: 'LoadingOverlay', inheritAttrs: false });

/** Extra content below the label — React's `children`. */
defineSlots<{ default?(): unknown; label?(): unknown }>();

const props = withDefaults(defineProps<LoadingOverlayProps>(), {
  isOpen: true,
  label: 'Loading…',
  isInline: false,
  hasBlur: false,
  spinnerSize: SizeToken.Lg,
  spinnerTone: SpinnerToneToken.Brand,
});

const attrs = useAttrs();
const slots = useSlots();
const el = useTemplateRef<HTMLDivElement>('el');

const hasLabel = computed(() => Boolean(props.label) || Boolean(slots.label));

/** React fell back to `"Loading"` whenever `label` was not a plain string; here the same guard covers a caller who blanks the caption. */
const spinnerLabel = computed(() => props.label || 'Loading');

/*
 * `data-state` is injected by <Presence>; the fade tokens are gated on it so
 * enter plays on mount and exit plays before Presence defers the unmount.
 * The inline scrim carries the tint and the blur itself; the viewport one is
 * click-through and leaves both to the portalled `Backdrop` behind it.
 */
const classes = computed(() =>
  cn(
    'flex flex-col items-center justify-center gap-3',
    'motion-safe:data-[state=open]:animate-(--animate-fade-in)',
    'motion-safe:data-[state=closed]:animate-(--animate-fade-out)',
    'motion-reduce:animate-none',
    props.isInline
      ? ['absolute inset-0 z-banner bg-background/70', props.hasBlur && 'backdrop-blur-sm']
      : 'fixed inset-0 z-modal pointer-events-none',
    attrs.class as string | undefined,
  ),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <!-- `Backdrop` self-wraps in `Presence`; driving `is-open` with `isOpen` lets its
       fade-out play before it defers its own unmount. -->
  <Backdrop
    v-if="!props.isInline"
    :is-open="props.isOpen"
    :is-blurred="props.hasBlur"
    class="bg-background/70"
  />
  <Presence :is-present="props.isOpen">
    <div ref="el" role="status" v-bind="rest" :class="classes">
      <Spinner :size="props.spinnerSize" :tone="props.spinnerTone" :label="spinnerLabel" />
      <div v-if="hasLabel" class="text-sm text-foreground">
        <slot name="label">{{ props.label }}</slot>
      </div>
      <slot />
    </div>
  </Presence>
</template>

// src/feedback/loadingOverlay/LoadingOverlay.tsx
import { forwardRef, type HTMLAttributes, type ReactNode } from 'react';
import { cn } from '../../utils';
import { Backdrop } from '../../overlays/backdrop';
import { Spinner } from '../spinner';
import type { SpinnerVariants } from '../spinner/Spinner.variants';

export interface LoadingOverlayProps extends HTMLAttributes<HTMLDivElement> {
  open?: boolean;
  label?: ReactNode;
  /** Position the scrim absolutely inside the parent (parent must be `position: relative`). */
  inline?: boolean;
  blur?: boolean;
  spinnerSize?: SpinnerVariants['size'];
  spinnerTone?: SpinnerVariants['tone'];
}

/**
 * Scrim + centered spinner. Use to block interaction with a region while a
 * long-running task is in flight. `inline` positions the scrim inside its
 * parent (which must be `position: relative`); the default covers the
 * viewport via `Backdrop`.
 */
export const LoadingOverlay = forwardRef<HTMLDivElement, LoadingOverlayProps>(
  function LoadingOverlay(
    {
      open = true,
      label = 'Loading…',
      inline = false,
      blur,
      spinnerSize = 'lg',
      spinnerTone = 'brand',
      className,
      children,
      ...rest
    },
    ref,
  ) {
    if (!open) return null;

    if (inline) {
      return (
        <div
          ref={ref}
          role="alert"
          aria-busy="true"
          className={cn(
            'absolute inset-0 z-40 flex flex-col items-center justify-center gap-3 bg-background/70',
            blur && 'backdrop-blur-sm',
            className,
          )}
          {...rest}
        >
          <Spinner size={spinnerSize} tone={spinnerTone} label={typeof label === 'string' ? label : 'Loading'} />
          {label && <div className="text-sm text-foreground">{label}</div>}
          {children}
        </div>
      );
    }

    return (
      <>
        <Backdrop open blur={blur} className="bg-background/70" />
        <div
          ref={ref}
          role="alert"
          aria-busy="true"
          className={cn(
            'fixed inset-0 z-50 flex flex-col items-center justify-center gap-3 pointer-events-none',
            className,
          )}
          {...rest}
        >
          <Spinner size={spinnerSize} tone={spinnerTone} label={typeof label === 'string' ? label : 'Loading'} />
          {label && <div className="text-sm text-foreground">{label}</div>}
          {children}
        </div>
      </>
    );
  },
);
LoadingOverlay.displayName = 'LoadingOverlay';
