// src/display/mark/Mark.tsx
import { forwardRef, type ComponentPropsWithoutRef } from 'react';
import { cn } from '../../utils';

export type MarkProps = ComponentPropsWithoutRef<'mark'>;

/**
 * Highlighted text — semantic `<mark>` with a yellow tint. Use for search
 * matches and "you mentioned this" affordances.
 */
export const Mark = forwardRef<HTMLElement, MarkProps>(({ className, ...props }, ref) => (
  <mark
    ref={ref}
    className={cn('rounded-sm bg-warning-soft px-0.5 text-warning-soft-foreground', className)}
    {...props}
  />
));
Mark.displayName = 'Mark';

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/mark/Mark.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue';

export type MarkProps = HTMLAttributes;
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';

/**
 * Highlighted text — semantic `<mark>` with a yellow tint. Use for search
 * matches and "you mentioned this" affordances.
 */
defineOptions({ name: 'Mark', inheritAttrs: false });

/** The highlighted text — React's `children`. */
defineSlots<{ default(): unknown }>();

const attrs = useAttrs();
const el = useTemplateRef<HTMLElement>('el');

const classes = computed(() =>
  cn(
    'rounded-sm bg-warning-soft px-0.5 text-warning-soft-foreground',
    attrs.class as string | undefined,
  ),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <mark ref="el" v-bind="rest" :class="classes"><slot /></mark>
</template>
