// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/actions/speedDial/SpeedDial.vue
<script lang="ts">
import type { SpeedDialDirection, SpeedDialPosition } from './SpeedDialContext';

export interface SpeedDialProps {
  /** The viewport anchor. Default `bottom-right`. */
  position?: SpeedDialPosition;

  /** The axis the action items fan out along. Defaults to the one implied by `position`. */
  direction?: SpeedDialDirection;

  /** The controlled open state. */
  isOpen?: boolean;

  /** The uncontrolled initial state. */
  defaultOpen?: boolean;

  /** The pixel gap between stacked action items. Default 12. */
  gap?: number;
}
</script>

<script setup lang="ts">
import {
  computed,
  provide,
  shallowRef,
  useAttrs,
  useSlots,
  useTemplateRef,
  type VNode,
} from 'vue';
import type { ClassValue } from 'clsx';
import { cn, Key, OverlayPosition } from '../../../foundation/utils';
import { Presence, renderableChildren } from '../../../foundation/primitives';
import { useControlled, useEscape, useOutsideClick } from '../../../foundation/hooks';
import {
  SpeedDialDirection as SpeedDialDirectionValue,
  SpeedDialKey,
} from './SpeedDialContext';
import SpeedDialList from './SpeedDialList.vue';
import SpeedDialTrigger from './SpeedDialTrigger.vue';

/* `inheritAttrs: false` so `class` folds into the component's own `cn()` call — plain fallthrough
   appends outside it and loses tailwind-merge conflict resolution. */
defineOptions({ name: 'SpeedDial', inheritAttrs: false });

/* `className` is Vue's `class` fallthrough attr; `children` is the default slot. */
const props = withDefaults(defineProps<SpeedDialProps>(), {
  position: OverlayPosition.BottomRight,
  direction: undefined,
  gap: 12,
  defaultOpen: false,
  isOpen: undefined,
});

const emit = defineEmits<{
  /** Emits the open state whenever it changes. */
  'open-change': [open: boolean];
}>();

const attrs = useAttrs();
const slots = useSlots();

const OWNED_ATTRS: ReadonlySet<string> = new Set(['class']);
const passthroughAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))),
);

const POSITION_TO_DIRECTION: Record<SpeedDialPosition, SpeedDialDirection> = {
  'bottom-right': SpeedDialDirectionValue.Up,
  'bottom-left': SpeedDialDirectionValue.Up,
  'bottom-center': SpeedDialDirectionValue.Up,
  'top-right': SpeedDialDirectionValue.Down,
  'top-left': SpeedDialDirectionValue.Down,
  'top-center': SpeedDialDirectionValue.Down,
};

const POSITION_OFFSETS: Record<SpeedDialPosition, string> = {
  'bottom-right': 'bottom-6 right-6',
  'bottom-left': 'bottom-6 left-6',
  'bottom-center': 'bottom-6 left-1/2 -translate-x-1/2',
  'top-right': 'top-6 right-6',
  'top-left': 'top-6 left-6',
  'top-center': 'top-6 left-1/2 -translate-x-1/2',
};

const DIRECTION_TO_STACK: Record<SpeedDialDirection, string> = {
  [SpeedDialDirectionValue.Up]: 'flex-col-reverse bottom-full mb-3',
  [SpeedDialDirectionValue.Down]: 'flex-col top-full mt-3',
  [SpeedDialDirectionValue.Left]: 'flex-row-reverse right-full mr-3',
  [SpeedDialDirectionValue.Right]: 'flex-row top-1/2 -translate-y-1/2 left-full ml-3',
};

const { value: open, setValue: setOpen } = useControlled<boolean>({
  controlled: () => props.isOpen,
  default: props.defaultOpen,
  onChange: (next) => emit('open-change', next),
});

const rootEl = useTemplateRef<HTMLDivElement>('rootEl');
const triggerEl = shallowRef<HTMLElement | null>(null);

const resolvedDirection = computed(
  () => props.direction ?? POSITION_TO_DIRECTION[props.position],
);

useEscape(() => {
  setOpen(false);
  requestAnimationFrame(() => triggerEl.value?.focus());
}, open);

useOutsideClick(
  rootEl,
  () => {
    if (open.value) setOpen(false);
  },
  open,
);

provide(SpeedDialKey, {
  get open() {
    return open.value;
  },
  setOpen,
  triggerEl,
  get direction() {
    return resolvedDirection.value;
  },
  get position() {
    return props.position;
  },
});

/* The trigger renders always (a closed dial must still be openable); only the action items are
   gated behind `open`. The React original partitioned `Children.toArray` on `child.type`; the
   same split runs over the slot's vnodes, so the authoring shape is unchanged. */
function splitChildren(keepTrigger: boolean): Array<VNode> {
  return renderableChildren(slots.default?.()).filter(
    (child) => (child.type === SpeedDialTrigger) === keepTrigger,
  );
}

const rootClass = computed(() =>
  cn('fixed', POSITION_OFFSETS[props.position], attrs.class as ClassValue),
);
const stackClass = computed(() => DIRECTION_TO_STACK[resolvedDirection.value]);

function handleKeydown(event: KeyboardEvent): void {
  if (!open.value || (event.key !== Key.ArrowDown && event.key !== Key.ArrowUp)) return;
  const root = rootEl.value;
  if (!root) return;
  const items = Array.from(root.querySelectorAll<HTMLButtonElement>('[role="menuitem"]'));
  if (items.length === 0) return;
  event.preventDefault();
  const currentIndex = items.indexOf(document.activeElement as HTMLButtonElement);
  const nextIndex =
    currentIndex === -1
      ? event.key === Key.ArrowDown
        ? 0
        : items.length - 1
      : (currentIndex + (event.key === Key.ArrowDown ? 1 : -1) + items.length) % items.length;
  items[nextIndex]?.focus();
}

/** The rendered element — the Vue stand-in for the React original's forwarded ref. */
defineExpose({ el: rootEl });
</script>

<template>
  <div
    ref="rootEl"
    :data-state="open ? 'open' : 'closed'"
    :class="rootClass"
    v-bind="passthroughAttrs"
    @keydown="handleKeydown"
  >
    <!-- `Presence` clones `data-state` ("open" | "closed") + a `ref` onto the list and defers
         unmount until its fade-out ends — keeps the exit from being killed by the hard `!open`
         unmount. Items pop in/out off the list's `group` state (see `SpeedDialAction`),
         staggered on enter. -->
    <Presence :is-present="open">
      <SpeedDialList
        :data-direction="resolvedDirection"
        :style="{ gap: `${gap}px` }"
        :class="stackClass"
      >
        <component :is="node" v-for="(node, index) in splitChildren(false)" :key="index" />
      </SpeedDialList>
    </Presence>
    <component :is="node" v-for="(node, index) in splitChildren(true)" :key="index" />
  </div>
</template>

// src/actions/speedDial/SpeedDial.tsx
import {
  Children,
  createContext,
  forwardRef,
  isValidElement,
  useContext,
  useMemo,
  useRef,
  type ButtonHTMLAttributes,
  type HTMLAttributes,
  type KeyboardEvent,
  type ReactNode,
} from 'react';
import { Plus, X } from 'lucide-react';
import { cn, composeRefs } from '../../utils';
import { useControlled, useEscape, useOutsideClick } from '../../hooks';
import { Presence } from '../../primitives';
import { Icon } from '../../icons';
import { FAB } from '../fab';
import type { FABVariants } from '../fab/FAB.variants';

export type SpeedDialPosition = NonNullable<FABVariants['position']>;
export type SpeedDialDirection = 'up' | 'down' | 'left' | 'right';

interface SpeedDialContextValue {
  open: boolean;
  setOpen: (open: boolean) => void;
  triggerRef: React.MutableRefObject<HTMLButtonElement | null>;
  rootRef: React.MutableRefObject<HTMLDivElement | null>;
  direction: SpeedDialDirection;
  position: SpeedDialPosition;
}

const SpeedDialContext = createContext<SpeedDialContextValue | null>(null);

function useSpeedDialContext() {
  const ctx = useContext(SpeedDialContext);
  if (!ctx) throw new Error('SpeedDial.* must be used inside <SpeedDial>');
  return ctx;
}

/**
 * `Presence`-clonable list: a single `forwardRef` element that spreads
 * `data-state` (injected by `Presence`) + `ref` onto its node. Marked `group`
 * so each action item animates off its `data-[state]`; carries its own fade so
 * `Presence` has an animation on *this* node to watch before unmount. `forwardRef`
 * + `{...props}` spread are required so the ref and `data-state` actually land here.
 */
const SpeedDialList = forwardRef<HTMLUListElement, HTMLAttributes<HTMLUListElement>>(
  function SpeedDialList({ className, children, ...props }, ref) {
    return (
      <ul
        ref={ref}
        role="menu"
        className={cn(
          'group absolute flex',
          /* list fade gated on data-state; motion-safe so reduced-motion users
             get no movement. */
          'motion-safe:data-[state=open]:animate-(--animate-fade-in)',
          'motion-safe:data-[state=closed]:animate-(--animate-fade-out)',
          'motion-reduce:animate-none',
          /* Per-item enter stagger: ramp `animation-delay` on the first few items
             while opening only (closed → delay 0 so no item outlasts the list's
             own fade-out, which gates unmount). */
          'motion-safe:group-data-[state=open]:[&>li:nth-child(2)]:[animation-delay:40ms]',
          'motion-safe:group-data-[state=open]:[&>li:nth-child(3)]:[animation-delay:80ms]',
          'motion-safe:group-data-[state=open]:[&>li:nth-child(4)]:[animation-delay:120ms]',
          'motion-safe:group-data-[state=open]:[&>li:nth-child(n+5)]:[animation-delay:160ms]',
          className,
        )}
        {...props}
      >
        {children}
      </ul>
    );
  },
);

const POSITION_TO_DIRECTION: Record<SpeedDialPosition, SpeedDialDirection> = {
  'bottom-right': 'up',
  'bottom-left': 'up',
  'bottom-center': 'up',
  'top-right': 'down',
  'top-left': 'down',
};

const POSITION_OFFSETS: Record<SpeedDialPosition, string> = {
  'bottom-right': 'bottom-6 right-6',
  'bottom-left': 'bottom-6 left-6',
  'bottom-center': 'bottom-6 left-1/2 -translate-x-1/2',
  'top-right': 'top-6 right-6',
  'top-left': 'top-6 left-6',
};

const DIRECTION_TO_STACK: Record<SpeedDialDirection, string> = {
  up: 'flex-col-reverse bottom-full mb-3',
  down: 'flex-col top-full mt-3',
  left: 'flex-row-reverse right-full mr-3',
  right: 'flex-row top-1/2 -translate-y-1/2 left-full ml-3',
};

const DIRECTION_LABEL_SIDE: Record<SpeedDialDirection, 'left' | 'right'> = {
  up: 'right',
  down: 'right',
  left: 'right',
  right: 'left',
};

export interface SpeedDialProps {
  position?: SpeedDialPosition;
  direction?: SpeedDialDirection;
  isOpen?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  gap?: number;
  className?: string;
  children: ReactNode;
}

function SpeedDialRoot({
  position = 'bottom-right',
  direction,
  isOpen: openProp,
  defaultOpen = false,
  onOpenChange,
  gap = 12,
  className,
  children,
}: SpeedDialProps) {
  const [open, setOpen] = useControlled({
    controlled: openProp,
    default: defaultOpen,
    onChange: onOpenChange,
  });
  const triggerRef = useRef<HTMLButtonElement | null>(null);
  const rootRef = useRef<HTMLDivElement | null>(null);
  const resolvedDirection = direction ?? POSITION_TO_DIRECTION[position];

  useEscape(() => {
    if (!open) return;
    setOpen(false);
    requestAnimationFrame(() => triggerRef.current?.focus());
  }, open);

  useOutsideClick(
    rootRef,
    () => {
      if (open) setOpen(false);
    },
    open,
  );

  const ctx = useMemo<SpeedDialContextValue>(
    () => ({ open, setOpen, triggerRef, rootRef, direction: resolvedDirection, position }),
    [open, setOpen, resolvedDirection, position],
  );

  // The trigger renders always (a closed dial must still be openable); only the
  // action items are gated behind `open`.
  const childArray = Children.toArray(children);
  const triggerChildren = childArray.filter(
    (child) => isValidElement(child) && child.type === SpeedDialTrigger,
  );
  const actionChildren = childArray.filter(
    (child) => !(isValidElement(child) && child.type === SpeedDialTrigger),
  );

  const handleKeyDown = (e: KeyboardEvent<HTMLDivElement>) => {
    if (!open || (e.key !== 'ArrowDown' && e.key !== 'ArrowUp')) return;
    const root = rootRef.current;
    if (!root) return;
    const items = Array.from(root.querySelectorAll<HTMLButtonElement>('[role="menuitem"]'));
    if (items.length === 0) return;
    e.preventDefault();
    const currentIndex = items.indexOf(document.activeElement as HTMLButtonElement);
    const nextIndex =
      currentIndex === -1
        ? e.key === 'ArrowDown'
          ? 0
          : items.length - 1
        : (currentIndex + (e.key === 'ArrowDown' ? 1 : -1) + items.length) % items.length;
    items[nextIndex]?.focus();
  };

  return (
    <SpeedDialContext.Provider value={ctx}>
      <div
        ref={rootRef}
        data-state={open ? 'open' : 'closed'}
        onKeyDown={handleKeyDown}
        className={cn('fixed', POSITION_OFFSETS[position], className)}
      >
        {/* `Presence` clones `data-state` ("open" | "closed") + a `ref` onto the
            list and defers unmount until its fade-out ends — keeps the exit from
            being killed by the hard `!open` unmount. Items pop in/out off the
            list's `group` state (see `SpeedDialAction`), staggered on enter. */}
        <Presence isPresent={open}>
          <SpeedDialList
            data-direction={resolvedDirection}
            style={{ gap }}
            className={DIRECTION_TO_STACK[resolvedDirection]}
          >
            {actionChildren}
          </SpeedDialList>
        </Presence>
        {triggerChildren}
      </div>
    </SpeedDialContext.Provider>
  );
}
SpeedDialRoot.displayName = 'SpeedDial';

export interface SpeedDialTriggerProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'children'> {
  /** Required accessible label. Default `"Toggle actions"`. */
  'aria-label'?: string;
  closedIcon?: ReactNode;
  openIcon?: ReactNode;
  variant?: FABVariants['variant'];
  size?: FABVariants['size'];
}

export const SpeedDialTrigger = forwardRef<HTMLButtonElement, SpeedDialTriggerProps>(
  function SpeedDialTrigger(
    {
      'aria-label': ariaLabel = 'Toggle actions',
      closedIcon,
      openIcon,
      variant,
      size,
      onClick,
      className,
      ...rest
    },
    forwardedRef,
  ) {
    const ctx = useSpeedDialContext();
    return (
      <FAB
        {...rest}
        ref={composeRefs(forwardedRef, ctx.triggerRef)}
        aria-label={ariaLabel}
        aria-haspopup="menu"
        aria-expanded={ctx.open}
        variant={variant}
        size={size}
        position={ctx.position}
        onClick={(e) => {
          onClick?.(e);
          if (e.defaultPrevented) return;
          ctx.setOpen(!ctx.open);
        }}
        className={cn('static !bottom-auto !left-auto !right-auto !top-auto !translate-x-0', className)}
      >
        {ctx.open ? openIcon ?? <Icon icon={X} size={20} /> : closedIcon ?? <Icon icon={Plus} size={20} />}
      </FAB>
    );
  },
);

export interface SpeedDialActionProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'children'> {
  'aria-label': string;
  icon: ReactNode;
  onSelect?: () => void;
  tooltip?: ReactNode;
}

export const SpeedDialAction = forwardRef<HTMLButtonElement, SpeedDialActionProps>(
  function SpeedDialAction(
    { 'aria-label': ariaLabel, icon, onSelect, tooltip, className, onClick, type = 'button', ...rest },
    forwardedRef,
  ) {
    const ctx = useSpeedDialContext();
    const labelSide = DIRECTION_LABEL_SIDE[ctx.direction];
    return (
      <li
        role="none"
        data-side={labelSide}
        className={cn(
          'flex items-center gap-2',
          /* fade+scale each action off the list's `group` state; motion-safe so
             reduced-motion users get no movement (delay ramp lives on the list). */
          'motion-safe:group-data-[state=open]:animate-(--animate-pop-in)',
          'motion-safe:group-data-[state=closed]:animate-(--animate-pop-out)',
          'motion-reduce:animate-none',
        )}
      >
        {tooltip && labelSide === 'left' && (
          <span className="rounded-md bg-popover px-2 py-1 text-xs text-popover-foreground shadow">
            {tooltip}
          </span>
        )}
        <button
          {...rest}
          ref={forwardedRef}
          type={type}
          role="menuitem"
          aria-label={ariaLabel}
          onClick={(e) => {
            onClick?.(e);
            if (e.defaultPrevented) return;
            onSelect?.();
            ctx.setOpen(false);
            requestAnimationFrame(() => ctx.triggerRef.current?.focus());
          }}
          className={cn(
            'inline-flex h-10 w-10 items-center justify-center rounded-full bg-card text-card-foreground shadow-md transition-all hover:shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
            className,
          )}
        >
          {icon}
        </button>
        {tooltip && labelSide === 'right' && (
          <span className="rounded-md bg-popover px-2 py-1 text-xs text-popover-foreground shadow">
            {tooltip}
          </span>
        )}
      </li>
    );
  },
);

export const SpeedDial = Object.assign(SpeedDialRoot, {
  Trigger: SpeedDialTrigger,
  Action: SpeedDialAction,
});

export default SpeedDial;
