// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/forms/multiSelect/MultiSelect.vue
<script lang="ts">
import type { Placement } from '@floating-ui/vue';

export interface MultiSelectProps {
  /** The selected values, controlled — React's spelling, which wins when both are set. */
  value?: ReadonlyArray<string>;

  /** The selected values, controlled. The `v-model` binding target. */
  modelValue?: ReadonlyArray<string>;

  /** The initial selected values when uncontrolled. */
  defaultValue?: ReadonlyArray<string>;

  /** The disabled state. Falls back to the surrounding form control's `isDisabled`. */
  isDisabled?: boolean;

  /** The hidden-input name; one hidden input is rendered per selected value. */
  name?: string;

  /** The invalid surface override. Falls back to the surrounding form control's `isInvalid`. */
  isInvalid?: boolean;

  /** The initial open state of the dropdown when uncontrolled. */
  defaultOpen?: boolean;

  /** The dropdown open state, controlled. The `v-model:open` binding target. */
  open?: boolean;

  /** The dropdown open state, controlled — the house boolean spelling of `open`, which wins. */
  isOpen?: boolean;

  /** The floating placement of the dropdown. */
  placement?: Placement;
}
</script>

<script setup lang="ts">
import { computed, provide, ref } from 'vue';
import { useControlled } from '../../../foundation/hooks';
import { useFormControl } from '../../../foundation/primitives';
import { Popover } from '../../overlays';
import { multiSelectContextKey, type MultiSelectContextValue } from './MultiSelectContext';

/**
 * State owner for a MultiSelect tree. Renders the `Popover` that hosts the trigger and the
 * panel, plus one hidden input per selected value.
 *
 * Inherits id/disabled/invalid/labelledby/describedby from a surrounding `<Field>`;
 * standalone props win when provided, context fills the gaps (Select parity).
 */
defineOptions({ name: 'MultiSelect', inheritAttrs: false });

/** The MultiSelect tree — trigger and content. React's `children`. */
defineSlots<{ default(): unknown }>();

const props = withDefaults(defineProps<MultiSelectProps>(), {
  defaultOpen: false,
  placement: 'bottom',
  /* Explicit `undefined` defaults are load-bearing: `useControlled` keys on `=== undefined`,
     and Vue casts an absent `boolean` prop to `false`. Without these, `open`/`isOpen` would
     read as "controlled, and closed" — pinning the dropdown shut and making `defaultOpen`
     dead — and `isDisabled`/`isInvalid` would shadow the surrounding `<Field>` context. */
  value: undefined,
  modelValue: undefined,
  open: undefined,
  isOpen: undefined,
  isDisabled: undefined,
  isInvalid: undefined,
});

const emit = defineEmits<{
  /** The `v-model` half. */
  'update:modelValue': [values: ReadonlyArray<string>];
  /** Replaces React's `onValueChange`. */
  'value-change': [values: ReadonlyArray<string>];
  /** The `v-model:open` half. */
  'update:open': [open: boolean];
  /** Replaces React's `onOpenChange`. */
  'open-change': [open: boolean];
}>();

/* `field` is a live-getter object — read fields off it, never destructure. */
const field = useFormControl();

const finalDisabled = computed(() => props.isDisabled ?? field?.isDisabled ?? false);
const finalInvalid = computed(() => props.isInvalid ?? field?.isInvalid);

const openCtl = useControlled<boolean>({
  controlled: () => props.open ?? props.isOpen,
  default: () => props.defaultOpen,
  onChange: (next) => {
    emit('update:open', next);
    emit('open-change', next);
  },
});

const valuesCtl = useControlled<ReadonlyArray<string>>({
  controlled: () => props.value ?? props.modelValue,
  default: () => props.defaultValue ?? [],
  onChange: (next) => {
    emit('update:modelValue', next);
    emit('value-change', next);
  },
});

const labels = ref<Record<string, string | number>>({});

function registerLabel(value: string, label: string | number): void {
  if (labels.value[value] === label) return;
  labels.value = { ...labels.value, [value]: label };
}

function unregisterLabel(value: string): void {
  if (!(value in labels.value)) return;
  const next = { ...labels.value };
  delete next[value];
  labels.value = next;
}

provide<MultiSelectContextValue>(multiSelectContextKey, {
  get open() {
    return openCtl.value.value;
  },
  setOpen: openCtl.setValue,
  get values() {
    return valuesCtl.value.value;
  },
  setValues: valuesCtl.setValue,
  get labels() {
    return labels.value;
  },
  registerLabel,
  unregisterLabel,
  get isDisabled() {
    return finalDisabled.value;
  },
  get name() {
    return props.name;
  },
  get isInvalid() {
    return finalInvalid.value;
  },
  get fieldId() {
    return field?.id;
  },
  get labelId() {
    return field?.labelledBy;
  },
  get describedBy() {
    return field?.describedBy;
  },
});

const isOpenNow = computed(() => openCtl.value.value);
const selected = computed(() => valuesCtl.value.value);
</script>

<template>
  <Popover
    :open="isOpenNow"
    :placement="placement"
    :offset="6"
    @open-change="openCtl.setValue"
  >
    <slot />
    <!-- Always-rendered — inside PopoverContent they would vanish from form submission when closed. -->
    <template v-if="name">
      <input v-for="v in selected" :key="v" type="hidden" :name="name" :value="v" />
    </template>
  </Popover>
</template>

// engineering/codebase/wow-two-front-beta-sdk/src/presentation/forms/multiSelect/MultiSelect.tsx
import {
  createContext,
  forwardRef,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ButtonHTMLAttributes,
  type ReactNode,
} from 'react';
import { ChevronDown, X } from 'lucide-react';
import { cn } from '../../../foundation/utils';
import { useControlled } from '../../../foundation/hooks';
import { useFormControl } from '../../../foundation/primitives/formControlContext/FormControlContext';
import { Popover, PopoverContent, PopoverTrigger } from '../../overlays';
import type { SurfaceVariants } from '../../../foundation/utils';
import {
  Listbox,
  ListboxItem,
  ListboxGroup,
  ListboxSeparator,
  ListboxEmpty,
} from '../listbox';
import { selectTriggerVariants, SelectSize, type SelectTriggerVariants } from '../select/Select.variants';
import { InputState } from '../InputStyles';

interface MultiSelectContextValue {
  open: boolean;
  setOpen: (open: boolean) => void;
  values: ReadonlyArray<string>;
  setValues: (values: ReadonlyArray<string>) => void;
  labels: Record<string, ReactNode>;
  registerLabel: (value: string, label: ReactNode) => void;
  unregisterLabel: (value: string) => void;
  isDisabled: boolean;
  name?: string;
  isInvalid?: boolean;

  /** Form-control wiring inherited from a surrounding `<Field>` (undefined when standalone).
   *  `labelId`/`describedBy` carry only ids of chrome that is actually rendered. */
  fieldId?: string;
  labelId?: string;
  describedBy?: string;
}

const MultiSelectContext = createContext<MultiSelectContextValue | null>(null);

function useMultiSelectContext() {
  const ctx = useContext(MultiSelectContext);
  if (!ctx) throw new Error('MultiSelect.* must be used inside <MultiSelect>');
  return ctx;
}

export interface MultiSelectProps {
  value?: ReadonlyArray<string>;
  defaultValue?: ReadonlyArray<string>;
  onValueChange?: (value: ReadonlyArray<string>) => void;
  isDisabled?: boolean;
  name?: string;
  isInvalid?: boolean;
  defaultOpen?: boolean;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  placement?: React.ComponentProps<typeof Popover>['placement'];
  children: ReactNode;
}

function MultiSelectRoot({
  value,
  defaultValue,
  onValueChange,
  isDisabled,
  name,
  isInvalid,
  defaultOpen = false,
  open: openProp,
  onOpenChange,
  placement = 'bottom',
  children,
}: MultiSelectProps) {
  /* Inherits id/disabled/invalid/labelledby/describedby from a surrounding <Field>;
     standalone props win when provided, context fills the gaps (Select parity). */
  const field = useFormControl();
  const finalDisabled = (isDisabled ?? field?.isDisabled) ?? false;
  const finalInvalid = isInvalid ?? field?.isInvalid;

  const [openState, setOpenState] = useControlled({
    controlled: openProp,
    default: defaultOpen,
    onChange: onOpenChange,
  });
  const [valuesState, setValuesState] = useControlled<ReadonlyArray<string>>({
    controlled: value,
    default: defaultValue ?? [],
    onChange: onValueChange,
  });
  const [labels, setLabels] = useState<Record<string, ReactNode>>({});

  const registerLabel = useCallback((v: string, label: ReactNode) => {
    setLabels((prev) => (prev[v] === label ? prev : { ...prev, [v]: label }));
  }, []);
  const unregisterLabel = useCallback((v: string) => {
    setLabels((prev) => {
      if (!(v in prev)) return prev;
      const next = { ...prev };
      delete next[v];
      return next;
    });
  }, []);

  const ctx = useMemo<MultiSelectContextValue>(
    () => ({
      open: openState,
      setOpen: setOpenState,
      values: valuesState,
      setValues: setValuesState,
      labels,
      registerLabel,
      unregisterLabel,
      isDisabled: finalDisabled,
      name,
      isInvalid: finalInvalid,
      fieldId: field?.id,
      labelId: field?.labelledBy,
      describedBy: field?.describedBy,
    }),
    [
      openState,
      setOpenState,
      valuesState,
      setValuesState,
      labels,
      registerLabel,
      unregisterLabel,
      finalDisabled,
      name,
      finalInvalid,
      field,
    ],
  );

  return (
    <MultiSelectContext.Provider value={ctx}>
      <Popover
        open={openState}
        onOpenChange={setOpenState}
        placement={placement}
        offset={6}
      >
        {children}
        {/* Always-rendered — inside PopoverContent they would vanish from form submission when closed. */}
        {name &&
          valuesState.map((v) => (
            <input key={v} type="hidden" name={name} value={v} />
          ))}
      </Popover>
    </MultiSelectContext.Provider>
  );
}
MultiSelectRoot.displayName = 'MultiSelect';

export interface MultiSelectTriggerProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'children'>,
    Omit<SelectTriggerVariants, 'size' | 'state'> {
  /** The trigger size. */
  size?: SelectSize;
  /** The validity surface. */
  state?: InputState;
  children?: ReactNode;
}

export const MultiSelectTrigger = forwardRef<HTMLButtonElement, MultiSelectTriggerProps>(
  function MultiSelectTrigger(
    { size, state, className, onKeyDown, children, 'aria-label': ariaLabel, ...rest },
    ref,
  ) {
    const ctx = useMultiSelectContext();
    const triggerState = state ?? (ctx.isInvalid ? InputState.Invalid : InputState.Default);
    /* Names the trigger from the Field label when present; an explicit aria-label always wins. */
    const labelledBy = !ariaLabel ? ctx.labelId : undefined;
    return (
      <PopoverTrigger asChild>
        <button
          ref={ref}
          type="button"
          id={ctx.fieldId}
          disabled={ctx.isDisabled}
          aria-invalid={triggerState === InputState.Invalid || undefined}
          aria-label={ariaLabel}
          aria-labelledby={labelledBy}
          aria-describedby={ctx.describedBy}
          onKeyDown={(e) => {
            onKeyDown?.(e);
            if (e.defaultPrevented) return;
            if (e.key === 'Backspace' && ctx.values.length > 0) {
              ctx.setValues(ctx.values.slice(0, -1));
            }
          }}
          className={cn(
            selectTriggerVariants({ size, state: triggerState }),
            'h-auto min-h-10 flex-wrap py-1.5',
            className,
          )}
          {...rest}
        >
          {children ?? <MultiSelectTags />}
          {/* Chevron rotate kept; gated motion-safe so reduced-motion users get an
              instant flip, not a tween. Panel pop-in/out is owned by PopoverContent
              (Presence + --animate-pop-*). */}
          <ChevronDown
            className={cn(
              'h-4 w-4 shrink-0 self-center text-muted-foreground motion-safe:transition-transform',
              ctx.open && 'rotate-180',
            )}
          />
        </button>
      </PopoverTrigger>
    );
  },
);

export interface MultiSelectTagsProps {
  /** The content shown when no values selected. */
  placeholder?: ReactNode;
}

export function MultiSelectTags({ placeholder }: MultiSelectTagsProps) {
  const ctx = useMultiSelectContext();
  if (ctx.values.length === 0) {
    /* `muted-foreground` (not `subtle-foreground`): the trigger surface is muted, where subtle is only 4.2:1 (see index.css). */
    return <span className="text-muted-foreground">{placeholder}</span>;
  }
  return (
    <span className="flex flex-1 flex-wrap items-center gap-1">
      {ctx.values.map((v) => (
        <span
          key={v}
          className="inline-flex items-center gap-1 rounded-sm bg-muted px-1.5 py-0.5 text-xs"
        >
          {ctx.labels[v] ?? v}
          {!ctx.isDisabled && (
            <span
              role="button"
              tabIndex={-1}
              aria-label={`Remove ${typeof ctx.labels[v] === 'string' ? ctx.labels[v] : v}`}
              onClick={(e) => {
                e.stopPropagation();
                ctx.setValues(ctx.values.filter((x) => x !== v));
              }}
              onPointerDown={(e) => e.stopPropagation()}
              className="cursor-pointer rounded-sm p-0.5 hover:bg-border"
            >
              <X className="h-3 w-3" />
            </span>
          )}
        </span>
      ))}
    </span>
  );
}

export interface MultiSelectContentProps extends SurfaceVariants {
  className?: string;
  children: ReactNode;
}

export function MultiSelectContent({
  className,
  variant,
  tone,
  radius,
  padding,
  elevation,
  children,
}: MultiSelectContentProps) {
  const ctx = useMultiSelectContext();
  return (
    <PopoverContent
      variant={variant}
      tone={tone}
      radius={radius}
      padding={padding ?? 'none'}
      elevation={elevation}
      className={cn('w-auto min-w-[var(--anchor-width)] overflow-hidden', className)}
    >
      <Listbox<string>
        isMultiple
        value={ctx.values}
        onValueChange={(v) => ctx.setValues(v)}
        variant="flat"
        radius="none"
      >
        {children}
      </Listbox>
    </PopoverContent>
  );
}

export interface MultiSelectItemProps {
  value: string;
  isDisabled?: boolean;
  className?: string;
  children: ReactNode;
}

export const MultiSelectItem = forwardRef<HTMLDivElement, MultiSelectItemProps>(
  function MultiSelectItem(props, ref) {
    const ctx = useMultiSelectContext();
    /* Stable refs out of ctx — same rationale as SelectItem (see comment there). */
    const { registerLabel } = ctx;
    /* Registers only — never unregisters; items unmount on popover close and the tags still need the labels. */
    useEffect(() => {
      registerLabel(props.value, props.children);
    }, [registerLabel, props.value, props.children]);
    return <ListboxItem ref={ref} {...props} />;
  },
);

export const MultiSelect = Object.assign(MultiSelectRoot, {
  Trigger: MultiSelectTrigger,
  Tags: MultiSelectTags,
  Content: MultiSelectContent,
  Item: MultiSelectItem,
  Group: ListboxGroup,
  Separator: ListboxSeparator,
  Empty: ListboxEmpty,
});

export default MultiSelect;
