// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/countBadge/CountBadge.vue
<script lang="ts">
import type { BadgeVariant } from '../badge/Badge.variants';

export interface CountBadgeProps {
  /** The numeric count. */
  value: number;

  /** The cap value — shows "max+" when exceeded. Default 99. */
  max?: number;

  /** The hide-when-zero mode — hides entirely when count is 0. Default true. */
  canHideZero?: boolean;

  /**
   * The color treatment. React spelled this `BadgeProps['variant']`; the named
   * `BadgeVariant` union it resolves to is used directly, because the SFC
   * compiler cannot follow an indexed access into an imported interface.
   */
  variant?: BadgeVariant;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { cn, Size } from '../../../foundation/utils';
import { BadgeVariant as BadgeVariantValue } from '../badge/Badge.variants';
import Badge from '../badge/Badge.vue';

/**
 * Numeric badge for notification / inbox counts. Shows "{value}" or "{max}+"
 * past the cap. Hides when `value === 0` unless `:can-hide-zero="false"`.
 */
defineOptions({ name: 'CountBadge', inheritAttrs: false });

const props = withDefaults(defineProps<CountBadgeProps>(), {
  max: 99,
  canHideZero: true,
  variant: BadgeVariantValue.Danger,
});

const attrs = useAttrs();
const inner = useTemplateRef<InstanceType<typeof Badge>>('inner');

/** The inner `Badge`'s root element — the React original's forwarded ref. */
const el = computed(() => inner.value?.el ?? null);

/** React returned `null` at zero; Vue renders nothing through `v-if`. */
const isVisible = computed(() => !(props.value === 0 && props.canHideZero));

const display = computed(() => (props.value > props.max ? `${props.max}+` : `${props.value}`));

const classes = computed(() =>
  cn('min-w-5 justify-center px-1.5', attrs.class as string | undefined),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <Badge
    v-if="isVisible"
    ref="inner"
    :variant="props.variant"
    :size="Size.Sm"
    v-bind="rest"
    :class="classes"
    >{{ display }}</Badge
  >
</template>

// src/presentation/display/countBadge/CountBadge.tsx
import { forwardRef, type ComponentPropsWithoutRef } from 'react';
import { cn } from '../../../foundation/utils';
import { Badge, type BadgeProps } from '../badge/Badge';

export interface CountBadgeProps extends Omit<ComponentPropsWithoutRef<'span'>, 'children'> {
  /** The numeric count. */
  value: number;
  /** Cap value — shows "max+" when exceeded. Default 99. */
  max?: number;
  /** Hide entirely when count is 0. Default true. */
  canHideZero?: boolean;
  variant?: BadgeProps['variant'];
}

/**
 * Numeric badge for notification / inbox counts. Shows "{value}" or "{max}+"
 * past the cap. Hides when `value === 0` unless `canHideZero={false}`.
 */
export const CountBadge = forwardRef<HTMLSpanElement, CountBadgeProps>(
  ({ value, max = 99, canHideZero = true, variant = 'danger', className, ...props }, ref) => {
    if (value === 0 && canHideZero) return null;
    const display = value > max ? `${max}+` : `${value}`;
    return (
      <Badge
        ref={ref}
        variant={variant}
        size="sm"
        className={cn('min-w-5 justify-center px-1.5', className)}
        {...props}
      >
        {display}
      </Badge>
    );
  },
);
CountBadge.displayName = 'CountBadge';
