// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/overlays/hoverCard/HoverCard.vue
<script lang="ts">
import { inject, type ComputedRef, type InjectionKey, type Ref, type ShallowRef } from 'vue';
import type { Placement } from '@floating-ui/vue';

/** The value shared with `HoverCardTrigger` / `HoverCardContent`. */
export interface HoverCardContextValue {
  /** The resolved open state. Writable — an assignment routes through `setOpen`. */
  open: Ref<boolean>;
  setOpen: (open: boolean) => void;
  /** The trigger element — the positioning anchor. */
  triggerEl: ShallowRef<HTMLElement | null>;
  /** Opens after `openDelay`. */
  show: () => void;
  /** Closes after `closeDelay`. */
  hide: () => void;
  /** Cancels a pending close — the pointer moved onto the card. */
  cancelHide: () => void;
  placement: ComputedRef<Placement>;
  offset: ComputedRef<number>;
}

export const hoverCardContextKey: InjectionKey<HoverCardContextValue> = Symbol('wow-two.hoverCard');

export function useHoverCardContext(): HoverCardContextValue {
  const context = inject(hoverCardContextKey, null);
  if (!context) throw new Error('HoverCard.* must be used inside <HoverCard>');
  return context;
}

/**
 * The prop surface of `HoverCard`.
 *
 * `open` and `isOpen` are the same controlled state under two names: `open` is
 * the `v-model:open` binding target, `isOpen` the house boolean spelling that
 * mirrors the rest of the port. `open` wins when both are set. React's
 * `onOpenChange` is the `open-change` emit; `update:open` fires alongside it so
 * `v-model:open` works.
 */
export interface HoverCardProps {
  /** The open state, controlled. The `v-model:open` binding target. */
  open?: boolean;

  /** The open state, controlled — the house spelling of `open`; `open` wins when both are set. */
  isOpen?: boolean;

  /** The initial open state when uncontrolled. Default `false`. */
  defaultOpen?: boolean;

  /** The hover dwell before opening, in ms. Default 700. */
  openDelay?: number;

  /** The grace period before closing, in ms. Default 300. */
  closeDelay?: number;

  /** The Floating UI placement. Default `bottom`. */
  placement?: Placement;

  /** The distance between anchor and card in px. Default 8. */
  offset?: number;
}
</script>

<script setup lang="ts">
import { computed, onScopeDispose, provide, shallowRef } from 'vue';
import { useControlled, useEscape } from '../../../foundation/hooks';

/**
 * State + hover-timing owner for a HoverCard tree. Renders only its slot —
 * React returned a bare context Provider, which has no element of its own.
 */
defineOptions({ name: 'HoverCard', inheritAttrs: false });

/** The HoverCard tree — `HoverCardTrigger` and `HoverCardContent`. React's `children`. */
defineSlots<{ default(): unknown }>();

/** `open` / `isOpen` default to `undefined` so an absent prop cannot read as an explicit `false`. */
const props = withDefaults(defineProps<HoverCardProps>(), {
  open: undefined,
  isOpen: undefined,
  defaultOpen: false,
  openDelay: 700,
  closeDelay: 300,
  placement: 'bottom',
  offset: 8,
});

const emit = defineEmits<{
  /** The `v-model:open` half. */
  'update:open': [open: boolean];
  /** Replaces React's `onOpenChange`. */
  'open-change': [open: boolean];
}>();

const controlled = useControlled<boolean>({
  controlled: () => (props.open !== undefined ? props.open : props.isOpen),
  default: () => props.defaultOpen,
  onChange: (value) => {
    emit('update:open', value);
    emit('open-change', value);
  },
});

const triggerEl = shallowRef<HTMLElement | null>(null);

let openTimer: ReturnType<typeof setTimeout> | null = null;
let closeTimer: ReturnType<typeof setTimeout> | null = null;

function clear(): void {
  if (openTimer) clearTimeout(openTimer);
  if (closeTimer) clearTimeout(closeTimer);
  openTimer = null;
  closeTimer = null;
}

function show(): void {
  clear();
  openTimer = setTimeout(() => controlled.setValue(true), props.openDelay);
}

function hide(): void {
  clear();
  closeTimer = setTimeout(() => controlled.setValue(false), props.closeDelay);
}

function cancelHide(): void {
  if (closeTimer) {
    clearTimeout(closeTimer);
    closeTimer = null;
  }
}

/* Clear pending timers on teardown — React's `useEffect(() => clear, …)`. */
onScopeDispose(clear);

// WCAG 1.4.13 — hover content must be dismissible without moving the pointer.
useEscape(
  () => {
    clear();
    controlled.setValue(false);
  },
  () => controlled.value.value,
);

provide(hoverCardContextKey, {
  open: controlled.value,
  setOpen: controlled.setValue,
  triggerEl,
  show,
  hide,
  cancelHide,
  placement: computed(() => props.placement),
  offset: computed(() => props.offset),
});
</script>

<template>
  <slot />
</template>

// src/overlays/hoverCard/HoverCard.tsx
import {
  cloneElement,
  createContext,
  forwardRef,
  isValidElement,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  type HTMLAttributes,
  type ReactElement,
  type ReactNode,
  type Ref,
} from 'react';
import { cn, composeRefs } from '../../utils';
import { useControlled, useEscape } from '../../hooks';
import {
  AnchoredPositioner,
  OverlayArrow,
  Portal,
  Presence,
  type AnchoredPositionerProps,
  type OverlayArrowProps,
} from '../../primitives';

interface HoverCardContextValue {
  open: boolean;
  setOpen: (open: boolean) => void;
  triggerRef: React.MutableRefObject<HTMLElement | null>;
  show: () => void;
  hide: () => void;
  cancelHide: () => void;
  placement: AnchoredPositionerProps['placement'];
  offset: number;
}

const HoverCardContext = createContext<HoverCardContextValue | null>(null);

function useHoverCardContext() {
  const ctx = useContext(HoverCardContext);
  if (!ctx) throw new Error('HoverCard.* must be used inside <HoverCard>');
  return ctx;
}

export interface HoverCardProps {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  openDelay?: number;
  closeDelay?: number;
  placement?: AnchoredPositionerProps['placement'];
  offset?: number;
  children: ReactNode;
}

function HoverCardRoot({
  open: openProp,
  defaultOpen = false,
  onOpenChange,
  openDelay = 700,
  closeDelay = 300,
  placement = 'bottom',
  offset = 8,
  children,
}: HoverCardProps) {
  const [open, setOpen] = useControlled({
    controlled: openProp,
    default: defaultOpen,
    onChange: onOpenChange,
  });
  const triggerRef = useRef<HTMLElement | null>(null);
  const openTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const closeTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const clear = useCallback(() => {
    if (openTimer.current) clearTimeout(openTimer.current);
    if (closeTimer.current) clearTimeout(closeTimer.current);
    openTimer.current = null;
    closeTimer.current = null;
  }, []);

  const show = useCallback(() => {
    clear();
    openTimer.current = setTimeout(() => setOpen(true), openDelay);
  }, [clear, openDelay, setOpen]);

  const hide = useCallback(() => {
    clear();
    closeTimer.current = setTimeout(() => setOpen(false), closeDelay);
  }, [clear, closeDelay, setOpen]);

  const cancelHide = useCallback(() => {
    if (closeTimer.current) {
      clearTimeout(closeTimer.current);
      closeTimer.current = null;
    }
  }, []);

  // Clear pending timers on unmount — avoids setState-after-unmount.
  useEffect(() => clear, [clear]);

  // WCAG 1.4.13 — hover content must be dismissible without moving the pointer.
  useEscape(() => {
    clear();
    setOpen(false);
  }, open);

  const ctx = useMemo<HoverCardContextValue>(
    () => ({ open, setOpen, triggerRef, show, hide, cancelHide, placement, offset }),
    [open, setOpen, show, hide, cancelHide, placement, offset],
  );

  return <HoverCardContext.Provider value={ctx}>{children}</HoverCardContext.Provider>;
}
HoverCardRoot.displayName = 'HoverCard';

export interface HoverCardTriggerProps {
  asChild?: boolean;
  children: ReactElement;
}

export function HoverCardTrigger({ children }: HoverCardTriggerProps) {
  const ctx = useHoverCardContext();
  if (!isValidElement(children)) return children;
  const trigger = children as ReactElement<{
    ref?: Ref<HTMLElement>;
    onPointerEnter?: (e: React.PointerEvent) => void;
    onPointerLeave?: (e: React.PointerEvent) => void;
    onFocus?: (e: React.FocusEvent) => void;
    onBlur?: (e: React.FocusEvent) => void;
  }> & { ref?: Ref<HTMLElement> };

  return cloneElement(trigger, {
    ref: composeRefs((node: HTMLElement | null) => {
      ctx.triggerRef.current = node;
    }, trigger.ref),
    onPointerEnter: (e: React.PointerEvent) => {
      trigger.props.onPointerEnter?.(e);
      ctx.show();
    },
    onPointerLeave: (e: React.PointerEvent) => {
      trigger.props.onPointerLeave?.(e);
      ctx.hide();
    },
    onFocus: (e: React.FocusEvent) => {
      trigger.props.onFocus?.(e);
      ctx.show();
    },
    onBlur: (e: React.FocusEvent) => {
      trigger.props.onBlur?.(e);
      ctx.hide();
    },
  });
}

export interface HoverCardContentProps extends HTMLAttributes<HTMLDivElement> {
  children: ReactNode;
}

/*
 * Presence clones its single child and injects `ref` + `data-state` onto it,
 * so that child must be the animated element. Portal/AnchoredPositioner can't
 * carry those props down to the styled div, so this forwardRef panel bridges
 * them: Presence drives this panel, the panel renders the Portal → positioner
 * tree, and forwards `ref` + the injected `data-state` (via `...rest`) onto the
 * inner div that carries the pop transition.
 */
const HoverCardPanel = forwardRef<HTMLDivElement, HoverCardContentProps>(
  function HoverCardPanel({ className, children, onPointerEnter, onPointerLeave, ...rest }, forwardedRef) {
    const ctx = useHoverCardContext();
    return (
      <Portal>
        <AnchoredPositioner
          anchor={ctx.triggerRef.current}
          placement={ctx.placement}
          offset={ctx.offset}
          className="z-dropdown"
        >
          <div
            ref={forwardedRef}
            onPointerEnter={(e) => {
              onPointerEnter?.(e);
              ctx.cancelHide();
            }}
            onPointerLeave={(e) => {
              onPointerLeave?.(e);
              ctx.hide();
            }}
            className={cn(
              'w-64 rounded-md border border-border bg-popover p-4 text-popover-foreground shadow-md outline-none',
              'motion-safe:data-[state=open]:animate-(--animate-pop-in) motion-safe:data-[state=closed]:animate-(--animate-pop-out) motion-reduce:animate-none',
              className,
            )}
            {...rest}
          >
            {children}
          </div>
        </AnchoredPositioner>
      </Portal>
    );
  },
);

export const HoverCardContent = forwardRef<HTMLDivElement, HoverCardContentProps>(
  function HoverCardContent(props, forwardedRef) {
    const ctx = useHoverCardContext();
    return (
      <Presence isPresent={ctx.open}>
        <HoverCardPanel ref={forwardedRef} {...props} />
      </Presence>
    );
  },
);

export function HoverCardArrow({ className, ...rest }: OverlayArrowProps) {
  return <OverlayArrow className={cn('text-popover', className)} {...rest} />;
}

export const HoverCard = Object.assign(HoverCardRoot, {
  Trigger: HoverCardTrigger,
  Content: HoverCardContent,
  Arrow: HoverCardArrow,
});

export default HoverCard;
