// src/presentation/feedback/toaster/Toaster.tsx
import {
  forwardRef,
  useEffect,
  useMemo,
  useRef,
  useState,
  type HTMLAttributes,
  type ReactNode,
} from 'react';
import { cn } from '../../../foundation/utils';
import { Announce, Portal, Presence } from '../../../foundation/primitives';
import { Toast } from '../toast';
import type { ToastSimpleVariants } from '../toastSimple/ToastSimple.variants';

export type ToastSeverity = NonNullable<ToastSimpleVariants['severity']>;

export type ToasterPosition =
  | 'top-right'
  | 'top-left'
  | 'top-center'
  | 'bottom-right'
  | 'bottom-left'
  | 'bottom-center';

export interface ToastOptions {
  title?: ReactNode;
  description?: ReactNode;
  icon?: ReactNode;
  severity?: ToastSeverity;
  /** ms before auto-dismiss. Default: Toaster's `defaultDuration`. `Infinity` = sticky. */
  duration?: number;
  action?: ReactNode;
}

interface ToastEntry extends ToastOptions {
  id: string;
}

type Listener = (toasts: ToastEntry[]) => void;

class ToasterStore {
  private items: ToastEntry[] = [];
  private listeners = new Set<Listener>();
  private idSeq = 0;

  toast(opts: ToastOptions): string {
    const id = `t_${++this.idSeq}`;
    this.items = [...this.items, { id, ...opts }];
    this.emit();
    return id;
  }

  dismiss(id: string): void {
    this.items = this.items.filter((t) => t.id !== id);
    this.emit();
  }

  dismissAll(): void {
    this.items = [];
    this.emit();
  }

  subscribe(fn: Listener): () => void {
    this.listeners.add(fn);
    fn(this.items);
    return () => {
      this.listeners.delete(fn);
    };
  }

  private emit() {
    for (const fn of this.listeners) fn(this.items);
  }
}

export const toaster = new ToasterStore();

export function useToaster() {
  return useMemo(
    () => ({
      toast: (opts: ToastOptions) => toaster.toast(opts),
      dismiss: (id: string) => toaster.dismiss(id),
      dismissAll: () => toaster.dismissAll(),
    }),
    [],
  );
}

const POSITION_CLASSES: Record<ToasterPosition, string> = {
  'top-right': 'top-4 right-4 items-end',
  'top-left': 'top-4 left-4 items-start',
  'top-center': 'top-4 left-1/2 -translate-x-1/2 items-center',
  'bottom-right': 'bottom-4 right-4 items-end',
  'bottom-left': 'bottom-4 left-4 items-start',
  'bottom-center': 'bottom-4 left-1/2 -translate-x-1/2 items-center',
};

/**
 * Enter/exit animation per position, gated on `data-state` (set by `Presence`)
 * and `motion-safe:` so reduced-motion users get an instant swap. Corner
 * toasts slide along their horizontal edge; centered toasts slide along the
 * vertical axis they're anchored to. Exit anims are shorter (`--duration-fast`).
 */
const MOTION_CLASSES: Record<ToasterPosition, string> = {
  'top-right':
    'motion-safe:data-[state=open]:animate-(--animate-slide-in-right) motion-safe:data-[state=closed]:animate-(--animate-slide-out-right) motion-reduce:animate-none',
  'top-left':
    'motion-safe:data-[state=open]:animate-(--animate-slide-in-left) motion-safe:data-[state=closed]:animate-(--animate-slide-out-left) motion-reduce:animate-none',
  'top-center':
    'motion-safe:data-[state=open]:animate-(--animate-slide-in-top) motion-safe:data-[state=closed]:animate-(--animate-slide-out-top) motion-reduce:animate-none',
  'bottom-right':
    'motion-safe:data-[state=open]:animate-(--animate-slide-in-right) motion-safe:data-[state=closed]:animate-(--animate-slide-out-right) motion-reduce:animate-none',
  'bottom-left':
    'motion-safe:data-[state=open]:animate-(--animate-slide-in-left) motion-safe:data-[state=closed]:animate-(--animate-slide-out-left) motion-reduce:animate-none',
  'bottom-center':
    'motion-safe:data-[state=open]:animate-(--animate-slide-in-bottom) motion-safe:data-[state=closed]:animate-(--animate-slide-out-bottom) motion-reduce:animate-none',
};

export interface ToasterProps {
  position?: ToasterPosition;
  max?: number;
  /** ms; per-toast `duration` overrides. Default 5000. `Infinity` to disable. */
  defaultDuration?: number;
  canPauseOnHover?: boolean;
  gap?: number;
  className?: string;
}

interface VisibleToast extends ToastEntry {
  resolvedDuration: number;
}

/**
 * Per-toast animated wrapper. `forwardRef` + `{...props}` spread so the
 * `data-state` Presence sets lands on this node (and Presence can ref it to
 * await `animationend` before unmount). Carries the slide+fade motion classes.
 *
 * Runs an unmount-only cleanup that calls `onRemoved` — since `Presence` keeps
 * this child mounted until its exit animation ends, that cleanup is our
 * "exit finished" signal (the read-only `Presence` API exposes no callback).
 */
interface ToastItemProps extends HTMLAttributes<HTMLDivElement> {
  motionClass: string;
  onRemoved?: () => void;
}

const ToastItem = forwardRef<HTMLDivElement, ToastItemProps>(
  ({ motionClass, onRemoved, className, children, ...props }, ref) => {
    const onRemovedRef = useRef(onRemoved);
    onRemovedRef.current = onRemoved;
    useEffect(() => () => onRemovedRef.current?.(), []);
    return (
      <div
        ref={ref}
        className={cn('pointer-events-auto w-80', motionClass, className)}
        {...props}
      >
        {children}
      </div>
    );
  },
);
ToastItem.displayName = 'ToastItem';

/**
 * Viewport that subscribes to the global `toaster` store and renders toasts
 * via the L4 `Toast` molecule. Mount once, per app.
 */
export function Toaster({
  position = 'bottom-right',
  max = 5,
  defaultDuration = 5000,
  canPauseOnHover = true,
  gap = 8,
  className,
}: ToasterProps) {
  const [items, setItems] = useState<ToastEntry[]>([]);
  const [paused, setPaused] = useState(false);
  const timersRef = useRef(new Map<string, number>());
  const remainingRef = useRef(new Map<string, number>());
  const startRef = useRef(new Map<string, number>());

  useEffect(() => {
    return toaster.subscribe(setItems);
  }, []);

  // Visible window (FIFO).
  const visible: VisibleToast[] = items.slice(0, max).map((t) => ({
    ...t,
    resolvedDuration: t.duration ?? defaultDuration,
  }));
  const visibleIds = useMemo(() => new Set(visible.map((v) => v.id)), [visible]);

  // Toasts that just left `visible` (dismissed, or pushed out of the FIFO
  // window) but must still play their exit animation. Kept mounted with
  // `data-state="closed"` until `Presence` unmounts the child — `ToastItem`
  // then fires `onRemoved`, pruning the entry here.
  const [exiting, setExiting] = useState<VisibleToast[]>([]);
  const prevVisibleRef = useRef<VisibleToast[]>([]);

  useEffect(() => {
    const gone = prevVisibleRef.current.filter((p) => !visibleIds.has(p.id));
    prevVisibleRef.current = visible;
    setExiting((cur) => {
      const known = new Set(cur.map((e) => e.id));
      // Add newly-gone toasts; drop any that re-entered `visible`.
      const merged = [...cur, ...gone.filter((g) => !known.has(g.id))].filter(
        (e) => !visibleIds.has(e.id),
      );
      return merged.length === cur.length &&
        merged.every((e, i) => e.id === cur[i]?.id)
        ? cur
        : merged;
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [visibleIds]);

  const removeExiting = (id: string) =>
    setExiting((cur) => cur.filter((e) => e.id !== id));

  // Visible (present) first, then the ones animating out.
  const rendered: Array<VisibleToast & { present: boolean }> = [
    ...visible.map((v) => ({ ...v, present: true })),
    ...exiting.map((e) => ({ ...e, present: false })),
  ];

  const latestTitle =
    typeof visible[visible.length - 1]?.title === 'string'
      ? (visible[visible.length - 1]!.title as string)
      : visible[visible.length - 1]?.description && typeof visible[visible.length - 1]!.description === 'string'
        ? (visible[visible.length - 1]!.description as string)
        : '';

  // Schedule auto-dismiss timers.
  useEffect(() => {
    const ids = new Set(visible.map((v) => v.id));
    // Clear timers for items that are no longer visible.
    for (const [id, h] of timersRef.current) {
      if (!ids.has(id)) {
        window.clearTimeout(h);
        timersRef.current.delete(id);
        remainingRef.current.delete(id);
        startRef.current.delete(id);
      }
    }
    if (paused) return;
    for (const v of visible) {
      if (v.resolvedDuration === Infinity) continue;
      if (timersRef.current.has(v.id)) continue;
      const remaining = remainingRef.current.get(v.id) ?? v.resolvedDuration;
      const handle = window.setTimeout(() => {
        toaster.dismiss(v.id);
      }, remaining);
      timersRef.current.set(v.id, handle);
      startRef.current.set(v.id, Date.now());
      remainingRef.current.set(v.id, remaining);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [items, max, defaultDuration, paused]);

  // Cleanup on unmount.
  useEffect(() => {
    const timers = timersRef.current;
    return () => {
      for (const h of timers.values()) window.clearTimeout(h);
      timers.clear();
    };
  }, []);

  const handlePause = () => {
    if (!canPauseOnHover || paused) return;
    setPaused(true);
    for (const [id, h] of timersRef.current) {
      window.clearTimeout(h);
      const start = startRef.current.get(id) ?? Date.now();
      const prev = remainingRef.current.get(id) ?? 0;
      const elapsed = Date.now() - start;
      remainingRef.current.set(id, Math.max(0, prev - elapsed));
    }
    timersRef.current.clear();
  };

  const handleResume = () => {
    if (!canPauseOnHover || !paused) return;
    setPaused(false);
  };

  if (rendered.length === 0) {
    return (
      <Portal>
        <Announce politeness="polite" />
      </Portal>
    );
  }

  return (
    <Portal>
      <div
        aria-label="Notifications"
        onMouseEnter={handlePause}
        onMouseLeave={handleResume}
        onFocus={handlePause}
        onBlur={handleResume}
        style={{ gap }}
        className={cn(
          'pointer-events-none fixed z-toast flex flex-col',
          POSITION_CLASSES[position],
          className,
        )}
      >
        {rendered.map((t) => (
          <Presence key={t.id} isPresent={t.present}>
            <ToastItem
              motionClass={MOTION_CLASSES[position]}
              onRemoved={t.present ? undefined : () => removeExiting(t.id)}
            >
              <Toast
                icon={t.icon}
                title={t.title}
                description={t.description}
                severity={t.severity}
                actions={t.action}
                onClose={() => toaster.dismiss(t.id)}
              />
            </ToastItem>
          </Presence>
        ))}
      </div>
      <Announce politeness="polite">{latestTitle}</Announce>
    </Portal>
  );
}

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/feedback/toaster/Toaster.vue
<script lang="ts">
import type { VNode } from 'vue';
import type { OverlayPosition } from '../../../foundation/utils';
import type { ToastSimpleVariants } from '../toastSimple/ToastSimple.variants';

export type ToastSeverity = NonNullable<ToastSimpleVariants['severity']>;

/**
 * A renderable slice of a toast. React's `ReactNode` becomes `string | VNode`:
 * these travel through the imperative `toaster.toast()` payload, not through a
 * slot, so a caller who wants markup builds it with `h()`.
 */
export type ToastNode = string | VNode;

export interface ToastOptions {
  title?: ToastNode;
  description?: ToastNode;
  icon?: ToastNode;
  severity?: ToastSeverity;
  /** ms before auto-dismiss. Default: Toaster's `defaultDuration`. `Infinity` = sticky. */
  duration?: number;
  action?: ToastNode;
  /** Fully custom body — replaces the default `Toast` chrome (icon/title/description/close). The toast still animates + auto-dismisses; the content owns its own close via the returned id. */
  content?: ToastNode;
  /** Fired when the toast is removed — auto-dismiss, close button, `dismiss(id)`, or `dismissAll()` (NOT on a dedup-update). For undo cleanup / analytics. */
  onDismiss?: () => void;
  /** Dedup key — a `toast` whose `key` is already showing updates that toast in place (refreshing its timer) instead of stacking a duplicate. */
  key?: string;
}

/** Content for a `toaster.promise` phase — a title string, or a full partial options object. */
export type ToastContent = string | Partial<ToastOptions>;

/** Options for `toaster.promise` — loading / success / error content (success + error may be a fn of the settled value). */
export interface ToastPromiseOptions<T> {
  loading: ToastContent;
  success: ToastContent | ((value: T) => ToastContent);
  error: ToastContent | ((err: unknown) => ToastContent);
  /** Auto-dismiss (ms) for the settled toast; defaults to the Toaster's `defaultDuration`. */
  duration?: number;
}

function normalizeContent(content: ToastContent): Partial<ToastOptions> {
  return typeof content === 'string' ? { title: content } : content;
}

interface ToastEntry extends ToastOptions {
  id: string;
  /** Bumped on every `update` / dedup so the viewport can reset that toast's auto-dismiss timer. */
  nonce: number;
}

type Listener = (toasts: ReadonlyArray<ToastEntry>) => void;

class ToasterStore {
  private items: ReadonlyArray<ToastEntry> = [];
  private listeners = new Set<Listener>();
  private idSeq = 0;

  toast(opts: ToastOptions): string {
    if (opts.key !== undefined) {
      const existing = this.items.find((t) => t.key === opts.key);
      if (existing) {
        this.update(existing.id, opts);
        return existing.id;
      }
    }
    const id = `t_${++this.idSeq}`;
    this.items = [...this.items, { id, ...opts, nonce: 0 }];
    this.emit();
    return id;
  }

  /** Merges a patch into an existing toast (content + severity + duration), refreshing its timer. */
  update(id: string, patch: Partial<ToastOptions>): void {
    this.items = this.items.map((t) => (t.id === id ? { ...t, ...patch, nonce: t.nonce + 1 } : t));
    this.emit();
  }

  /** Shows a sticky loading toast, then updates it in place to success / error when `promise` settles. Returns `promise`. */
  promise<T>(promise: Promise<T>, opts: ToastPromiseOptions<T>): Promise<T> {
    const id = this.toast({ ...normalizeContent(opts.loading), severity: 'info', duration: Infinity });
    const settle = (content: ToastContent, severity: ToastSeverity) =>
      this.update(id, { ...normalizeContent(content), severity, duration: opts.duration });
    promise.then(
      (value) => settle(typeof opts.success === 'function' ? opts.success(value) : opts.success, 'success'),
      (err) => settle(typeof opts.error === 'function' ? opts.error(err) : opts.error, 'danger'),
    );
    return promise;
  }

  dismiss(id: string): void {
    const entry = this.items.find((t) => t.id === id);
    this.items = this.items.filter((t) => t.id !== id);
    entry?.onDismiss?.();
    this.emit();
  }

  dismissAll(): void {
    const gone = this.items;
    this.items = [];
    for (const t of gone) t.onDismiss?.();
    this.emit();
  }

  subscribe(fn: Listener): () => void {
    this.listeners.add(fn);
    fn(this.items);
    return () => {
      this.listeners.delete(fn);
    };
  }

  private emit() {
    for (const fn of this.listeners) fn(this.items);
  }
}

export const toaster = new ToasterStore();

/**
 * The imperative toast API, bound to the app-wide store. Plain object rather
 * than React's `useMemo` — the store is a module singleton, so there is nothing
 * per-instance to memoize.
 */
export function useToaster() {
  return {
    toast: (opts: ToastOptions) => toaster.toast(opts),
    update: (id: string, patch: Partial<ToastOptions>) => toaster.update(id, patch),
    promise: <T,>(promise: Promise<T>, opts: ToastPromiseOptions<T>) => toaster.promise(promise, opts),
    dismiss: (id: string) => toaster.dismiss(id),
    dismissAll: () => toaster.dismissAll(),
  };
}

const POSITION_CLASSES: Record<OverlayPosition, string> = {
  'top-right': 'top-4 right-4 items-end',
  'top-left': 'top-4 left-4 items-start',
  'top-center': 'top-4 left-1/2 -translate-x-1/2 items-center',
  'bottom-right': 'bottom-4 right-4 items-end',
  'bottom-left': 'bottom-4 left-4 items-start',
  'bottom-center': 'bottom-4 left-1/2 -translate-x-1/2 items-center',
};

/**
 * Enter/exit animation per position, gated on `data-state` (set by `Presence`)
 * and `motion-safe:` so reduced-motion users get an instant swap. Corner
 * toasts slide along their horizontal edge; centered toasts slide along the
 * vertical axis they're anchored to. Exit anims are shorter (`--duration-fast`).
 */
const MOTION_CLASSES: Record<OverlayPosition, string> = {
  'top-right':
    'motion-safe:data-[state=open]:animate-(--animate-slide-in-right) motion-safe:data-[state=closed]:animate-(--animate-slide-out-right) motion-reduce:animate-none',
  'top-left':
    'motion-safe:data-[state=open]:animate-(--animate-slide-in-left) motion-safe:data-[state=closed]:animate-(--animate-slide-out-left) motion-reduce:animate-none',
  'top-center':
    'motion-safe:data-[state=open]:animate-(--animate-slide-in-top) motion-safe:data-[state=closed]:animate-(--animate-slide-out-top) motion-reduce:animate-none',
  'bottom-right':
    'motion-safe:data-[state=open]:animate-(--animate-slide-in-right) motion-safe:data-[state=closed]:animate-(--animate-slide-out-right) motion-reduce:animate-none',
  'bottom-left':
    'motion-safe:data-[state=open]:animate-(--animate-slide-in-left) motion-safe:data-[state=closed]:animate-(--animate-slide-out-left) motion-reduce:animate-none',
  'bottom-center':
    'motion-safe:data-[state=open]:animate-(--animate-slide-in-bottom) motion-safe:data-[state=closed]:animate-(--animate-slide-out-bottom) motion-reduce:animate-none',
};

export interface ToasterProps {
  position?: OverlayPosition;
  max?: number;
  /** The default auto-dismiss delay in ms; per-toast `duration` overrides. Default 5000. `Infinity` to disable. */
  defaultDuration?: number;
  canPauseOnHover?: boolean;
  gap?: number;
}

interface VisibleToast extends ToastEntry {
  resolvedDuration: number;
}
</script>

<script setup lang="ts">
import {
  computed,
  defineComponent,
  onMounted,
  onUnmounted,
  ref,
  shallowRef,
  useAttrs,
  watch,
  type PropType,
} from 'vue';
import { cn, OverlayPosition as OverlayPositionToken } from '../../../foundation/utils';
import { Announce, Portal, Presence } from '../../../foundation/primitives';
import Toast from '../toast/Toast.vue';

/** Renders a `ToastNode` — either a plain string or a caller-built VNode. */
const ToastNodeView = defineComponent({
  name: 'ToastNodeView',
  props: { node: { type: [String, Object] as PropType<ToastNode>, required: true } },
  setup: (nodeProps) => () => nodeProps.node,
});

/**
 * Viewport that subscribes to the global `toaster` store and renders toasts
 * via the L4 `Toast` molecule. Mount once, per app.
 *
 * React's `className` arrives as the ordinary `class` attr and lands on the
 * stack container, the same node it landed on in React.
 */
defineOptions({ name: 'Toaster', inheritAttrs: false });

const props = withDefaults(defineProps<ToasterProps>(), {
  position: OverlayPositionToken.BottomRight,
  max: 5,
  defaultDuration: 5000,
  canPauseOnHover: true,
  gap: 8,
});

const attrs = useAttrs();

const items = shallowRef<ReadonlyArray<ToastEntry>>([]);
const paused = ref(false);

/* `useRef` counterparts — mutated across ticks, never rendered. */
const timers = new Map<string, number>();
const remaining = new Map<string, number>();
const startedAt = new Map<string, number>();
const nonces = new Map<string, number>();

let unsubscribe: (() => void) | undefined;
onMounted(() => {
  unsubscribe = toaster.subscribe((next) => {
    items.value = next;
  });
});

// Visible window (FIFO).
const visible = computed<ReadonlyArray<VisibleToast>>(() =>
  items.value.slice(0, props.max).map((t) => ({
    ...t,
    resolvedDuration: t.duration ?? props.defaultDuration,
  })),
);
const visibleIds = computed(() => new Set(visible.value.map((v) => v.id)));

// Toasts that just left `visible` (dismissed, or pushed out of the FIFO
// window) but must still play their exit animation. Kept mounted with
// `data-state="closed"` until `Presence` unmounts the child — the `@vue:unmounted`
// hook below then prunes the entry here.
const exiting = shallowRef<ReadonlyArray<VisibleToast>>([]);
let prevVisible: ReadonlyArray<VisibleToast> = [];

watch(
  visibleIds,
  (ids) => {
    const gone = prevVisible.filter((p) => !ids.has(p.id));
    prevVisible = visible.value;
    const current = exiting.value;
    const known = new Set(current.map((e) => e.id));
    // Add newly-gone toasts; drop any that re-entered `visible`.
    const merged = [...current, ...gone.filter((g) => !known.has(g.id))].filter(
      (e) => !ids.has(e.id),
    );
    if (merged.length !== current.length || !merged.every((e, i) => e.id === current[i]?.id)) {
      exiting.value = merged;
    }
  },
  { immediate: true, flush: 'post' },
);

const removeExiting = (id: string) => {
  exiting.value = exiting.value.filter((e) => e.id !== id);
};

// Visible (present) first, then the ones animating out.
const rendered = computed<Array<VisibleToast & { present: boolean }>>(() => [
  ...visible.value.map((v) => ({ ...v, present: true })),
  ...exiting.value.map((e) => ({ ...e, present: false })),
]);

const latestTitle = computed(() => {
  const last = visible.value[visible.value.length - 1];
  if (typeof last?.title === 'string') return last.title;
  if (typeof last?.description === 'string') return last.description;
  return '';
});

// Schedule auto-dismiss timers.
watch(
  [items, () => props.max, () => props.defaultDuration, paused],
  () => {
    const ids = visibleIds.value;
    // Clear timers for items that are no longer visible.
    for (const [id, handle] of timers) {
      if (!ids.has(id)) {
        window.clearTimeout(handle);
        timers.delete(id);
        remaining.delete(id);
        startedAt.delete(id);
      }
    }
    for (const id of nonces.keys()) {
      if (!ids.has(id)) nonces.delete(id);
    }
    if (paused.value) return;
    // A content update / dedup bumps `nonce` — clear that toast's timer so it reschedules fresh.
    for (const v of visible.value) {
      const seen = nonces.get(v.id);
      if (seen !== undefined && seen !== v.nonce) {
        const handle = timers.get(v.id);
        if (handle !== undefined) window.clearTimeout(handle);
        timers.delete(v.id);
        remaining.delete(v.id);
        startedAt.delete(v.id);
      }
      nonces.set(v.id, v.nonce);
    }
    for (const v of visible.value) {
      if (v.resolvedDuration === Infinity) continue;
      if (timers.has(v.id)) continue;
      const left = remaining.get(v.id) ?? v.resolvedDuration;
      const handle = window.setTimeout(() => {
        toaster.dismiss(v.id);
      }, left);
      timers.set(v.id, handle);
      startedAt.set(v.id, Date.now());
      remaining.set(v.id, left);
    }
  },
  { immediate: true, flush: 'post' },
);

// Cleanup on unmount.
onUnmounted(() => {
  unsubscribe?.();
  for (const handle of timers.values()) window.clearTimeout(handle);
  timers.clear();
});

const handlePause = () => {
  if (!props.canPauseOnHover || paused.value) return;
  paused.value = true;
  for (const [id, handle] of timers) {
    window.clearTimeout(handle);
    const start = startedAt.get(id) ?? Date.now();
    const previous = remaining.get(id) ?? 0;
    const elapsed = Date.now() - start;
    remaining.set(id, Math.max(0, previous - elapsed));
  }
  timers.clear();
};

const handleResume = () => {
  if (!props.canPauseOnHover || !paused.value) return;
  paused.value = false;
};

const stackClasses = computed(() =>
  cn(
    'pointer-events-none fixed z-toast flex flex-col',
    POSITION_CLASSES[props.position],
    attrs.class as string | undefined,
  ),
);

const itemClasses = computed(() => cn('pointer-events-auto w-80', MOTION_CLASSES[props.position]));

/** Vue does not auto-suffix numeric style values with `px` the way React does. */
const stackStyle = computed(() => ({ gap: `${props.gap}px` }));
</script>

<template>
  <Portal>
    <div
      v-if="rendered.length > 0"
      aria-label="Notifications"
      :style="stackStyle"
      :class="stackClasses"
      @mouseenter="handlePause"
      @mouseleave="handleResume"
      @focus="handlePause"
      @blur="handleResume"
    >
      <Presence v-for="t in rendered" :key="t.id" :is-present="t.present">
        <!--
          `Presence` clones `data-state` onto this node and keeps it mounted
          until the exit animation ends; the `@vue:unmounted` hook is that
          "exit finished" signal (the read-only `Presence` API exposes no
          callback), replacing React's unmount-only `onRemoved` effect.
        -->
        <div :class="itemClasses" @vue:unmounted="t.present ? undefined : removeExiting(t.id)">
          <ToastNodeView v-if="t.content" :node="t.content" />
          <Toast v-else :severity="t.severity" @close="toaster.dismiss(t.id)">
            <template v-if="t.icon" #icon><ToastNodeView :node="t.icon" /></template>
            <template v-if="t.title" #title><ToastNodeView :node="t.title" /></template>
            <template v-if="t.description" #description>
              <ToastNodeView :node="t.description" />
            </template>
            <template v-if="t.action" #actions><ToastNodeView :node="t.action" /></template>
          </Toast>
        </div>
      </Presence>
    </div>
    <Announce politeness="polite">{{ latestTitle }}</Announce>
  </Portal>
</template>
