// src/layout/grid/Grid.tsx
import {
  forwardRef,
  type ComponentPropsWithoutRef,
  type ElementType,
  type Ref,
} from 'react';
import { cn } from '../../utils';
import { gridVariants, type GridVariants } from './Grid.variants';

export interface GridProps
  extends Omit<ComponentPropsWithoutRef<'div'>, 'as'>,
    GridVariants {
  as?: ElementType;
}

/**
 * CSS grid container with column and gap variants. For non-uniform tracks
 * pass an explicit `style={{ gridTemplateColumns }}` — the variant covers
 * the equal-column case.
 */
export const Grid = forwardRef<HTMLElement, GridProps>(
  ({ as: Component = 'div', className, columns, gap, ...props }, ref) => (
    <Component
      ref={ref as Ref<HTMLElement>}
      className={cn(gridVariants({ columns, gap }), className)}
      {...props}
    />
  ),
);
Grid.displayName = 'Grid';

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/layout/grid/Grid.vue
<script lang="ts">
import type { ElementType } from '../../../foundation/utils';
import type { GridColumns, GridGap, GridResponsive } from './Grid.variants';

export interface GridProps {
  as?: ElementType;
  /**
   * The equal-column track count. Scalar (`'3'`) emits `grid-cols-3`; a responsive
   * map (`{ base: '1', md: '2', lg: '3' }`) emits per-breakpoint prefixed
   * classes. Default `'2'`.
   */
  columns?: GridColumns | GridResponsive<GridColumns>;

  /**
   * The gap between tracks. Scalar (`'4'`) emits `gap-4`; a responsive map
   * (`{ base: '2', lg: '6' }`) emits per-breakpoint prefixed classes. Default `'4'`.
   */
  gap?: GridGap | GridResponsive<GridGap>;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';
import { resolveGridColumns, resolveGridGap } from './Grid.variants';

/**
 * CSS grid container with column and gap variants. Both `columns` and `gap`
 * accept a scalar value or a responsive `{ base, sm, md, lg, xl }` map. For
 * non-uniform tracks pass an explicit `:style="{ gridTemplateColumns }"` — the
 * variant covers the equal-column case.
 */
defineOptions({ name: 'Grid', inheritAttrs: false });

const props = withDefaults(defineProps<GridProps>(), {
  as: 'div',
  columns: '2',
  gap: '4',
});

const attrs = useAttrs();
const el = useTemplateRef<HTMLElement>('el');

const classes = computed(() =>
  cn('grid', resolveGridColumns(props.columns), resolveGridGap(props.gap), attrs.class as string | undefined),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <component :is="props.as" ref="el" v-bind="rest" :class="classes"><slot /></component>
</template>
