// src/presentation/display/text/Text.tsx
import {
  forwardRef,
  type ComponentPropsWithoutRef,
  type ElementType,
  type Ref,
} from 'react';
import { cn } from '../../../foundation/utils';
import { textVariants, type TextVariants } from './Text.variants';

export interface TextProps
  extends Omit<ComponentPropsWithoutRef<'p'>, 'as' | 'color'>,
    TextVariants {
  as?: ElementType;
}

/**
 * Body text. Renders as `<p>` by default; pass `as="span"` (or any element)
 * to keep semantics consistent with the surrounding markup.
 */
export const Text = forwardRef<HTMLElement, TextProps>(
  ({ as: Component = 'p', className, size, weight, color, align, isTruncated, isTabular, ...props }, ref) => (
    <Component
      ref={ref as Ref<HTMLElement>}
      className={cn(textVariants({ size, weight, color, align, isTruncated, isTabular }), className)}
      {...props}
    />
  ),
);
Text.displayName = 'Text';

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/text/Text.vue
<script lang="ts">
import type { ElementType, Size } from '../../../foundation/utils';
import type { TextAlign, TextColor, TextWeight } from './Text.variants';

export interface TextProps {
  as?: ElementType;
  /** The font size step. */
  size?: Size;
  /** The font weight. */
  weight?: TextWeight;
  /** The color role. */
  color?: TextColor;
  /** The text alignment. */
  align?: TextAlign;
  /** The single-line truncation with an ellipsis. */
  isTruncated?: boolean;
  /** The tabular (fixed-width) figures treatment. */
  isTabular?: boolean;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';
import { textVariants } from './Text.variants';

/**
 * Body text. Renders as `<p>` by default; pass `as="span"` (or any element)
 * to keep semantics consistent with the surrounding markup.
 */
defineOptions({ name: 'Text', inheritAttrs: false });

/** The text content — React's `children`. */
defineSlots<{ default(): unknown }>();

/**
 * `isTruncated` / `isTabular` default to `undefined`, not `false`: Vue casts an
 * absent `Boolean` prop to `false`, which would hand `textVariants` an explicit
 * `false` where React handed it `undefined`. Same rendered class either way for
 * these two, but the tri-state is what the variants config expects.
 */
const props = withDefaults(defineProps<TextProps>(), {
  as: 'p',
  isTruncated: undefined,
  isTabular: undefined,
});

const attrs = useAttrs();
const el = useTemplateRef<HTMLElement>('el');

const classes = computed(() =>
  cn(
    textVariants({
      size: props.size,
      weight: props.weight,
      color: props.color,
      align: props.align,
      isTruncated: props.isTruncated,
      isTabular: props.isTabular,
    }),
    attrs.class as string | undefined,
  ),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <component :is="props.as" ref="el" v-bind="rest" :class="classes"><slot /></component>
</template>
