// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/forms/listbox/Listbox.vue
<script lang="ts">
import type {
  SurfaceElevation,
  SurfacePadding,
  SurfaceRadius,
  SurfaceTone,
  SurfaceVariant,
} from '../../../foundation/utils';
import type { EqualityFn, ListboxIndicator } from './ListboxContext';

/**
 * Represents the prop surface of the `Listbox` root.
 *
 * React modelled single- vs multi-select as a discriminated union
 * (`SingleProps<T> | MultiProps<T>`) over a generic `T`. Vue's `defineProps`
 * resolves one flat runtime shape, and a `generic="T"` SFC cannot host the
 * exported interface in the plain `<script>` block — so the union is flattened
 * and `T` is fixed to `unknown`. `isMultiple` still discriminates at runtime:
 * the value is an array in multi mode and a scalar in single mode.
 *
 * The five surface axes are spelled out rather than inherited from
 * `SurfaceVariants`: that alias is `VariantProps<typeof surfaceVariants>`, which
 * the SFC compiler cannot follow as a heritage clause — it throws `Failed to
 * resolve extends base type` at build time while `vue-tsc` stays green. Named
 * types resolve fine, and the props have to be generated (not treated as
 * fallthrough attrs) because `rootClass` reads them.
 */
export interface ListboxProps {
  /** The surface style. */
  variant?: SurfaceVariant;

  /** The surface tone. */
  tone?: SurfaceTone;

  /** The corner radius. */
  radius?: SurfaceRadius;

  /** The inner padding. Default `xs` (p-1), for items breathing room. */
  padding?: SurfacePadding;

  /** The elevation / shadow step. */
  elevation?: SurfaceElevation;

  /** The multi-select state — the value becomes an array and items toggle. */
  isMultiple?: boolean;

  /** The selection, controlled. The `v-model` binding target. Array in multi mode. */
  modelValue?: unknown;

  /** The selection, controlled — React's spelling of `modelValue`, which wins when both are set. */
  value?: unknown;

  /** The initial selection when uncontrolled. Defaults to `[]` in multi mode. */
  defaultValue?: unknown;

  /** Disables all items when true. */
  isDisabled?: boolean;

  /** Compares item values for equality; defaults to `Object.is`. */
  isEqual?: EqualityFn<unknown>;

  /** Sets the selection-indicator style; default `check` (single) or `checkbox` (multi). */
  indicator?: ListboxIndicator;

  /** The tab index of the list container. Defaults to `0`, or `-1` while disabled. */
  tabindex?: number;
}
</script>

<script setup lang="ts">
import { computed, onMounted, provide, ref, useAttrs, useTemplateRef, watch } from 'vue';
import type { ClassValue } from 'clsx';
import { cn, surfaceVariants } from '../../../foundation/utils';
import { useControlled, useTypeahead } from '../../../foundation/hooks';
import { listboxVariants } from './Listbox.variants';
import {
  defaultEquals,
  listboxContextKey,
  ListboxIndicator as ListboxIndicatorValue,
  type ItemEntry,
  type ListboxContextValue,
} from './ListboxContext';

/**
 * Roving-`aria-activedescendant` listbox with type-to-select, single or multi
 * selection, and pluggable selection indicators. Items register themselves, so
 * arbitrary `children` work without threading a label prop.
 */
/* `inheritAttrs: false` so `class` folds into the component's own `cn()` call — plain fallthrough
   appends outside it and loses tailwind-merge conflict resolution. */
defineOptions({ name: 'Listbox', inheritAttrs: false });

const props = withDefaults(defineProps<ListboxProps>(), {
  /* Explicit `undefined` defaults: Vue casts an absent `boolean` prop to `false`, which would
     make `isDisabled` read as an explicit "enabled" and, for `isMultiple`, is simply the real
     default — but `isDisabled` must stay tri-state for the `aria-disabled` / tabindex branches. */
  isMultiple: false,
  isDisabled: undefined,
});

const emit = defineEmits<{
  /** The `v-model` half. */
  'update:modelValue': [value: unknown];
  /** Replaces React's `onValueChange`. */
  'value-change': [value: unknown];
  /**
   * Replaces React's `onActiveChange`. Fires after commit whenever the active
   * (`aria-activedescendant`) option id changes — including the initial auto-active
   * on mount. Lets a hosting combobox mirror the id without scraping the DOM.
   */
  'active-change': [id: string | null];
}>();

const attrs = useAttrs();

/* `EqualityFn` is already imported by the plain `<script>` block above — both blocks share one
   module scope, so re-importing it here would be a duplicate declaration. */
const equals = computed<EqualityFn<unknown>>(() => props.isEqual ?? defaultEquals);

const resolvedIndicator = computed(
  () =>
    props.indicator ??
    (props.isMultiple ? ListboxIndicatorValue.Checkbox : ListboxIndicatorValue.Check),
);

const controlled = useControlled<unknown>({
  controlled: () => (props.value !== undefined ? props.value : props.modelValue),
  default: () => props.defaultValue ?? (props.isMultiple ? [] : undefined),
  onChange: (next) => {
    emit('update:modelValue', next);
    emit('value-change', next);
  },
});

const values = computed<ReadonlyArray<unknown>>(() => {
  const current = controlled.value.value;
  if (Array.isArray(current)) return current as unknown[];
  return current === undefined ? [] : [current];
});

/* A plain array, not a ref: React held this in a `useRef` precisely so registration churn
   never drove a render, and the reads below all happen inside event handlers. `activeId` is
   the reactive half, and it is what descendants actually re-render on. */
const items: ItemEntry[] = [];
const activeId = ref<string | null>(null);

function registerItem(entry: ItemEntry): void {
  const idx = items.findIndex((i) => i.id === entry.id);
  if (idx >= 0) items[idx] = entry;
  else items.push(entry);
}

function unregisterItem(id: string): void {
  const idx = items.findIndex((i) => i.id === id);
  if (idx >= 0) items.splice(idx, 1);
}

function setActiveId(id: string | null): void {
  activeId.value = id;
}

function onItemSelect(next: unknown): void {
  if (props.isMultiple) {
    const current = controlled.value.value;
    const list = (Array.isArray(current) ? current : []) as unknown[];
    const has = list.some((v) => equals.value(v, next));
    controlled.setValue(has ? list.filter((v) => !equals.value(v, next)) : [...list, next]);
  } else {
    controlled.setValue(next);
  }
}

/* The initial auto-active: first selected enabled option, else the first enabled one.
   `onMounted` is the Vue equivalent of React's mount-only effect — children have registered
   by then, and it never runs on the server. */
onMounted(() => {
  if (activeId.value) return;
  const firstSelected = items.find(
    (i) => !i.isDisabled && values.value.some((v) => equals.value(v, i.value)),
  );
  const firstEnabled = items.find((i) => !i.isDisabled);
  activeId.value = (firstSelected ?? firstEnabled)?.id ?? null;
});

/* Mirrors the active id to a hosting combobox after commit, including the initial auto-active. */
watch(activeId, (id) => emit('active-change', id), { flush: 'post' });

const root = useTemplateRef<HTMLDivElement>('root');

/** Activates an option by id and keeps it visible (lists are `max-h-72 overflow-y-auto`). */
function activateById(id: string): void {
  activeId.value = id;
  /* Event-driven only, so `document` is always defined here — but the guard keeps the
     function safe if it is ever reached from a render-time path under SSR. */
  if (typeof document === 'undefined') return;
  document.getElementById(id)?.scrollIntoView({ block: 'nearest' });
}

function moveActive(direction: 1 | -1, jump = 1): void {
  const list = items.filter((i) => !i.isDisabled);
  if (list.length === 0) return;
  const currentIdx = list.findIndex((i) => i.id === activeId.value);
  let nextIdx = currentIdx + direction * jump;
  if (currentIdx === -1) nextIdx = direction === 1 ? 0 : list.length - 1;
  if (nextIdx < 0) nextIdx = 0;
  if (nextIdx >= list.length) nextIdx = list.length - 1;
  const nextEntry = list[nextIdx];
  if (nextEntry) activateById(nextEntry.id);
}

/* Type-to-select over the registered options. Labels are read from the live DOM text of each
   option (`document.getElementById` inside the user-event path → SSR-safe), so arbitrary
   children work without threading a label prop. Disabled options are skipped by the matcher. */
const typeahead = useTypeahead<ItemEntry>({
  items: () => items,
  getLabel: (entry) =>
    typeof document === 'undefined' ? '' : (document.getElementById(entry.id)?.textContent ?? ''),
  isDisabled: (entry) => entry.isDisabled,
  getActiveIndex: () => items.findIndex((i) => i.id === activeId.value),
  onMatch: (entry) => activateById(entry.id),
});

function handleKeyDown(event: KeyboardEvent): void {
  /* React called the consumer's `onKeyDown` first and then honoured `defaultPrevented`.
     A fallthrough listener would be merged AFTER this handler and lose that ordering, so the
     consumer's handler is pulled off `attrs` and invoked by hand (and excluded from the
     passthrough below so it cannot fire twice). */
  (attrs.onKeydown as ((e: KeyboardEvent) => void) | undefined)?.(event);
  if (event.defaultPrevented || props.isDisabled) return;
  /* Type-to-select first: a printable char (incl. Space while a buffer is active) is consumed
     here and must not fall through to Enter/Space selection or anything else. */
  if (typeahead.onKeyDown(event)) {
    event.preventDefault();
    return;
  }
  switch (event.key) {
    case 'ArrowDown':
      event.preventDefault();
      moveActive(1);
      break;
    case 'ArrowUp':
      event.preventDefault();
      moveActive(-1);
      break;
    case 'Home':
      event.preventDefault();
      moveActive(-1, items.length);
      break;
    case 'End':
      event.preventDefault();
      moveActive(1, items.length);
      break;
    case 'PageDown':
      event.preventDefault();
      moveActive(1, 10);
      break;
    case 'PageUp':
      event.preventDefault();
      moveActive(-1, 10);
      break;
    case 'Enter':
    case ' ': {
      if (!activeId.value) return;
      const entry = items.find((i) => i.id === activeId.value);
      if (!entry || entry.isDisabled) return;
      event.preventDefault();
      onItemSelect(entry.value);
      break;
    }
  }
}

const context: ListboxContextValue = {
  get isMultiple() {
    return props.isMultiple;
  },
  get values() {
    return values.value;
  },
  get isEqual() {
    return equals.value;
  },
  get activeId() {
    return activeId.value;
  },
  get indicator() {
    return resolvedIndicator.value;
  },
  get isDisabled() {
    return props.isDisabled ?? false;
  },
  onItemSelect,
  registerItem,
  unregisterItem,
  setActiveId,
};

provide(listboxContextKey, context);

const OWNED_ATTRS: ReadonlySet<string> = new Set(['class', 'onKeydown']);
const passthroughAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))),
);

const listTabIndex = computed(() => (props.isDisabled ? -1 : (props.tabindex ?? 0)));

const rootClass = computed(() =>
  cn(
    surfaceVariants({
      variant: props.variant,
      tone: props.tone,
      radius: props.radius,
      /* Default padding is `xs` (p-1) for items breathing room — overridable. */
      padding: props.padding ?? 'xs',
      elevation: props.elevation,
    }),
    listboxVariants(),
    attrs.class as ClassValue,
  ),
);

/** The rendered element — the Vue stand-in for the React original's forwarded ref. */
defineExpose({ el: root });
</script>

<template>
  <div
    ref="root"
    role="listbox"
    :tabindex="listTabIndex"
    :aria-multiselectable="isMultiple || undefined"
    :aria-activedescendant="activeId ?? undefined"
    :aria-disabled="isDisabled || undefined"
    :class="rootClass"
    v-bind="passthroughAttrs"
    @keydown="handleKeyDown"
  >
    <slot />
  </div>
</template>

// src/presentation/forms/listbox/Listbox.tsx
import {
  createContext,
  forwardRef,
  useCallback,
  useContext,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type ForwardedRef,
  type HTMLAttributes,
  type KeyboardEvent,
  type ReactElement,
  type ReactNode,
  type Ref,
} from 'react';
import { Check } from 'lucide-react';
import { cn, surfaceVariants, type SurfaceVariants } from '../../../foundation/utils';
import { useControlled, useTypeahead } from '../../../foundation/hooks';
import {
  listboxEmptyVariants,
  listboxGroupLabelVariants,
  listboxItemVariants,
  listboxSeparatorVariants,
  listboxVariants,
} from './Listbox.variants';

/** Represents a function that matches items against the current selection. */
export type EqualityFn<T> = (a: T, b: T) => boolean;

/** Provides the default equality (Object.is) — primitives + reference equality. */
const defaultEquals: EqualityFn<unknown> = (a, b) => Object.is(a, b);

/** Represents the selection-indicator style applied to every item under this listbox. */
export type ListboxIndicator = 'check' | 'checkbox' | 'radio' | 'dot' | 'none';

/** Represents the per-item registry entry maintained by the listbox. */
interface ItemEntry {
  id: string;
  value: unknown;
  isDisabled: boolean;
}

/** Represents the shape of the listbox context shared with descendants. */
interface ListboxContextValue {
  isMultiple: boolean;
  values: unknown[];
  isEqual: EqualityFn<unknown>;
  activeId: string | null;
  onItemSelect: (value: unknown) => void;
  registerItem: (entry: ItemEntry) => void;
  unregisterItem: (id: string) => void;
  setActiveId: (id: string | null) => void;
  indicator: ListboxIndicator;
  isDisabled: boolean;
}

const ListboxContext = createContext<ListboxContextValue | null>(null);

function useListboxContext() {
  const ctx = useContext(ListboxContext);
  if (!ctx) throw new Error('Listbox.Item / Group / Separator must be used inside <Listbox>');
  return ctx;
}

type SingleProps<T> = {
  isMultiple?: false;
  value?: T;
  defaultValue?: T;
  onValueChange?: (value: T | undefined) => void;
};

type MultiProps<T> = {
  isMultiple: true;
  value?: T[];
  defaultValue?: T[];
  onValueChange?: (value: T[]) => void;
};

/** Represents the props shared between single-select and multi-select modes. */
type CommonProps<T> = SurfaceVariants & {
  /** Disables all items when true. */
  isDisabled?: boolean;
  /** Compares item values for equality; defaults to `Object.is`. */
  isEqual?: EqualityFn<T>;
  /** Sets the selection-indicator style; default `check` (single) or `checkbox` (multi). */
  indicator?: ListboxIndicator;
  /** Fires after commit whenever the active (`aria-activedescendant`) option id changes —
   *  including the initial auto-active on mount. Lets a hosting combobox mirror the id without
   *  scraping the rendered DOM attribute. */
  onActiveChange?: (id: string | null) => void;
  className?: string;
  children: ReactNode;
};

export type ListboxProps<T = string> = Omit<
  HTMLAttributes<HTMLDivElement>,
  'defaultValue' | 'onChange'
> &
  (SingleProps<T> | MultiProps<T>) &
  CommonProps<T>;

function ListboxImpl<T>(
  props: ListboxProps<T>,
  ref: ForwardedRef<HTMLDivElement>,
): ReactElement {
  const {
    isMultiple = false,
    value,
    defaultValue,
    onValueChange,
    isEqual,
    indicator,
    onActiveChange,
    variant,
    tone,
    radius,
    padding,
    elevation,
    isDisabled,
    className,
    children,
    onKeyDown,
    ...rest
  } = props as ListboxProps<T> & {
    isMultiple?: boolean;
    value?: T | T[];
    defaultValue?: T | T[];
    onValueChange?: ((v: T | undefined) => void) | ((v: T[]) => void);
    onActiveChange?: (id: string | null) => void;
  };

  const equals = (isEqual as EqualityFn<unknown> | undefined) ?? defaultEquals;
  const resolvedIndicator: ListboxIndicator = indicator ?? (isMultiple ? 'checkbox' : 'check');

  const initial: T | T[] | undefined = defaultValue ?? (isMultiple ? ([] as T[]) : undefined);
  const [current, setCurrent] = useControlled<T | T[] | undefined>({
    controlled: value,
    default: initial,
    onChange: onValueChange as (v: T | T[] | undefined) => void,
  });

  const values: unknown[] = useMemo(() => {
    if (Array.isArray(current)) return current as unknown[];
    return current === undefined ? [] : [current];
  }, [current]);

  const items = useRef<ItemEntry[]>([]);
  const [activeId, setActiveId] = useState<string | null>(null);

  const registerItem = useCallback((entry: ItemEntry) => {
    const idx = items.current.findIndex((i) => i.id === entry.id);
    if (idx >= 0) items.current[idx] = entry;
    else items.current.push(entry);
  }, []);

  const unregisterItem = useCallback((id: string) => {
    items.current = items.current.filter((i) => i.id !== id);
  }, []);

  const onItemSelect = useCallback(
    (next: unknown) => {
      if (isMultiple) {
        const cur = (Array.isArray(current) ? current : []) as unknown[];
        const has = cur.some((v) => equals(v, next));
        const out = has ? cur.filter((v) => !equals(v, next)) : [...cur, next];
        (setCurrent as (v: unknown[]) => void)(out);
      } else {
        (setCurrent as (v: unknown) => void)(next);
      }
    },
    [isMultiple, current, setCurrent, equals],
  );

  useEffect(() => {
    if (activeId) return;
    const firstSelected = items.current.find(
      (i) => !i.isDisabled && values.some((v) => equals(v, i.value)),
    );
    const firstEnabled = items.current.find((i) => !i.isDisabled);
    setActiveId((firstSelected ?? firstEnabled)?.id ?? null);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  /* Mirrors the active id to a hosting combobox after commit. Ref-stabilised so swapping the
     handler doesn't re-fire; runs on every `activeId` change including the initial auto-active. */
  const onActiveChangeRef = useRef(onActiveChange);
  onActiveChangeRef.current = onActiveChange;
  useEffect(() => {
    onActiveChangeRef.current?.(activeId);
  }, [activeId]);

  /** Activates an option by id and keeps it visible (lists are `max-h-72 overflow-y-auto`). */
  const activateById = useCallback((id: string) => {
    setActiveId(id);
    document.getElementById(id)?.scrollIntoView({ block: 'nearest' });
  }, []);

  const moveActive = useCallback(
    (direction: 1 | -1, jump = 1) => {
      const list = items.current.filter((i) => !i.isDisabled);
      if (list.length === 0) return;
      const currentIdx = list.findIndex((i) => i.id === activeId);
      let nextIdx = currentIdx + direction * jump;
      if (currentIdx === -1) nextIdx = direction === 1 ? 0 : list.length - 1;
      if (nextIdx < 0) nextIdx = 0;
      if (nextIdx >= list.length) nextIdx = list.length - 1;
      const nextEntry = list[nextIdx];
      if (nextEntry) activateById(nextEntry.id);
    },
    [activeId, activateById],
  );

  /* Type-to-select over the registered options. Labels are read from the live DOM text of each
     option (`document.getElementById` inside the user-event path → SSR-safe), so arbitrary
     `children` work without threading a label prop. Disabled options are skipped by the matcher. */
  const typeahead = useTypeahead<ItemEntry>({
    items: () => items.current,
    getLabel: (entry) => document.getElementById(entry.id)?.textContent ?? '',
    isDisabled: (entry) => entry.isDisabled,
    getActiveIndex: () => items.current.findIndex((i) => i.id === activeId),
    onMatch: (entry) => activateById(entry.id),
  });

  const handleKeyDown = useCallback(
    (event: KeyboardEvent<HTMLDivElement>) => {
      onKeyDown?.(event);
      if (event.defaultPrevented || isDisabled) return;
      /* Type-to-select first: a printable char (incl. Space while a buffer is active) is consumed
         here and must not fall through to Enter/Space selection or anything else. */
      if (typeahead.onKeyDown(event)) {
        event.preventDefault();
        return;
      }
      switch (event.key) {
        case 'ArrowDown':
          event.preventDefault();
          moveActive(1);
          break;
        case 'ArrowUp':
          event.preventDefault();
          moveActive(-1);
          break;
        case 'Home':
          event.preventDefault();
          moveActive(-1, items.current.length);
          break;
        case 'End':
          event.preventDefault();
          moveActive(1, items.current.length);
          break;
        case 'PageDown':
          event.preventDefault();
          moveActive(1, 10);
          break;
        case 'PageUp':
          event.preventDefault();
          moveActive(-1, 10);
          break;
        case 'Enter':
        case ' ': {
          if (!activeId) return;
          const entry = items.current.find((i) => i.id === activeId);
          if (!entry || entry.isDisabled) return;
          event.preventDefault();
          onItemSelect(entry.value);
          break;
        }
      }
    },
    [activeId, isDisabled, moveActive, onItemSelect, onKeyDown, typeahead],
  );

  const ctx = useMemo<ListboxContextValue>(
    () => ({
      isMultiple,
      values,
      isEqual: equals,
      activeId,
      onItemSelect,
      registerItem,
      unregisterItem,
      setActiveId,
      indicator: resolvedIndicator,
      isDisabled: isDisabled ?? false,
    }),
    [
      isMultiple,
      values,
      equals,
      activeId,
      onItemSelect,
      registerItem,
      unregisterItem,
      resolvedIndicator,
      isDisabled,
    ],
  );

  /* Default padding is `xs` (p-1) for items breathing room — overridable. */
  const resolvedPadding = padding ?? 'xs';

  return (
    <ListboxContext.Provider value={ctx}>
      <div
        ref={ref}
        role="listbox"
        tabIndex={isDisabled ? -1 : 0}
        aria-multiselectable={isMultiple || undefined}
        aria-activedescendant={activeId ?? undefined}
        aria-disabled={isDisabled || undefined}
        onKeyDown={handleKeyDown}
        className={cn(
          surfaceVariants({ variant, tone, radius, padding: resolvedPadding, elevation }),
          listboxVariants(),
          className,
        )}
        {...rest}
      >
        {children}
      </div>
    </ListboxContext.Provider>
  );
}

const ListboxForwardRef = forwardRef(ListboxImpl) as <T = string>(
  props: ListboxProps<T> & { ref?: Ref<HTMLDivElement> },
) => ReactElement;

/* ---------- Indicator visuals ---------- */

/** Provides the leading selection indicator (checkbox · radio · dot). */
function LeadingIndicator({
  indicator,
  isSelected,
}: {
  indicator: ListboxIndicator;
  isSelected: boolean;
}) {
  if (indicator === 'checkbox') {
    return (
      <span
        aria-hidden
        className={cn(
          'flex h-4 w-4 shrink-0 items-center justify-center rounded-sm border',
          isSelected
            ? 'border-primary bg-primary text-primary-foreground'
            : 'border-border',
        )}
      >
        {isSelected && <Check className="h-3 w-3" />}
      </span>
    );
  }
  if (indicator === 'radio') {
    return (
      <span
        aria-hidden
        className={cn(
          'flex h-4 w-4 shrink-0 items-center justify-center rounded-full border',
          isSelected ? 'border-primary' : 'border-border',
        )}
      >
        {isSelected && <span className="h-2 w-2 rounded-full bg-primary" />}
      </span>
    );
  }
  if (indicator === 'dot') {
    return (
      <span
        aria-hidden
        className={cn(
          'h-1.5 w-1.5 shrink-0 rounded-full',
          isSelected ? 'bg-primary' : 'bg-transparent',
        )}
      />
    );
  }
  return null;
}

/** Provides the trailing selection indicator (check icon). */
function TrailingIndicator({
  indicator,
  isSelected,
  isMultiple,
}: {
  indicator: ListboxIndicator;
  isSelected: boolean;
  isMultiple: boolean;
}) {
  if (indicator === 'check' && isSelected) {
    return <Check className={cn('h-4 w-4 shrink-0', !isMultiple && 'opacity-80')} />;
  }
  return null;
}

/* ---------- Item ---------- */

/** Represents the prop surface of `Listbox.Item`. */
export interface ListboxItemProps extends Omit<HTMLAttributes<HTMLDivElement>, 'children'> {
  /** Holds the item value; compared via the parent listbox's `isEqual`. */
  value: unknown;
  /** Disables this item when true. */
  isDisabled?: boolean;
  /** Overrides the listbox-level indicator for this single item. */
  indicator?: ListboxIndicator;
  children: ReactNode;
}

export const ListboxItem = forwardRef<HTMLDivElement, ListboxItemProps>(function ListboxItem(
  { value, isDisabled = false, indicator: itemIndicator, className, children, onClick, onPointerEnter, ...rest },
  forwardedRef,
) {
  const ctx = useListboxContext();
  const id = useId();
  const ref = useRef<HTMLDivElement | null>(null);
  const indicator = itemIndicator ?? ctx.indicator;

  useEffect(() => {
    ctx.registerItem({ id, value, isDisabled });
    return () => ctx.unregisterItem(id);
  }, [ctx, id, value, isDisabled]);

  const isSelected = ctx.values.some((v) => ctx.isEqual(v, value));
  const isActive = ctx.activeId === id;
  const state = isDisabled
    ? 'disabled'
    : isSelected
      ? 'selected'
      : isActive
        ? 'active'
        : 'default';

  const setRefs = (node: HTMLDivElement | null) => {
    ref.current = node;
    if (typeof forwardedRef === 'function') forwardedRef(node);
    else if (forwardedRef) forwardedRef.current = node;
  };

  return (
    <div
      ref={setRefs}
      id={id}
      role="option"
      aria-selected={isSelected}
      aria-disabled={isDisabled || undefined}
      data-active={isActive ? '' : undefined}
      data-selected={isSelected ? '' : undefined}
      data-disabled={isDisabled ? '' : undefined}
      onClick={(e) => {
        onClick?.(e);
        /* `ctx.isDisabled` = listbox-level disabled — keyboard is blocked in handleKeyDown; mirror for mouse. */
        if (e.defaultPrevented || isDisabled || ctx.isDisabled) return;
        ctx.onItemSelect(value);
      }}
      onPointerEnter={(e) => {
        onPointerEnter?.(e);
        if (!isDisabled) ctx.setActiveId(id);
      }}
      className={cn(listboxItemVariants({ state }), className)}
      {...rest}
    >
      <LeadingIndicator indicator={indicator} isSelected={isSelected} />
      {/* `data-listbox-item-content` is a stable hook for hosts that need to target the option's
          content wrapper (e.g. Select's `matchWidth` truncation) without a brittle structural
          selector. */}
      <span data-listbox-item-content className="flex min-w-0 flex-1 items-center gap-2">
        {children}
      </span>
      <TrailingIndicator indicator={indicator} isSelected={isSelected} isMultiple={ctx.isMultiple} />
    </div>
  );
});

/** Represents the prop surface of `Listbox.Group`. */
export interface ListboxGroupProps extends HTMLAttributes<HTMLDivElement> {
  /** Renders an optional group heading above the contained items. */
  label?: ReactNode;
  children: ReactNode;
}

/** Provides a labelled group wrapping a subset of items. */
export function ListboxGroup({ label, children, className, ...rest }: ListboxGroupProps) {
  const labelId = useId();
  return (
    <div role="group" aria-labelledby={label ? labelId : undefined} className={className} {...rest}>
      {label && (
        <div id={labelId} className={listboxGroupLabelVariants()}>
          {label}
        </div>
      )}
      {children}
    </div>
  );
}

/** Provides a thin horizontal rule between groups of items. */
export function ListboxSeparator(props: HTMLAttributes<HTMLDivElement>) {
  return <div role="separator" className={listboxSeparatorVariants()} {...props} />;
}

/** Provides the message shown when no items match (e.g., after search filter). */
export function ListboxEmpty({ children, className, ...rest }: HTMLAttributes<HTMLDivElement>) {
  return (
    <div role="presentation" className={cn(listboxEmptyVariants(), className)} {...rest}>
      {children}
    </div>
  );
}

type ListboxComponent = (<T = string>(
  props: ListboxProps<T> & { ref?: Ref<HTMLDivElement> },
) => ReactElement) & {
  Item: typeof ListboxItem;
  Group: typeof ListboxGroup;
  Separator: typeof ListboxSeparator;
  Empty: typeof ListboxEmpty;
};

const Listbox = ListboxForwardRef as ListboxComponent;
Listbox.Item = ListboxItem;
Listbox.Group = ListboxGroup;
Listbox.Separator = ListboxSeparator;
Listbox.Empty = ListboxEmpty;

export { Listbox };
export default Listbox;
