// src/presentation/forms/checkboxField/CheckboxField.tsx
import { forwardRef, type ReactNode } from 'react';
import { cn } from '../../../foundation/utils';
import { useId } from '../../../foundation/hooks';
import { useFormControl } from '../../../foundation/primitives/formControlContext/FormControlContext';
import { Checkbox, type CheckboxProps } from '../checkbox/Checkbox';

export interface CheckboxFieldProps extends Omit<CheckboxProps, 'children'> {
  /** The right-side label. */
  label: ReactNode;

  /** The smaller helper / description below. */
  description?: ReactNode;

  /** The wrap-element className (the `<label>`). */
  wrapperClassName?: string;
}

/**
 * Checkbox + right-side label + optional description, wrapped in a single
 * `<label>` so clicking text toggles the box.
 */
export const CheckboxField = forwardRef<HTMLInputElement, CheckboxFieldProps>(
  ({ label, description, id, wrapperClassName, className, ...props }, ref) => {
    const generated = useId();
    // Context id wins over the generated fallback — inside a `Field`/`form.Field`
    // the surrounding Label's `htmlFor` targets `ctx.id`, so the box must carry it.
    const ctx = useFormControl();
    const inputId = id ?? ctx?.id ?? generated;
    return (
      <label
        htmlFor={inputId}
        className={cn('flex items-start gap-2.5 cursor-pointer', wrapperClassName)}
      >
        <Checkbox ref={ref} id={inputId} className={className} {...props} />
        <span className="flex flex-col gap-0.5 text-sm">
          <span className="font-medium text-foreground">{label}</span>
          {description && <span className="text-muted-foreground">{description}</span>}
        </span>
      </label>
    );
  },
);
CheckboxField.displayName = 'CheckboxField';

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/forms/checkboxField/CheckboxField.vue
<script lang="ts">
import type { CheckboxProps } from '../checkbox';

export interface CheckboxFieldProps extends CheckboxProps {
  /** The right-side label. Fill the `label` slot instead for richer content. */
  label?: string | number;

  /** The smaller helper / description below. Fill the `description` slot for richer content. */
  description?: string | number;

  /**
   * The wrap-element class (the `<label>`).
   *
   * React put `className` on the inner `Checkbox` and `wrapperClassName` on the `<label>`;
   * that split is preserved, so Vue's `class` fallthrough attr reaches the CHECKBOX, not
   * the root. Style the wrapper through this prop.
   */
  wrapperClassName?: string;

  /**
   * The key this item contributes to a surrounding `CheckboxGroup`'s selection.
   *
   * React read it off the cloned child (`ChildLike.value`); here the group provides a
   * context and this prop is what the item registers under. Ignored outside a group.
   */
  value?: string;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useSlots, useTemplateRef } from 'vue';
import type { ClassValue } from 'clsx';
import { cn } from '../../../foundation/utils';
import { useId } from '../../../foundation/hooks';
import { FormControlProvider, useFormControl } from '../../../foundation/primitives';
import { useCheckboxGroup } from '../checkboxGroup/CheckboxGroupContext';
import Checkbox from '../checkbox/Checkbox.vue';

/**
 * Checkbox + right-side label + optional description, wrapped in a single
 * `<label>` so clicking text toggles the box.
 */
/* `inheritAttrs: false` so `class` reaches the inner Checkbox (React's `className`) rather
   than landing on the `<label>`. */
defineOptions({ name: 'CheckboxField', inheritAttrs: false });

const props = defineProps<CheckboxFieldProps>();

defineSlots<{
  label?(): unknown;
  description?(): unknown;
}>();

const attrs = useAttrs();
const slots = useSlots();

const generated = useId();
/* Context id wins over the generated fallback — inside a `Field`/`form.Field` the
   surrounding Label's `htmlFor` targets `ctx.id`, so the box must carry it. Inside a
   `CheckboxGroup` the group already claimed that id, so siblings fall back to their own. */
const ctx = useFormControl();
const group = useCheckboxGroup();
const inputId = computed(() => props.id ?? (group ? generated : (ctx?.id ?? generated)));

const isInGroup = computed(() => group !== null);
const groupChecked = computed(() => group?.isSelected(props.value) ?? false);
const groupDisabled = computed(() => props.disabled ?? group?.isDisabled());
const groupInvalid = computed(() => group?.isInvalid() ?? false);

function onGroupChange(): void {
  group?.toggle(props.value);
}

const hasDescription = computed(() => Boolean(props.description) || Boolean(slots.description));

/*
 * No `defineEmits` on purpose: `update:modelValue` / `value-change` are NOT re-declared, so a
 * consumer's listeners stay in `useAttrs()` and reach `Checkbox` through the passthrough —
 * declaring them here would strip the listeners and silently break `v-model`.
 */
const OWNED_ATTRS: ReadonlySet<string> = new Set(['class']);
const passthroughAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))),
);

/** This component's own props must not reach the inner `Checkbox`. */
const checkboxProps = computed(() => {
  const {
    label: _label,
    description: _description,
    wrapperClassName: _wrapperClassName,
    value: _value,
    ...rest
  } = props;
  return rest;
});

const wrapperClass = computed(() => cn('flex items-start gap-2.5 cursor-pointer', props.wrapperClassName));

const checkboxClass = computed(() => attrs.class as ClassValue);

const inner = useTemplateRef<{ el: HTMLInputElement | null }>('inner');

/** The rendered `<input>` — the Vue stand-in for the React original's forwarded ref. */
defineExpose({ el: computed(() => inner.value?.el ?? null) });
</script>

<template>
  <label :for="inputId" :class="wrapperClass">
    <!-- Inside a group the item gets a FRESH provider — React wrapped each cloned child in
         one so siblings never adopt the surrounding Field's id or `describedBy`, while the
         group's disabled/invalid flags still cascade. -->
    <FormControlProvider v-if="isInGroup" :is-disabled="groupDisabled" :is-invalid="groupInvalid">
      <Checkbox
        ref="inner"
        v-bind="{ ...checkboxProps, ...passthroughAttrs }"
        :id="inputId"
        :checked="groupChecked"
        :class="checkboxClass"
        @change="onGroupChange"
      />
    </FormControlProvider>
    <Checkbox
      v-else
      ref="inner"
      v-bind="{ ...checkboxProps, ...passthroughAttrs }"
      :id="inputId"
      :class="checkboxClass"
    />
    <span class="flex flex-col gap-0.5 text-sm">
      <span class="font-medium text-foreground">
        <slot name="label">{{ label }}</slot>
      </span>
      <span v-if="hasDescription" class="text-muted-foreground">
        <slot name="description">{{ description }}</slot>
      </span>
    </span>
  </label>
</template>
