// src/presentation/display/frameGlyph/FrameGlyph.tsx
/** Defines props for a frame glyph. */
export interface FrameGlyphProps {
  /** The outer frame's corner radius (`0` = square). */
  readonly frameRx: number;

  /** The pupil's roundness as a fraction of its size (`0` = square, `0.5` = circle). */
  readonly pupilRoundness: number;

  /** The dot-only mode — renders only the enlarged inner pupil instead of the full frame + pupil. */
  readonly isDot?: boolean;

  /** The glyph's pixel size. */
  readonly size?: number;
}

/** Renders a nested-frame glyph — an outer frame + inner pupil, or (with `isDot`) just the enlarged pupil; a scanner / viewfinder / QR-eye indicator. */
export function FrameGlyph({ frameRx, pupilRoundness, isDot, size = 20 }: FrameGlyphProps) {
  const pupilSize = isDot ? 12 : 8;
  const pupilOffset = isDot ? 6 : 8;
  return (
    <svg viewBox="0 0 24 24" width={size} height={size} aria-hidden="true">
      {!isDot && (
        <rect x={2} y={2} width={20} height={20} rx={frameRx} fill="none" stroke="currentColor" strokeWidth={2.5} />
      )}
      <rect
        x={pupilOffset}
        y={pupilOffset}
        width={pupilSize}
        height={pupilSize}
        rx={pupilSize * pupilRoundness}
        fill="currentColor"
      />
    </svg>
  );
}

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/frameGlyph/FrameGlyph.vue
<script lang="ts">
/** Defines props for a frame glyph. */
export interface FrameGlyphProps {
  /** The outer frame's corner radius (`0` = square). */
  readonly frameRx: number;

  /** The pupil's roundness as a fraction of its size (`0` = square, `0.5` = circle). */
  readonly pupilRoundness: number;

  /** The dot-only mode — renders only the enlarged inner pupil instead of the full frame + pupil. */
  readonly isDot?: boolean;

  /** The glyph's pixel size. */
  readonly size?: number;
}
</script>

<script setup lang="ts">
import { computed, useTemplateRef } from 'vue';

/** Renders a nested-frame glyph — an outer frame + inner pupil, or (with `isDot`) just the enlarged pupil; a scanner / viewfinder / QR-eye indicator. */
defineOptions({ name: 'FrameGlyph' });

/* `isDot` defaults to `undefined`, not `false`: Vue casts an absent `Boolean`
   prop to `false`, and React's original left it genuinely optional. */
const props = withDefaults(defineProps<FrameGlyphProps>(), { isDot: undefined, size: 20 });

const el = useTemplateRef<SVGSVGElement>('el');

const pupilSize = computed(() => (props.isDot ? 12 : 8));
const pupilOffset = computed(() => (props.isDot ? 6 : 8));

defineExpose({ el });
</script>

<template>
  <svg ref="el" viewBox="0 0 24 24" :width="props.size" :height="props.size" aria-hidden="true">
    <rect
      v-if="!props.isDot"
      :x="2"
      :y="2"
      :width="20"
      :height="20"
      :rx="props.frameRx"
      fill="none"
      stroke="currentColor"
      :stroke-width="2.5"
    />
    <rect
      :x="pupilOffset"
      :y="pupilOffset"
      :width="pupilSize"
      :height="pupilSize"
      :rx="pupilSize * props.pupilRoundness"
      fill="currentColor"
    />
  </svg>
</template>
