// src/primitives/portal/Portal.tsx
import { type ReactNode } from 'react';
import { createPortal } from 'react-dom';

export interface PortalProps {
  children: ReactNode;
  /** Container to render into. Default: `document.body`. */
  container?: HTMLElement | null;
  /** Optional named layer — sets `data-portal-name` on the wrapper. */
  name?: string;
}

/**
 * Render children into a different DOM node (default `document.body`).
 * Client-only — package targets pure CSR consumers.
 */
export function Portal({ children, container, name }: PortalProps): ReactNode {
  const target = container ?? document.body;
  return createPortal(<div data-portal-name={name}>{children}</div>, target);
}

// engineering/codebase/wow-two-front-vue-beta-sdk/src/foundation/primitives/portal/Portal.vue
<script lang="ts">
export interface PortalProps {
  /** The container to render into. Default: `document.body`. */
  container?: HTMLElement | null;

  /** The optional named layer — sets `data-portal-name` on the wrapper. */
  name?: string;
}
</script>

<script setup lang="ts">
import { computed, onMounted, shallowRef } from 'vue';

/**
 * Render slot content into a different DOM node (default `document.body`).
 * SSR-inert — renders nothing on the server, teleports in after mount on the client.
 *
 * React's `createPortal` becomes `<Teleport>`; the mount gate is kept because
 * `document.body` cannot be resolved during SSR, and because a `to` target that
 * does not exist yet makes Teleport warn and drop its content.
 */
defineOptions({ name: 'Portal' });

const props = defineProps<PortalProps>();

const isMounted = shallowRef(false);
onMounted(() => {
  isMounted.value = true;
});

const target = computed<HTMLElement | null>(() =>
  isMounted.value ? (props.container ?? document.body) : null,
);
</script>

<template>
  <Teleport v-if="target" :to="target">
    <div :data-portal-name="name"><slot /></div>
  </Teleport>
</template>
