// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/quote/Quote.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue';

export type QuoteProps = HTMLAttributes;
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';

/**
 * Block quote with subtle left border and italic body text.
 */
defineOptions({ name: 'Quote', inheritAttrs: false });

/** The quoted copy — React's `children`. */
defineSlots<{ default(): unknown }>();

const attrs = useAttrs();
const el = useTemplateRef<HTMLQuoteElement>('el');

const classes = computed(() =>
  cn(
    'border-l-4 border-border pl-4 italic text-muted-foreground',
    attrs.class as string | undefined,
  ),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <blockquote ref="el" v-bind="rest" :class="classes"><slot /></blockquote>
</template>

// src/display/quote/Quote.tsx
import { forwardRef, type ComponentPropsWithoutRef } from 'react';
import { cn } from '../../utils';

export type QuoteProps = ComponentPropsWithoutRef<'blockquote'>;

/**
 * Block quote with subtle left border and italic body text.
 */
export const Quote = forwardRef<HTMLQuoteElement, QuoteProps>(
  ({ className, ...props }, ref) => (
    <blockquote
      ref={ref}
      className={cn(
        'border-l-4 border-border pl-4 italic text-muted-foreground',
        className,
      )}
      {...props}
    />
  ),
);
Quote.displayName = 'Quote';
