// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/layout/appShell/AppShell.vue
<script lang="ts">
import { inject, type ComputedRef, type InjectionKey, type Ref } from 'vue';

/** Defines the responsive breakpoint at which `AppShell` collapses its sidebar / aside. */
export const Breakpoint = {
  /** Refers to the `sm` (640px) breakpoint. */
  Sm: 'sm',
  /** Refers to the `md` (768px) breakpoint. */
  Md: 'md',
  /** Refers to the `lg` (1024px) breakpoint. */
  Lg: 'lg',
  /** Refers to the `xl` (1280px) breakpoint. */
  Xl: 'xl',
  /** Refers to the `2xl` (1536px) breakpoint. */
  Xxl: '2xl',
} as const;

export type Breakpoint = (typeof Breakpoint)[keyof typeof Breakpoint];

const BREAKPOINT_PX: Record<Breakpoint, number> = {
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
  '2xl': 1536,
};

/**
 * The value shared with `AppShellSidebar` / `AppShellAside`.
 *
 * React's context held plain values re-created on every render behind a
 * `useMemo`; here every field stays a ref or a computed, so a child reads the
 * live value and the root never re-renders to publish one.
 */
export interface AppShellContextValue {
  sidebarWidth: ComputedRef<string>;
  asideWidth: ComputedRef<string>;
  sidebarBreakpoint: ComputedRef<Breakpoint>;
  /** The resolved mobile-sidebar open state. Writable — an assignment routes through `setSidebarOpen`. */
  isSidebarOpen: Ref<boolean>;
  setSidebarOpen: (open: boolean) => void;
  /** True below `sidebarBreakpoint` — the sidebar renders as a `Drawer`. */
  isSidebarCollapsed: ComputedRef<boolean>;
  /** True below `asideBreakpoint` — the aside renders nothing. */
  isAsideHidden: ComputedRef<boolean>;
}

export const appShellContextKey: InjectionKey<AppShellContextValue> = Symbol('wow-two.appShell');

export function useAppShellContext(): AppShellContextValue {
  const context = inject(appShellContextKey, null);
  if (!context) throw new Error('AppShell.* must be used inside <AppShell>');
  return context;
}

/** Reads the enclosing `AppShell`'s state — widths, breakpoint, and the mobile-sidebar toggle. */
export function useAppShell(): AppShellContextValue {
  return useAppShellContext();
}

/**
 * The prop surface of `AppShell`.
 *
 * `sidebarOpen` and `isSidebarOpen` are the same controlled state under two
 * names: `sidebarOpen` is the `v-model:sidebarOpen` binding target,
 * `isSidebarOpen` React's spelling. `sidebarOpen` wins when both are set.
 * React's `onSidebarOpenChange` is the `sidebar-open-change` emit;
 * `update:sidebarOpen` fires alongside it so `v-model` works.
 */
export interface AppShellProps {
  /** The sidebar column width, any CSS length. Default `240px`. */
  sidebarWidth?: string;

  /** The aside rail width, any CSS length. Default `280px`. */
  asideWidth?: string;

  /** The sidebar collapses below this breakpoint. Default `lg`. */
  sidebarBreakpoint?: Breakpoint;

  /** The aside hides below this breakpoint. Default `xl`. */
  asideBreakpoint?: Breakpoint;

  /** The mobile-sidebar open state, controlled. The `v-model:sidebarOpen` binding target. */
  sidebarOpen?: boolean;

  /** The mobile-sidebar open state, controlled — React's spelling, which `sidebarOpen` wins over. */
  isSidebarOpen?: boolean;

  /** The initial mobile-sidebar state when uncontrolled. Default `false`. */
  defaultSidebarOpen?: boolean;
}
</script>

<script setup lang="ts">
import { computed, normalizeStyle, provide, useAttrs, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';
import { useControlled, useMediaQuery } from '../../../foundation/hooks';

/**
 * Top-level page frame. Children: `AppShellHeader` / `AppShellSidebar` /
 * `AppShellMain` / `AppShellAside` / `AppShellFooter`. CSS-grid layout; the
 * sidebar collapses to a `Drawer` below `sidebarBreakpoint`.
 */
defineOptions({ name: 'AppShell', inheritAttrs: false });

/** The shell's regions — React's required `children`. */
defineSlots<{ default(): unknown }>();

/**
 * `sidebarOpen: undefined` / `isSidebarOpen: undefined` are load-bearing: Vue
 * coerces an absent `Boolean` prop to `false` unless the declaration *owns* a
 * `default` key, which would strand the uncontrolled path behind a
 * permanently-closed controlled one.
 */
const props = withDefaults(defineProps<AppShellProps>(), {
  sidebarWidth: '240px',
  asideWidth: '280px',
  sidebarBreakpoint: 'lg',
  asideBreakpoint: 'xl',
  sidebarOpen: undefined,
  isSidebarOpen: undefined,
  defaultSidebarOpen: false,
});

const emit = defineEmits<{
  /** The `v-model:sidebarOpen` half. */
  'update:sidebarOpen': [open: boolean];
  /** Replaces React's `onSidebarOpenChange`. */
  'sidebar-open-change': [open: boolean];
}>();

const attrs = useAttrs();
const el = useTemplateRef<HTMLDivElement>('el');

const controlled = useControlled<boolean>({
  controlled: () => props.sidebarOpen ?? props.isSidebarOpen,
  default: () => props.defaultSidebarOpen,
  onChange: (value) => {
    emit('update:sidebarOpen', value);
    emit('sidebar-open-change', value);
  },
});

const isSidebarWide = useMediaQuery(
  () => `(min-width: ${BREAKPOINT_PX[props.sidebarBreakpoint]}px)`,
);
const isAsideWide = useMediaQuery(() => `(min-width: ${BREAKPOINT_PX[props.asideBreakpoint]}px)`);

const isSidebarCollapsed = computed(() => !isSidebarWide.value);
const isAsideHidden = computed(() => !isAsideWide.value);

provide(appShellContextKey, {
  sidebarWidth: computed(() => props.sidebarWidth),
  asideWidth: computed(() => props.asideWidth),
  sidebarBreakpoint: computed(() => props.sidebarBreakpoint),
  isSidebarOpen: controlled.value,
  setSidebarOpen: controlled.setValue,
  isSidebarCollapsed,
  isAsideHidden,
});

/** Collapsed drops the sidebar track entirely; header and footer always span the full width. */
const gridTemplate = computed(() =>
  isSidebarCollapsed.value
    ? `'header header' auto 'main main' 1fr 'footer footer' auto / 1fr`
    : `'header header' auto 'sidebar main' 1fr 'sidebar footer' auto / ${props.sidebarWidth} 1fr`,
);

const classes = computed(() =>
  cn('grid min-h-svh bg-background text-foreground', attrs.class as string | undefined),
);

/** `gridTemplate` is normalized first so a caller's `style` still wins per-property. */
const rootStyle = computed(() =>
  normalizeStyle([{ gridTemplate: gridTemplate.value }, attrs.style]),
);

/** Everything but `class` / `style`, both re-applied above. */
const rest = computed(() => {
  const { class: _class, style: _style, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <div ref="el" v-bind="rest" :style="rootStyle" :class="classes">
    <a
      href="#app-shell-main"
      class="sr-only focus:not-sr-only focus:fixed focus:left-2 focus:top-2 focus:z-modal focus:rounded-md focus:bg-card focus:px-3 focus:py-2 focus:shadow"
    >
      Skip to content
    </a>
    <slot />
  </div>
</template>

// src/presentation/layout/appShell/AppShell.tsx
import {
  createContext,
  forwardRef,
  useContext,
  useMemo,
  type HTMLAttributes,
  type ReactNode,
} from 'react';
import { cn } from '../../../foundation/utils';
import { useControlled, useMediaQuery } from '../../../foundation/hooks';
import { Drawer, DrawerContent } from '../../overlays/drawer';

type Breakpoint = 'sm' | 'md' | 'lg' | 'xl' | '2xl';

const BREAKPOINT_PX: Record<Breakpoint, number> = {
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
  '2xl': 1536,
};

// Complete class strings per breakpoint — Tailwind can't see interpolated names.
const SIDEBAR_STATIC_CLASSES: Record<Breakpoint, string> = {
  sm: 'hidden sm:flex',
  md: 'hidden md:flex',
  lg: 'hidden lg:flex',
  xl: 'hidden xl:flex',
  '2xl': 'hidden 2xl:flex',
};

interface AppShellContextValue {
  sidebarWidth: string;
  asideWidth: string;
  sidebarBreakpoint: Breakpoint;
  isSidebarOpen: boolean;
  setSidebarOpen: (open: boolean) => void;
  isSidebarCollapsed: boolean;
  isAsideHidden: boolean;
}

const AppShellContext = createContext<AppShellContextValue | null>(null);

function useAppShellContext() {
  const ctx = useContext(AppShellContext);
  if (!ctx) throw new Error('AppShell.* must be used inside <AppShell>');
  return ctx;
}

export interface AppShellProps extends HTMLAttributes<HTMLDivElement> {
  sidebarWidth?: string;
  asideWidth?: string;
  sidebarBreakpoint?: Breakpoint;
  asideBreakpoint?: Breakpoint;
  isSidebarOpen?: boolean;
  defaultSidebarOpen?: boolean;
  onSidebarOpenChange?: (open: boolean) => void;
  children: ReactNode;
}

/**
 * Top-level page frame. Children: `AppShell.Header / Sidebar / Main / Aside /
 * Footer`. CSS-grid layout; sidebar collapses to a Drawer below
 * `sidebarBreakpoint`.
 */
const AppShellRoot = forwardRef<HTMLDivElement, AppShellProps>(function AppShell(
  {
    sidebarWidth = '240px',
    asideWidth = '280px',
    sidebarBreakpoint = 'lg',
    asideBreakpoint = 'xl',
    isSidebarOpen: sidebarOpenProp,
    defaultSidebarOpen = false,
    onSidebarOpenChange,
    className,
    children,
    ...rest
  },
  ref,
) {
  const [isSidebarOpen, setSidebarOpen] = useControlled({
    controlled: sidebarOpenProp,
    default: defaultSidebarOpen,
    onChange: onSidebarOpenChange,
  });

  const isSidebarCollapsed = !useMediaQuery(`(min-width: ${BREAKPOINT_PX[sidebarBreakpoint]}px)`);
  const isAsideHidden = !useMediaQuery(`(min-width: ${BREAKPOINT_PX[asideBreakpoint]}px)`);

  const ctx = useMemo<AppShellContextValue>(
    () => ({
      sidebarWidth,
      asideWidth,
      sidebarBreakpoint,
      isSidebarOpen,
      setSidebarOpen,
      isSidebarCollapsed,
      isAsideHidden,
    }),
    [sidebarWidth, asideWidth, sidebarBreakpoint, isSidebarOpen, setSidebarOpen, isSidebarCollapsed, isAsideHidden],
  );

  const gridTemplate = isSidebarCollapsed
    ? `'header header' auto 'main main' 1fr 'footer footer' auto / 1fr`
    : `'header header' auto 'sidebar main' 1fr 'sidebar footer' auto / ${sidebarWidth} 1fr`;

  return (
    <AppShellContext.Provider value={ctx}>
      <div
        ref={ref}
        className={cn('grid min-h-svh bg-background text-foreground', className)}
        style={{ gridTemplate }}
        {...rest}
      >
        <a
          href="#app-shell-main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-2 focus:top-2 focus:z-modal focus:rounded-md focus:bg-card focus:px-3 focus:py-2 focus:shadow"
        >
          Skip to content
        </a>
        {children}
      </div>
    </AppShellContext.Provider>
  );
});

export type AppShellHeaderProps = HTMLAttributes<HTMLElement>;

export const AppShellHeader = forwardRef<HTMLElement, AppShellHeaderProps>(
  function AppShellHeader({ className, ...rest }, ref) {
    return (
      <header
        ref={ref}
        role="banner"
        className={cn(
          'sticky top-0 z-sticky flex h-14 items-center gap-3 border-b border-border bg-card px-4 [grid-area:header]',
          className,
        )}
        {...rest}
      />
    );
  },
);

export type AppShellSidebarProps = HTMLAttributes<HTMLElement>;

export const AppShellSidebar = forwardRef<HTMLElement, AppShellSidebarProps>(
  function AppShellSidebar({ className, children, ...rest }, ref) {
    const ctx = useAppShellContext();

    if (ctx.isSidebarCollapsed) {
      return (
        <Drawer open={ctx.isSidebarOpen} onOpenChange={ctx.setSidebarOpen} side="left">
          <DrawerContent className="w-72 max-w-[80%]">
            <nav className={cn('flex h-full flex-col', className)}>{children}</nav>
          </DrawerContent>
        </Drawer>
      );
    }
    return (
      <aside
        ref={ref}
        className={cn(
          'sticky top-14 h-[calc(100svh-3.5rem)] overflow-y-auto border-r border-border bg-card [grid-area:sidebar]',
          SIDEBAR_STATIC_CLASSES[ctx.sidebarBreakpoint],
          className,
        )}
        {...rest}
      >
        <nav className="flex h-full w-full flex-col p-3">{children}</nav>
      </aside>
    );
  },
);

export type AppShellMainProps = HTMLAttributes<HTMLElement>;

export const AppShellMain = forwardRef<HTMLElement, AppShellMainProps>(
  function AppShellMain({ className, children, ...rest }, ref) {
    return (
      <main
        ref={ref}
        id="app-shell-main"
        className={cn(
          'flex flex-col [grid-area:main] focus:outline-none',
          className,
        )}
        tabIndex={-1}
        {...rest}
      >
        {children}
      </main>
    );
  },
);

export type AppShellContentProps = HTMLAttributes<HTMLDivElement>;

export const AppShellContent = forwardRef<HTMLDivElement, AppShellContentProps>(
  function AppShellContent({ className, ...rest }, ref) {
    return <div ref={ref} className={cn('flex-1 overflow-y-auto p-6', className)} {...rest} />;
  },
);

export type AppShellAsideProps = HTMLAttributes<HTMLElement>;

export const AppShellAside = forwardRef<HTMLElement, AppShellAsideProps>(
  function AppShellAside({ className, ...rest }, ref) {
    const ctx = useAppShellContext();
    if (ctx.isAsideHidden) return null;
    return (
      <aside
        ref={ref}
        style={{ width: ctx.asideWidth }}
        className={cn(
          'sticky top-14 h-[calc(100svh-3.5rem)] shrink-0 overflow-y-auto border-l border-border bg-card p-4',
          className,
        )}
        {...rest}
      />
    );
  },
);

export type AppShellFooterProps = HTMLAttributes<HTMLElement>;

export const AppShellFooter = forwardRef<HTMLElement, AppShellFooterProps>(
  function AppShellFooter({ className, ...rest }, ref) {
    return (
      <footer
        ref={ref}
        role="contentinfo"
        className={cn(
          'border-t border-border bg-card px-4 py-3 text-sm text-muted-foreground [grid-area:footer]',
          className,
        )}
        {...rest}
      />
    );
  },
);

export const AppShell = Object.assign(AppShellRoot, {
  Header: AppShellHeader,
  Sidebar: AppShellSidebar,
  Main: AppShellMain,
  Content: AppShellContent,
  Aside: AppShellAside,
  Footer: AppShellFooter,
});

export function useAppShell() {
  return useAppShellContext();
}

export default AppShell;
