// src/presentation/display/badgeOverlay/BadgeOverlay.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from 'react';
import { cn } from '../../../foundation/utils';

export interface BadgeOverlayProps extends ComponentPropsWithoutRef<'div'> {
  /** Element to overlay on (avatar, button, image). */
  children: ReactNode;
  /** Badge content (count, dot, icon). */
  badge: ReactNode;
  /** Position of the badge relative to the wrapper. Default `top-right`. */
  position?: 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';
  /** Hide badge when truthy (e.g. when count is 0). */
  isHidden?: boolean;
}

const POS: Record<NonNullable<BadgeOverlayProps['position']>, string> = {
  'top-right': 'top-0 right-0 -translate-y-1/2 translate-x-1/2',
  'top-left': 'top-0 left-0 -translate-y-1/2 -translate-x-1/2',
  'bottom-right': 'bottom-0 right-0 translate-y-1/2 translate-x-1/2',
  'bottom-left': 'bottom-0 left-0 translate-y-1/2 -translate-x-1/2',
};

/**
 * Decorator that overlays a badge / dot on top of any child. Use to
 * attach `CountBadge`, `NotificationDot`, or arbitrary `Badge` to an
 * `Avatar`, icon, or `<Button shape="square"/circle">`.
 */
export const BadgeOverlay = forwardRef<HTMLDivElement, BadgeOverlayProps>(
  ({ children, badge, position = 'top-right', isHidden, className, ...props }, ref) => (
    <div ref={ref} className={cn('relative inline-flex', className)} {...props}>
      {children}
      {!isHidden && (
        <span className={cn('absolute z-raised', POS[position])}>{badge}</span>
      )}
    </div>
  ),
);
BadgeOverlay.displayName = 'BadgeOverlay';

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/badgeOverlay/BadgeOverlay.vue
<script lang="ts">
/* `CornerPosition` is imported here (not in `<script setup>`) so the one binding serves
   as both the type below and the runtime value used in `withDefaults`. */
import { CornerPosition } from '../../../foundation/utils';

export interface BadgeOverlayProps {
  /** The position of the badge relative to the wrapper. Default `top-right`. */
  position?: CornerPosition;

  /** The hidden state — hides the badge when truthy (e.g. when count is 0). */
  isHidden?: boolean;
}

const POS: Record<NonNullable<BadgeOverlayProps['position']>, string> = {
  'top-right': 'top-0 right-0 -translate-y-1/2 translate-x-1/2',
  'top-left': 'top-0 left-0 -translate-y-1/2 -translate-x-1/2',
  'bottom-right': 'bottom-0 right-0 translate-y-1/2 translate-x-1/2',
  'bottom-left': 'bottom-0 left-0 translate-y-1/2 -translate-x-1/2',
};
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';

/**
 * Decorator that overlays a badge / dot on top of any child. Use to
 * attach `CountBadge`, `NotificationDot`, or arbitrary `Badge` to an
 * `Avatar`, icon, or `<Button shape="square"/circle">`.
 */
defineOptions({ name: 'BadgeOverlay', inheritAttrs: false });

/** Both of React's required `ReactNode` props are structural, so both become slots. */
defineSlots<{
  /** The element to overlay on (avatar, button, image). */
  default(): unknown;

  /** The badge content (count, dot, icon). */
  badge(): unknown;
}>();

const props = withDefaults(defineProps<BadgeOverlayProps>(), {
  position: CornerPosition.TopRight,
});

const attrs = useAttrs();
const el = useTemplateRef<HTMLDivElement>('el');

const classes = computed(() => cn('relative inline-flex', attrs.class as string | undefined));

const badgeClasses = computed(() => cn('absolute z-raised', POS[props.position]));

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <div ref="el" v-bind="rest" :class="classes">
    <slot />
    <span v-if="!props.isHidden" :class="badgeClasses"><slot name="badge" /></span>
  </div>
</template>
