// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/forms/inputGroup/InputGroup.vue
<script lang="ts">
import type { Orientation } from '../../../foundation/utils';

export interface InputGroupProps {
  /** The layout axis. Default `horizontal`. */
  orientation?: Orientation;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import type { ClassValue } from 'clsx';
import { cn, Orientation as OrientationValue } from '../../../foundation/utils';

/**
 * Visually joins a row/column of inputs (TextInput, NumberInput, etc.)
 * — collapses inner radii so they read as one connected control. Mirror
 * of `actions/ButtonGroup`.
 */
/* `inheritAttrs: false` so `class` folds into the component's own `cn()` call — plain fallthrough
   appends outside it and loses tailwind-merge conflict resolution. */
defineOptions({ name: 'InputGroup', inheritAttrs: false });

const props = withDefaults(defineProps<InputGroupProps>(), {
  orientation: OrientationValue.Horizontal,
});

/** The joined controls — React's `children`. */
defineSlots<{ default(): unknown }>();

const attrs = useAttrs();

const isHorizontal = computed(() => props.orientation === OrientationValue.Horizontal);

const OWNED_ATTRS: ReadonlySet<string> = new Set(['class']);
const passthroughAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))),
);

const rootClass = computed(() =>
  cn(
    'inline-flex w-full',
    isHorizontal.value ? 'flex-row' : 'flex-col',
    isHorizontal.value
      ? '[&>*]:rounded-none [&>*:first-child]:rounded-l-md [&>*:last-child]:rounded-r-md [&>*:not(:first-child)]:-ml-px'
      : '[&>*]:rounded-none [&>*:first-child]:rounded-t-md [&>*:last-child]:rounded-b-md [&>*:not(:first-child)]:-mt-px',
    attrs.class as ClassValue,
  ),
);

const root = useTemplateRef<HTMLDivElement>('root');

/** The rendered element — the Vue stand-in for the React original's forwarded ref. */
defineExpose({ el: root });
</script>

<template>
  <div ref="root" :class="rootClass" v-bind="passthroughAttrs">
    <slot />
  </div>
</template>

// src/presentation/forms/inputGroup/InputGroup.tsx
import { forwardRef, type ComponentPropsWithoutRef } from 'react';
import { cn, Orientation } from '../../../foundation/utils';

export interface InputGroupProps extends ComponentPropsWithoutRef<'div'> {
  /** The layout axis. Default `horizontal`. */
  orientation?: Orientation;
}

/**
 * Visually joins a row/column of inputs (TextInput, NumberInput, etc.)
 * — collapses inner radii so they read as one connected control. Mirror
 * of `actions/ButtonGroup`.
 */
export const InputGroup = forwardRef<HTMLDivElement, InputGroupProps>(
  ({ orientation = Orientation.Horizontal, className, ...props }, ref) => (
    <div
      ref={ref}
      className={cn(
        'inline-flex w-full',
        orientation === Orientation.Horizontal ? 'flex-row' : 'flex-col',
        orientation === Orientation.Horizontal
          ? '[&>*]:rounded-none [&>*:first-child]:rounded-l-md [&>*:last-child]:rounded-r-md [&>*:not(:first-child)]:-ml-px'
          : '[&>*]:rounded-none [&>*:first-child]:rounded-t-md [&>*:last-child]:rounded-b-md [&>*:not(:first-child)]:-mt-px',
        className,
      )}
      {...props}
    />
  ),
);
InputGroup.displayName = 'InputGroup';
