// engineering/codebase/wow-two-front-beta-sdk/src/router/NavigationProgress.tsx
import { useNavigation } from 'react-router-dom';

import { useOptionalNavigationProgress } from './UseNavigationProgress';

/** Defines the visual form of the navigation indicator — a slim top bar or a pulsing heartbeat. */
export const NavigationProgressVariant = {
  /** Refers to a slim indeterminate top bar. */
  Bar: 'bar',
  /** Refers to a pulsing heartbeat dot. */
  Heartbeat: 'heartbeat',
} as const;

export type NavigationProgressVariant = (typeof NavigationProgressVariant)[keyof typeof NavigationProgressVariant];

/** Defines which busy sources drive the indicator — route navigation, manual spans, or both. */
export const NavigationProgressMode = {
  /** Refers to route-navigation busy state (react-router). */
  Auto: 'auto',
  /** Refers to manual / backend busy spans. */
  Manual: 'manual',
  /** Refers to either busy source. */
  Both: 'both',
} as const;

export type NavigationProgressMode = (typeof NavigationProgressMode)[keyof typeof NavigationProgressMode];

/** Defines props for the navigation progress indicator. */
interface NavigationProgressProps {
  /** The visual form — a slim top bar (default) or a pulsing heartbeat. */
  readonly variant?: NavigationProgressVariant;

  /** The busy sources that toggle visibility — route (default), manual (backend), or both. */
  readonly mode?: NavigationProgressMode;

  /** The accessible label announced while the indicator is busy. */
  readonly 'aria-label'?: string;
}

/** Renders the navigation / backend-wait progress indicator — a slim bar or a pulsing heartbeat, shown only while busy. */
export function NavigationProgress(props: NavigationProgressProps) {
  const {
    variant = NavigationProgressVariant.Bar,
    mode = NavigationProgressMode.Auto,
    'aria-label': ariaLabel = 'Loading',
  } = props;

  // `useNavigation` covers lazy-chunk + loader waits; the optional context covers app data fetches.
  const routeBusy = useNavigation().state !== 'idle';
  const manualBusy = useOptionalNavigationProgress()?.isBusy ?? false;

  const isActive =
    mode === NavigationProgressMode.Manual
      ? manualBusy
      : mode === NavigationProgressMode.Both
        ? routeBusy || manualBusy
        : routeBusy;

  if (!isActive) return null;

  if (variant === NavigationProgressVariant.Heartbeat) {
    return (
      <div
        role="progressbar"
        aria-busy={true}
        aria-label={ariaLabel}
        data-variant={variant}
        className="fixed right-4 top-4 z-toast inline-flex h-3 w-3 items-center justify-center"
      >
        {/* Ping ring conveys the beat; reduced-motion drops it, leaving the solid dot as a static cue. */}
        <span className="absolute inline-flex h-full w-full rounded-full bg-primary/60 animate-ping motion-reduce:hidden" />
        <span className="relative inline-flex h-2.5 w-2.5 rounded-full bg-primary" />
      </div>
    );
  }

  return (
    <div
      role="progressbar"
      aria-busy={true}
      aria-label={ariaLabel}
      data-variant={variant}
      className="fixed inset-x-0 top-0 z-toast h-0.5 overflow-hidden"
    >
      {/* Indeterminate slide; reduced-motion pins it full-width and static. */}
      <div className="h-full w-1/3 bg-primary animate-indeterminate motion-reduce:w-full motion-reduce:animate-none" />
    </div>
  );
}

// engineering/codebase/wow-two-front-vue-beta-sdk/src/router/NavigationProgress.vue
<script lang="ts">
import type { NavigationProgressMode, NavigationProgressVariant } from './NavigationProgressModes';

/**
 * Defines the props for {@link NavigationProgress}.
 *
 * `aria-label` is NOT declared: a hyphenated prop arrives as `props.ariaLabel` and stops being an
 * attribute, so it stays a fallthrough attr, read off `useAttrs()` and defaulted to `Loading`.
 */
export interface NavigationProgressProps {
  /** The visual form — a slim top bar (default) or a pulsing heartbeat. */
  variant?: NavigationProgressVariant;

  /** The busy sources that toggle visibility — route (default), manual (backend), or both. */
  mode?: NavigationProgressMode;
}

/** Attrs this component places by hand — everything else falls through untouched. */
const OWNED_ATTRS: ReadonlySet<string> = new Set(['class', 'aria-label']);
</script>

<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import { cn } from '../foundation/utils';

// `NavigationProgressMode` / `NavigationProgressVariant` are already imported as TYPES by the plain
// `<script>` block above; the two blocks compile into ONE module, so the VALUES come in under local
// aliases rather than re-importing the same identifiers.
import {
  NavigationProgressMode as ModeToken,
  NavigationProgressVariant as VariantToken,
} from './NavigationProgressModes';
import { useOptionalNavigationProgress } from './UseNavigationProgress';
import { useRouteNavigating } from './UseRouteNavigating';

/** Renders the navigation / backend-wait progress indicator — a slim bar or a pulsing heartbeat, shown only while busy. */
defineOptions({ name: 'NavigationProgress', inheritAttrs: false });

const props = withDefaults(defineProps<NavigationProgressProps>(), {
  variant: VariantToken.Bar,
  mode: ModeToken.Auto,
});

const attrs = useAttrs();

// `useRouteNavigating` covers lazy-chunk + async-guard waits (react-router's `useNavigation`); the
// optional injected state covers app data fetches. Neither requires the other to be present.
const routeBusy = useRouteNavigating();
const progress = useOptionalNavigationProgress();

const isHeartbeat = computed(() => props.variant === VariantToken.Heartbeat);

const isActive = computed(() => {
  const manualBusy = progress?.isBusy ?? false;
  if (props.mode === ModeToken.Manual) return manualBusy;
  if (props.mode === ModeToken.Both) return routeBusy.value || manualBusy;
  return routeBusy.value;
});

const ariaLabel = computed(() => (attrs['aria-label'] as string | undefined) ?? 'Loading');

const classes = computed(() =>
  cn(
    isHeartbeat.value
      ? 'fixed right-4 top-4 z-toast inline-flex h-3 w-3 items-center justify-center'
      : 'fixed inset-x-0 top-0 z-toast h-0.5 overflow-hidden',
    attrs.class as string | undefined,
  ),
);

/** Everything this component does not place itself — `class` folds through `cn`, `aria-label` through its default. */
const rest = computed(() => Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))));
</script>

<template>
  <div
    v-if="isActive"
    role="progressbar"
    :aria-busy="true"
    :aria-label="ariaLabel"
    :data-variant="props.variant"
    v-bind="rest"
    :class="classes"
  >
    <template v-if="isHeartbeat">
      <!-- Ping ring conveys the beat; reduced-motion drops it, leaving the solid dot as a static cue. -->
      <span class="absolute inline-flex h-full w-full rounded-full bg-primary/60 animate-ping motion-reduce:hidden" />
      <span class="relative inline-flex h-2.5 w-2.5 rounded-full bg-primary" />
    </template>
    <!-- Indeterminate slide; reduced-motion pins it full-width and static. -->
    <div v-else class="h-full w-1/3 bg-primary animate-indeterminate motion-reduce:w-full motion-reduce:animate-none" />
  </div>
</template>
