// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/diffViewer/DiffViewer.vue
<script lang="ts">
/** Defines the DiffViewer layout mode. */
export const DiffView = {
  /** Refers to side-by-side columns. */
  Split: 'split',
  /** Refers to a single interleaved column. */
  Unified: 'unified',
} as const;

export type DiffView = (typeof DiffView)[keyof typeof DiffView];

/** Defines a diff row's change operation. */
const DiffOp = {
  /** Refers to an unchanged line. */
  Unchanged: 'unchanged',
  /** Refers to an added line. */
  Added: 'added',
  /** Refers to a removed line. */
  Removed: 'removed',
} as const;

type DiffOp = (typeof DiffOp)[keyof typeof DiffOp];

/** Defines which side of a split diff a column renders. */
const DiffSide = {
  /** Refers to the left (old) column. */
  Left: 'left',
  /** Refers to the right (new) column. */
  Right: 'right',
} as const;

type DiffSide = (typeof DiffSide)[keyof typeof DiffSide];

interface DiffRow {
  op: DiffOp;
  leftNum: number | null;
  rightNum: number | null;
  text: string;
}

export interface DiffViewerProps {
  left: string;
  right: string;
  view?: DiffView;
  /** The label for the original text. Default `"Before"`. Rich content → the `leftLabel` slot. */
  leftLabel?: string | number;
  /** The label for the modified text. Default `"After"`. Rich content → the `rightLabel` slot. */
  rightLabel?: string | number;
  hasStats?: boolean;
}

/**
 * LCS-based line diff. Returns ordered rows with `unchanged` / `added` /
 * `removed` operations. O(n×m) time + space.
 */
function computeDiff(left: string, right: string): ReadonlyArray<DiffRow> {
  const a = left.split('\n');
  const b = right.split('\n');
  const n = a.length;
  const m = b.length;

  // LCS table: dp[i][j] = LCS length of a[0..i] and b[0..j].
  const dp: Array<Array<number>> = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));
  for (let i = 1; i <= n; i++) {
    for (let j = 1; j <= m; j++) {
      if (a[i - 1] === b[j - 1]) dp[i]![j] = dp[i - 1]![j - 1]! + 1;
      else dp[i]![j] = Math.max(dp[i - 1]![j]!, dp[i]![j - 1]!);
    }
  }

  // Backtrack.
  const rows: Array<DiffRow> = [];
  let i = n;
  let j = m;
  while (i > 0 || j > 0) {
    if (i > 0 && j > 0 && a[i - 1] === b[j - 1]) {
      rows.push({ op: DiffOp.Unchanged, leftNum: i, rightNum: j, text: a[i - 1]! });
      i--;
      j--;
    } else if (j > 0 && (i === 0 || dp[i]![j - 1]! >= dp[i - 1]![j]!)) {
      rows.push({ op: DiffOp.Added, leftNum: null, rightNum: j, text: b[j - 1]! });
      j--;
    } else if (i > 0) {
      rows.push({ op: DiffOp.Removed, leftNum: i, rightNum: null, text: a[i - 1]! });
      i--;
    } else {
      break;
    }
  }
  rows.reverse();
  return rows;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';

/**
 * Line-level diff viewer (split / unified). Own LCS implementation; no
 * external diff dep. For intra-line word highlighting, install `diff` and
 * post-process — deferred.
 *
 * React's private `SplitView` / `UnifiedView` / `DiffColumn` components render
 * inline here: they held no state and were never exported, so a computed cell
 * model plus two template branches replaces them.
 */
defineOptions({ name: 'DiffViewer', inheritAttrs: false });

defineSlots<{
  /** The left-label override, when a plain string is not enough. */
  leftLabel(): unknown;

  /** The right-label override, when a plain string is not enough. */
  rightLabel(): unknown;
}>();

const props = withDefaults(defineProps<DiffViewerProps>(), {
  view: DiffView.Split,
  leftLabel: 'Before',
  rightLabel: 'After',
  hasStats: true,
});

const attrs = useAttrs();
const el = useTemplateRef<HTMLDivElement>('el');

/** One rendered line of a column. `op: null` marks a filler (the other side has no counterpart). */
interface DiffCell {
  key: number;
  op: DiffOp | null;
  num: number | null;
  text: string;
  rowClass: string;
}

/** One rendered line of the unified column — carries both line numbers and the `+` / `−` marker. */
interface UnifiedCell {
  key: number;
  op: DiffOp;
  leftNum: number | null;
  rightNum: number | null;
  sign: string;
  text: string;
  rowClass: string;
}

const rows = computed(() => computeDiff(props.left, props.right));

const stats = computed(() => {
  let added = 0;
  let removed = 0;
  for (const r of rows.value) {
    if (r.op === DiffOp.Added) added += 1;
    if (r.op === DiffOp.Removed) removed += 1;
  }
  return { added, removed };
});

const isSplit = computed(() => props.view === DiffView.Split);

const toCell = (row: DiffRow | undefined, index: number, side: DiffSide): DiffCell => {
  if (!row) return { key: index, op: null, num: null, text: '', rowClass: '' };
  const isChanged =
    (side === DiffSide.Left && row.op === DiffOp.Removed) ||
    (side === DiffSide.Right && row.op === DiffOp.Added);
  return {
    key: index,
    op: row.op,
    num: side === DiffSide.Left ? row.leftNum : row.rightNum,
    text: row.text,
    rowClass: cn(
      'flex',
      isChanged && side === DiffSide.Left && 'bg-destructive-soft',
      isChanged && side === DiffSide.Right && 'bg-success-soft',
    ),
  };
};

/**
 * Pair removed/added rows row-by-row when possible to align them.
 * Simple alignment: walk, when we hit "removed" followed by "added", pair them.
 */
const splitColumns = computed<ReadonlyArray<ReadonlyArray<DiffCell>>>(() => {
  const pairs: Array<{ left?: DiffRow; right?: DiffRow }> = [];
  const source = rows.value;
  for (let i = 0; i < source.length; i++) {
    const r = source[i]!;
    if (r.op === DiffOp.Unchanged) {
      pairs.push({ left: r, right: r });
    } else if (r.op === DiffOp.Removed) {
      const next = source[i + 1];
      if (next && next.op === DiffOp.Added) {
        pairs.push({ left: r, right: next });
        i++;
      } else {
        pairs.push({ left: r });
      }
    } else if (r.op === DiffOp.Added) {
      pairs.push({ right: r });
    }
  }
  return [
    pairs.map((p, i) => toCell(p.left, i, DiffSide.Left)),
    pairs.map((p, i) => toCell(p.right, i, DiffSide.Right)),
  ];
});

const unifiedRows = computed<ReadonlyArray<UnifiedCell>>(() =>
  rows.value.map((r, i) => ({
    key: i,
    op: r.op,
    leftNum: r.leftNum,
    rightNum: r.rightNum,
    sign: r.op === DiffOp.Added ? '+' : r.op === DiffOp.Removed ? '−' : ' ',
    text: r.text,
    rowClass: cn(
      'flex',
      r.op === DiffOp.Added && 'bg-success-soft',
      r.op === DiffOp.Removed && 'bg-destructive-soft',
    ),
  })),
);

const classes = computed(() =>
  cn(
    'overflow-hidden rounded-md border border-border bg-card font-mono text-xs text-card-foreground shadow-sm',
    attrs.class as string | undefined,
  ),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <div ref="el" v-bind="rest" :class="classes">
    <div
      v-if="props.hasStats"
      class="flex items-center justify-between border-b border-border bg-muted/40 px-3 py-1.5 text-xs"
    >
      <div class="text-muted-foreground">
        <slot name="leftLabel">{{ props.leftLabel }}</slot> →
        <slot name="rightLabel">{{ props.rightLabel }}</slot>
      </div>
      <div class="flex items-center gap-3">
        <span class="text-success font-medium">+{{ stats.added }}</span>
        <span class="text-destructive font-medium">−{{ stats.removed }}</span>
      </div>
    </div>

    <div v-if="isSplit" class="grid grid-cols-2 divide-x divide-border">
      <div v-for="(column, columnIndex) in splitColumns" :key="columnIndex" class="overflow-x-auto">
        <template v-for="cell in column" :key="cell.key">
          <div v-if="cell.op === null" class="flex bg-muted/30">
            <span class="select-none w-10 shrink-0 px-2 py-0.5 text-right text-muted-foreground"
              >·</span
            >
            <span class="flex-1 whitespace-pre px-2 py-0.5">&nbsp;</span>
          </div>
          <div v-else :data-state="cell.op" :class="cell.rowClass">
            <span
              class="select-none w-10 shrink-0 border-r border-border px-2 py-0.5 text-right text-muted-foreground tabular-nums"
              >{{ cell.num ?? '' }}</span
            >
            <span class="flex-1 whitespace-pre px-2 py-0.5">{{ cell.text || ' ' }}</span>
          </div>
        </template>
      </div>
    </div>

    <div v-else class="overflow-x-auto">
      <div v-for="row in unifiedRows" :key="row.key" :data-state="row.op" :class="row.rowClass">
        <span
          class="select-none w-10 shrink-0 border-r border-border px-2 py-0.5 text-right text-muted-foreground tabular-nums"
          >{{ row.leftNum ?? '' }}</span
        >
        <span
          class="select-none w-10 shrink-0 border-r border-border px-2 py-0.5 text-right text-muted-foreground tabular-nums"
          >{{ row.rightNum ?? '' }}</span
        >
        <span class="w-5 shrink-0 px-1 py-0.5 text-center text-muted-foreground">{{
          row.sign
        }}</span>
        <span class="flex-1 whitespace-pre px-2 py-0.5">{{ row.text || ' ' }}</span>
      </div>
    </div>
  </div>
</template>

// src/display/diffViewer/DiffViewer.tsx
import { forwardRef, useMemo, type HTMLAttributes, type ReactNode } from 'react';
import { cn } from '../../utils';

export type DiffView = 'split' | 'unified';

type DiffOp = 'unchanged' | 'added' | 'removed';

interface DiffRow {
  op: DiffOp;
  leftNum: number | null;
  rightNum: number | null;
  text: string;
}

export interface DiffViewerProps extends HTMLAttributes<HTMLDivElement> {
  left: string;
  right: string;
  view?: DiffView;
  leftLabel?: ReactNode;
  rightLabel?: ReactNode;
  showStats?: boolean;
}

/**
 * Line-level diff viewer (split / unified). Own LCS implementation; no
 * external diff dep. For intra-line word highlighting, install `diff` and
 * post-process — deferred.
 */
export const DiffViewer = forwardRef<HTMLDivElement, DiffViewerProps>(function DiffViewer(
  { left, right, view = 'split', leftLabel = 'Before', rightLabel = 'After', showStats = true, className, ...rest },
  ref,
) {
  const rows = useMemo(() => computeDiff(left, right), [left, right]);
  const stats = useMemo(() => {
    let added = 0;
    let removed = 0;
    for (const r of rows) {
      if (r.op === 'added') added += 1;
      if (r.op === 'removed') removed += 1;
    }
    return { added, removed };
  }, [rows]);

  return (
    <div
      ref={ref}
      className={cn(
        'overflow-hidden rounded-md border border-border bg-card font-mono text-xs text-card-foreground shadow-sm',
        className,
      )}
      {...rest}
    >
      {showStats && (
        <div className="flex items-center justify-between border-b border-border bg-muted/40 px-3 py-1.5 text-xs">
          <div className="text-muted-foreground">{leftLabel} → {rightLabel}</div>
          <div className="flex items-center gap-3">
            <span className="text-success font-medium">+{stats.added}</span>
            <span className="text-destructive font-medium">−{stats.removed}</span>
          </div>
        </div>
      )}
      {view === 'split' ? <SplitView rows={rows} /> : <UnifiedView rows={rows} />}
    </div>
  );
});

function SplitView({ rows }: { rows: DiffRow[] }) {
  // Pair removed/added rows row-by-row when possible to align them.
  // Simple alignment: walk, when we hit "removed" followed by "added", pair them.
  const pairs: Array<{ left?: DiffRow; right?: DiffRow }> = [];
  for (let i = 0; i < rows.length; i++) {
    const r = rows[i]!;
    if (r.op === 'unchanged') {
      pairs.push({ left: r, right: r });
    } else if (r.op === 'removed') {
      const next = rows[i + 1];
      if (next && next.op === 'added') {
        pairs.push({ left: r, right: next });
        i++;
      } else {
        pairs.push({ left: r });
      }
    } else if (r.op === 'added') {
      pairs.push({ right: r });
    }
  }

  return (
    <div className="grid grid-cols-2 divide-x divide-border">
      <DiffColumn rows={pairs.map((p) => p.left)} />
      <DiffColumn rows={pairs.map((p) => p.right)} side="right" />
    </div>
  );
}

function DiffColumn({ rows, side = 'left' }: { rows: Array<DiffRow | undefined>; side?: 'left' | 'right' }) {
  return (
    <div className="overflow-x-auto">
      {rows.map((r, i) => {
        if (!r) {
          return (
            <div key={i} className="flex bg-muted/30">
              <span className="select-none w-10 shrink-0 px-2 py-0.5 text-right text-muted-foreground">·</span>
              <span className="flex-1 whitespace-pre px-2 py-0.5">&nbsp;</span>
            </div>
          );
        }
        const num = side === 'left' ? r.leftNum : r.rightNum;
        const isChanged =
          (side === 'left' && r.op === 'removed') || (side === 'right' && r.op === 'added');
        return (
          <div
            key={i}
            data-state={r.op}
            className={cn(
              'flex',
              isChanged && side === 'left' && 'bg-destructive-soft',
              isChanged && side === 'right' && 'bg-success-soft',
            )}
          >
            <span className="select-none w-10 shrink-0 border-r border-border px-2 py-0.5 text-right text-muted-foreground tabular-nums">
              {num ?? ''}
            </span>
            <span className="flex-1 whitespace-pre px-2 py-0.5">{r.text || ' '}</span>
          </div>
        );
      })}
    </div>
  );
}

function UnifiedView({ rows }: { rows: DiffRow[] }) {
  return (
    <div className="overflow-x-auto">
      {rows.map((r, i) => (
        <div
          key={i}
          data-state={r.op}
          className={cn(
            'flex',
            r.op === 'added' && 'bg-success-soft',
            r.op === 'removed' && 'bg-destructive-soft',
          )}
        >
          <span className="select-none w-10 shrink-0 border-r border-border px-2 py-0.5 text-right text-muted-foreground tabular-nums">
            {r.leftNum ?? ''}
          </span>
          <span className="select-none w-10 shrink-0 border-r border-border px-2 py-0.5 text-right text-muted-foreground tabular-nums">
            {r.rightNum ?? ''}
          </span>
          <span className="w-5 shrink-0 px-1 py-0.5 text-center text-muted-foreground">
            {r.op === 'added' ? '+' : r.op === 'removed' ? '−' : ' '}
          </span>
          <span className="flex-1 whitespace-pre px-2 py-0.5">{r.text || ' '}</span>
        </div>
      ))}
    </div>
  );
}

/**
 * LCS-based line diff. Returns ordered rows with `unchanged` / `added` /
 * `removed` operations. O(n×m) time + space.
 */
function computeDiff(left: string, right: string): DiffRow[] {
  const a = left.split('\n');
  const b = right.split('\n');
  const n = a.length;
  const m = b.length;

  // LCS table: dp[i][j] = LCS length of a[0..i] and b[0..j].
  const dp: number[][] = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));
  for (let i = 1; i <= n; i++) {
    for (let j = 1; j <= m; j++) {
      if (a[i - 1] === b[j - 1]) dp[i]![j] = dp[i - 1]![j - 1]! + 1;
      else dp[i]![j] = Math.max(dp[i - 1]![j]!, dp[i]![j - 1]!);
    }
  }

  // Backtrack.
  const rows: DiffRow[] = [];
  let i = n;
  let j = m;
  while (i > 0 || j > 0) {
    if (i > 0 && j > 0 && a[i - 1] === b[j - 1]) {
      rows.push({ op: 'unchanged', leftNum: i, rightNum: j, text: a[i - 1]! });
      i--;
      j--;
    } else if (j > 0 && (i === 0 || dp[i]![j - 1]! >= dp[i - 1]![j]!)) {
      rows.push({ op: 'added', leftNum: null, rightNum: j, text: b[j - 1]! });
      j--;
    } else if (i > 0) {
      rows.push({ op: 'removed', leftNum: i, rightNum: null, text: a[i - 1]! });
      i--;
    } else {
      break;
    }
  }
  rows.reverse();
  return rows;
}
