// engineering/codebase/wow-two-front-beta-sdk/src/presentation/nav/commandPalette/CommandPalette.tsx
import {
  createContext,
  forwardRef,
  useCallback,
  useContext,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type HTMLAttributes,
  type InputHTMLAttributes,
  type KeyboardEvent,
  type ReactNode,
} from 'react';
import { Search } from 'lucide-react';
import { cn } from '../../../foundation/utils';
import { useControlled } from '../../../foundation/hooks';
import { Icon } from '../../../foundation/icons';
import { useHotkeys } from '../../../foundation/shortcuts';
import { Modal, ModalContent } from '../../overlays/modal';
import {
  listboxEmptyVariants,
  listboxGroupLabelVariants,
  listboxItemVariants,
  listboxSeparatorVariants,
} from '../../forms/listbox/Listbox.variants';

interface CommandItemEntry {
  id: string;
  value: string;
  searchText: string;
  disabled: boolean;
  onSelect: () => void;
  closeOnSelect: boolean;
}

interface CommandPaletteContextValue {
  open: boolean;
  setOpen: (open: boolean) => void;
  inputValue: string;
  setInputValue: (input: string) => void;
  activeId: string | null;
  setActiveId: (id: string | null) => void;
  itemsRef: React.MutableRefObject<Array<CommandItemEntry>>;
  registerItem: (entry: CommandItemEntry) => void;
  unregisterItem: (id: string) => void;
  /** Bumped on every register/unregister — lets consumers observe the mutable registry. */
  registryVersion: number;
  filter: (searchText: string, search: string) => boolean;
  inputId: string;
  listboxId: string;
  inputRef: React.MutableRefObject<HTMLInputElement | null>;
}

const CommandPaletteContext = createContext<CommandPaletteContextValue | null>(null);

function useCommandPaletteContext() {
  const ctx = useContext(CommandPaletteContext);
  if (!ctx) throw new Error('CommandPalette.* must be used inside <CommandPalette>');
  return ctx;
}

const defaultFilter = (searchText: string, search: string) =>
  searchText.toLowerCase().includes(search.toLowerCase());

export interface CommandPaletteProps {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  inputValue?: string;
  defaultInputValue?: string;
  onInputChange?: (input: string) => void;
  triggerKey?: string;
  filter?: (searchText: string, search: string) => boolean;
  children: ReactNode;
}

function CommandPaletteRoot({
  open: openProp,
  defaultOpen = false,
  onOpenChange,
  inputValue: inputProp,
  defaultInputValue,
  onInputChange,
  triggerKey,
  filter = defaultFilter,
  children,
}: CommandPaletteProps) {
  const [open, setOpen] = useControlled({
    controlled: openProp,
    default: defaultOpen,
    onChange: onOpenChange,
  });
  const [inputValue, setInputValue] = useControlled({
    controlled: inputProp,
    default: defaultInputValue ?? '',
    onChange: onInputChange,
  });

  const itemsRef = useRef<Array<CommandItemEntry>>([]);
  const inputRef = useRef<HTMLInputElement | null>(null);
  const [activeId, setActiveId] = useState<string | null>(null);
  // Items register via effects post-render; bump a version so registry readers recompute once items exist (fresh-open flow).
  const [registryVersion, setRegistryVersion] = useState(0);
  const inputId = useId();
  const listboxId = useId();

  const registerItem = useCallback((entry: CommandItemEntry) => {
    const idx = itemsRef.current.findIndex((i) => i.id === entry.id);
    if (idx >= 0) itemsRef.current[idx] = entry;
    else itemsRef.current.push(entry);
    setRegistryVersion((v) => v + 1);
  }, []);

  const unregisterItem = useCallback((id: string) => {
    itemsRef.current = itemsRef.current.filter((i) => i.id !== id);
    setRegistryVersion((v) => v + 1);
  }, []);

  // Global keybinding (cmd-/ctrl-K). `mod` = ⌘ on Apple / Ctrl elsewhere; the explicit `ctrl+`/`meta+` pair keeps
  // the spec's "we accept both on every platform" contract. The chord must always parse (`+` is the token
  // separator → `plus`; a falsy `triggerKey` needs a placeholder), so `enabled` — not an early return — unbinds.
  const chordKey = !triggerKey ? 'k' : triggerKey === '+' ? 'plus' : triggerKey;
  useHotkeys([`mod+${chordKey}`, `ctrl+${chordKey}`, `meta+${chordKey}`], () => setOpen(true), {
    enabled: Boolean(triggerKey),
  });

  // Reset search + active id on open/close transitions.
  useEffect(() => {
    if (!open) {
      setActiveId(null);
    }
  }, [open]);

  const ctx = useMemo<CommandPaletteContextValue>(
    () => ({
      open,
      setOpen,
      inputValue,
      setInputValue,
      activeId,
      setActiveId,
      itemsRef,
      registerItem,
      unregisterItem,
      registryVersion,
      filter,
      inputId,
      listboxId,
      inputRef,
    }),
    [
      open,
      setOpen,
      inputValue,
      setInputValue,
      activeId,
      registerItem,
      unregisterItem,
      registryVersion,
      filter,
      inputId,
      listboxId,
    ],
  );

  return (
    <CommandPaletteContext.Provider value={ctx}>
      <Modal open={open} onOpenChange={setOpen}>
        {children}
      </Modal>
    </CommandPaletteContext.Provider>
  );
}
CommandPaletteRoot.displayName = 'CommandPalette';

export type CommandPaletteContentProps = HTMLAttributes<HTMLDivElement>;

export const CommandPaletteContent = forwardRef<HTMLDivElement, CommandPaletteContentProps>(
  function CommandPaletteContent({ className, children, ...rest }, forwardedRef) {
    return (
      <ModalContent
        ref={forwardedRef}
        className={cn('w-full max-w-xl gap-0 overflow-hidden p-0', className)}
        {...rest}
      >
        {children}
      </ModalContent>
    );
  },
);

export type CommandPaletteInputProps = Omit<
  InputHTMLAttributes<HTMLInputElement>,
  'value' | 'onChange'
>;

export const CommandPaletteInput = forwardRef<HTMLInputElement, CommandPaletteInputProps>(
  function CommandPaletteInput(
    { className, placeholder = 'Type a command…', onKeyDown, ...rest },
    forwardedRef,
  ) {
    const ctx = useCommandPaletteContext();

    // Keep DOM focus on the input whenever palette is open.
    useEffect(() => {
      if (ctx.open && ctx.inputRef.current) ctx.inputRef.current.focus();
    }, [ctx.open, ctx.inputRef]);

    const visibleItems = useCallback(() => {
      return ctx.itemsRef.current.filter(
        (i) => !i.disabled && (ctx.inputValue === '' || ctx.filter(i.searchText, ctx.inputValue)),
      );
    }, [ctx]);

    // Auto-set first match when the filter or the item registry changes.
    useEffect(() => {
      const list = visibleItems();
      if (list.length > 0 && !list.some((i) => i.id === ctx.activeId)) {
        ctx.setActiveId(list[0]!.id);
      } else if (list.length === 0) {
        ctx.setActiveId(null);
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [ctx.inputValue, ctx.registryVersion]);

    const moveActive = (direction: 1 | -1) => {
      const list = visibleItems();
      if (list.length === 0) return;
      const idx = list.findIndex((i) => i.id === ctx.activeId);
      let nextIdx = idx + direction;
      if (idx === -1) nextIdx = direction === 1 ? 0 : list.length - 1;
      if (nextIdx < 0) nextIdx = list.length - 1;
      if (nextIdx >= list.length) nextIdx = 0;
      ctx.setActiveId(list[nextIdx]!.id);
    };

    const handleKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
      onKeyDown?.(e);
      if (e.defaultPrevented) return;
      switch (e.key) {
        case 'ArrowDown':
          e.preventDefault();
          moveActive(1);
          break;
        case 'ArrowUp':
          e.preventDefault();
          moveActive(-1);
          break;
        case 'Home':
          if (e.target === ctx.inputRef.current) {
            const list = visibleItems();
            if (list.length > 0) ctx.setActiveId(list[0]!.id);
          }
          break;
        case 'End':
          if (e.target === ctx.inputRef.current) {
            const list = visibleItems();
            if (list.length > 0) ctx.setActiveId(list[list.length - 1]!.id);
          }
          break;
        case 'Enter': {
          if (!ctx.activeId) return;
          const entry = ctx.itemsRef.current.find((i) => i.id === ctx.activeId);
          if (!entry || entry.disabled) return;
          e.preventDefault();
          entry.onSelect();
          if (entry.closeOnSelect) ctx.setOpen(false);
          break;
        }
      }
    };

    return (
      <div className="flex items-center gap-2 border-b border-border px-3">
        <Icon icon={Search} size={16} className="text-muted-foreground" />
        <input
          {...rest}
          ref={(el) => {
            ctx.inputRef.current = el;
            if (typeof forwardedRef === 'function') forwardedRef(el);
            else if (forwardedRef)
              (forwardedRef as React.MutableRefObject<HTMLInputElement | null>).current = el;
          }}
          id={ctx.inputId}
          type="text"
          role="combobox"
          aria-expanded
          aria-controls={ctx.listboxId}
          aria-activedescendant={ctx.activeId ?? undefined}
          aria-autocomplete="list"
          placeholder={placeholder}
          value={ctx.inputValue}
          onChange={(e) => ctx.setInputValue(e.target.value)}
          onKeyDown={handleKeyDown}
          className={cn(
            'flex h-12 w-full bg-transparent text-sm text-foreground placeholder:text-subtle-foreground outline-none disabled:cursor-not-allowed disabled:opacity-50',
            className,
          )}
        />
      </div>
    );
  },
);

export type CommandPaletteListProps = HTMLAttributes<HTMLDivElement>;

export const CommandPaletteList = forwardRef<HTMLDivElement, CommandPaletteListProps>(
  function CommandPaletteList({ className, children, ...rest }, forwardedRef) {
    const ctx = useCommandPaletteContext();
    return (
      <div
        ref={forwardedRef}
        id={ctx.listboxId}
        role="listbox"
        aria-labelledby={ctx.inputId}
        className={cn('max-h-80 overflow-y-auto p-1', className)}
        {...rest}
      >
        {children}
      </div>
    );
  },
);

export interface CommandPaletteGroupProps extends HTMLAttributes<HTMLDivElement> {
  label?: ReactNode;
}

export function CommandPaletteGroup({
  label,
  children,
  className,
  ...rest
}: CommandPaletteGroupProps) {
  const labelId = useId();
  return (
    <div
      role="group"
      aria-labelledby={label ? labelId : undefined}
      className={className}
      {...rest}
    >
      {label && (
        <div id={labelId} className={listboxGroupLabelVariants()}>
          {label}
        </div>
      )}
      {children}
    </div>
  );
}

export function CommandPaletteSeparator(props: HTMLAttributes<HTMLDivElement>) {
  return <div role="separator" className={listboxSeparatorVariants()} {...props} />;
}

export interface CommandPaletteItemProps extends HTMLAttributes<HTMLDivElement> {
  value: string;
  /** The text used by the filter; defaults to `value`. Pass when children include icons. */
  searchText?: string;
  isDisabled?: boolean;
  onSelect?: () => void;
  closeOnSelect?: boolean;
  children: ReactNode;
}

export const CommandPaletteItem = forwardRef<HTMLDivElement, CommandPaletteItemProps>(
  function CommandPaletteItem(
    {
      value,
      searchText,
      isDisabled = false,
      onSelect,
      closeOnSelect = true,
      className,
      children,
      onClick,
      onPointerEnter,
      ...rest
    },
    forwardedRef,
  ) {
    const ctx = useCommandPaletteContext();
    const id = useId();

    // Resolve text for filter — fall back to children if string.
    const resolvedSearch =
      searchText ??
      (typeof children === 'string' ? children : Array.isArray(children) ? children.filter((c) => typeof c === 'string').join(' ') : value);

    // Depend on stable callbacks, not `ctx`: registering bumps registryVersion (new ctx identity), which would re-run this effect forever.
    const { registerItem, unregisterItem } = ctx;
    useEffect(() => {
      registerItem({
        id,
        value,
        searchText: resolvedSearch,
        disabled: isDisabled,
        onSelect: () => onSelect?.(),
        closeOnSelect,
      });
      return () => unregisterItem(id);
    }, [registerItem, unregisterItem, id, value, resolvedSearch, isDisabled, onSelect, closeOnSelect]);

    // Hide if filtered out.
    const matches = ctx.inputValue === '' || ctx.filter(resolvedSearch, ctx.inputValue);
    if (!matches) return null;

    const isActive = ctx.activeId === id;
    const state = isDisabled ? 'disabled' : isActive ? 'active' : 'default';

    return (
      <div
        ref={forwardedRef}
        id={id}
        role="option"
        aria-selected={isActive}
        aria-disabled={isDisabled || undefined}
        data-active={isActive ? '' : undefined}
        onClick={(e) => {
          onClick?.(e);
          if (e.defaultPrevented || isDisabled) return;
          onSelect?.();
          if (closeOnSelect) ctx.setOpen(false);
        }}
        onPointerEnter={(e) => {
          onPointerEnter?.(e);
          if (!isDisabled) ctx.setActiveId(id);
        }}
        className={cn(listboxItemVariants({ state }), className)}
        {...rest}
      >
        {children}
      </div>
    );
  },
);

export type CommandPaletteEmptyProps = HTMLAttributes<HTMLDivElement>;

export const CommandPaletteEmpty = forwardRef<HTMLDivElement, CommandPaletteEmptyProps>(
  function CommandPaletteEmpty({ className, children, ...rest }, forwardedRef) {
    const ctx = useCommandPaletteContext();
    // Show only when zero items match.
    const matchCount = ctx.itemsRef.current.filter(
      (i) => ctx.inputValue === '' || ctx.filter(i.searchText, ctx.inputValue),
    ).length;
    if (matchCount > 0) return null;
    return (
      <div
        ref={forwardedRef}
        // Polite live region — "no results" must be announced, not hidden as
        // presentational chrome.
        role="status"
        className={cn(listboxEmptyVariants(), className)}
        {...rest}
      >
        {children}
      </div>
    );
  },
);

export const CommandPalette = Object.assign(CommandPaletteRoot, {
  Content: CommandPaletteContent,
  Input: CommandPaletteInput,
  List: CommandPaletteList,
  Group: CommandPaletteGroup,
  Item: CommandPaletteItem,
  Empty: CommandPaletteEmpty,
  Separator: CommandPaletteSeparator,
});

export default CommandPalette;

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/nav/commandPalette/CommandPalette.vue
<script lang="ts">
/**
 * The prop surface of `CommandPalette`.
 *
 * `open` and `isOpen` are the same controlled state under two names: `open` is
 * the `v-model:open` binding target and React's own spelling, `isOpen` the house
 * boolean spelling. `open` wins when both are set. React's `onOpenChange` is the
 * `open-change` emit; `update:open` fires alongside it so `v-model:open` works,
 * and `update:inputValue` does the same for the search text.
 */
export interface CommandPaletteProps {
  /** The open state, controlled. The `v-model:open` binding target. */
  open?: boolean;

  /** The open state, controlled — the house spelling of `open`, which wins when both are set. */
  isOpen?: boolean;

  /** The initial open state when uncontrolled. Default `false`. */
  defaultOpen?: boolean;

  /** The search text, controlled. The `v-model:input-value` binding target. */
  inputValue?: string;

  /** The initial search text when uncontrolled. Default `''`. */
  defaultInputValue?: string;

  /** The key that opens the palette with ⌘/Ctrl. Omit to bind no global shortcut. */
  triggerKey?: string;

  /** The match predicate. Default case-insensitive substring. */
  filter?: (searchText: string, search: string) => boolean;
}
</script>

<script setup lang="ts">
import { computed, provide, shallowRef, watch } from 'vue';
import { useControlled, useId } from '../../../foundation/hooks';
import { useHotkeys } from '../../../foundation/shortcuts';
import { Modal } from '../../overlays/modal';
import {
  commandPaletteContextKey,
  defaultFilter,
  type CommandItemEntry,
} from './CommandPaletteContext';

/**
 * State owner for a CommandPalette tree — owns open state, search text and the
 * item registry, and renders the whole thing inside a `Modal`.
 */
defineOptions({ name: 'CommandPalette', inheritAttrs: false });

/** The palette tree — `CommandPaletteContent` and its parts. React's `children`. */
defineSlots<{ default(): unknown }>();

/** `open` / `isOpen` default to `undefined` so an absent prop cannot read as an explicit `false`. */
const props = withDefaults(defineProps<CommandPaletteProps>(), {
  open: undefined,
  isOpen: undefined,
  defaultOpen: false,
  inputValue: undefined,
  defaultInputValue: undefined,
  triggerKey: undefined,
  filter: defaultFilter,
});

const emit = defineEmits<{
  /** The `v-model:open` half. */
  'update:open': [open: boolean];

  /** Replaces React's `onOpenChange`. */
  'open-change': [open: boolean];

  /** The `v-model:input-value` half. */
  'update:inputValue': [input: string];

  /** Replaces React's `onInputChange`. */
  'input-change': [input: string];
}>();

const openState = useControlled<boolean>({
  controlled: () => props.open ?? props.isOpen,
  default: () => props.defaultOpen,
  onChange: (value) => {
    emit('update:open', value);
    emit('open-change', value);
  },
});

const inputState = useControlled<string>({
  controlled: () => props.inputValue,
  default: () => props.defaultInputValue ?? '',
  onChange: (value) => {
    emit('update:inputValue', value);
    emit('input-change', value);
  },
});

const items = shallowRef<ReadonlyArray<CommandItemEntry>>([]);
const activeId = shallowRef<string | null>(null);
const inputEl = shallowRef<HTMLInputElement | null>(null);
const inputId = useId();
const listboxId = useId();

function registerItem(entry: CommandItemEntry): void {
  const next = items.value.slice();
  const index = next.findIndex((i) => i.id === entry.id);
  if (index >= 0) next[index] = entry;
  else next.push(entry);
  items.value = next;
}

function unregisterItem(id: string): void {
  items.value = items.value.filter((i) => i.id !== id);
}

/* Global keybinding (cmd-/ctrl-K). `mod` = ⌘ on Apple / Ctrl elsewhere; the explicit `ctrl+`/`meta+` pair keeps
   the spec's "we accept both on every platform" contract. The chord must always parse (`+` is the token
   separator → `plus`; a falsy `triggerKey` needs a placeholder), so `enabled` — not an early return — unbinds. */
const chordKey = computed(() => {
  const key = props.triggerKey;
  return !key ? 'k' : key === '+' ? 'plus' : key;
});

useHotkeys(
  () => [`mod+${chordKey.value}`, `ctrl+${chordKey.value}`, `meta+${chordKey.value}`],
  () => openState.setValue(true),
  { enabled: () => Boolean(props.triggerKey) },
);

// Reset the active id on close.
watch(
  () => openState.value.value,
  (isOpen) => {
    if (!isOpen) activeId.value = null;
  },
  { flush: 'post' },
);

provide(commandPaletteContextKey, {
  open: openState.value,
  setOpen: openState.setValue,
  inputValue: inputState.value,
  setInputValue: inputState.setValue,
  activeId,
  setActiveId: (id: string | null) => {
    activeId.value = id;
  },
  items,
  registerItem,
  unregisterItem,
  /* Wrapped rather than stored, so a `filter` prop change is picked up live —
     React re-created the whole context value for the same effect. */
  filter: (searchText: string, search: string) => props.filter(searchText, search),
  inputId,
  listboxId,
  inputEl,
});

/* Lifted to a setup const so the template auto-unwraps it. Named `resolvedOpen`
   rather than `isOpen` — that name is already a declared prop here. */
const resolvedOpen = openState.value;
</script>

<template>
  <Modal :open="resolvedOpen" @open-change="openState.setValue"><slot /></Modal>
</template>
