// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/gantt/Gantt.vue
<script lang="ts">
import { Temporal } from 'temporal-polyfill';
import { addDays } from '../../forms/DateExtensions';

// Gantt models tasks/milestones as date-only spans → `Temporal.PlainDate`
// (calendar math, no time zone), the shape the day-column grid wants. Day
// counts + iteration go through the shared, Temporal-based `DateExtensions`.

export interface GanttTask {
  id: string;
  /** The row label. React took a `ReactNode`; richer content goes through the `task` slot. */
  label: string | number;
  start: Temporal.PlainDate;
  end: Temporal.PlainDate;
  color?: string;
  /** 0..1 — fills the bar from the left. */
  progress?: number;
}

export interface GanttDependency {
  from: string;
  to: string;
}

export interface GanttMilestone {
  id: string;
  /** The milestone label. React took a `ReactNode`; the marker itself renders no text. */
  label: string | number;
  date: Temporal.PlainDate;
}

export interface GanttProps {
  tasks: ReadonlyArray<GanttTask>;
  dependencies?: ReadonlyArray<GanttDependency>;
  milestones?: ReadonlyArray<GanttMilestone>;
  from?: Temporal.PlainDate;
  to?: Temporal.PlainDate;
  cellWidth?: number;
  rowHeight?: number;
  labelWidth?: number;
  hasWeekends?: boolean;
}

/** Earlier of two dates. */
function minDate(a: Temporal.PlainDate, b: Temporal.PlainDate): Temporal.PlainDate {
  return Temporal.PlainDate.compare(a, b) <= 0 ? a : b;
}

/** Later of two dates. */
function maxDate(a: Temporal.PlainDate, b: Temporal.PlainDate): Temporal.PlainDate {
  return Temporal.PlainDate.compare(a, b) >= 0 ? a : b;
}

function* eachDay(
  from: Temporal.PlainDate,
  to: Temporal.PlainDate,
): Generator<Temporal.PlainDate> {
  let cur = from;
  while (Temporal.PlainDate.compare(cur, to) <= 0) {
    yield cur;
    cur = addDays(cur, 1);
  }
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef, type StyleValue } from 'vue';
import type { ClassValue } from 'clsx';
import { cn } from '../../../foundation/utils';
import { daysBetween, isWeekend, today } from '../../forms/DateExtensions';

/**
 * First-generation Gantt chart. Tasks rendered as horizontal bars positioned
 * by start/end. Optional dependency arrows + "today" indicator. Drag-resize,
 * drag-move, critical path, group rows all deferred.
 */
/* `inheritAttrs: false` so `class` folds into the component's own `cn()` call — plain fallthrough
   appends outside it and loses tailwind-merge conflict resolution. */
defineOptions({ name: 'Gantt', inheritAttrs: false });

const props = withDefaults(defineProps<GanttProps>(), {
  dependencies: () => [],
  milestones: () => [],
  cellWidth: 40,
  rowHeight: 36,
  labelWidth: 200,
  hasWeekends: true,
});

const emit = defineEmits<{
  /** Fires when a task bar is clicked. Replaces React's `onTaskClick`. */
  'task-click': [task: GanttTask];
}>();

/** Replaces React's inline `task.label` rendering with an override hook. */
defineSlots<{
  /** Overrides a task's label, in both the label column and the bar. */
  task?(props: { task: GanttTask }): unknown;
}>();

const attrs = useAttrs();

/* `today()` reads the host time zone through `Temporal.Now` — universal, not a browser
   global, so it is safe to evaluate on the server. */
const range = computed(() => {
  if (props.tasks.length === 0) {
    const now = today();
    return { from: now, to: now, totalDays: 1 };
  }
  const minStart = props.from ?? props.tasks.map((t) => t.start).reduce(minDate);
  const maxEnd = props.to ?? props.tasks.map((t) => t.end).reduce(maxDate);
  return { from: minStart, to: maxEnd, totalDays: daysBetween(minStart, maxEnd) + 1 };
});

const rangeFrom = computed(() => range.value.from);
const totalDays = computed(() => range.value.totalDays);

const headerDates = computed(() => Array.from(eachDay(range.value.from, range.value.to)));
const todayOffset = computed(() => daysBetween(rangeFrom.value, today()));
const todayInRange = computed(
  () => todayOffset.value >= 0 && todayOffset.value < totalDays.value,
);

const taskIndex = computed(() => new Map(props.tasks.map((t, i) => [t.id, i])));

const timelineWidth = computed(() => totalDays.value * props.cellWidth);

/* Numeric CSS lengths are spelled with their unit — React's style object auto-appended `px`,
   Vue's does not, so a bare `36` would be dropped as an invalid declaration. */
const labelColumnStyle = computed<StyleValue>(() => ({ width: `${props.labelWidth}px` }));
const rowStyle = computed<StyleValue>(() => ({ height: `${props.rowHeight}px` }));
const cellStyle = computed<StyleValue>(() => ({ width: `${props.cellWidth}px` }));
const timelineStyle = computed<StyleValue>(() => ({ width: `${timelineWidth.value}px` }));
const overlayStyle = computed<StyleValue>(() => ({
  left: '0px',
  top: `${props.rowHeight}px`,
  width: `${timelineWidth.value}px`,
  height: `${props.tasks.length * props.rowHeight}px`,
}));

function headerCellClass(d: Temporal.PlainDate): string {
  return cn(
    'border-r border-border text-[10px] tabular-nums',
    isWeekend(d) && props.hasWeekends && 'bg-muted/40',
    d.day === 1 && 'border-l-2 border-l-border-strong',
  );
}

function gridlineClass(d: Temporal.PlainDate): string {
  return cn('border-r border-border/60', isWeekend(d) && props.hasWeekends && 'bg-muted/30');
}

function monthLabel(d: Temporal.PlainDate): string {
  return d.toLocaleString(undefined, { month: 'short', year: '2-digit' });
}

function barStyle(task: GanttTask): StyleValue {
  const offset = daysBetween(rangeFrom.value, task.start);
  const length = Math.max(1, daysBetween(task.start, task.end) + 1);
  return {
    left: `${offset * props.cellWidth + 4}px`,
    width: `${length * props.cellWidth - 8}px`,
    top: '6px',
    bottom: '6px',
    background: task.color,
  };
}

function barClass(task: GanttTask): string {
  return cn(
    'absolute overflow-hidden rounded-md border border-border/60 px-2 text-left text-[11px] font-medium transition-colors hover:brightness-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
    !task.color && 'bg-primary text-primary-foreground',
  );
}

function progressStyle(task: GanttTask): StyleValue {
  return { width: `${(task.progress ?? 0) * 100}%` };
}

function taskLabel(task: GanttTask): string {
  /* React narrowed a `ReactNode` label to a string before using it as a name; a numeric
     label falls back to the id here for the same reason. */
  return `${typeof task.label === 'string' ? task.label : task.id}: ${task.start.toLocaleString()} – ${task.end.toLocaleString()}`;
}

interface DependencyArrow {
  key: number;
  path: string;
  points: string;
}

const dependencyArrows = computed<Array<DependencyArrow>>(() => {
  const arrows: Array<DependencyArrow> = [];
  props.dependencies.forEach((dep, i) => {
    const fromIdx = taskIndex.value.get(dep.from);
    const toIdx = taskIndex.value.get(dep.to);
    if (fromIdx === undefined || toIdx === undefined) return;
    const fromTask = props.tasks[fromIdx]!;
    const toTask = props.tasks[toIdx]!;
    const fromX = (daysBetween(rangeFrom.value, fromTask.end) + 1) * props.cellWidth;
    const fromY = fromIdx * props.rowHeight + props.rowHeight / 2;
    const toX = daysBetween(rangeFrom.value, toTask.start) * props.cellWidth;
    const toY = toIdx * props.rowHeight + props.rowHeight / 2;
    const midX = Math.max(fromX + 8, (fromX + toX) / 2);
    arrows.push({
      key: i,
      path: `M ${fromX} ${fromY} L ${midX} ${fromY} L ${midX} ${toY} L ${toX - 4} ${toY}`,
      points: `${toX - 4},${toY - 3} ${toX - 4},${toY + 3} ${toX},${toY}`,
    });
  });
  return arrows;
});

function milestonePoints(m: GanttMilestone): string {
  const x = daysBetween(rangeFrom.value, m.date) * props.cellWidth + props.cellWidth / 2;
  return `${x},2 ${x + 6},10 ${x},18 ${x - 6},10`;
}

const todayX = computed(
  () => todayOffset.value * props.cellWidth + props.cellWidth / 2,
);
const todayY2 = computed(() => props.tasks.length * props.rowHeight);

const OWNED_ATTRS: ReadonlySet<string> = new Set(['class']);
const passthroughAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))),
);

const rootClass = computed(() =>
  cn(
    'overflow-auto rounded-md border border-border bg-card text-sm shadow-sm',
    attrs.class as ClassValue,
  ),
);

const root = useTemplateRef<HTMLDivElement>('root');

/** The rendered element — the Vue stand-in for the React original's forwarded ref. */
defineExpose({ el: root });
</script>

<template>
  <div
    ref="root"
    role="grid"
    aria-label="Gantt chart"
    :class="rootClass"
    v-bind="passthroughAttrs"
  >
    <div class="flex">
      <!-- Label column -->
      <div class="shrink-0 border-r border-border bg-muted/30" :style="labelColumnStyle">
        <div
          class="border-b border-border px-3 py-2 text-xs font-medium text-muted-foreground"
          :style="rowStyle"
        >
          Task
        </div>
        <div
          v-for="task in tasks"
          :key="task.id"
          class="flex items-center border-b border-border px-3 text-xs last:border-b-0"
          :style="rowStyle"
        >
          <span class="truncate font-medium">
            <slot name="task" :task="task">{{ task.label }}</slot>
          </span>
        </div>
      </div>
      <!-- Timeline -->
      <div class="relative flex-1 overflow-x-auto" style="min-width: 0">
        <div :style="timelineStyle">
          <!-- Header -->
          <div class="flex border-b border-border" :style="rowStyle">
            <div
              v-for="(d, i) in headerDates"
              :key="i"
              :class="headerCellClass(d)"
              :style="cellStyle"
            >
              <div
                v-if="d.day === 1"
                class="border-b border-border bg-muted px-1 py-0.5 text-center font-medium text-muted-foreground"
              >
                {{ monthLabel(d) }}
              </div>
              <div class="px-1 py-0.5 text-center text-muted-foreground">{{ d.day }}</div>
            </div>
          </div>
          <!-- Rows -->
          <div
            v-for="task in tasks"
            :key="task.id"
            class="relative border-b border-border last:border-b-0"
            :style="rowStyle"
          >
            <!-- Vertical day gridlines + weekend shading -->
            <div class="absolute inset-0 flex pointer-events-none">
              <div
                v-for="(d, i) in headerDates"
                :key="i"
                :style="cellStyle"
                :class="gridlineClass(d)"
              />
            </div>
            <!-- Bar -->
            <button
              type="button"
              :aria-label="taskLabel(task)"
              :style="barStyle(task)"
              :class="barClass(task)"
              @click="emit('task-click', task)"
            >
              <!-- Progress fill -->
              <div
                v-if="(task.progress ?? 0) > 0"
                aria-hidden="true"
                class="absolute inset-y-0 left-0 bg-foreground/20"
                :style="progressStyle(task)"
              />
              <span class="relative inline-flex h-full items-center truncate">
                <slot name="task" :task="task">{{ task.label }}</slot>
              </span>
            </button>
          </div>
        </div>
        <!-- Dependency arrows + today line -->
        <svg class="pointer-events-none absolute" :style="overlayStyle">
          <g v-for="arrow in dependencyArrows" :key="arrow.key">
            <path
              :d="arrow.path"
              fill="none"
              stroke="currentColor"
              :stroke-width="1"
              class="text-border-strong"
            />
            <polygon :points="arrow.points" class="fill-border-strong" />
          </g>
          <g v-for="m in milestones" :key="m.id">
            <polygon
              :points="milestonePoints(m)"
              class="fill-warning stroke-warning-foreground"
              :stroke-width="1"
            />
          </g>
          <line
            v-if="todayInRange"
            :x1="todayX"
            :x2="todayX"
            :y1="0"
            :y2="todayY2"
            class="stroke-primary"
            :stroke-width="1.5"
            stroke-dasharray="4 3"
          />
        </svg>
      </div>
    </div>
  </div>
</template>

// src/display/gantt/Gantt.tsx
import { forwardRef, useMemo, type HTMLAttributes, type ReactNode } from 'react';
import { Temporal } from '@js-temporal/polyfill';
import { cn } from '../../utils';
import { addDays, daysBetween, isWeekend, today } from '../../forms/DateExtensions';

// Gantt models tasks/milestones as date-only spans → `Temporal.PlainDate`
// (calendar math, no time zone), the shape the day-column grid wants. Day
// counts + iteration go through the shared, Temporal-based `DateExtensions`.

export interface GanttTask {
  id: string;
  label: ReactNode;
  start: Temporal.PlainDate;
  end: Temporal.PlainDate;
  color?: string;
  /** 0..1 — fills the bar from the left. */
  progress?: number;
}

export interface GanttDependency {
  from: string;
  to: string;
}

export interface GanttMilestone {
  id: string;
  label: ReactNode;
  date: Temporal.PlainDate;
}

export interface GanttProps extends HTMLAttributes<HTMLDivElement> {
  tasks: GanttTask[];
  dependencies?: GanttDependency[];
  milestones?: GanttMilestone[];
  from?: Temporal.PlainDate;
  to?: Temporal.PlainDate;
  cellWidth?: number;
  rowHeight?: number;
  labelWidth?: number;
  hasWeekends?: boolean;
  onTaskClick?: (task: GanttTask) => void;
}

/** Earlier of two dates. */
function minDate(a: Temporal.PlainDate, b: Temporal.PlainDate): Temporal.PlainDate {
  return Temporal.PlainDate.compare(a, b) <= 0 ? a : b;
}

/** Later of two dates. */
function maxDate(a: Temporal.PlainDate, b: Temporal.PlainDate): Temporal.PlainDate {
  return Temporal.PlainDate.compare(a, b) >= 0 ? a : b;
}

function* eachDay(from: Temporal.PlainDate, to: Temporal.PlainDate): Generator<Temporal.PlainDate> {
  let cur = from;
  while (Temporal.PlainDate.compare(cur, to) <= 0) {
    yield cur;
    cur = addDays(cur, 1);
  }
}

/**
 * First-generation Gantt chart. Tasks rendered as horizontal bars positioned
 * by start/end. Optional dependency arrows + "today" indicator. Drag-resize,
 * drag-move, critical path, group rows all deferred.
 */
export const Gantt = forwardRef<HTMLDivElement, GanttProps>(function Gantt(
  {
    tasks,
    dependencies = [],
    milestones = [],
    from: fromProp,
    to: toProp,
    cellWidth = 40,
    rowHeight = 36,
    labelWidth = 200,
    hasWeekends = true,
    onTaskClick,
    className,
    ...rest
  },
  ref,
) {
  const { from, to, totalDays } = useMemo(() => {
    if (tasks.length === 0) {
      const now = today();
      return { from: now, to: now, totalDays: 1 };
    }
    const minStart = fromProp ?? tasks.map((t) => t.start).reduce(minDate);
    const maxEnd = toProp ?? tasks.map((t) => t.end).reduce(maxDate);
    return {
      from: minStart,
      to: maxEnd,
      totalDays: daysBetween(minStart, maxEnd) + 1,
    };
  }, [tasks, fromProp, toProp]);

  const headerDates = useMemo(() => Array.from(eachDay(from, to)), [from, to]);
  const todayOffset = daysBetween(from, today());
  const todayInRange = todayOffset >= 0 && todayOffset < totalDays;

  const taskIndex = useMemo(() => new Map(tasks.map((t, i) => [t.id, i])), [tasks]);

  const timelineWidth = totalDays * cellWidth;

  return (
    <div
      ref={ref}
      role="grid"
      aria-label="Gantt chart"
      className={cn('overflow-auto rounded-md border border-border bg-card text-sm shadow-sm', className)}
      {...rest}
    >
      <div className="flex">
        {/* Label column */}
        <div className="shrink-0 border-r border-border bg-muted/30" style={{ width: labelWidth }}>
          <div className="border-b border-border px-3 py-2 text-xs font-medium text-muted-foreground" style={{ height: rowHeight }}>
            Task
          </div>
          {tasks.map((task) => (
            <div
              key={task.id}
              className="flex items-center border-b border-border px-3 text-xs last:border-b-0"
              style={{ height: rowHeight }}
            >
              <span className="truncate font-medium">{task.label}</span>
            </div>
          ))}
        </div>
        {/* Timeline */}
        <div className="relative flex-1 overflow-x-auto" style={{ minWidth: 0 }}>
          <div style={{ width: timelineWidth }}>
            {/* Header */}
            <div className="flex border-b border-border" style={{ height: rowHeight }}>
              {headerDates.map((d, i) => {
                const weekend = isWeekend(d);
                const isFirstOfMonth = d.day === 1;
                return (
                  <div
                    key={i}
                    className={cn(
                      'border-r border-border text-[10px] tabular-nums',
                      weekend && hasWeekends && 'bg-muted/40',
                      isFirstOfMonth && 'border-l-2 border-l-border-strong',
                    )}
                    style={{ width: cellWidth }}
                  >
                    {isFirstOfMonth && (
                      <div className="border-b border-border bg-muted px-1 py-0.5 text-center font-medium text-muted-foreground">
                        {d.toLocaleString(undefined, { month: 'short', year: '2-digit' })}
                      </div>
                    )}
                    <div className="px-1 py-0.5 text-center text-muted-foreground">
                      {d.day}
                    </div>
                  </div>
                );
              })}
            </div>
            {/* Rows */}
            {tasks.map((task) => {
              const offset = daysBetween(from, task.start);
              const length = Math.max(1, daysBetween(task.start, task.end) + 1);
              const left = offset * cellWidth;
              const width = length * cellWidth;
              const progress = task.progress ?? 0;
              return (
                <div
                  key={task.id}
                  className="relative border-b border-border last:border-b-0"
                  style={{ height: rowHeight }}
                >
                  {/* Vertical day gridlines + weekend shading */}
                  <div className="absolute inset-0 flex pointer-events-none">
                    {headerDates.map((d, i) => {
                      const weekend = isWeekend(d);
                      return (
                        <div
                          key={i}
                          style={{ width: cellWidth }}
                          className={cn(
                            'border-r border-border/60',
                            weekend && hasWeekends && 'bg-muted/30',
                          )}
                        />
                      );
                    })}
                  </div>
                  {/* Bar */}
                  <button
                    type="button"
                    role="button"
                    aria-label={`${typeof task.label === 'string' ? task.label : task.id}: ${task.start.toLocaleString()} – ${task.end.toLocaleString()}`}
                    onClick={() => onTaskClick?.(task)}
                    style={{
                      left: left + 4,
                      width: width - 8,
                      top: 6,
                      bottom: 6,
                      background: task.color,
                    }}
                    className={cn(
                      'absolute overflow-hidden rounded-md border border-border/60 px-2 text-left text-[11px] font-medium transition-colors hover:brightness-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
                      !task.color && 'bg-primary text-primary-foreground',
                    )}
                  >
                    {/* Progress fill */}
                    {progress > 0 && (
                      <div
                        aria-hidden="true"
                        className="absolute inset-y-0 left-0 bg-foreground/20"
                        style={{ width: `${progress * 100}%` }}
                      />
                    )}
                    <span className="relative inline-flex h-full items-center truncate">
                      {task.label}
                    </span>
                  </button>
                </div>
              );
            })}
          </div>
          {/* Dependency arrows + today line */}
          <svg
            className="pointer-events-none absolute"
            style={{
              left: 0,
              top: rowHeight,
              width: timelineWidth,
              height: tasks.length * rowHeight,
            }}
          >
            {dependencies.map((dep, i) => {
              const fromIdx = taskIndex.get(dep.from);
              const toIdx = taskIndex.get(dep.to);
              if (fromIdx == null || toIdx == null) return null;
              const fromTask = tasks[fromIdx]!;
              const toTask = tasks[toIdx]!;
              const fromX = (daysBetween(from, fromTask.end) + 1) * cellWidth;
              const fromY = fromIdx * rowHeight + rowHeight / 2;
              const toX = daysBetween(from, toTask.start) * cellWidth;
              const toY = toIdx * rowHeight + rowHeight / 2;
              const midX = Math.max(fromX + 8, (fromX + toX) / 2);
              const path = `M ${fromX} ${fromY} L ${midX} ${fromY} L ${midX} ${toY} L ${toX - 4} ${toY}`;
              return (
                <g key={i}>
                  <path d={path} fill="none" stroke="currentColor" strokeWidth={1} className="text-border-strong" />
                  <polygon
                    points={`${toX - 4},${toY - 3} ${toX - 4},${toY + 3} ${toX},${toY}`}
                    className="fill-border-strong"
                  />
                </g>
              );
            })}
            {milestones.map((m) => {
              const x = daysBetween(from, m.date) * cellWidth + cellWidth / 2;
              return (
                <g key={m.id}>
                  <polygon
                    points={`${x},2 ${x + 6},10 ${x},18 ${x - 6},10`}
                    className="fill-warning stroke-warning-foreground"
                    strokeWidth={1}
                  />
                </g>
              );
            })}
            {todayInRange && (
              <line
                x1={todayOffset * cellWidth + cellWidth / 2}
                x2={todayOffset * cellWidth + cellWidth / 2}
                y1={0}
                y2={tasks.length * rowHeight}
                className="stroke-primary"
                strokeWidth={1.5}
                strokeDasharray="4 3"
              />
            )}
          </svg>
        </div>
      </div>
    </div>
  );
});
