// src/presentation/feedback/bannerSimple/BannerSimple.tsx
import { forwardRef, type ComponentPropsWithoutRef } from 'react';
import { cn, type Severity } from '../../../foundation/utils';
import { bannerSimpleVariants, type BannerSimpleVariants } from './BannerSimple.variants';

export interface BannerSimpleProps
  extends ComponentPropsWithoutRef<'div'>,
    Omit<BannerSimpleVariants, 'severity'> {
  /** The semantic severity palette. */
  severity?: Severity;
}

/**
 * Full-width banner — typically pinned to the top of the app to broadcast
 * status. Atom; for structured slotted layout use `Banner` (L4).
 */
export const BannerSimple = forwardRef<HTMLDivElement, BannerSimpleProps>(
  ({ className, severity, role = 'status', ...props }, ref) => (
    <div
      ref={ref}
      role={role}
      className={cn(bannerSimpleVariants({ severity }), className)}
      {...props}
    />
  ),
);
BannerSimple.displayName = 'BannerSimple';

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/feedback/bannerSimple/BannerSimple.vue
<script lang="ts">
import type { Severity } from '../../../foundation/utils';

export interface BannerSimpleProps {
  /** The semantic severity palette. */
  severity?: Severity;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';
import { bannerSimpleVariants } from './BannerSimple.variants';

/**
 * Full-width banner — typically pinned to the top of the app to broadcast
 * status. Atom; for structured slotted layout use `Banner` (L4).
 *
 * `role="status"` is the live-region contract; bound before `v-bind="rest"`
 * so a caller-supplied `role` still wins.
 */
defineOptions({ name: 'BannerSimple', inheritAttrs: false });

const props = defineProps<BannerSimpleProps>();

const attrs = useAttrs();
const el = useTemplateRef<HTMLDivElement>('el');

const classes = computed(() =>
  cn(bannerSimpleVariants({ severity: props.severity }), attrs.class as string | undefined),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <div ref="el" role="status" v-bind="rest" :class="classes"><slot /></div>
</template>
