// engineering/codebase/wow-two-front-beta-sdk/src/presentation/forms/fileUpload/FileUpload.tsx
import {
  forwardRef,
  useCallback,
  useImperativeHandle,
  useRef,
  useState,
  type DragEvent,
  type InputHTMLAttributes,
  type KeyboardEvent,
  type ReactNode,
} from 'react';
import { UploadCloud } from 'lucide-react';
import { cn } from '../../../foundation/utils';
import { Icon } from '../../../foundation/icons';
import { matchesAccept, matchesAcceptType } from '../../../foundation/files';
import { useFormControl } from '../../../foundation/primitives/formControlContext/FormControlContext';

/** Defines why a picked file was rejected by the uploader. */
export const FileRejectionReason = {
  /** Refers to a file whose MIME type / extension is not accepted. */
  Type: 'type',
  /** Refers to a file exceeding the max size. */
  Size: 'size',
  /** Refers to a file beyond the max file count. */
  Count: 'count',
} as const;

export type FileRejectionReason = (typeof FileRejectionReason)[keyof typeof FileRejectionReason];

export interface FileRejection {
  file: File;
  reason: FileRejectionReason;
}

export interface FileUploadProps
  extends Omit<
    InputHTMLAttributes<HTMLInputElement>,
    'type' | 'value' | 'onChange' | 'children' | 'size'
  > {
  /** The per-file byte cap. Files exceeding this drop into `rejected`. */
  maxSize?: number;
  /** The cap on total accepted files (multiple mode). Excess go to `rejected`. */
  maxFiles?: number;
  onFilesChange?: (accepted: ReadonlyArray<File>, rejected: ReadonlyArray<FileRejection>) => void;
  isInvalid?: boolean;
  label?: ReactNode;
  hint?: ReactNode;
  children?: ReactNode;
}

/**
 * Drag-drop file zone with click-to-pick fallback. Validates against
 * `accept`, `maxSize`, and `maxFiles`. Emits accepted + rejected lists via
 * `onFilesChange`. The zone itself is a `role="button"` — Enter/Space opens
 * the native file picker.
 */
export const FileUpload = forwardRef<HTMLInputElement, FileUploadProps>(function FileUpload(
  {
    accept,
    multiple = false,
    maxSize,
    maxFiles,
    onFilesChange,
    disabled,
    isInvalid,
    label = 'Drop files here, or click to browse',
    hint,
    children,
    className,
    name,
    id,
    ...rest
  },
  forwardedRef,
) {
  const inputRef = useRef<HTMLInputElement | null>(null);
  useImperativeHandle(forwardedRef, () => inputRef.current as HTMLInputElement);
  const dragCounter = useRef(0);
  const [dragState, setDragState] = useState<'idle' | 'over' | 'reject'>('idle');

  /* FormControlContext adoption — explicit props stay as overrides. The HIDDEN native
     input carries the context id, so `Field`-rendered labels/describedby reference it
     (label click opens the picker). The dropzone mirrors describedby for keyboard users. */
  const ctx = useFormControl();
  const isDisabled = disabled ?? ctx?.isDisabled;
  const invalid = isInvalid ?? ctx?.isInvalid;

  const partition = useCallback(
    (files: FileList | ReadonlyArray<File>): [File[], ReadonlyArray<FileRejection>] => {
      const accepted: Array<File> = [];
      const rejected: Array<FileRejection> = [];
      const arr = Array.from(files);
      for (const f of arr) {
        if (!matchesAccept(f, accept)) {
          rejected.push({ file: f, reason: FileRejectionReason.Type });
          continue;
        }
        if (maxSize != null && f.size > maxSize) {
          rejected.push({ file: f, reason: FileRejectionReason.Size });
          continue;
        }
        accepted.push(f);
      }
      if (maxFiles != null && accepted.length > maxFiles) {
        const overflow = accepted.splice(maxFiles);
        for (const f of overflow) rejected.push({ file: f, reason: FileRejectionReason.Count });
      }
      return [accepted, rejected];
    },
    [accept, maxSize, maxFiles],
  );

  const openPicker = () => {
    if (!isDisabled) inputRef.current?.click();
  };

  const handleDragEnter = (e: DragEvent<HTMLDivElement>) => {
    if (isDisabled) return;
    e.preventDefault();
    dragCounter.current += 1;
    const items = e.dataTransfer?.items;
    let reject = false;
    /* Only the MIME type is exposed pre-drop — size is unavailable and extension tokens are
       unverifiable, so this check is advisory and stays optimistic (`extensionTokens: 'allow'`).
       `handleDrop` re-checks authoritatively with `matchesAccept`. */
    if (items && accept) {
      for (let i = 0; i < items.length; i++) {
        const it = items[i];
        if (!it || it.kind !== 'file') continue;
        if (!matchesAcceptType(it.type, accept)) {
          reject = true;
          break;
        }
      }
    }
    setDragState(reject ? 'reject' : 'over');
  };

  const handleDragOver = (e: DragEvent<HTMLDivElement>) => {
    if (isDisabled) return;
    e.preventDefault();
    e.dataTransfer.dropEffect = 'copy';
  };

  const handleDragLeave = (e: DragEvent<HTMLDivElement>) => {
    if (isDisabled) return;
    e.preventDefault();
    dragCounter.current -= 1;
    if (dragCounter.current <= 0) {
      dragCounter.current = 0;
      setDragState('idle');
    }
  };

  const handleDrop = (e: DragEvent<HTMLDivElement>) => {
    if (isDisabled) return;
    e.preventDefault();
    dragCounter.current = 0;
    setDragState('idle');
    const files = e.dataTransfer?.files;
    if (!files || files.length === 0) return;
    const [accepted, rejected] = partition(files);
    onFilesChange?.(accepted, rejected);
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLDivElement>) => {
    if (isDisabled) return;
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      openPicker();
    }
  };

  const showError = invalid || dragState === 'reject';

  return (
    <div className={cn('flex flex-col gap-3', className)}>
      <div
        role="button"
        tabIndex={isDisabled ? -1 : 0}
        aria-disabled={isDisabled || undefined}
        aria-describedby={ctx?.describedBy}
        data-drag-state={dragState}
        data-invalid={showError || undefined}
        onClick={openPicker}
        onKeyDown={handleKeyDown}
        onDragEnter={handleDragEnter}
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        onDrop={handleDrop}
        className={cn(
          'flex flex-col items-center justify-center gap-2 rounded-md border-2 border-dashed border-input bg-background px-6 py-10 text-center text-sm text-muted-foreground transition-colors',
          'hover:border-border-strong hover:bg-muted/40',
          'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
          dragState === 'over' && 'border-primary bg-primary-soft/30 text-foreground',
          showError && 'border-destructive bg-destructive-soft/30 text-destructive',
          isDisabled && 'cursor-not-allowed opacity-60 hover:border-input hover:bg-background',
        )}
      >
        <Icon
          icon={UploadCloud}
          size={28}
          className={cn(
            'text-muted-foreground',
            dragState === 'over' && 'text-primary',
            showError && 'text-destructive',
          )}
        />
        <div className="font-medium text-foreground">{label}</div>
        {hint && <div className="text-xs">{hint}</div>}
        <input
          {...rest}
          ref={inputRef}
          type="file"
          id={id ?? ctx?.id}
          accept={accept}
          multiple={multiple}
          disabled={isDisabled}
          aria-invalid={invalid || undefined}
          aria-describedby={ctx?.describedBy}
          /* aria- (not native) required — onChange resets `value` after handing files out, so a native `required` would block every submit. */
          aria-required={ctx?.isRequired || undefined}
          name={name}
          className="sr-only"
          onChange={(e) => {
            const files = e.target.files;
            if (!files || files.length === 0) return;
            const [accepted, rejected] = partition(files);
            onFilesChange?.(accepted, rejected);
            // reset so picking the same file again still fires
            e.target.value = '';
          }}
        />
      </div>
      {children}
    </div>
  );
});
FileUpload.displayName = 'FileUpload';

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/forms/fileUpload/FileUpload.vue
<script lang="ts">
/** Defines why a picked file was rejected by the uploader. */
export const FileRejectionReason = {
  /** Refers to a file whose MIME type / extension is not accepted. */
  Type: 'type',
  /** Refers to a file exceeding the max size. */
  Size: 'size',
  /** Refers to a file beyond the max file count. */
  Count: 'count',
} as const;

export type FileRejectionReason = (typeof FileRejectionReason)[keyof typeof FileRejectionReason];

export interface FileRejection {
  file: File;
  reason: FileRejectionReason;
}

/** Reflects the drop zone's live drag state; surfaced as `data-drag-state`. */
type DragState = 'idle' | 'over' | 'reject';

export interface FileUploadProps {
  /** The `accept` token list handed to the native input and used for validation. */
  accept?: string;

  /** Whether more than one file may be picked. Default `false`. */
  multiple?: boolean;

  /** The per-file byte cap. Files exceeding this drop into `rejected`. */
  maxSize?: number;

  /** The cap on total accepted files (multiple mode). Excess go to `rejected`. */
  maxFiles?: number;

  /** The invalid surface override. Falls back to the surrounding form control's `isInvalid`. */
  isInvalid?: boolean;

  /** The zone's headline. Fill the `label` slot for richer content. */
  label?: string | number;

  /** The zone's sub-line. Fill the `hint` slot for richer content. */
  hint?: string | number;

  /** The disabled state. Falls back to the surrounding form control's `isDisabled`. */
  disabled?: boolean;

  /** The native input name. */
  name?: string;

  /** The control's id. Auto-filled from `FormControl` context when omitted. */
  id?: string;
}
</script>

<script setup lang="ts">
import { computed, ref, useAttrs, useSlots, useTemplateRef } from 'vue';
import type { ClassValue } from 'clsx';
import { UploadCloud } from 'lucide-vue-next';
import { cn } from '../../../foundation/utils';
import { matchesAccept, matchesAcceptType } from '../../../foundation/files';
import { Icon } from '../../../foundation/icons';
import { useFormControl } from '../../../foundation/primitives';

/**
 * Drag-drop file zone with click-to-pick fallback. Validates against
 * `accept`, `maxSize`, and `maxFiles`. Emits accepted + rejected lists via
 * `files-change`. The zone itself is a `role="button"` — Enter/Space opens
 * the native file picker.
 */
/* `inheritAttrs: false` so `class` folds into the wrapper's own `cn()` call, and so the rest
   of the attrs land on the hidden native `<input>` rather than the wrapper. */
defineOptions({ name: 'FileUpload', inheritAttrs: false });

const props = withDefaults(defineProps<FileUploadProps>(), {
  multiple: false,
  label: 'Drop files here, or click to browse',
  /* Explicit `undefined` defaults: each flag falls back to the form control context, and Vue
     casts an absent `boolean` prop to `false` — which would shadow it. */
  isInvalid: undefined,
  disabled: undefined,
});

const emit = defineEmits<{
  /** Emits the partitioned pick. Replaces React's `onFilesChange`. */
  'files-change': [accepted: ReadonlyArray<File>, rejected: ReadonlyArray<FileRejection>];
}>();

defineSlots<{
  /** The content rendered under the drop zone — React's `children`. */
  default?(): unknown;
  label?(): unknown;
  hint?(): unknown;
}>();

const attrs = useAttrs();
const slots = useSlots();

const input = useTemplateRef<HTMLInputElement>('input');
const dragCounter = ref(0);
const dragState = ref<DragState>('idle');

/* FormControlContext adoption — explicit props stay as overrides. The HIDDEN native
   input carries the context id, so `Field`-rendered labels/describedby reference it
   (label click opens the picker). The dropzone mirrors describedby for keyboard users. */
const ctx = useFormControl();
const isDisabled = computed(() => props.disabled ?? ctx?.isDisabled);
const invalid = computed(() => props.isInvalid ?? ctx?.isInvalid);

function partition(files: FileList | ReadonlyArray<File>): [File[], ReadonlyArray<FileRejection>] {
  const accepted: Array<File> = [];
  const rejected: Array<FileRejection> = [];
  const arr = Array.from(files);
  for (const f of arr) {
    if (!matchesAccept(f, props.accept)) {
      rejected.push({ file: f, reason: FileRejectionReason.Type });
      continue;
    }
    if (props.maxSize != null && f.size > props.maxSize) {
      rejected.push({ file: f, reason: FileRejectionReason.Size });
      continue;
    }
    accepted.push(f);
  }
  if (props.maxFiles != null && accepted.length > props.maxFiles) {
    const overflow = accepted.splice(props.maxFiles);
    for (const f of overflow) rejected.push({ file: f, reason: FileRejectionReason.Count });
  }
  return [accepted, rejected];
}

function openPicker(): void {
  if (!isDisabled.value) input.value?.click();
}

function onDragEnter(event: DragEvent): void {
  if (isDisabled.value) return;
  event.preventDefault();
  dragCounter.value += 1;
  const items = event.dataTransfer?.items;
  let reject = false;
  /* Only the MIME type is exposed pre-drop — size is unavailable and extension tokens are
     unverifiable, so this check is advisory and stays optimistic (`extensionTokens: 'allow'`).
     `onDrop` re-checks authoritatively with `matchesAccept`. */
  if (items && props.accept) {
    for (let i = 0; i < items.length; i++) {
      const it = items[i];
      if (!it || it.kind !== 'file') continue;
      if (!matchesAcceptType(it.type, props.accept)) {
        reject = true;
        break;
      }
    }
  }
  dragState.value = reject ? 'reject' : 'over';
}

function onDragOver(event: DragEvent): void {
  if (isDisabled.value) return;
  event.preventDefault();
  if (event.dataTransfer) event.dataTransfer.dropEffect = 'copy';
}

function onDragLeave(event: DragEvent): void {
  if (isDisabled.value) return;
  event.preventDefault();
  dragCounter.value -= 1;
  if (dragCounter.value <= 0) {
    dragCounter.value = 0;
    dragState.value = 'idle';
  }
}

function onDrop(event: DragEvent): void {
  if (isDisabled.value) return;
  event.preventDefault();
  dragCounter.value = 0;
  dragState.value = 'idle';
  const files = event.dataTransfer?.files;
  if (!files || files.length === 0) return;
  const [accepted, rejected] = partition(files);
  emit('files-change', accepted, rejected);
}

function onKeydown(event: KeyboardEvent): void {
  if (isDisabled.value) return;
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    openPicker();
  }
}

function onChange(event: Event): void {
  const target = event.target as HTMLInputElement;
  const files = target.files;
  if (!files || files.length === 0) return;
  const [accepted, rejected] = partition(files);
  emit('files-change', accepted, rejected);
  // reset so picking the same file again still fires
  target.value = '';
}

const showError = computed(() => invalid.value || dragState.value === 'reject');

const hasHint = computed(() => Boolean(props.hint) || Boolean(slots.hint));

const inputId = computed(() => props.id ?? ctx?.id);

const OWNED_ATTRS: ReadonlySet<string> = new Set(['class']);
const passthroughAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))),
);

const wrapperClass = computed(() => cn('flex flex-col gap-3', attrs.class as ClassValue));

const zoneClass = computed(() =>
  cn(
    'flex flex-col items-center justify-center gap-2 rounded-md border-2 border-dashed border-input bg-background px-6 py-10 text-center text-sm text-muted-foreground transition-colors',
    'hover:border-border-strong hover:bg-muted/40',
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
    dragState.value === 'over' && 'border-primary bg-primary-soft/30 text-foreground',
    showError.value && 'border-destructive bg-destructive-soft/30 text-destructive',
    isDisabled.value && 'cursor-not-allowed opacity-60 hover:border-input hover:bg-background',
  ),
);

const iconClass = computed(() =>
  cn('text-muted-foreground', dragState.value === 'over' && 'text-primary', showError.value && 'text-destructive'),
);

const UploadIcon = UploadCloud;

/** The rendered `<input type="file">` — the Vue stand-in for the React original's forwarded ref. */
defineExpose({ el: input });
</script>

<template>
  <div :class="wrapperClass">
    <div
      role="button"
      :tabindex="isDisabled ? -1 : 0"
      :aria-disabled="isDisabled || undefined"
      :aria-describedby="ctx?.describedBy"
      :data-drag-state="dragState"
      :data-invalid="showError || undefined"
      :class="zoneClass"
      @click="openPicker"
      @keydown="onKeydown"
      @dragenter="onDragEnter"
      @dragover="onDragOver"
      @dragleave="onDragLeave"
      @drop="onDrop"
    >
      <Icon :icon="UploadIcon" :size="28" :class="iconClass" />
      <div class="font-medium text-foreground">
        <slot name="label">{{ label }}</slot>
      </div>
      <div v-if="hasHint" class="text-xs">
        <slot name="hint">{{ hint }}</slot>
      </div>
      <input
        ref="input"
        type="file"
        :id="inputId"
        :accept="accept"
        :multiple="multiple"
        :disabled="isDisabled"
        :aria-invalid="invalid || undefined"
        :aria-describedby="ctx?.describedBy"
        :aria-required="ctx?.isRequired || undefined"
        :name="name"
        class="sr-only"
        v-bind="passthroughAttrs"
        @change="onChange"
      />
    </div>
    <slot />
  </div>
</template>
