// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/videoPlayer/VideoPlayer.vue
<script lang="ts">
/** Defines the kind of a video text track. */
export const VideoTrackKind = {
  /** Refers to translation subtitles. */
  Subtitles: 'subtitles',
  /** Refers to closed captions. */
  Captions: 'captions',
  /** Refers to audio descriptions. */
  Descriptions: 'descriptions',
  /** Refers to chapter markers. */
  Chapters: 'chapters',
  /** Refers to script-only metadata. */
  Metadata: 'metadata',
} as const;

export type VideoTrackKind = (typeof VideoTrackKind)[keyof typeof VideoTrackKind];

export interface VideoTrack {
  src: string;
  srcLang: string;
  label: string;
  kind?: VideoTrackKind;
  default?: boolean;
}

export interface VideoPlayerProps {
  /** The video source URL. */
  src: string;
  /** The preview image shown before playback. */
  poster?: string;
  /** The caption/subtitle tracks rendered as `<track>` children. */
  tracks?: ReadonlyArray<VideoTrack>;
  /** The CSS `aspect-ratio` of the frame. Default `16 / 9`. */
  aspectRatio?: string | number;
  /** The autoplay state, forwarded to the native `<video>`. */
  autoPlay?: boolean;
  /** The loop state, forwarded to the native `<video>`. */
  loop?: boolean;
  /** The initial muted state — seeds the internal toggle, exactly as React's `muted` did. */
  muted?: boolean;
  /** The initial volume in 0..1. Default `1`. */
  defaultVolume?: number;
  /** The initial playback rate. Default `1`. */
  defaultPlaybackRate?: number;
}

const SPEEDS: ReadonlyArray<number> = [0.5, 0.75, 1, 1.25, 1.5, 2];

function formatTime(seconds: number): string {
  if (!Number.isFinite(seconds) || seconds < 0) return '0:00';
  const total = Math.floor(seconds);
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const sec = total % 60;
  if (h > 0) return `${h}:${String(m).padStart(2, '0')}:${String(sec).padStart(2, '0')}`;
  return `${m}:${String(sec).padStart(2, '0')}`;
}

/** The idle delay, in ms, before the controls bar fades out during playback. */
const IDLE_HIDE_MS = 3000;

const ICON_BUTTON_CLASS =
  'inline-flex h-7 w-7 items-center justify-center rounded text-white/80 hover:bg-white/20 hover:text-white';
</script>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, useAttrs, useTemplateRef, watch } from 'vue';
import {
  Captions,
  CaptionsOff,
  Maximize,
  Minimize,
  Pause,
  PictureInPicture2,
  Play,
  Volume2,
  VolumeX,
} from 'lucide-vue-next';
import { cn } from '../../../foundation/utils';
import { Icon } from '../../../foundation/icons';

/**
 * Custom-controls video player. Click video to toggle play; controls
 * auto-hide after 3s during playback; keyboard shortcuts (Space/F/M/C/←/→/↑/↓).
 */
defineOptions({ name: 'VideoPlayer', inheritAttrs: false });

const props = withDefaults(defineProps<VideoPlayerProps>(), {
  poster: undefined,
  tracks: undefined,
  aspectRatio: '16 / 9',
  // Explicit `undefined` so an absent Boolean prop is not cast to `false` and the
  // native element keeps its own default.
  autoPlay: undefined,
  loop: undefined,
  muted: undefined,
  defaultVolume: 1,
  defaultPlaybackRate: 1,
});

const attrs = useAttrs();
/** The wrapper — React held it as `containerRef`; fullscreen and the idle timer target it. */
const container = useTemplateRef<HTMLDivElement>('container');
/** The native `<video>` — React exposed it through `useImperativeHandle`. */
const el = useTemplateRef<HTMLVideoElement>('el');

const playing = ref(!!props.autoPlay);
const currentTime = ref(0);
const duration = ref(0);
const volume = ref(props.defaultVolume);
/**
 * Named apart from the `muted` prop, which only seeds it. A setup ref and a prop
 * of the same name collapse into one template binding, so the prop keeps its
 * React name and the state gets a distinct one.
 */
const isMuted = ref(!!props.muted);
const speed = ref(props.defaultPlaybackRate);
const fullscreen = ref(false);
const captionsOn = ref(false);
const showControls = ref(true);

let idleTimer: number | null = null;

/** Push the three imperative settings onto the element — React's first `useEffect`. */
function applyVideoSettings(): void {
  const video = el.value;
  if (!video) return;
  video.volume = volume.value;
  video.muted = isMuted.value;
  video.playbackRate = speed.value;
}

onMounted(applyVideoSettings);
watch([volume, isMuted, speed], applyVideoSettings, { flush: 'post' });

/** Mirror the caption toggle onto every `TextTrack` — React's second `useEffect`. */
function applyCaptionMode(): void {
  const video = el.value;
  if (!video || !video.textTracks) return;
  for (let i = 0; i < video.textTracks.length; i++) {
    const track = video.textTracks[i];
    if (track) track.mode = captionsOn.value ? 'showing' : 'hidden';
  }
}

onMounted(applyCaptionMode);
watch([captionsOn, () => props.tracks], applyCaptionMode, { flush: 'post' });

function onFullscreenChange(): void {
  fullscreen.value = document.fullscreenElement === container.value;
}

onMounted(() => {
  document.addEventListener('fullscreenchange', onFullscreenChange);
});

onBeforeUnmount(() => {
  document.removeEventListener('fullscreenchange', onFullscreenChange);
});

function togglePlay(): void {
  const video = el.value;
  if (!video) return;
  if (video.paused) {
    video.play().catch(() => {
      /* autoplay rejection */
    });
  } else {
    video.pause();
  }
}

function seekTo(seconds: number): void {
  const video = el.value;
  if (!video || !Number.isFinite(seconds)) return;
  video.currentTime = Math.max(0, Math.min(video.duration || 0, seconds));
}

function toggleFullscreen(): void {
  const node = container.value;
  if (!node) return;
  if (!document.fullscreenElement) {
    void node.requestFullscreen?.().catch(() => {
      /* denied by the user agent */
    });
  } else {
    void document.exitFullscreen?.().catch(() => {
      /* already exiting */
    });
  }
}

function togglePiP(): void {
  const video = el.value;
  if (!video) return;
  if ('pictureInPictureElement' in document && document.pictureInPictureElement) {
    void (document as unknown as { exitPictureInPicture?: () => Promise<void> }).exitPictureInPicture?.()?.catch(() => {
      /* not in picture-in-picture */
    });
  } else if ('requestPictureInPicture' in video) {
    void (video as HTMLVideoElement & { requestPictureInPicture?: () => Promise<unknown> })
      .requestPictureInPicture?.()
      ?.catch(() => {
        /* refused by the user agent */
      });
  }
}

/** Reveal the controls, and re-arm the idle fade only while playing. */
function bumpControls(): void {
  showControls.value = true;
  if (idleTimer != null) window.clearTimeout(idleTimer);
  if (playing.value) {
    idleTimer = window.setTimeout(() => {
      showControls.value = false;
    }, IDLE_HIDE_MS);
  }
}

onMounted(bumpControls);
watch(playing, bumpControls);
onBeforeUnmount(() => {
  if (idleTimer != null) window.clearTimeout(idleTimer);
});

function onMouseLeave(): void {
  if (playing.value) showControls.value = false;
}

function onKeydown(event: KeyboardEvent): void {
  // Only handle shortcuts aimed at the container itself — never hijack
  // keys from interactive children (seek slider, speed select, buttons).
  if (event.target !== event.currentTarget) return;
  switch (event.key) {
    case ' ':
    case 'Spacebar':
      event.preventDefault();
      togglePlay();
      break;
    case 'ArrowRight':
      event.preventDefault();
      seekTo(currentTime.value + 5);
      break;
    case 'ArrowLeft':
      event.preventDefault();
      seekTo(currentTime.value - 5);
      break;
    case 'ArrowUp':
      event.preventDefault();
      volume.value = Math.min(1, volume.value + 0.1);
      break;
    case 'ArrowDown':
      event.preventDefault();
      volume.value = Math.max(0, volume.value - 0.1);
      break;
    case 'm':
    case 'M':
      event.preventDefault();
      isMuted.value = !isMuted.value;
      break;
    case 'f':
    case 'F':
      event.preventDefault();
      toggleFullscreen();
      break;
    case 'c':
    case 'C':
      event.preventDefault();
      if (props.tracks && props.tracks.length > 0) captionsOn.value = !captionsOn.value;
      break;
  }
}

/*
 * The five handlers below sit AFTER `v-bind="rest"` on the `<video>`, so a
 * consumer's own listener for the same event runs first and this one second —
 * the order React's `composeEventHandlers(theirs, ours)` produced. The
 * `defaultPrevented` guard is that helper's `checkForDefaultPrevented`.
 */
function onNativePlay(event: Event): void {
  if (event.defaultPrevented) return;
  playing.value = true;
}

function onNativePause(event: Event): void {
  if (event.defaultPrevented) return;
  playing.value = false;
}

function onNativeTimeUpdate(event: Event): void {
  if (event.defaultPrevented) return;
  const video = el.value;
  if (!video) return;
  currentTime.value = video.currentTime;
}

function onNativeLoadedMetadata(event: Event): void {
  if (event.defaultPrevented) return;
  const video = el.value;
  if (video) duration.value = video.duration || 0;
}

function onVideoClick(event: MouseEvent): void {
  if (event.defaultPrevented) return;
  togglePlay();
}

function onRangeInput(event: Event): void {
  seekTo(Number((event.target as HTMLInputElement).value));
}

const classes = computed(() =>
  cn(
    'group relative overflow-hidden rounded-md bg-black text-white shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
    attrs.class as string | undefined,
  ),
);

/** `aspect-ratio` is unitless, so the numeric form only needs stringifying. */
const containerStyle = computed(() => ({
  aspectRatio: typeof props.aspectRatio === 'number' ? String(props.aspectRatio) : props.aspectRatio,
}));

const controlsClasses = computed(() =>
  cn(
    'absolute inset-x-0 bottom-0 flex items-center gap-2 bg-gradient-to-t from-black/80 to-transparent px-3 pb-2 pt-6 transition-opacity',
    showControls.value ? 'opacity-100' : 'opacity-0',
  ),
);

const hasTracks = computed(() => !!props.tracks && props.tracks.length > 0);

/**
 * Everything but `class` — and, exactly as in the React original, it lands on
 * the inner `<video>`, not on the wrapper. `class` is re-applied through `cn`.
 */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <div
    ref="container"
    role="region"
    aria-label="Video player"
    :tabindex="0"
    :class="classes"
    :style="containerStyle"
    @keydown="onKeydown"
    @mousemove="bumpControls"
    @mouseleave="onMouseLeave"
  >
    <video
      ref="el"
      :src="src"
      :poster="poster"
      :autoplay="autoPlay"
      :loop="loop"
      :muted="isMuted"
      v-bind="rest"
      class="h-full w-full bg-black"
      @play="onNativePlay"
      @pause="onNativePause"
      @timeupdate="onNativeTimeUpdate"
      @loadedmetadata="onNativeLoadedMetadata"
      @click="onVideoClick"
    >
      <track
        v-for="(item, index) in tracks"
        :key="index"
        :src="item.src"
        :srclang="item.srcLang"
        :label="item.label"
        :kind="item.kind ?? 'captions'"
        :default="item.default"
      />
    </video>

    <!-- Big center play button when paused -->
    <button
      v-if="!playing"
      type="button"
      aria-label="Play"
      class="absolute inset-0 grid place-items-center bg-black/30 transition-opacity hover:bg-black/40"
      @click="togglePlay"
    >
      <span class="grid h-16 w-16 place-items-center rounded-full bg-white/90 text-foreground shadow-lg">
        <Icon :icon="Play" :size="28" />
      </span>
    </button>

    <!-- Controls bar -->
    <div :class="controlsClasses">
      <button
        type="button"
        :aria-label="playing ? 'Pause' : 'Play'"
        class="inline-flex h-8 w-8 items-center justify-center rounded-full bg-white/20 text-white hover:bg-white/30"
        @click="togglePlay"
      >
        <Icon :icon="playing ? Pause : Play" :size="14" />
      </button>
      <span class="text-xs tabular-nums"> {{ formatTime(currentTime) }} / {{ formatTime(duration) }} </span>
      <input
        type="range"
        role="slider"
        aria-label="Seek"
        :aria-valuetext="formatTime(currentTime)"
        :min="0"
        :max="duration || 0"
        step="any"
        :value="currentTime"
        class="flex-1 accent-primary"
        @input="onRangeInput"
      />
      <button
        type="button"
        :aria-label="isMuted || volume === 0 ? 'Unmute' : 'Mute'"
        :class="ICON_BUTTON_CLASS"
        @click="isMuted = !isMuted"
      >
        <Icon :icon="isMuted || volume === 0 ? VolumeX : Volume2" :size="14" />
      </button>
      <select
        v-model="speed"
        aria-label="Playback speed"
        class="h-7 rounded-sm border border-white/20 bg-black/40 px-1 text-xs"
      >
        <option v-for="rate in SPEEDS" :key="rate" :value="rate" class="text-foreground">{{ rate }}×</option>
      </select>
      <button
        v-if="hasTracks"
        type="button"
        :aria-label="captionsOn ? 'Hide captions' : 'Show captions'"
        :aria-pressed="captionsOn"
        :class="ICON_BUTTON_CLASS"
        @click="captionsOn = !captionsOn"
      >
        <Icon :icon="captionsOn ? Captions : CaptionsOff" :size="14" />
      </button>
      <button type="button" aria-label="Picture in picture" :class="ICON_BUTTON_CLASS" @click="togglePiP">
        <Icon :icon="PictureInPicture2" :size="14" />
      </button>
      <button
        type="button"
        :aria-label="fullscreen ? 'Exit fullscreen' : 'Enter fullscreen'"
        :class="ICON_BUTTON_CLASS"
        @click="toggleFullscreen"
      >
        <Icon :icon="fullscreen ? Minimize : Maximize" :size="14" />
      </button>
    </div>
  </div>
</template>

// src/presentation/display/videoPlayer/VideoPlayer.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
  type KeyboardEvent,
  type VideoHTMLAttributes,
} from 'react';
import {
  Captions,
  CaptionsOff,
  Maximize,
  Minimize,
  Pause,
  PictureInPicture2,
  Play,
  Volume2,
  VolumeX,
} from 'lucide-react';
import { cn, composeEventHandlers } from '../../../foundation/utils';
import { Icon } from '../../../foundation/icons';

export interface VideoTrack {
  src: string;
  srcLang: string;
  label: string;
  kind?: 'subtitles' | 'captions' | 'descriptions' | 'chapters' | 'metadata';
  default?: boolean;
}

export interface VideoPlayerProps
  extends Omit<VideoHTMLAttributes<HTMLVideoElement>, 'controls'> {
  src: string;
  poster?: string;
  tracks?: VideoTrack[];
  aspectRatio?: string | number;
  defaultVolume?: number;
  defaultPlaybackRate?: number;
}

const SPEEDS = [0.5, 0.75, 1, 1.25, 1.5, 2];

function formatTime(s: number): string {
  if (!Number.isFinite(s) || s < 0) return '0:00';
  const total = Math.floor(s);
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const sec = total % 60;
  if (h > 0) return `${h}:${String(m).padStart(2, '0')}:${String(sec).padStart(2, '0')}`;
  return `${m}:${String(sec).padStart(2, '0')}`;
}

/**
 * Custom-controls video player. Click video to toggle play; controls
 * auto-hide after 3s during playback; keyboard shortcuts (Space/F/M/C/←/→/↑/↓).
 */
export const VideoPlayer = forwardRef<HTMLVideoElement, VideoPlayerProps>(
  function VideoPlayer(
    {
      src,
      poster,
      tracks,
      aspectRatio = '16 / 9',
      autoPlay,
      loop,
      muted: mutedProp,
      defaultVolume = 1,
      defaultPlaybackRate = 1,
      onPlay,
      onPause,
      onTimeUpdate,
      onLoadedMetadata,
      onClick,
      className,
      ...rest
    },
    forwardedRef,
  ) {
    const containerRef = useRef<HTMLDivElement | null>(null);
    const videoRef = useRef<HTMLVideoElement | null>(null);
    useImperativeHandle(forwardedRef, () => videoRef.current as HTMLVideoElement);
    const [playing, setPlaying] = useState(!!autoPlay);
    const [currentTime, setCurrentTime] = useState(0);
    const [duration, setDuration] = useState(0);
    const [volume, setVolume] = useState(defaultVolume);
    const [muted, setMuted] = useState(!!mutedProp);
    const [speed, setSpeed] = useState(defaultPlaybackRate);
    const [fullscreen, setFullscreen] = useState(false);
    const [captionsOn, setCaptionsOn] = useState(false);
    const [showControls, setShowControls] = useState(true);
    const idleTimerRef = useRef<number | null>(null);

    useEffect(() => {
      const v = videoRef.current;
      if (!v) return;
      v.volume = volume;
      v.muted = muted;
      v.playbackRate = speed;
    }, [volume, muted, speed]);

    useEffect(() => {
      const v = videoRef.current;
      if (!v || !v.textTracks) return;
      for (let i = 0; i < v.textTracks.length; i++) {
        v.textTracks[i]!.mode = captionsOn ? 'showing' : 'hidden';
      }
    }, [captionsOn, tracks]);

    useEffect(() => {
      const onFsChange = () => setFullscreen(document.fullscreenElement === containerRef.current);
      document.addEventListener('fullscreenchange', onFsChange);
      return () => document.removeEventListener('fullscreenchange', onFsChange);
    }, []);

    const togglePlay = useCallback(() => {
      const v = videoRef.current;
      if (!v) return;
      if (v.paused) v.play().catch(() => {});
      else v.pause();
    }, []);

    const seekTo = useCallback((seconds: number) => {
      const v = videoRef.current;
      if (!v || !Number.isFinite(seconds)) return;
      v.currentTime = Math.max(0, Math.min(v.duration || 0, seconds));
    }, []);

    const toggleFullscreen = useCallback(async () => {
      const c = containerRef.current;
      if (!c) return;
      if (!document.fullscreenElement) {
        await c.requestFullscreen?.().catch(() => {});
      } else {
        await document.exitFullscreen?.().catch(() => {});
      }
    }, []);

    const togglePiP = useCallback(async () => {
      const v = videoRef.current;
      if (!v) return;
      if ('pictureInPictureElement' in document && document.pictureInPictureElement) {
        await (document as unknown as { exitPictureInPicture?: () => Promise<void> })
          .exitPictureInPicture?.()
          ?.catch(() => {});
      } else if ('requestPictureInPicture' in v) {
        await (v as HTMLVideoElement & { requestPictureInPicture?: () => Promise<unknown> })
          .requestPictureInPicture?.()
          ?.catch(() => {});
      }
    }, []);

    const bumpControls = useCallback(() => {
      setShowControls(true);
      if (idleTimerRef.current != null) window.clearTimeout(idleTimerRef.current);
      if (playing) {
        idleTimerRef.current = window.setTimeout(() => setShowControls(false), 3000);
      }
    }, [playing]);

    useEffect(() => {
      bumpControls();
      return () => {
        if (idleTimerRef.current != null) window.clearTimeout(idleTimerRef.current);
      };
    }, [playing, bumpControls]);

    const handleKey = (e: KeyboardEvent<HTMLDivElement>) => {
      // Only handle shortcuts aimed at the container itself — never hijack
      // keys from interactive children (seek slider, speed select, buttons).
      if (e.target !== e.currentTarget) return;
      switch (e.key) {
        case ' ':
        case 'Spacebar':
          e.preventDefault();
          togglePlay();
          break;
        case 'ArrowRight':
          e.preventDefault();
          seekTo(currentTime + 5);
          break;
        case 'ArrowLeft':
          e.preventDefault();
          seekTo(currentTime - 5);
          break;
        case 'ArrowUp':
          e.preventDefault();
          setVolume((v) => Math.min(1, v + 0.1));
          break;
        case 'ArrowDown':
          e.preventDefault();
          setVolume((v) => Math.max(0, v - 0.1));
          break;
        case 'm':
        case 'M':
          e.preventDefault();
          setMuted((m) => !m);
          break;
        case 'f':
        case 'F':
          e.preventDefault();
          toggleFullscreen();
          break;
        case 'c':
        case 'C':
          e.preventDefault();
          if (tracks && tracks.length > 0) setCaptionsOn((c) => !c);
          break;
      }
    };

    return (
      <div
        ref={containerRef}
        role="region"
        aria-label="Video player"
        tabIndex={0}
        onKeyDown={handleKey}
        onMouseMove={bumpControls}
        onMouseLeave={() => {
          if (playing) setShowControls(false);
        }}
        className={cn(
          'group relative overflow-hidden rounded-md bg-black text-white shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
          className,
        )}
        style={{ aspectRatio: typeof aspectRatio === 'number' ? String(aspectRatio) : aspectRatio }}
      >
        <video
          ref={videoRef}
          src={src}
          poster={poster}
          autoPlay={autoPlay}
          loop={loop}
          muted={muted}
          {...rest}
          onPlay={composeEventHandlers(onPlay, () => setPlaying(true))}
          onPause={composeEventHandlers(onPause, () => setPlaying(false))}
          onTimeUpdate={composeEventHandlers(onTimeUpdate, () => {
            const v = videoRef.current;
            if (!v) return;
            setCurrentTime(v.currentTime);
          })}
          onLoadedMetadata={composeEventHandlers(onLoadedMetadata, () => {
            const v = videoRef.current;
            if (v) setDuration(v.duration || 0);
          })}
          onClick={composeEventHandlers(onClick, togglePlay)}
          className="h-full w-full bg-black"
        >
          {tracks?.map((t, i) => (
            <track
              key={i}
              src={t.src}
              srcLang={t.srcLang}
              label={t.label}
              kind={t.kind ?? 'captions'}
              default={t.default}
            />
          ))}
        </video>

        {/* Big center play button when paused */}
        {!playing && (
          <button
            type="button"
            aria-label="Play"
            onClick={togglePlay}
            className="absolute inset-0 grid place-items-center bg-black/30 transition-opacity hover:bg-black/40"
          >
            <span className="grid h-16 w-16 place-items-center rounded-full bg-white/90 text-foreground shadow-lg">
              <Icon icon={Play} size={28} />
            </span>
          </button>
        )}

        {/* Controls bar */}
        <div
          className={cn(
            'absolute inset-x-0 bottom-0 flex items-center gap-2 bg-gradient-to-t from-black/80 to-transparent px-3 pb-2 pt-6 transition-opacity',
            showControls ? 'opacity-100' : 'opacity-0',
          )}
        >
          <button
            type="button"
            aria-label={playing ? 'Pause' : 'Play'}
            onClick={togglePlay}
            className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-white/20 text-white hover:bg-white/30"
          >
            <Icon icon={playing ? Pause : Play} size={14} />
          </button>
          <span className="text-xs tabular-nums">
            {formatTime(currentTime)} / {formatTime(duration)}
          </span>
          <input
            type="range"
            role="slider"
            aria-label="Seek"
            aria-valuetext={formatTime(currentTime)}
            min={0}
            max={duration || 0}
            step="any"
            value={currentTime}
            onChange={(e) => seekTo(Number(e.target.value))}
            className="flex-1 accent-primary"
          />
          <button
            type="button"
            aria-label={muted || volume === 0 ? 'Unmute' : 'Mute'}
            onClick={() => setMuted((m) => !m)}
            className="inline-flex h-7 w-7 items-center justify-center rounded text-white/80 hover:bg-white/20 hover:text-white"
          >
            <Icon icon={muted || volume === 0 ? VolumeX : Volume2} size={14} />
          </button>
          <select
            aria-label="Playback speed"
            value={speed}
            onChange={(e) => setSpeed(Number(e.target.value))}
            className="h-7 rounded-sm border border-white/20 bg-black/40 px-1 text-xs"
          >
            {SPEEDS.map((s) => (
              <option key={s} value={s} className="text-foreground">
                {s}×
              </option>
            ))}
          </select>
          {tracks && tracks.length > 0 && (
            <button
              type="button"
              aria-label={captionsOn ? 'Hide captions' : 'Show captions'}
              aria-pressed={captionsOn}
              onClick={() => setCaptionsOn((c) => !c)}
              className="inline-flex h-7 w-7 items-center justify-center rounded text-white/80 hover:bg-white/20 hover:text-white"
            >
              <Icon icon={captionsOn ? Captions : CaptionsOff} size={14} />
            </button>
          )}
          <button
            type="button"
            aria-label="Picture in picture"
            onClick={togglePiP}
            className="inline-flex h-7 w-7 items-center justify-center rounded text-white/80 hover:bg-white/20 hover:text-white"
          >
            <Icon icon={PictureInPicture2} size={14} />
          </button>
          <button
            type="button"
            aria-label={fullscreen ? 'Exit fullscreen' : 'Enter fullscreen'}
            onClick={toggleFullscreen}
            className="inline-flex h-7 w-7 items-center justify-center rounded text-white/80 hover:bg-white/20 hover:text-white"
          >
            <Icon icon={fullscreen ? Minimize : Maximize} size={14} />
          </button>
        </div>
      </div>
    );
  },
);
