// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/forms/tagsInput/TagsInput.vue
<script lang="ts">
import type { TagVariant } from '../../display/tag';
import type { InputSize, InputState } from '../InputStyles';

export interface TagsInputProps {
  /** The control size. */
  size?: InputSize;

  /** The validity surface. */
  state?: InputState;

  /** The committed tags, controlled — React's spelling, which wins when both are set. */
  value?: ReadonlyArray<string>;

  /** The committed tags, controlled. The `v-model` binding target. */
  modelValue?: ReadonlyArray<string>;

  /** The initial tags when uncontrolled. */
  defaultValue?: ReadonlyArray<string>;

  /** The in-flight text, controlled. The `v-model:input-value` binding target. */
  inputValue?: string;

  /** The empty-state placeholder. */
  placeholder?: string;

  /** The characters that commit the current input. Enter and Tab always do. */
  delimiters?: ReadonlyArray<string>;

  /**
   * The predicate gating committed tags. Default: non-empty after trim.
   *
   * Kept a PROP, not an emit: it RETURNS a verdict, which an emit cannot do.
   */
  validate?: (tag: string) => boolean;

  /** Whether the same tag may be committed twice. */
  allowsDuplicates?: boolean;

  /** The cap on committed tags. */
  max?: number;

  /** The invalid surface override. Falls back to the surrounding form control's `isInvalid`. */
  isInvalid?: boolean;

  /** The hidden input name; the hidden input emits the comma-joined value. */
  name?: string;

  /**
   * The chip variant.
   *
   * The NAMED type, not `TagVariants['variant']` as React spelled it — the SFC prop
   * resolver cannot follow an indexed access into an imported interface, and the build
   * fails on it while `vue-tsc` stays green.
   */
  tagVariant?: TagVariant;

  /** The control's id. Auto-filled from `FormControl` context when omitted. */
  id?: string;

  /** The disabled state. Falls back to the surrounding form control's `isDisabled`. */
  disabled?: boolean;

  /** The read-only state — React's spelling. Falls back to the form control's `isReadOnly`. */
  readOnly?: boolean;

  /** The DOM spelling of {@link TagsInputProps.readOnly}, which wins when both are set. */
  readonly?: boolean;
}
</script>

<script setup lang="ts">
import { computed, ref, useAttrs, useTemplateRef } from 'vue';
import type { ClassValue } from 'clsx';
import { cn } from '../../../foundation/utils';
import { useControlled } from '../../../foundation/hooks';
import { useFormControl } from '../../../foundation/primitives';
import Tag from '../../display/tag/Tag.vue';
import { inputBaseVariants, InputState as InputStateValue } from '../InputStyles';

/**
 * Free-form tag entry. Type → Enter/comma/Tab commits. Backspace at empty
 * input removes the last tag. Renders chips via `display/Tag`.
 */
/* `inheritAttrs: false` so `class` folds into the container's own `cn()` call — plain fallthrough
   appends outside it and loses tailwind-merge conflict resolution. */
defineOptions({ name: 'TagsInput', inheritAttrs: false });

const props = withDefaults(defineProps<TagsInputProps>(), {
  placeholder: 'Add tag…',
  delimiters: () => [','],
  validate: (t: string) => t.trim().length > 0,
  allowsDuplicates: false,
  tagVariant: 'neutral',
  /* Explicit `undefined` defaults are load-bearing: each flag falls back to the form control
     context, and Vue casts an absent `boolean` prop to `false` — which would shadow it. */
  isInvalid: undefined,
  disabled: undefined,
  readOnly: undefined,
  readonly: undefined,
});

const emit = defineEmits<{
  /** The `v-model` half. */
  'update:modelValue': [tags: ReadonlyArray<string>];
  /** Replaces React's `onValueChange`. */
  'value-change': [tags: ReadonlyArray<string>];
  /** The `v-model:input-value` half. */
  'update:inputValue': [input: string];
  /** Replaces React's `onInputChange`. */
  'input-change': [input: string];
}>();

const attrs = useAttrs();

const tagsControlled = useControlled<ReadonlyArray<string>>({
  controlled: () => props.value ?? props.modelValue,
  default: () => props.defaultValue ?? [],
  onChange: (next) => {
    emit('update:modelValue', next);
    emit('value-change', next);
  },
});

const textControlled = useControlled<string>({
  controlled: () => props.inputValue,
  default: () => '',
  onChange: (next) => {
    emit('update:inputValue', next);
    emit('input-change', next);
  },
});

const tags = tagsControlled.value;
const text = textControlled.value;

const input = useTemplateRef<HTMLInputElement>('input');
const pendingDelete = ref(false);

/* FormControlContext adoption — explicit props stay as overrides. */
const ctx = useFormControl();
const isDisabled = computed(() => props.disabled ?? ctx?.isDisabled);
const isReadOnly = computed(() => props.readonly ?? props.readOnly ?? ctx?.isReadOnly);
const invalid = computed(() => props.isInvalid ?? ctx?.isInvalid);
const finalState = computed(
  () =>
    props.state ?? (invalid.value ? InputStateValue.Invalid : InputStateValue.Default),
);

function commit(raw: string): void {
  const trimmed = raw.trim();
  if (!trimmed || !props.validate(trimmed)) return;
  if (!props.allowsDuplicates && tags.value.includes(trimmed)) return;
  if (props.max != null && tags.value.length >= props.max) return;
  tagsControlled.setValue([...tags.value, trimmed]);
  textControlled.setValue('');
}

function removeAt(index: number): void {
  tagsControlled.setValue(tags.value.filter((_, i) => i !== index));
}

function onInput(event: Event): void {
  textControlled.setValue((event.target as HTMLInputElement).value);
}

/* Runs after any caller-supplied `@keydown` (declared after `v-bind`), exactly as React's
   `onKeyDown?.(e)` ran before this body. */
function onKeydown(event: KeyboardEvent): void {
  if (event.defaultPrevented || isDisabled.value || isReadOnly.value) return;
  if (event.key === 'Enter' || (event.key === 'Tab' && text.value)) {
    if (text.value) {
      event.preventDefault();
      commit(text.value);
      pendingDelete.value = false;
    }
    return;
  }
  if (props.delimiters.includes(event.key)) {
    event.preventDefault();
    commit(text.value);
    pendingDelete.value = false;
    return;
  }
  if (event.key === 'Backspace' && !text.value && tags.value.length > 0) {
    if (pendingDelete.value) {
      event.preventDefault();
      removeAt(tags.value.length - 1);
      pendingDelete.value = false;
    } else {
      pendingDelete.value = true;
    }
    return;
  }
  pendingDelete.value = false;
}

/* React did not gate blur on `defaultPrevented`; neither does this. */
function onBlur(): void {
  if (text.value) commit(text.value);
  pendingDelete.value = false;
}

function onContainerClick(event: MouseEvent): void {
  if (event.target === event.currentTarget) input.value?.focus();
}

function isPendingDelete(index: number): boolean {
  return pendingDelete.value && index === tags.value.length - 1;
}

/**
 * The Vue `Tag` renders its close button only when the consumer bound `@close` — the same
 * `onClose && <button/>` guard React had. A listener cannot be conditionally omitted with
 * `@close`, so it is bound through `v-on` with an object that is empty when closing is off.
 */
function tagListeners(index: number): Record<string, () => void> {
  if (isDisabled.value || isReadOnly.value) return {};
  return { close: () => removeAt(index) };
}

function tagClass(index: number): string {
  return cn(isPendingDelete(index) && 'ring-1 ring-ring');
}

/* Never declared props — a declared `'aria-describedby'` would arrive as
   `props.ariaDescribedby` and stop reaching the DOM. Both are read off the attrs so the
   consumer's value can override the context's. */
const ariaDescribedBy = computed(() => attrs['aria-describedby'] as string | undefined);
const ariaRequired = computed(() => attrs['aria-required'] as 'true' | 'false' | boolean | undefined);

const inputId = computed(() => props.id ?? ctx?.id);
const describedBy = computed(() => ariaDescribedBy.value ?? ctx?.describedBy);
/* aria- (not native) required — the tag list is the value; a native `required` on the empty
   inner input would block submits even with tags committed. */
const requiredAttr = computed(() => ariaRequired.value ?? (ctx?.isRequired || undefined));
const inputPlaceholder = computed(() =>
  tags.value.length === 0 ? props.placeholder : undefined,
);
const hiddenValue = computed(() => tags.value.join(','));

const OWNED_ATTRS: ReadonlySet<string> = new Set([
  'class',
  'aria-describedby',
  'aria-required',
]);
const passthroughAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))),
);

const rootClass = computed(() =>
  cn(
    inputBaseVariants({ size: props.size, state: finalState.value }),
    'h-auto min-h-10 flex-wrap items-center gap-1.5 py-1.5',
    isDisabled.value && 'cursor-not-allowed opacity-60',
    attrs.class as ClassValue,
  ),
);

/** The rendered `<input>` — the Vue stand-in for the React original's forwarded ref. */
defineExpose({ el: input });
</script>

<template>
  <div
    role="group"
    :data-disabled="isDisabled || undefined"
    :data-readonly="isReadOnly || undefined"
    :data-invalid="invalid || undefined"
    :class="rootClass"
    @click="onContainerClick"
  >
    <Tag
      v-for="(t, i) in tags"
      :key="`${t}-${i}`"
      :variant="tagVariant"
      :data-pending-delete="isPendingDelete(i) ? '' : undefined"
      :class="tagClass(i)"
      v-on="tagListeners(i)"
    >
      {{ t }}
    </Tag>
    <input
      ref="input"
      type="text"
      :id="inputId"
      :value="text"
      :placeholder="inputPlaceholder"
      :disabled="isDisabled"
      :readonly="isReadOnly"
      :aria-invalid="invalid || undefined"
      :aria-describedby="describedBy"
      :aria-required="requiredAttr"
      class="min-w-[6rem] flex-1 border-0 bg-transparent p-0 text-sm outline-none placeholder:text-subtle-foreground disabled:cursor-not-allowed"
      v-bind="passthroughAttrs"
      @input="onInput"
      @keydown="onKeydown"
      @blur="onBlur"
    />
    <input v-if="name" type="hidden" :name="name" :value="hiddenValue" />
  </div>
</template>

// src/presentation/forms/tagsInput/TagsInput.tsx
import {
  forwardRef,
  useCallback,
  useRef,
  useState,
  type InputHTMLAttributes,
  type KeyboardEvent,
  type MouseEvent,
} from 'react';
import { cn, composeRefs } from '../../../foundation/utils';
import { useControlled } from '../../../foundation/hooks';
import { Tag, type TagVariants } from '../../display/tag';
import { inputBaseVariants, InputSize, InputState, type InputBaseVariants } from '../InputStyles';

export interface TagsInputProps
  extends Omit<
      InputHTMLAttributes<HTMLInputElement>,
      'value' | 'defaultValue' | 'onChange' | 'size'
    >,
    Omit<InputBaseVariants, 'size' | 'state'> {
  /** The control size. */
  size?: InputSize;
  /** The validity surface. */
  state?: InputState;
  value?: ReadonlyArray<string>;
  defaultValue?: ReadonlyArray<string>;
  onValueChange?: (tags: ReadonlyArray<string>) => void;
  inputValue?: string;
  onInputChange?: (input: string) => void;
  /** The characters that commit the current input. Enter and Tab always do. */
  delimiters?: ReadonlyArray<string>;
  /** The predicate gating committed tags. Default: non-empty after trim. */
  validate?: (tag: string) => boolean;
  allowsDuplicates?: boolean;
  max?: number;
  isInvalid?: boolean;
  /** The hidden input name; the hidden input emits the comma-joined value. */
  name?: string;
  tagVariant?: TagVariants['variant'];
}

/**
 * Free-form tag entry. Type → Enter/comma/Tab commits. Backspace at empty
 * input removes the last tag. Renders chips via `display/Tag`.
 */
export const TagsInput = forwardRef<HTMLInputElement, TagsInputProps>(function TagsInput(
  {
    value,
    defaultValue,
    onValueChange,
    inputValue,
    onInputChange,
    placeholder = 'Add tag…',
    delimiters = [','],
    validate = (t) => t.trim().length > 0,
    allowsDuplicates = false,
    max,
    isInvalid,
    disabled,
    readOnly,
    name,
    tagVariant = 'neutral',
    size,
    className,
    onKeyDown,
    onBlur,
    ...rest
  },
  forwardedRef,
) {
  const [tags, setTags] = useControlled({
    controlled: value,
    default: defaultValue ?? [],
    onChange: onValueChange,
  });
  const [text, setText] = useControlled({
    controlled: inputValue,
    default: '',
    onChange: onInputChange,
  });

  const inputRef = useRef<HTMLInputElement | null>(null);
  const [pendingDelete, setPendingDelete] = useState(false);
  const state = isInvalid ? InputState.Invalid : InputState.Default;

  const commit = useCallback(
    (raw: string) => {
      const trimmed = raw.trim();
      if (!trimmed || !validate(trimmed)) return;
      if (!allowsDuplicates && tags.includes(trimmed)) return;
      if (max != null && tags.length >= max) return;
      setTags([...tags, trimmed]);
      setText('');
    },
    [tags, validate, allowsDuplicates, max, setTags, setText],
  );

  const removeAt = useCallback(
    (idx: number) => {
      setTags(tags.filter((_, i) => i !== idx));
    },
    [tags, setTags],
  );

  const handleKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
    onKeyDown?.(e);
    if (e.defaultPrevented || disabled || readOnly) return;
    if (e.key === 'Enter' || (e.key === 'Tab' && text)) {
      if (text) {
        e.preventDefault();
        commit(text);
        setPendingDelete(false);
      }
      return;
    }
    if (delimiters.includes(e.key)) {
      e.preventDefault();
      commit(text);
      setPendingDelete(false);
      return;
    }
    if (e.key === 'Backspace' && !text && tags.length > 0) {
      if (pendingDelete) {
        e.preventDefault();
        removeAt(tags.length - 1);
        setPendingDelete(false);
      } else {
        setPendingDelete(true);
      }
      return;
    }
    setPendingDelete(false);
  };

  const handleContainerClick = (e: MouseEvent<HTMLDivElement>) => {
    if (e.target === e.currentTarget) inputRef.current?.focus();
  };

  return (
    <div
      role="group"
      onClick={handleContainerClick}
      data-disabled={disabled || undefined}
      data-readonly={readOnly || undefined}
      data-invalid={isInvalid || undefined}
      className={cn(
        inputBaseVariants({ size, state }),
        'h-auto min-h-10 flex-wrap items-center gap-1.5 py-1.5',
        disabled && 'cursor-not-allowed opacity-60',
        className,
      )}
    >
      {tags.map((t, i) => (
        <Tag
          key={`${t}-${i}`}
          variant={tagVariant}
          data-pending-delete={pendingDelete && i === tags.length - 1 ? '' : undefined}
          onClose={!disabled && !readOnly ? () => removeAt(i) : undefined}
          className={cn(pendingDelete && i === tags.length - 1 && 'ring-1 ring-ring')}
        >
          {t}
        </Tag>
      ))}
      <input
        {...rest}
        ref={composeRefs(forwardedRef, inputRef)}
        type="text"
        value={text}
        placeholder={tags.length === 0 ? placeholder : undefined}
        disabled={disabled}
        readOnly={readOnly}
        aria-invalid={isInvalid || undefined}
        onChange={(e) => setText(e.target.value)}
        onKeyDown={handleKeyDown}
        onBlur={(e) => {
          onBlur?.(e);
          if (text) commit(text);
          setPendingDelete(false);
        }}
        className="min-w-[6rem] flex-1 border-0 bg-transparent p-0 text-sm outline-none placeholder:text-subtle-foreground disabled:cursor-not-allowed"
      />
      {name && <input type="hidden" name={name} value={tags.join(',')} />}
    </div>
  );
});
TagsInput.displayName = 'TagsInput';
