// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/forms/datePicker/DatePicker.vue
<script lang="ts">
import type { Temporal } from 'temporal-polyfill';
import type { SelectSize } from '../select';
import type { InputState } from '../InputStyles';

export interface DatePickerProps {
  /** The selected date, controlled — React's spelling, which wins when both are set. */
  value?: Temporal.PlainDate | null;

  /** The selected date, controlled. The `v-model` binding target. */
  modelValue?: Temporal.PlainDate | null;

  /** The uncontrolled initial selection. */
  defaultValue?: Temporal.PlainDate | null;

  /** The empty-state text on the trigger. */
  placeholder?: string;

  /**
   * The trigger's date formatter.
   *
   * Kept a PROP, not an emit: it RETURNS the rendered string, which an emit cannot do.
   */
  format?: (date: Temporal.PlainDate) => string;

  /** The minimum selectable date. */
  min?: Temporal.PlainDate | null;

  /** The maximum selectable date. */
  max?: Temporal.PlainDate | null;

  /** The custom per-day disable predicate. Also a returning prop. */
  isDisabled?: (date: Temporal.PlainDate) => boolean;

  /** The invalid surface override. Falls back to the surrounding form control's `isInvalid`. */
  isInvalid?: boolean;

  /** The hidden input name; when set, a hidden input ships the ISO value with form submission. */
  name?: string;

  /** The trigger size. */
  size?: SelectSize;

  /** The validity surface. */
  state?: InputState;

  /** The trigger's id. Auto-filled from `FormControl` context when omitted. */
  id?: string;

  /** The disabled state. Falls back to the surrounding form control's `isDisabled`. */
  disabled?: boolean;
}
</script>

<script setup lang="ts">
import { computed, ref, useAttrs, useTemplateRef } from 'vue';
import type { ClassValue } from 'clsx';
import { Calendar as CalendarIcon } from 'lucide-vue-next';
import { cn } from '../../../foundation/utils';
import { useControlled } from '../../../foundation/hooks';
import { useFormControl } from '../../../foundation/primitives';
import { Popover, PopoverContent, PopoverTrigger } from '../../overlays';
import { selectTriggerVariants } from '../select/Select.variants';
import { InputState as InputStateValue } from '../InputStyles';
import { formatISODate, today } from '../DateExtensions';
import Calendar from '../calendar/Calendar.vue';

/** Trigger button + popover `Calendar`. */
/* `inheritAttrs: false` so `class` folds into the trigger's own `cn()` call — plain fallthrough
   appends outside it and loses tailwind-merge conflict resolution. */
defineOptions({ name: 'DatePicker', inheritAttrs: false });

const props = withDefaults(defineProps<DatePickerProps>(), {
  placeholder: 'Pick a date',
  format: (d: Temporal.PlainDate) => d.toLocaleString(undefined, { year: 'numeric', month: 'short', day: 'numeric' }),
  /* Explicit `undefined` defaults are load-bearing: each flag falls back to the form control
     context, and Vue casts an absent `boolean` prop to `false` — which would shadow it. */
  isInvalid: undefined,
  disabled: undefined,
});

const emit = defineEmits<{
  /** The `v-model` half. */
  'update:modelValue': [date: Temporal.PlainDate | null];
  /** Replaces React's `onValueChange`. */
  'value-change': [date: Temporal.PlainDate | null];
}>();

const attrs = useAttrs();

/* Inherits id/disabled/invalid/labelledby/describedby from a surrounding <Field>;
   standalone props win when provided, context fills the gaps (Select parity). */
const field = useFormControl();

const finalDisabled = computed(() => props.disabled ?? field?.isDisabled);
const finalInvalid = computed(() => props.isInvalid ?? field?.isInvalid);

const controlled = useControlled<Temporal.PlainDate | null>({
  /* `??` is wrong here — `null` is a MEANINGFUL selection, and `??` would fall through it
     to `modelValue`. Only `undefined` means "not controlled". */
  controlled: () => (props.value !== undefined ? props.value : props.modelValue),
  default: () => props.defaultValue ?? null,
  onChange: (next) => {
    emit('update:modelValue', next);
    emit('value-change', next);
  },
});

const date = controlled.value;

const open = ref(false);

function onCalendarChange(next: Temporal.PlainDate | null): void {
  controlled.setValue(next);
  open.value = false;
}

const triggerState = computed(
  () => props.state ?? (finalInvalid.value ? InputStateValue.Invalid : InputStateValue.Default),
);

const displayText = computed(() => (date.value ? props.format(date.value) : props.placeholder));

/* Never a declared prop — a declared `'aria-label'` would arrive as `props.ariaLabel`. */
const ariaLabel = computed(() => attrs['aria-label'] as string | undefined);

const triggerId = computed(() => props.id ?? field?.id);
/* Names the trigger from the Field label when present; an explicit aria-label always wins. */
const labelledBy = computed(() => (ariaLabel.value ? undefined : field?.labelledBy));
const describedBy = computed(() => field?.describedBy);
const ariaInvalid = computed(() => triggerState.value === InputStateValue.Invalid || undefined);

const defaultMonth = computed(() => date.value ?? today());
const hiddenValue = computed(() => formatISODate(date.value));

const OWNED_ATTRS: ReadonlySet<string> = new Set(['class', 'aria-label']);
const passthroughAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))),
);

const triggerClass = computed(() =>
  cn(selectTriggerVariants({ size: props.size, state: triggerState.value }), attrs.class as ClassValue),
);

const labelClass = computed(() => cn('truncate', !date.value && 'text-muted-foreground'));

const trigger = useTemplateRef<{ el: HTMLElement | null }>('trigger');

/** The rendered trigger — the Vue stand-in for the React original's forwarded ref. */
defineExpose({ el: computed(() => trigger.value?.el ?? null) });
</script>

<template>
  <Popover v-model:open="open" placement="bottom-start" :offset="6">
    <PopoverTrigger
      ref="trigger"
      :id="triggerId"
      :disabled="finalDisabled"
      :aria-invalid="ariaInvalid"
      :aria-label="ariaLabel"
      :aria-labelledby="labelledBy"
      :aria-describedby="describedBy"
      :class="triggerClass"
      v-bind="passthroughAttrs"
    >
      <!-- `muted-foreground` (not `subtle-foreground`): the trigger surface is muted, where
           subtle is only 4.2:1 (see index.css). -->
      <span :class="labelClass">{{ displayText }}</span>
      <CalendarIcon class="h-4 w-4 shrink-0 text-muted-foreground" />
    </PopoverTrigger>
    <PopoverContent is-bare>
      <Calendar
        :value="date"
        :default-month="defaultMonth"
        :min="min"
        :max="max"
        :is-disabled="isDisabled"
        @value-change="onCalendarChange"
      />
    </PopoverContent>
    <input v-if="name" type="hidden" :name="name" :value="hiddenValue" />
  </Popover>
</template>

// src/forms/datePicker/DatePicker.tsx
import { forwardRef, type ButtonHTMLAttributes } from 'react';
import { Temporal } from '@js-temporal/polyfill';
import { Calendar as CalendarIcon } from 'lucide-react';
import { cn } from '../../utils';
import { useControlled } from '../../hooks';
import { Popover, PopoverContent, PopoverTrigger } from '../../overlays';
import { selectTriggerVariants, type SelectTriggerVariants } from '../select/Select.variants';
import { formatISODate, today } from '../DateExtensions';
import { Calendar } from '../calendar';

export interface DatePickerProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'onChange' | 'value' | 'defaultValue'>,
    SelectTriggerVariants {
  value?: Temporal.PlainDate | null;
  defaultValue?: Temporal.PlainDate | null;
  onValueChange?: (date: Temporal.PlainDate | null) => void;
  placeholder?: string;
  format?: (date: Temporal.PlainDate) => string;
  min?: Temporal.PlainDate | null;
  max?: Temporal.PlainDate | null;
  isDisabled?: (date: Temporal.PlainDate) => boolean;
  isInvalid?: boolean;
  /** When `name` is set, a hidden input ships the ISO value with form submission. */
  name?: string;
}

const defaultFormat = (d: Temporal.PlainDate) =>
  d.toLocaleString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });

export const DatePicker = forwardRef<HTMLButtonElement, DatePickerProps>(function DatePicker(
  {
    value,
    defaultValue,
    onValueChange,
    placeholder = 'Pick a date',
    format = defaultFormat,
    min,
    max,
    isDisabled: dayDisabled,
    isInvalid,
    name,
    size,
    state,
    className,
    disabled,
    ...rest
  },
  forwardedRef,
) {
  const [date, setDate] = useControlled<Temporal.PlainDate | null>({
    controlled: value,
    default: defaultValue ?? null,
    onChange: onValueChange,
  });
  const [open, setOpen] = useControlled<boolean>({
    controlled: undefined,
    default: false,
  });

  const triggerState = state ?? (isInvalid ? 'invalid' : 'default');

  return (
    <Popover open={open} onOpenChange={setOpen} placement="bottom-start" offset={6}>
      <PopoverTrigger asChild>
        <button
          ref={forwardedRef}
          type="button"
          disabled={disabled}
          className={cn(selectTriggerVariants({ size, state: triggerState }), className)}
          {...rest}
        >
          <span className={cn('truncate', !date && 'text-subtle-foreground')}>
            {date ? format(date) : placeholder}
          </span>
          <CalendarIcon className="h-4 w-4 shrink-0 text-muted-foreground" />
        </button>
      </PopoverTrigger>
      <PopoverContent isBare>
        <Calendar
          value={date}
          onValueChange={(d) => {
            setDate(d);
            setOpen(false);
          }}
          defaultMonth={date ?? today()}
          min={min}
          max={max}
          isDisabled={dayDisabled}
        />
      </PopoverContent>
      {name && <input type="hidden" name={name} value={formatISODate(date)} />}
    </Popover>
  );
});
