// src/presentation/display/pricingCard/PricingCard.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from 'react';
import { Check } from 'lucide-react';
import { cn } from '../../../foundation/utils';
import { Icon } from '../../../foundation/icons';
import { Badge } from '../badge/Badge';
import { Card } from '../card/Card';
import { Heading } from '../heading/Heading';
import { Text } from '../text/Text';

export interface PricingCardProps extends ComponentPropsWithoutRef<'div'> {
  /** Tier name (e.g. "Pro"). */
  name: ReactNode;
  /** Headline price (e.g. "$9"). */
  price: ReactNode;
  /** Billing cadence beside the price (e.g. "/mo"). */
  cadence?: ReactNode;
  /** Short positioning line below the price. */
  tagline?: ReactNode;
  /** Feature bullets — each rendered with a leading `Check`. */
  features: ReadonlyArray<ReactNode>;
  /** Highlight this tier — primary border + shadow + a badge. */
  featured?: boolean;
  /** Badge label shown when `featured`. Default "Most popular". */
  badgeLabel?: ReactNode;
  /** CTA slot pinned to the bottom — pass a `Button` (e.g. `<Button asChild><Link/></Button>`). */
  children?: ReactNode;
}

/**
 * Pricing tier card — name + price baseline + tagline + checked feature list +
 * bottom-pinned CTA slot. Content-only: the CTA is `children`, never baked
 * routing. `featured` adds a primary border, shadow, and "Most popular" badge.
 */
export const PricingCard = forwardRef<HTMLDivElement, PricingCardProps>(
  (
    { name, price, cadence, tagline, features, featured = false, badgeLabel = 'Most popular', children, className, ...props },
    ref,
  ) => (
    <Card
      ref={ref}
      variant="outline"
      radius="2xl"
      elevation={0}
      className={cn(
        'relative flex flex-col bg-card p-6',
        featured ? 'border-primary shadow-lg shadow-primary/10' : 'border-border',
        className,
      )}
      {...props}
    >
      {featured && (
        <Badge
          variant="brand"
          size="md"
          className="absolute -top-3 left-6 bg-primary px-3 py-1 text-xs font-medium text-primary-foreground"
        >
          {badgeLabel}
        </Badge>
      )}
      <Heading level={3} size="md" className="tracking-normal">
        {name}
      </Heading>
      <div className="mt-2 flex items-baseline gap-1">
        <span className="text-3xl font-bold tracking-tight">{price}</span>
        {cadence && (
          <Text as="span" size="sm" color="muted">
            {cadence}
          </Text>
        )}
      </div>
      {tagline && (
        <Text size="sm" color="muted" className="mt-2">
          {tagline}
        </Text>
      )}
      <ul className="mt-5 flex flex-1 flex-col gap-2.5">
        {features.map((feature, index) => (
          <li key={index} className="flex items-start gap-2 text-sm">
            <Icon icon={Check} size={16} className="mt-0.5 text-primary" />
            <span>{feature}</span>
          </li>
        ))}
      </ul>
      {children && <div className="mt-6">{children}</div>}
    </Card>
  ),
);
PricingCard.displayName = 'PricingCard';

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/pricingCard/PricingCard.vue
<script lang="ts">
export interface PricingCardProps {
  /**
   * The tier name (e.g. "Pro"). React typed this `ReactNode`; a scalar stays a
   * prop so it remains the discriminator, and the same-named slot is the rich
   * override. The same pairing applies to `price` / `cadence` / `tagline` /
   * `badgeLabel` below.
   */
  name: string | number;

  /** The headline price (e.g. "$9"). */
  price: string | number;

  /** The billing cadence beside the price (e.g. "/mo"). */
  cadence?: string | number;

  /** The short positioning line below the price. */
  tagline?: string | number;

  /** The feature bullets — each rendered with a leading `Check`. Override a row's rendering with the scoped `feature` slot. */
  features: ReadonlyArray<string | number>;

  /** The featured state — highlights this tier with a primary border + shadow + a badge. */
  featured?: boolean;

  /** The badge label shown when `featured`. Default "Most popular". */
  badgeLabel?: string | number;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { Check } from 'lucide-vue-next';
import { cn } from '../../../foundation/utils';
import { Icon } from '../../../foundation/icons';
import Badge from '../badge/Badge.vue';
import Card from '../card/Card.vue';
import Heading from '../heading/Heading.vue';
import Text from '../text/Text.vue';

/**
 * Pricing tier card — name + price baseline + tagline + checked feature list +
 * bottom-pinned CTA slot. Content-only: the CTA is the default slot, never baked
 * routing. `featured` adds a primary border, shadow, and "Most popular" badge.
 */
defineOptions({ name: 'PricingCard', inheritAttrs: false });

/**
 * React's `children` was the CTA region; it becomes the default slot. Every
 * scalar prop above pairs with a same-named override slot, and `feature` is
 * scoped so a consumer can render a rich bullet per entry.
 */
defineSlots<{
  /** The tier name — overrides the `name` prop's rendering. */
  name(): unknown;
  /** The headline price — overrides the `price` prop's rendering. */
  price(): unknown;
  /** The billing cadence — overrides the `cadence` prop's rendering. */
  cadence(): unknown;
  /** The positioning line — overrides the `tagline` prop's rendering. */
  tagline(): unknown;
  /** The featured badge label — overrides the `badgeLabel` prop's rendering. */
  badgeLabel(): unknown;
  /** One feature bullet — overrides the row body (the leading `Check` stays). */
  feature(props: { feature: string | number; index: number }): unknown;
  /** The CTA pinned to the bottom — pass a `Button`. */
  default(): unknown;
}>();

const props = withDefaults(defineProps<PricingCardProps>(), {
  cadence: undefined,
  tagline: undefined,
  featured: false,
  badgeLabel: 'Most popular',
});

const attrs = useAttrs();
const el = useTemplateRef<InstanceType<typeof Card>>('el');

const classes = computed(() =>
  cn(
    'relative flex flex-col bg-card p-6',
    props.featured ? 'border-primary shadow-lg shadow-primary/10' : 'border-border',
    attrs.class as string | undefined,
  ),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <Card ref="el" variant="outline" radius="2xl" :elevation="0" v-bind="rest" :class="classes">
    <Badge
      v-if="props.featured"
      variant="brand"
      size="md"
      class="absolute -top-3 left-6 bg-primary px-3 py-1 text-xs font-medium text-primary-foreground"
    >
      <slot name="badgeLabel">{{ props.badgeLabel }}</slot>
    </Badge>
    <Heading :level="3" size="md" class="tracking-normal">
      <slot name="name">{{ props.name }}</slot>
    </Heading>
    <div class="mt-2 flex items-baseline gap-1">
      <span class="text-3xl font-bold tracking-tight">
        <slot name="price">{{ props.price }}</slot>
      </span>
      <Text v-if="props.cadence !== undefined || $slots.cadence" as="span" size="sm" color="muted">
        <slot name="cadence">{{ props.cadence }}</slot>
      </Text>
    </div>
    <Text v-if="props.tagline !== undefined || $slots.tagline" size="sm" color="muted" class="mt-2">
      <slot name="tagline">{{ props.tagline }}</slot>
    </Text>
    <ul class="mt-5 flex flex-1 flex-col gap-2.5">
      <li
        v-for="(feature, index) in props.features"
        :key="index"
        class="flex items-start gap-2 text-sm"
      >
        <Icon :icon="Check" :size="16" class="mt-0.5 text-primary" />
        <span><slot name="feature" :feature="feature" :index="index">{{ feature }}</slot></span>
      </li>
    </ul>
    <div v-if="$slots.default" class="mt-6"><slot /></div>
  </Card>
</template>
