// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/feedback/onboardingChecklist/OnboardingChecklist.vue
<script lang="ts">
import { inject, type InjectionKey } from 'vue';

export interface OnboardingContextValue {
  /** A live getter — read it, never destructure it. */
  readonly open: boolean;
  setOpen: (open: boolean) => void;
}

/**
 * The record a `OnboardingChecklistTask` hands the root on mount. `isDone` is a
 * live getter over the task's own prop, so the root's progress computeds track
 * it without the task re-registering on every toggle.
 */
export interface OnboardingTaskRecord {
  readonly isDone: boolean;
}

export interface OnboardingRegistry {
  register: (task: OnboardingTaskRecord) => void;
  unregister: (task: OnboardingTaskRecord) => void;
}

export const onboardingContextKey: InjectionKey<OnboardingContextValue> =
  Symbol('wow-two.onboardingChecklist');

/**
 * Replaces React's `Children.toArray` + `isValidElement` child-walking, which
 * has no Vue counterpart: slots are functions, so the root cannot inspect its
 * children's props. Tasks register themselves instead.
 */
export const onboardingRegistryKey: InjectionKey<OnboardingRegistry> = Symbol(
  'wow-two.onboardingChecklist.registry',
);

export interface OnboardingChecklistProps {
  /** The card heading. Rich content → the `title` slot. */
  title?: string;
  defaultOpen?: boolean;
  canDismissOnComplete?: boolean;
  /** The delay in ms after 100% before unmounting. */
  dismissDelay?: number;
}

export function useOnboardingChecklist(): OnboardingContextValue {
  const context = inject(onboardingContextKey, null);
  if (!context) throw new Error('useOnboardingChecklist must be used inside <OnboardingChecklist>');
  return context;
}
</script>

<script setup lang="ts">
import { computed, provide, ref, shallowRef, useAttrs, useTemplateRef, watch } from 'vue';
import { ChevronDown } from 'lucide-vue-next';
import { cn } from '../../../foundation/utils';
import { Icon } from '../../../foundation/icons';

const ChevronDownIcon = ChevronDown;

/**
 * Onboarding task card. The default slot holds `OnboardingChecklistTask`
 * components; progress is auto-derived from the `isDone` prop each one
 * registers with this root.
 */
defineOptions({ name: 'OnboardingChecklist', inheritAttrs: false });

const props = withDefaults(defineProps<OnboardingChecklistProps>(), {
  title: 'Get started',
  defaultOpen: true,
  canDismissOnComplete: false,
  dismissDelay: 2000,
});

const emit = defineEmits<{
  /** Replaces React's `onDismiss`. Fires once, `dismissDelay` ms after the last task completes. */
  dismiss: [];
}>();

const attrs = useAttrs();
const el = useTemplateRef<HTMLDivElement>('el');

const open = ref(props.defaultOpen);
const dismissed = ref(false);

const tasks = shallowRef<ReadonlyArray<OnboardingTaskRecord>>([]);

provide<OnboardingRegistry>(onboardingRegistryKey, {
  register: (task) => {
    if (!tasks.value.includes(task)) tasks.value = [...tasks.value, task];
  },
  unregister: (task) => {
    tasks.value = tasks.value.filter((existing) => existing !== task);
  },
});

provide<OnboardingContextValue>(onboardingContextKey, {
  get open() {
    return open.value;
  },
  setOpen: (value: boolean) => {
    open.value = value;
  },
});

const total = computed(() => tasks.value.length);
const done = computed(() => tasks.value.filter((task) => task.isDone).length);
const complete = computed(() => total.value > 0 && done.value === total.value);

watch(
  [complete, () => props.canDismissOnComplete, () => props.dismissDelay, dismissed],
  ([isComplete, canDismiss, delay, isDismissed], _previous, onCleanup) => {
    if (!canDismiss || !isComplete || isDismissed) return;
    const handle = window.setTimeout(() => {
      dismissed.value = true;
      emit('dismiss');
    }, delay);
    onCleanup(() => window.clearTimeout(handle));
  },
  { immediate: true, flush: 'post' },
);

const classes = computed(() =>
  cn(
    'overflow-hidden rounded-lg border border-border bg-card shadow-sm',
    attrs.class as string | undefined,
  ),
);

const fillClasses = computed(() =>
  cn('h-full bg-primary transition-[width] duration-300', complete.value && 'bg-success'),
);

const fillStyle = computed(() => ({
  width: total.value ? `${(done.value / total.value) * 100}%` : '0%',
}));

const chevronClasses = computed(() =>
  cn('text-muted-foreground transition-transform', open.value && 'rotate-180'),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <div v-if="!dismissed" ref="el" v-bind="rest" :class="classes">
    <button
      type="button"
      :aria-expanded="open"
      class="flex w-full items-center gap-3 px-4 py-3 text-left transition-colors hover:bg-muted/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring"
      @click="open = !open"
    >
      <div class="flex-1">
        <div class="text-sm font-medium text-foreground">
          <slot name="title">{{ props.title }}</slot>
        </div>
        <div class="mt-1 text-xs text-muted-foreground">{{ done }} of {{ total }} tasks complete</div>
        <div class="mt-2 h-1.5 overflow-hidden rounded-full bg-border">
          <div :class="fillClasses" :style="fillStyle" />
        </div>
      </div>
      <Icon :icon="ChevronDownIcon" :size="16" :class="chevronClasses" />
    </button>
    <!--
      Tasks register on mount, so they must stay mounted for `total` / `done` to
      be correct while collapsed — `v-show`, not `v-if`, unlike React's `{open && …}`
      which could re-derive counts from the children array without rendering them.
    -->
    <ul v-show="open" role="list" class="border-t border-border">
      <slot />
    </ul>
  </div>
</template>

// src/feedback/onboardingChecklist/OnboardingChecklist.tsx
import {
  Children,
  createContext,
  forwardRef,
  isValidElement,
  useContext,
  useEffect,
  useMemo,
  useState,
  type HTMLAttributes,
  type ReactNode,
} from 'react';
import { Check, ChevronDown } from 'lucide-react';
import { cn } from '../../utils';
import { Icon } from '../../icons';

interface OnboardingContextValue {
  open: boolean;
  setOpen: (open: boolean) => void;
}

const OnboardingContext = createContext<OnboardingContextValue | null>(null);

export interface OnboardingChecklistProps extends Omit<HTMLAttributes<HTMLDivElement>, 'title'> {
  title?: ReactNode;
  defaultOpen?: boolean;
  canDismissOnComplete?: boolean;
  /** ms after 100% before unmounting. */
  dismissDelay?: number;
  onDismiss?: () => void;
  children: ReactNode;
}

/**
 * Onboarding task card. Children are `OnboardingChecklist.Task` elements;
 * progress is auto-derived from their `isDone` props.
 */
const OnboardingChecklistRoot = forwardRef<HTMLDivElement, OnboardingChecklistProps>(
  function OnboardingChecklist(
    {
      title = 'Get started',
      defaultOpen = true,
      canDismissOnComplete = false,
      dismissDelay = 2000,
      onDismiss,
      className,
      children,
      ...rest
    },
    ref,
  ) {
    const [open, setOpen] = useState(defaultOpen);
    const [dismissed, setDismissed] = useState(false);

    const tasks = Children.toArray(children).filter(
      (c): c is React.ReactElement<OnboardingChecklistTaskProps> =>
        isValidElement(c) &&
        (c.type as { displayName?: string }).displayName === 'OnboardingChecklistTask',
    );
    const total = tasks.length;
    const done = tasks.filter((t) => t.props.isDone).length;
    const complete = total > 0 && done === total;

    useEffect(() => {
      if (!canDismissOnComplete || !complete || dismissed) return;
      const handle = window.setTimeout(() => {
        setDismissed(true);
        onDismiss?.();
      }, dismissDelay);
      return () => window.clearTimeout(handle);
    }, [complete, canDismissOnComplete, dismissDelay, dismissed, onDismiss]);

    const ctx = useMemo<OnboardingContextValue>(() => ({ open, setOpen }), [open]);

    if (dismissed) return null;

    return (
      <OnboardingContext.Provider value={ctx}>
        <div
          ref={ref}
          className={cn(
            'overflow-hidden rounded-lg border border-border bg-card shadow-sm',
            className,
          )}
          {...rest}
        >
          <button
            type="button"
            aria-expanded={open}
            onClick={() => setOpen(!open)}
            className="flex w-full items-center gap-3 px-4 py-3 text-left transition-colors hover:bg-muted/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring"
          >
            <div className="flex-1">
              <div className="text-sm font-medium text-foreground">{title}</div>
              <div className="mt-1 text-xs text-muted-foreground">
                {done} of {total} tasks complete
              </div>
              <div className="mt-2 h-1.5 overflow-hidden rounded-full bg-border">
                <div
                  className={cn(
                    'h-full bg-primary transition-[width] duration-300',
                    complete && 'bg-success',
                  )}
                  style={{ width: total ? `${(done / total) * 100}%` : '0%' }}
                />
              </div>
            </div>
            <Icon
              icon={ChevronDown}
              size={16}
              className={cn('text-muted-foreground transition-transform', open && 'rotate-180')}
            />
          </button>
          {open && (
            <ul role="list" className="border-t border-border">
              {children}
            </ul>
          )}
        </div>
      </OnboardingContext.Provider>
    );
  },
);

export interface OnboardingChecklistTaskProps extends HTMLAttributes<HTMLLIElement> {
  label: ReactNode;
  description?: ReactNode;
  isDone?: boolean;
  action?: ReactNode;
}

export const OnboardingChecklistTask = forwardRef<
  HTMLLIElement,
  OnboardingChecklistTaskProps
>(function OnboardingChecklistTask(
  { label, description, isDone = false, action, className, ...rest },
  ref,
) {
  return (
    <li
      ref={ref}
      data-done={isDone || undefined}
      className={cn(
        'flex items-start gap-3 px-4 py-3 transition-colors',
        isDone && 'opacity-60',
        className,
      )}
      {...rest}
    >
      <span
        aria-hidden="true"
        className={cn(
          'mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full border',
          isDone ? 'border-success bg-success text-success-foreground' : 'border-border',
        )}
      >
        {isDone && <Icon icon={Check} size={12} />}
      </span>
      <div className="min-w-0 flex-1">
        <div className={cn('text-sm font-medium text-foreground', isDone && 'line-through')}>
          {label}
        </div>
        {description && (
          <div className="mt-0.5 text-xs text-muted-foreground">{description}</div>
        )}
      </div>
      {action && !isDone && <div className="shrink-0">{action}</div>}
    </li>
  );
});
OnboardingChecklistTask.displayName = 'OnboardingChecklistTask';

export const OnboardingChecklist = Object.assign(OnboardingChecklistRoot, {
  Task: OnboardingChecklistTask,
});

export function useOnboardingChecklist() {
  const ctx = useContext(OnboardingContext);
  if (!ctx) throw new Error('useOnboardingChecklist must be used inside <OnboardingChecklist>');
  return ctx;
}

export default OnboardingChecklist;
