// src/display/reactionBar/ReactionBar.tsx
import {
  forwardRef,
  type ButtonHTMLAttributes,
  type HTMLAttributes,
  type ReactNode,
} from 'react';
import { SmilePlus } from 'lucide-react';
import { cn } from '../../utils';

export interface Reaction {
  /** Stable id (typically the emoji or shortcode). */
  key: string;
  /** Emoji or icon node displayed in the chip. */
  emoji: ReactNode;
  /** Total count of users who reacted. */
  count: number;
  /** Whether the current viewer has reacted with this. */
  reactedByMe?: boolean;
  /** Optional list of user names — surfaced in the chip's `title`. */
  users?: string[];
}

export interface ReactionBarProps extends Omit<HTMLAttributes<HTMLDivElement>, 'onSelect'> {
  reactions: Reaction[];
  /** Click handler for an existing reaction chip. Toggles user's reaction. */
  onReact?: (key: string) => void;
  /** Click handler for the trailing "add" button. Opens a picker. */
  onAdd?: () => void;
  /** Hide the trailing "add reaction" button. */
  hideAddButton?: boolean;
  /** Compact mode — emoji only, no counts. */
  compact?: boolean;
  /** Hide chips with `count === 0`. Default true. */
  hideEmpty?: boolean;
}

interface ChipProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  reactedByMe?: boolean;
}

function ReactionChip({ reactedByMe, className, ...rest }: ChipProps) {
  return (
    <button
      type="button"
      data-active={reactedByMe ? '' : undefined}
      className={cn(
        'inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-xs leading-none transition-colors',
        'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
        reactedByMe
          ? 'border-primary bg-primary-soft text-primary-soft-foreground'
          : 'border-border bg-background hover:bg-muted',
        className,
      )}
      {...rest}
    />
  );
}

/**
 * Row of reaction chips with optional add-reaction button. Each chip toggles
 * `onReact(key)`; the trailing `+` opens a picker via `onAdd`. Pair with
 * `forms/ReactionPicker` to wire the add flow.
 */
export const ReactionBar = forwardRef<HTMLDivElement, ReactionBarProps>(
  (
    {
      reactions,
      onReact,
      onAdd,
      hideAddButton,
      compact,
      hideEmpty = true,
      className,
      ...props
    },
    ref,
  ) => {
    const visible = hideEmpty ? reactions.filter((r) => r.count > 0) : reactions;
    return (
      <div
        ref={ref}
        role="group"
        aria-label="Reactions"
        className={cn('inline-flex flex-wrap items-center gap-1', className)}
        {...props}
      >
        {visible.map((r) => (
          <ReactionChip
            key={r.key}
            reactedByMe={r.reactedByMe}
            title={r.users?.length ? r.users.join(', ') : undefined}
            onClick={() => onReact?.(r.key)}
          >
            <span className="text-sm leading-none">{r.emoji}</span>
            {!compact && <span className="font-medium tabular-nums">{r.count}</span>}
          </ReactionChip>
        ))}
        {!hideAddButton && onAdd && (
          <button
            type="button"
            onClick={onAdd}
            aria-label="Add reaction"
            className={cn(
              'inline-flex items-center justify-center rounded-full border border-dashed border-border px-2 py-0.5 text-muted-foreground transition-colors',
              'hover:bg-muted hover:text-foreground',
              'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
            )}
          >
            <SmilePlus className="h-3.5 w-3.5" />
          </button>
        )}
      </div>
    );
  },
);
ReactionBar.displayName = 'ReactionBar';

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/reactionBar/ReactionBar.vue
<script lang="ts">
export interface Reaction {
  /** Stable id (typically the emoji or shortcode). */
  key: string;

  /** Emoji displayed in the chip. Rich content → the `emoji` scoped slot. */
  emoji: string | number;

  /** Total count of users who reacted. */
  count: number;

  /** Whether the current viewer has reacted with this. */
  isReactedByMe?: boolean;

  /** Optional list of user names — surfaced in the chip's `title`. */
  users?: ReadonlyArray<string>;
}

export interface ReactionBarProps {
  reactions: ReadonlyArray<Reaction>;

  /** The trailing "add reaction" button's visibility. Default true. */
  hasAddButton?: boolean;

  /** The compact mode — emoji only, no counts. */
  isCompact?: boolean;

  /** The empty-chip visibility — renders chips with `count === 0`. Default false. */
  hasEmpty?: boolean;
}
</script>

<script setup lang="ts">
import { computed, getCurrentInstance, useAttrs, useTemplateRef } from 'vue';
import { SmilePlus } from 'lucide-vue-next';
import { cn, dataAttr } from '../../../foundation/utils';

/**
 * Row of reaction chips with optional add-reaction button. Each chip emits
 * `@react` with its key; the trailing `+` emits `@add` to open a picker. Pair
 * with `forms/ReactionPicker` to wire the add flow.
 */
defineOptions({ name: 'ReactionBar', inheritAttrs: false });

/**
 * React typed `Reaction.emoji` as a `ReactNode`, so a chip could hold a custom
 * glyph. The prop keeps the scalar form and the per-row node becomes a scoped
 * slot whose fallback is the default rendering.
 */
defineSlots<{
  /** The chip glyph override, per reaction. */
  emoji(props: { reaction: Reaction; index: number }): unknown;
}>();

const props = withDefaults(defineProps<ReactionBarProps>(), {
  hasAddButton: true,
  isCompact: undefined,
  hasEmpty: false,
});

const emit = defineEmits<{
  /** Emits the key of the toggled reaction chip. */
  react: [key: string];

  /** Fires when the trailing "add" button is activated (opens a picker). */
  add: [];
}>();

const attrs = useAttrs();
const instance = getCurrentInstance();
const el = useTemplateRef<HTMLDivElement>('el');

/**
 * Mirrors React's `hasAddButton && onAdd && <button/>` guard — the button
 * renders only when the consumer bound `@add`. Read through a call, not a
 * cached computed: `instance.vnode` is replaced on every re-render.
 */
const hasAdd = () => props.hasAddButton && Boolean(instance?.vnode.props?.onAdd);

const visible = computed(() =>
  props.hasEmpty ? props.reactions : props.reactions.filter((r) => r.count > 0),
);

/** Was React's private `ReactionChip` component — a class map is all it carried. */
const chipClasses = (reaction: Reaction): string =>
  cn(
    'inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-xs leading-none transition-colors',
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
    reaction.isReactedByMe
      ? 'border-primary bg-primary-soft text-primary-soft-foreground'
      : 'border-border bg-background hover:bg-muted',
  );

const chipTitle = (reaction: Reaction): string | undefined =>
  reaction.users?.length ? reaction.users.join(', ') : undefined;

const classes = computed(() =>
  cn('inline-flex flex-wrap items-center gap-1', attrs.class as string | undefined),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <div ref="el" role="group" aria-label="Reactions" v-bind="rest" :class="classes">
    <button
      v-for="(reaction, index) in visible"
      :key="reaction.key"
      type="button"
      :data-active="dataAttr(reaction.isReactedByMe)"
      :title="chipTitle(reaction)"
      :class="chipClasses(reaction)"
      @click="emit('react', reaction.key)"
    >
      <span class="text-sm leading-none">
        <slot name="emoji" :reaction="reaction" :index="index">{{ reaction.emoji }}</slot>
      </span>
      <span v-if="!props.isCompact" class="font-medium tabular-nums">{{ reaction.count }}</span>
    </button>
    <button
      v-if="hasAdd()"
      type="button"
      aria-label="Add reaction"
      class="inline-flex items-center justify-center rounded-full border border-dashed border-border px-2 py-0.5 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
      @click="emit('add')"
    >
      <SmilePlus class="h-3.5 w-3.5" />
    </button>
  </div>
</template>
