// src/nav/pagination/Pagination.tsx
import { forwardRef, type ComponentPropsWithoutRef } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { cn } from '../../utils';
import { Icon } from '../../icons';

export interface PaginationProps extends Omit<ComponentPropsWithoutRef<'nav'>, 'onChange'> {
  /** Total page count (1-based). */
  total: number;
  /** Current page (1-based). */
  page: number;
  /** Fires with the new page on click. */
  onPageChange: (page: number) => void;
  /** Number of page buttons surrounding the current. Default `1` (so 1 + current + 1 = 3). */
  siblings?: number;
  /** Hide first/last buttons (just show prev/next + numbers). */
  hideFirstLast?: boolean;
}

function range(start: number, end: number): number[] {
  return Array.from({ length: end - start + 1 }, (_, i) => start + i);
}

function buildPages(total: number, page: number, siblings: number): (number | 'ellipsis')[] {
  if (total <= 1) return [1];
  const left = Math.max(2, page - siblings);
  const right = Math.min(total - 1, page + siblings);
  const pages: (number | 'ellipsis')[] = [1];
  if (left > 2) pages.push('ellipsis');
  pages.push(...range(left, right));
  if (right < total - 1) pages.push('ellipsis');
  if (total > 1) pages.push(total);
  return pages;
}

/**
 * Compact page-number row with prev/next + ellipses for skipped ranges.
 * Stateless — consumer drives `page` and reacts to `onPageChange`.
 */
export const Pagination = forwardRef<HTMLElement, PaginationProps>(
  (
    { total, page, onPageChange, siblings = 1, className, ...props },
    ref,
  ) => {
    const pages = buildPages(total, page, siblings);
    const go = (p: number) => onPageChange(Math.min(total, Math.max(1, p)));

    const baseBtn =
      'inline-flex h-8 min-w-8 items-center justify-center rounded-md border border-transparent px-2 text-sm transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50';

    return (
      <nav ref={ref} aria-label="Pagination" className={cn('inline-flex items-center gap-1', className)} {...props}>
        <button
          type="button"
          aria-label="Previous page"
          disabled={page <= 1}
          onClick={() => go(page - 1)}
          className={cn(baseBtn, 'hover:bg-muted')}
        >
          <Icon icon={ChevronLeft} size={16} />
        </button>
        {pages.map((p, i) =>
          p === 'ellipsis' ? (
            <span key={`e-${i}`} className="px-1 text-muted-foreground">…</span>
          ) : (
            <button
              key={p}
              type="button"
              aria-current={p === page ? 'page' : undefined}
              onClick={() => go(p)}
              className={cn(
                baseBtn,
                p === page ? 'border-primary bg-primary text-primary-foreground' : 'hover:bg-muted',
              )}
            >
              {p}
            </button>
          ),
        )}
        <button
          type="button"
          aria-label="Next page"
          disabled={page >= total}
          onClick={() => go(page + 1)}
          className={cn(baseBtn, 'hover:bg-muted')}
        >
          <Icon icon={ChevronRight} size={16} />
        </button>
      </nav>
    );
  },
);
Pagination.displayName = 'Pagination';

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/nav/pagination/Pagination.vue
<script lang="ts">
export interface PaginationProps {
  /** The total page count (1-based). */
  total: number;

  /** The current page (1-based). The `v-model:page` binding target. */
  page: number;

  /** The number of page buttons surrounding the current. Default `1` (so 1 + current + 1 = 3). */
  siblings?: number;

  /** The hide-first/last toggle (just show prev/next + numbers). */
  hideFirstLast?: boolean;
}

function range(start: number, end: number): ReadonlyArray<number> {
  return Array.from({ length: end - start + 1 }, (_, i) => start + i);
}

function buildPages(
  total: number,
  page: number,
  siblings: number,
): ReadonlyArray<number | 'ellipsis'> {
  if (total <= 1) return [1];
  const left = Math.max(2, page - siblings);
  const right = Math.min(total - 1, page + siblings);
  const pages: Array<number | 'ellipsis'> = [1];
  if (left > 2) pages.push('ellipsis');
  pages.push(...range(left, right));
  if (right < total - 1) pages.push('ellipsis');
  if (total > 1) pages.push(total);
  return pages;
}

const BASE_BTN =
  'inline-flex h-8 min-w-8 items-center justify-center rounded-md border border-transparent px-2 text-sm transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50';
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from 'lucide-vue-next';
import { cn } from '../../../foundation/utils';
import { Icon } from '../../../foundation/icons';

/**
 * Compact page-number row with prev/next + ellipses for skipped ranges.
 * Stateless — consumer drives `page` and reacts to `page-change`.
 */
defineOptions({ name: 'Pagination', inheritAttrs: false });

const props = withDefaults(defineProps<PaginationProps>(), {
  siblings: 1,
  hideFirstLast: false,
});

const emit = defineEmits<{
  /** The `v-model:page` half. */
  'update:page': [page: number];

  /** Replaces React's `onPageChange` — emits the new page on click. */
  'page-change': [page: number];
}>();

const attrs = useAttrs();
const el = useTemplateRef<HTMLElement>('el');

const pages = computed(() => buildPages(props.total, props.page, props.siblings));

function go(page: number): void {
  const next = Math.min(props.total, Math.max(1, page));
  emit('update:page', next);
  emit('page-change', next);
}

const classes = computed(() =>
  cn('inline-flex items-center gap-1', attrs.class as string | undefined),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <nav ref="el" aria-label="Pagination" v-bind="rest" :class="classes">
    <button
      v-if="!props.hideFirstLast"
      type="button"
      aria-label="First page"
      :disabled="props.page <= 1"
      :class="cn(BASE_BTN, 'hover:bg-muted')"
      @click="go(1)"
    >
      <Icon :icon="ChevronsLeft" :size="16" />
    </button>
    <button
      type="button"
      aria-label="Previous page"
      :disabled="props.page <= 1"
      :class="cn(BASE_BTN, 'hover:bg-muted')"
      @click="go(props.page - 1)"
    >
      <Icon :icon="ChevronLeft" :size="16" />
    </button>
    <template v-for="(p, i) in pages">
      <span v-if="p === 'ellipsis'" :key="`e-${i}`" class="px-1 text-muted-foreground">…</span>
      <button
        v-else
        :key="p"
        type="button"
        :aria-current="p === props.page ? 'page' : undefined"
        :class="
          cn(
            BASE_BTN,
            p === props.page ? 'border-primary bg-primary text-primary-foreground' : 'hover:bg-muted',
          )
        "
        @click="go(p)"
      >
        {{ p }}
      </button>
    </template>
    <button
      type="button"
      aria-label="Next page"
      :disabled="props.page >= props.total"
      :class="cn(BASE_BTN, 'hover:bg-muted')"
      @click="go(props.page + 1)"
    >
      <Icon :icon="ChevronRight" :size="16" />
    </button>
    <button
      v-if="!props.hideFirstLast"
      type="button"
      aria-label="Last page"
      :disabled="props.page >= props.total"
      :class="cn(BASE_BTN, 'hover:bg-muted')"
      @click="go(props.total)"
    >
      <Icon :icon="ChevronsRight" :size="16" />
    </button>
  </nav>
</template>
