// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/separator/Separator.vue
<script lang="ts">
/* `Orientation` is imported here (not in `<script setup>`) so the one binding
   serves as both the type below and the runtime value used in `withDefaults`. */
import { Orientation } from '../../../foundation/utils';

export interface SeparatorProps {
  orientation?: Orientation;
  /** The decorative mode — `role="none"`, unannounced. Default `true`; set `false` when meaningful in context. */
  isDecorative?: boolean;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';

/**
 * Visual divider. Defaults to a horizontal hairline; pass `orientation="vertical"`
 * for column dividers (use inside a flex/grid with explicit height).
 */
defineOptions({ name: 'Separator', inheritAttrs: false });

const props = withDefaults(defineProps<SeparatorProps>(), {
  orientation: Orientation.Horizontal,
  isDecorative: true,
});

const attrs = useAttrs();
const el = useTemplateRef<HTMLDivElement>('el');

const classes = computed(() =>
  cn(
    'bg-border',
    props.orientation === Orientation.Horizontal ? 'h-px w-full' : 'w-px self-stretch',
    attrs.class as string | undefined,
  ),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <div
    ref="el"
    :role="props.isDecorative ? 'none' : 'separator'"
    :aria-orientation="props.isDecorative ? undefined : props.orientation"
    v-bind="rest"
    :class="classes"
  />
</template>

// src/display/separator/Separator.tsx
import { forwardRef, type ComponentPropsWithoutRef } from 'react';
import { cn } from '../../utils';

export interface SeparatorProps extends ComponentPropsWithoutRef<'div'> {
  orientation?: 'horizontal' | 'vertical';
  /** When `true`, the separator is purely decorative — `role="none"` and
   *  unannounced. Default `true`. Set `false` when meaningful in context. */
  decorative?: boolean;
}

/**
 * Visual divider. Defaults to a horizontal hairline; pass `orientation="vertical"`
 * for column dividers (use inside a flex/grid with explicit height).
 */
export const Separator = forwardRef<HTMLDivElement, SeparatorProps>(
  ({ orientation = 'horizontal', decorative = true, className, ...props }, ref) => (
    <div
      ref={ref}
      role={decorative ? 'none' : 'separator'}
      aria-orientation={decorative ? undefined : orientation}
      className={cn(
        'bg-border',
        orientation === 'horizontal' ? 'h-px w-full' : 'w-px self-stretch',
        className,
      )}
      {...props}
    />
  ),
);
Separator.displayName = 'Separator';
