// src/presentation/forms/timePicker/TimePicker.tsx
import { forwardRef, useEffect, useMemo, useRef, type ButtonHTMLAttributes } from 'react';
import { Temporal } from 'temporal-polyfill';
import { Clock } from 'lucide-react';
import { cn } from '../../../foundation/utils';
import { useControlled } from '../../../foundation/hooks';
import { Popover, PopoverContent, PopoverTrigger } from '../../overlays';
import { selectTriggerVariants, SelectSize, type SelectTriggerVariants } from '../select/Select.variants';
import { InputState } from '../InputStyles';

export interface TimePickerProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'onChange' | 'value' | 'defaultValue'>,
    Omit<SelectTriggerVariants, 'size' | 'state'> {
  value?: Temporal.PlainTime | null;
  defaultValue?: Temporal.PlainTime | null;
  onValueChange?: (time: Temporal.PlainTime | null) => void;
  /** The minute interval. Default 5. */
  minuteStep?: number;
  placeholder?: string;
  format?: (time: Temporal.PlainTime) => string;
  isInvalid?: boolean;
  name?: string;
  /** The trigger size. */
  size?: SelectSize;
  /** The validity surface. */
  state?: InputState;
}

const defaultFormat = (t: Temporal.PlainTime) => t.toString({ smallestUnit: 'minute' });

const HOURS = Array.from({ length: 24 }, (_, i) => i);

export const TimePicker = forwardRef<HTMLButtonElement, TimePickerProps>(function TimePicker(
  {
    value,
    defaultValue,
    onValueChange,
    minuteStep = 5,
    placeholder = 'Pick a time',
    format = defaultFormat,
    isInvalid,
    name,
    size,
    state,
    className,
    disabled,
    ...rest
  },
  forwardedRef,
) {
  const [time, setTime] = useControlled<Temporal.PlainTime | null>({
    controlled: value,
    default: defaultValue ?? null,
    onChange: onValueChange,
  });
  const [open, setOpen] = useControlled<boolean>({
    controlled: undefined,
    default: false,
  });
  const hoursRef = useRef<HTMLDivElement | null>(null);
  const minutesRef = useRef<HTMLDivElement | null>(null);

  const minutes = useMemo(() => {
    const list: Array<number> = [];
    for (let m = 0; m < 60; m += minuteStep) list.push(m);
    return list;
  }, [minuteStep]);

  // Auto-scroll selected hour/minute into view when opening.
  useEffect(() => {
    if (!open) return;
    requestAnimationFrame(() => {
      hoursRef.current
        ?.querySelector<HTMLButtonElement>('[data-selected]')
        ?.scrollIntoView({ block: 'center' });
      minutesRef.current
        ?.querySelector<HTMLButtonElement>('[data-selected]')
        ?.scrollIntoView({ block: 'center' });
    });
  }, [open]);

  const triggerState = state ?? (isInvalid ? InputState.Invalid : InputState.Default);

  const update = (next: { hour?: number; minute?: number }) => {
    const merged = Temporal.PlainTime.from({
      hour: next.hour ?? time?.hour ?? 0,
      minute: next.minute ?? time?.minute ?? 0,
    });
    setTime(merged);
  };

  return (
    <Popover open={open} onOpenChange={setOpen} placement="bottom-start" offset={6}>
      <PopoverTrigger asChild>
        <button
          ref={forwardedRef}
          type="button"
          disabled={disabled}
          className={cn(selectTriggerVariants({ size, state: triggerState }), className)}
          {...rest}
        >
          {/* `muted-foreground` (not `subtle-foreground`): the trigger surface is muted, where subtle is only 4.2:1 (see index.css). */}
          <span className={cn('truncate', !time && 'text-muted-foreground')}>
            {time ? format(time) : placeholder}
          </span>
          <Clock className="h-4 w-4 shrink-0 text-muted-foreground" />
        </button>
      </PopoverTrigger>
      <PopoverContent isBare>
        <div className="flex gap-1 rounded-md border border-border bg-popover p-2 text-popover-foreground shadow-md">
          <div
            ref={hoursRef}
            role="listbox"
            aria-label="Hours"
            className="flex max-h-56 flex-col gap-0.5 overflow-y-auto pr-1"
          >
            {HOURS.map((h) => {
              const selected = time?.hour === h;
              return (
                <button
                  key={h}
                  type="button"
                  role="option"
                  aria-selected={selected}
                  data-selected={selected ? '' : undefined}
                  onClick={() => update({ hour: h })}
                  className={cn(
                    'grid h-8 w-12 place-items-center rounded-sm text-sm transition-colors hover:bg-muted',
                    selected && 'bg-primary text-primary-foreground hover:bg-primary',
                  )}
                >
                  {String(h).padStart(2, '0')}
                </button>
              );
            })}
          </div>
          <div className="w-px self-stretch bg-border" />
          <div
            ref={minutesRef}
            role="listbox"
            aria-label="Minutes"
            className="flex max-h-56 flex-col gap-0.5 overflow-y-auto pl-1"
          >
            {minutes.map((m) => {
              const selected = time?.minute === m;
              return (
                <button
                  key={m}
                  type="button"
                  role="option"
                  aria-selected={selected}
                  data-selected={selected ? '' : undefined}
                  onClick={() => update({ minute: m })}
                  className={cn(
                    'grid h-8 w-12 place-items-center rounded-sm text-sm transition-colors hover:bg-muted',
                    selected && 'bg-primary text-primary-foreground hover:bg-primary',
                  )}
                >
                  {String(m).padStart(2, '0')}
                </button>
              );
            })}
          </div>
        </div>
      </PopoverContent>
      {name && time && (
        <input type="hidden" name={name} value={time.toString({ smallestUnit: 'minute' })} />
      )}
    </Popover>
  );
});

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/forms/timePicker/TimePicker.vue
<script lang="ts">
import type { Temporal } from 'temporal-polyfill';
import type { SelectSize } from '../select';
import type { InputState } from '../InputStyles';

export interface TimePickerProps {
  /** The selected time, controlled — React's spelling, which wins when both are set. */
  value?: Temporal.PlainTime | null;

  /** The selected time, controlled. The `v-model` binding target. */
  modelValue?: Temporal.PlainTime | null;

  /** The uncontrolled initial selection. */
  defaultValue?: Temporal.PlainTime | null;

  /** The minute interval. Default 5. */
  minuteStep?: number;

  /** The empty-state text on the trigger. */
  placeholder?: string;

  /**
   * The trigger's time formatter.
   *
   * Kept a PROP, not an emit: it RETURNS the rendered string, which an emit cannot do.
   */
  format?: (time: Temporal.PlainTime) => string;

  /** The invalid surface override. Falls back to the surrounding form control's `isInvalid`. */
  isInvalid?: boolean;

  /** The hidden input name; when set, a hidden input ships the value with form submission. */
  name?: string;

  /** The trigger size. */
  size?: SelectSize;

  /** The validity surface. */
  state?: InputState;

  /** The trigger's id. Auto-filled from `FormControl` context when omitted. */
  id?: string;

  /** The disabled state. Falls back to the surrounding form control's `isDisabled`. */
  disabled?: boolean;
}
</script>

<script setup lang="ts">
import { computed, ref, useAttrs, useTemplateRef } from 'vue';
import type { ClassValue } from 'clsx';
import { Clock } from 'lucide-vue-next';
import { cn } from '../../../foundation/utils';
import { useControlled } from '../../../foundation/hooks';
import { useFormControl } from '../../../foundation/primitives';
import { Popover, PopoverContent, PopoverTrigger } from '../../overlays';
import { selectTriggerVariants } from '../select/Select.variants';
import { InputState as InputStateValue } from '../InputStyles';
import TimeColumns from '../TimeColumns.vue';

/** Trigger button + popover hour/minute columns. */
/* `inheritAttrs: false` so `class` folds into the trigger's own `cn()` call — plain fallthrough
   appends outside it and loses tailwind-merge conflict resolution. */
defineOptions({ name: 'TimePicker', inheritAttrs: false });

const props = withDefaults(defineProps<TimePickerProps>(), {
  minuteStep: 5,
  placeholder: 'Pick a time',
  format: (t: Temporal.PlainTime) => t.toString({ smallestUnit: 'minute' }),
  /* Explicit `undefined` defaults are load-bearing: each flag falls back to the form control
     context, and Vue casts an absent `boolean` prop to `false` — which would shadow it. */
  isInvalid: undefined,
  disabled: undefined,
});

const emit = defineEmits<{
  /** The `v-model` half. */
  'update:modelValue': [time: Temporal.PlainTime | null];
  /** Replaces React's `onValueChange`. */
  'value-change': [time: Temporal.PlainTime | null];
}>();

const attrs = useAttrs();

/* Inherits id/disabled/invalid/labelledby/describedby from a surrounding <Field>;
   standalone props win when provided, context fills the gaps (Select parity). */
const field = useFormControl();

const finalDisabled = computed(() => props.disabled ?? field?.isDisabled);
const finalInvalid = computed(() => props.isInvalid ?? field?.isInvalid);

const controlled = useControlled<Temporal.PlainTime | null>({
  /* `??` is wrong here — `null` is a MEANINGFUL selection, and `??` would fall through it
     to `modelValue`. Only `undefined` means "not controlled". */
  controlled: () => (props.value !== undefined ? props.value : props.modelValue),
  default: () => props.defaultValue ?? null,
  onChange: (next) => {
    emit('update:modelValue', next);
    emit('value-change', next);
  },
});

const time = controlled.value;

const open = ref(false);

const triggerState = computed(
  () => props.state ?? (finalInvalid.value ? InputStateValue.Invalid : InputStateValue.Default),
);

/* The columns live in the shared `TimeColumns` — the same panel `TimeInput` and
   `DateTimeInput` open, so the three cannot drift. */
function onColumnsChange(next: Temporal.PlainTime): void {
  controlled.setValue(next);
}

const displayText = computed(() => (time.value ? props.format(time.value) : props.placeholder));

/* Never a declared prop — a declared `'aria-label'` would arrive as `props.ariaLabel`. */
const ariaLabel = computed(() => attrs['aria-label'] as string | undefined);

const triggerId = computed(() => props.id ?? field?.id);
/* Names the trigger from the Field label when present; an explicit aria-label always wins. */
const labelledBy = computed(() => (ariaLabel.value ? undefined : field?.labelledBy));
const describedBy = computed(() => field?.describedBy);
const ariaInvalid = computed(() => triggerState.value === InputStateValue.Invalid || undefined);

const hiddenValue = computed(() => time.value?.toString({ smallestUnit: 'minute' }) ?? '');

const OWNED_ATTRS: ReadonlySet<string> = new Set(['class', 'aria-label']);
const passthroughAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))),
);

const triggerClass = computed(() =>
  cn(selectTriggerVariants({ size: props.size, state: triggerState.value }), attrs.class as ClassValue),
);

const labelClass = computed(() => cn('truncate', !time.value && 'text-muted-foreground'));

const trigger = useTemplateRef<{ el: HTMLElement | null }>('trigger');

/** The rendered trigger — the Vue stand-in for the React original's forwarded ref. */
defineExpose({ el: computed(() => trigger.value?.el ?? null) });
</script>

<template>
  <Popover v-model:open="open" placement="bottom-start" :offset="6">
    <PopoverTrigger
      ref="trigger"
      :id="triggerId"
      :disabled="finalDisabled"
      :aria-invalid="ariaInvalid"
      :aria-label="ariaLabel"
      :aria-labelledby="labelledBy"
      :aria-describedby="describedBy"
      :class="triggerClass"
      v-bind="passthroughAttrs"
    >
      <!-- `muted-foreground` (not `subtle-foreground`): the trigger surface is muted, where
           subtle is only 4.2:1 (see index.css). -->
      <span :class="labelClass">{{ displayText }}</span>
      <Clock class="h-4 w-4 shrink-0 text-muted-foreground" />
    </PopoverTrigger>
    <PopoverContent is-bare>
      <TimeColumns :value="time" :minute-step="minuteStep" :on-time-change="onColumnsChange" />
    </PopoverContent>
    <input v-if="name && time" type="hidden" :name="name" :value="hiddenValue" />
  </Popover>
</template>
