// src/actions/button/Button.tsx
import {
  forwardRef,
  useEffect,
  useRef,
  type ButtonHTMLAttributes,
  type CSSProperties,
  type KeyboardEvent,
  type KeyboardEventHandler,
  type MouseEvent,
  type MouseEventHandler,
  type PointerEvent,
  type PointerEventHandler,
  type ReactNode,
} from 'react';
import {
  cn,
  ColorExtensions,
  composeEventHandlers,
  ButtonType,
  CssExtensions,
  HtmlElement,
  IS_DEV,
  Key,
  OptionalExtensions,
  PressExtensions,
  type BoxSizeOverrides,
  type ColorProp,
  type ColorTone,
  type PaddingProp,
  type PressEvent,
  type RadiusProp,
  type SizePreset,
  type SizeUnion,
  type SizeValue,
} from '../../utils';
import { Slot } from '../../primitives';
import { useFormControl } from '../../primitives/formControlContext/FormControlContext';
import { Spinner } from '../../icons';
import { useDebounceHandler } from '../../hooks';
import { buttonVariants, type ButtonVariants } from './Button.variants';

const COMPONENT_NAME = 'Button';

/* Named size presets — used for variant lookup. Any other string/number/object flows to box-overrides. Subset of the canonical `SizePreset` vocabulary. */
type ButtonSizePreset = Extract<SizePreset, 'xs' | 'sm' | 'md' | 'lg' | 'xl'>;
const BUTTON_SIZE_PRESETS: ReadonlySet<string> = new Set<ButtonSizePreset>(['xs', 'sm', 'md', 'lg', 'xl']);

/* `size`: preset (variant class) | number/string (square inline dims) | `{width,height,minWidth,minHeight,boxSize}`.
   Raw/object forms set inline dims only — pair with `padding` if text-bearing. */
export type ButtonSize = SizeUnion<ButtonSizePreset>;

/* Observable state surfaced via the `data-state` DOM attribute. */
const ButtonDataState = {
  Loading: 'loading',
  Skeleton: 'skeleton',
  Disabled: 'disabled',
} as const;
type ButtonDataState = (typeof ButtonDataState)[keyof typeof ButtonDataState];

export interface ButtonProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'type' | 'disabled' | 'color'>,
    Omit<ButtonVariants, 'size'> {
  /* Preset name OR raw value OR explicit dim object — see `ButtonSize` for details. */
  size?: ButtonSize;

  /* Per-instance color override for the active `tone`. String → all slots derived; object → per-slot (bg/text/soft/softText/ring). Sets local CSS vars that `bg-{tone}` etc. pick up. */
  color?: ColorProp;

  /* Slot before children (logical start). */
  leadingSlot?: ReactNode;

  /* Slot after children (logical end). */
  trailingSlot?: ReactNode;

  /* Content shown in place of `children` on hover / focus-visible (CSS-only swap — no JS hover state).
     Idle → `children` visible; hover/focus-visible → `hoverSlot` visible. Pairs with `variant="reveal"`
     for a reveal-on-hover icon swap. When undefined, `children` renders normally. */
  hoverSlot?: ReactNode;

  /* Custom indicator shown in place of the built-in `<Spinner/>` when `isLoading` is true. */
  loadingSlot?: ReactNode;

  /* Action-loading: replaces leading w/ spinner, sets aria-busy, blocks clicks. */
  isLoading?: boolean;

  /* Replaces children when loading. No default — consumer supplies (i18n). */
  loadingText?: string;

  /* Content-loading: hides content (preserves dimensions) + shimmer. Mutually exclusive with `isLoading`. */
  isSkeleton?: boolean;

  /* Removes from focus order, blocks clicks. Forwards to native `disabled`. Inherited from an enclosing `Field` when omitted. */
  isDisabled?: boolean;

  /* Stretches to fill container width. */
  isFullWidth?: boolean;

  /* Allows multi-line label wrap; default truncates to single line. */
  isMultiline?: boolean;

  /* Render as the single child element via Slot. */
  asChild?: boolean;

  /* Independent padding override (preset token or `{x, y}` object). */
  padding?: PaddingProp;

  /* Independent radius override (preset token or raw value). */
  radius?: RadiusProp;

  /* Explicit width override. Number = px; string = any CSS unit. */
  width?: SizeValue;

  /* Explicit height override. Number = px; string = any CSS unit. */
  height?: SizeValue;

  /* Reserve a min width so the button doesn't reflow when its label morphs. */
  minWidth?: SizeValue;

  /* Reserve a min height — symmetric with `minWidth`. */
  minHeight?: SizeValue;

  /* Square shorthand — applied as fallback for both `width` and `height`. Explicit `width`/`height` win when both are set. Pairs with `shape="square"` / `shape="circle"` for icon buttons. */
  boxSize?: SizeValue;

  /* Default `ButtonType.Button` — NOT browser-default `'submit'`. */
  type?: ButtonType;

  /* Fires on pointer-down OR Space/Enter keydown (first event in a gesture). */
  onPressStart?: (event: PressEvent<HTMLButtonElement>) => void;

  /* Fires on pointer-up/cancel OR Space/Enter keyup. */
  onPressEnd?: (event: PressEvent<HTMLButtonElement>) => void;

  /* Fires when the pointer is held for `longPressDelay` ms. Suppresses the next click. */
  onLongPress?: (event: PointerEvent<HTMLButtonElement>) => void;

  /* Long-press duration (ms). Default 500. Out-of-range values trigger a dev warning. */
  longPressDelay?: number;

  /* Throttle clicks within window — first wins; subsequent swallowed via `preventDefault()`. */
  debounceMs?: number;
}

interface UseButtonInteractivityOptions {
  isInactive: boolean;
  isLoading: boolean;
  isSkeleton: boolean;
  longPressDelay: number;
  debounceMs?: number;
  onClick?: MouseEventHandler<HTMLButtonElement>;
  onPressStart?: (event: PressEvent<HTMLButtonElement>) => void;
  onPressEnd?: (event: PressEvent<HTMLButtonElement>) => void;
  onLongPress?: (event: PointerEvent<HTMLButtonElement>) => void;
  onPointerDown?: PointerEventHandler<HTMLButtonElement>;
  onPointerUp?: PointerEventHandler<HTMLButtonElement>;
  onPointerCancel?: PointerEventHandler<HTMLButtonElement>;
  onPointerLeave?: PointerEventHandler<HTMLButtonElement>;
  onKeyDown?: KeyboardEventHandler<HTMLButtonElement>;
  onKeyUp?: KeyboardEventHandler<HTMLButtonElement>;
}

/* Press / long-press / debounce wiring. Returns the 6 DOM event handlers for spread onto the element. */
function useButtonInteractivity(opts: UseButtonInteractivityOptions) {
  const isPressingRef = useRef(false);
  const longPressTimerRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const longPressFiredRef = useRef(false);

  useEffect(
    () => () => {
      if (longPressTimerRef.current !== undefined) {
        clearTimeout(longPressTimerRef.current);
      }
    },
    [],
  );

  const cancelLongPress = () => {
    if (longPressTimerRef.current !== undefined) {
      clearTimeout(longPressTimerRef.current);
      longPressTimerRef.current = undefined;
    }
  };

  const endPress = (e: PressEvent<HTMLButtonElement>) => {
    if (isPressingRef.current) {
      isPressingRef.current = false;
      opts.onPressEnd?.(e);
    }
  };

  const handlePointerDown = (e: PointerEvent<HTMLButtonElement>) => {
    if (opts.isInactive) return;
    // Cancel any pending timer, then arm only on the first pointer of a gesture — a second
    // pointer-down must not stack a second long-press timer.
    cancelLongPress();
    if (!isPressingRef.current) {
      isPressingRef.current = true;
      longPressFiredRef.current = false;
      opts.onPressStart?.(e);
      if (opts.onLongPress) {
        longPressTimerRef.current = setTimeout(() => {
          longPressFiredRef.current = true;
          opts.onLongPress?.(e);
          longPressTimerRef.current = undefined;
        }, opts.longPressDelay);
      }
    }
  };

  const handlePointerUp = (e: PointerEvent<HTMLButtonElement>) => {
    cancelLongPress();
    endPress(e);
  };

  const handlePointerCancel = (e: PointerEvent<HTMLButtonElement>) => {
    cancelLongPress();
    endPress(e);
  };

  const handlePointerLeave = () => {
    // Pointer leaving cancels a pending long-press but does NOT end the press itself —
    // pointer-up/cancel handlers do that. Matches React Aria.
    cancelLongPress();
  };

  const isActivationKey = (e: KeyboardEvent<HTMLButtonElement>) =>
    e.key === Key.Space || e.key === Key.Enter;

  const handleKeyDown = (e: KeyboardEvent<HTMLButtonElement>) => {
    if (opts.isInactive) return;
    if (isActivationKey(e) && !e.repeat && !isPressingRef.current) {
      isPressingRef.current = true;
      longPressFiredRef.current = false;
      opts.onPressStart?.(e);
    }
  };

  const handleKeyUp = (e: KeyboardEvent<HTMLButtonElement>) => {
    if (isActivationKey(e) && isPressingRef.current) {
      isPressingRef.current = false;
      opts.onPressEnd?.(e);
    }
  };

  // Long-press suppression happens BEFORE this — a suppressed click does NOT advance the throttle window.
  const debouncedOnClick = useDebounceHandler(opts.onClick, opts.debounceMs);

  const handleClick = (e: MouseEvent<HTMLButtonElement>) => {
    if (opts.isLoading || opts.isSkeleton) {
      // Block native activation too — e.g. `type="submit"` must not submit while loading.
      e.preventDefault();
      return;
    }
    if (longPressFiredRef.current) {
      longPressFiredRef.current = false;
      e.preventDefault();
      return;
    }
    debouncedOnClick(e);
  };

  return {
    onClick: handleClick,
    onPointerDown: composeEventHandlers(opts.onPointerDown, handlePointerDown),
    onPointerUp: composeEventHandlers(opts.onPointerUp, handlePointerUp),
    onPointerCancel: composeEventHandlers(opts.onPointerCancel, handlePointerCancel),
    onPointerLeave: composeEventHandlers(opts.onPointerLeave, handlePointerLeave),
    onKeyDown: composeEventHandlers(opts.onKeyDown, handleKeyDown),
    onKeyUp: composeEventHandlers(opts.onKeyUp, handleKeyUp),
  };
}

/* Renders an action button — for text and/or icon content. */
export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      className,
      style,
      variant,
      tone,
      size,
      shape,
      isFullWidth,
      isMultiline,
      padding,
      radius,
      width,
      height,
      minWidth,
      minHeight,
      boxSize,
      leadingSlot,
      trailingSlot,
      hoverSlot,
      loadingSlot,
      isLoading,
      loadingText,
      isSkeleton,
      isDisabled,
      asChild,
      color,
      type = ButtonType.Button,
      children,
      onClick,
      onPressStart,
      onPressEnd,
      onLongPress,
      longPressDelay = PressExtensions.longPressDelay.default,
      debounceMs,
      onPointerDown,
      onPointerUp,
      onPointerCancel,
      onPointerLeave,
      onKeyDown,
      onKeyUp,
      ...rest
    },
    ref,
  ) => {
    if (IS_DEV && isLoading && isSkeleton) {
      console.warn(
        `[${COMPONENT_NAME}] \`isLoading\` and \`isSkeleton\` are mutually exclusive — \`isSkeleton\` takes precedence.`,
      );
    }

    let safeLongPressDelay = longPressDelay;
    if (
      longPressDelay < PressExtensions.longPressDelay.min ||
      longPressDelay > PressExtensions.longPressDelay.max
    ) {
      if (IS_DEV) {
        console.warn(
          `[${COMPONENT_NAME}] longPressDelay=${longPressDelay}ms is outside reasonable range (${PressExtensions.longPressDelay.min}–${PressExtensions.longPressDelay.max}ms). Falling back to ${PressExtensions.longPressDelay.default}ms.`,
        );
      }
      safeLongPressDelay = PressExtensions.longPressDelay.default;
    }

    if (
      IS_DEV &&
      (children === undefined || children === null || children === false) &&
      rest['aria-label'] === undefined &&
      rest['aria-labelledby'] === undefined
    ) {
      console.warn(
        `[${COMPONENT_NAME}] icon-only button (no text children) is missing an accessible name — pass \`aria-label\` or \`aria-labelledby\` (Button.standard.md rule 12).`,
      );
    }

    /* Inherit disabled-state from an enclosing `Field` when the local prop is omitted; standalone when no context. */
    const formControl = useFormControl();
    const resolvedDisabled = isDisabled ?? formControl?.isDisabled ?? false;

    const skeletonActive = !!isSkeleton;
    const loadingActive = !skeletonActive && !!isLoading;
    const isInactive = loadingActive || skeletonActive || resolvedDisabled;

    const dataState: ButtonDataState | undefined = skeletonActive
      ? ButtonDataState.Skeleton
      : loadingActive
        ? ButtonDataState.Loading
        : resolvedDisabled
          ? ButtonDataState.Disabled
          : undefined;

    const Comp = asChild ? Slot : HtmlElement.Button;

    /* Parse the union-typed `size` prop into preset (for variant lookup) + box overrides (for inline dims). */
    const { preset: sizePreset, box: sizeBox } = CssExtensions.parseSizeUnion<ButtonSizePreset>(
      size,
      BUTTON_SIZE_PRESETS,
    );

    const overrideStyle: CSSProperties | undefined = (() => {
      const padStyle = CssExtensions.resolvePadding(padding);
      const radStyle = CssExtensions.resolveRadius(radius);
      /* Box overrides — `size` (object form or raw value) is the base; flat width/height/minWidth/minHeight/boxSize props win when both are set. */
      const composedBox: BoxSizeOverrides = {
        ...(sizeBox ?? {}),
        ...(width !== undefined ? { width } : {}),
        ...(height !== undefined ? { height } : {}),
        ...(minWidth !== undefined ? { minWidth } : {}),
        ...(minHeight !== undefined ? { minHeight } : {}),
        ...(boxSize !== undefined ? { boxSize } : {}),
      };
      const boxStyle = CssExtensions.resolveBoxSize(composedBox);
      /* Per-instance color override → sets CSS vars on element, scoped locally. */
      const colorStyle = ColorExtensions.toneColorOverride(color, tone as ColorTone | undefined);
      if (!padStyle && !radStyle && !boxStyle && !colorStyle && !style) return undefined;
      return { ...colorStyle, ...padStyle, ...radStyle, ...boxStyle, ...style };
    })();

    const eventHandlers = useButtonInteractivity({
      isInactive,
      isLoading: loadingActive,
      isSkeleton: skeletonActive,
      longPressDelay: safeLongPressDelay,
      debounceMs,
      onClick,
      onPressStart,
      onPressEnd,
      onLongPress,
      onPointerDown,
      onPointerUp,
      onPointerCancel,
      onPointerLeave,
      onKeyDown,
      onKeyUp,
    });

    const content = loadingActive ? (
      <>
        {loadingSlot ?? <Spinner />}
        {loadingText !== undefined ? (
          <span>{loadingText}</span>
        ) : (
          // No loadingText: keep children in sr-only so the accessible name survives (Spinner is aria-hidden).
          <span className="sr-only">{children}</span>
        )}
      </>
    ) : hoverSlot !== undefined ? (
      <>
        {leadingSlot}
        {/* CSS-only hover/focus-visible swap: `children` occupies the box and reserves its size;
            `hoverSlot` overlays it centered. Toggle via `group-hover`/`group-focus-visible` on the
            root `group` — no JS hover state. `aria-hidden` on the hidden layer so AT reads one label. */}
        <span className="relative inline-flex items-center justify-center">
          <span className="inline-flex items-center justify-center group-hover:invisible group-focus-visible:invisible">
            {children}
          </span>
          <span
            aria-hidden
            className="invisible absolute inset-0 inline-flex items-center justify-center group-hover:visible group-focus-visible:visible"
          >
            {hoverSlot}
          </span>
        </span>
        {trailingSlot}
      </>
    ) : (
      <>
        {leadingSlot}
        {children}
        {trailingSlot}
      </>
    );

    /* asChild → Slot merges onto the user's element; leadingSlot/trailingSlot/isLoading aren't rendered (consumer owns children). */
    const renderedContent = asChild ? children : content;

    return (
      <Comp
        ref={ref}
        type={asChild ? undefined : type}
        className={cn(
          buttonVariants({
            variant,
            tone,
            size: sizePreset,
            shape,
            fullWidth: isFullWidth,
            wrap: isMultiline,
          }),
          className,
        )}
        style={overrideStyle}
        disabled={OptionalExtensions.from(resolvedDisabled, true)}
        aria-busy={OptionalExtensions.from(loadingActive || skeletonActive, true)}
        aria-disabled={OptionalExtensions.from(loadingActive || skeletonActive, true)}
        tabIndex={OptionalExtensions.from(skeletonActive, -1)}
        data-state={dataState}
        {...eventHandlers}
        {...rest}
      >
        {renderedContent}
      </Comp>
    );
  },
);

Button.displayName = COMPONENT_NAME;

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/actions/button/Button.vue
<script lang="ts">
import type { ButtonHTMLAttributes, VNodeChild } from 'vue';
import type {
  ColorProp,
  ColorTone,
  PaddingProp,
  RadiusProp,
  SizePreset,
  SizeUnion,
  SizeValue,
} from '../../../foundation/utils';
import type { ButtonVariant, ButtonShape, ButtonVariants } from './Button.variants';

/* Named size presets — used for variant lookup. Any other string/number/object flows to box-overrides. Subset of the canonical `SizePreset` vocabulary. */
type ButtonSizePreset = Extract<SizePreset, 'xs' | 'sm' | 'md' | 'lg' | 'xl'>;

/* `size`: preset (variant class) | number/string (square inline dims) | `{width,height,minWidth,minHeight,boxSize}`.
   Raw/object forms set inline dims only — pair with `padding` if text-bearing. */
export type ButtonSize = SizeUnion<ButtonSizePreset>;

/* Both heritage types are `@vue-ignore`d: they contribute to the *type* surface exactly as in the
   React original, but must not become runtime props. Native button attributes belong in attribute
   fallthrough, and `ButtonVariants` resolves through `typeof buttonVariants`, which the SFC prop
   compiler cannot walk. */
export interface ButtonProps
  extends /* @vue-ignore */ Omit<
      ButtonHTMLAttributes,
      'type' | 'disabled' | 'color' | 'onClick'
    >,
    /* @vue-ignore */ Omit<ButtonVariants, 'size' | 'variant' | 'tone' | 'shape'> {
  /** The visual surface style. */
  variant?: ButtonVariant;

  /** The semantic tone palette. */
  tone?: ColorTone;

  /** The button silhouette (default · square · circle). */
  shape?: ButtonShape;

  /** The size — preset name OR raw value OR explicit dim object; see `ButtonSize` for details. */
  size?: ButtonSize;

  /** The per-instance color override for the active `tone`. String → all slots derived; object → per-slot (bg/text/soft/softText/ring). Sets local CSS vars that `bg-{tone}` etc. pick up. */
  color?: ColorProp;

  /** The slot before children (logical start). Prefer the `leading` named slot; this prop stays for parity with the React API. */
  leadingSlot?: VNodeChild;

  /** The slot after children (logical end). Prefer the `trailing` named slot; this prop stays for parity with the React API. */
  trailingSlot?: VNodeChild;

  /** The content shown in place of children on hover / focus-visible (CSS-only swap — no JS hover state).
     Idle → children visible; hover/focus-visible → `hoverSlot` visible. Pairs with `variant="reveal"`
     for a reveal-on-hover icon swap. When undefined (and no `hover` slot), children render normally. */
  hoverSlot?: VNodeChild;

  /** The indicator shown in place of the built-in `<Spinner/>` when `isLoading` is true. Prefer the `loading` named slot. */
  loadingSlot?: VNodeChild;

  /** The action-loading state — replaces leading w/ spinner, sets aria-busy, blocks clicks. */
  isLoading?: boolean;

  /** The text that replaces children when loading. No default — consumer supplies (i18n). */
  loadingText?: string;

  /** The content-loading state — hides content (preserves dimensions) + shimmer. Mutually exclusive with `isLoading`. */
  isSkeleton?: boolean;

  /** The disabled state — removes from focus order, blocks clicks. Forwards to native `disabled`. Inherited from an enclosing `Field` when omitted. */
  isDisabled?: boolean;

  /** The full-width state — stretches to fill container width. */
  isFullWidth?: boolean;

  /** The multi-line state — allows label wrap; default truncates to single line. */
  isMultiline?: boolean;

  /** The as-child flag — renders as the single child element via `Primitive`'s `asChild` merge. */
  asChild?: boolean;

  /** The independent padding override (preset token or `{x, y}` object). */
  padding?: PaddingProp;

  /** The independent radius override (preset token or raw value). */
  radius?: RadiusProp;

  /** The explicit width override. Number = px; string = any CSS unit. */
  width?: SizeValue;

  /** The explicit height override. Number = px; string = any CSS unit. */
  height?: SizeValue;

  /** The min width reserved so the button doesn't reflow when its label morphs. */
  minWidth?: SizeValue;

  /** The min height reserved — symmetric with `minWidth`. */
  minHeight?: SizeValue;

  /** The square-size shorthand — applied as fallback for both `width` and `height`. Explicit `width`/`height` win when both are set. Pairs with `shape="square"` / `shape="circle"` for icon buttons. */
  boxSize?: SizeValue;

  /** The button type. Default `ButtonType.Button` — NOT browser-default `'submit'`. */
  type?: ButtonType;

  /** The long-press duration (ms). Default 500. Out-of-range values trigger a dev warning. */
  longPressDelay?: number;

  /** The click-throttle window (ms) — first wins; subsequent swallowed via `preventDefault()`. */
  debounceMs?: number;
}
</script>

<script setup lang="ts">
import {
  computed,
  defineComponent,
  getCurrentInstance,
  normalizeStyle,
  onBeforeUnmount,
  useAttrs,
  useSlots,
  useTemplateRef,
  watchEffect,
  type ComponentPublicInstance,
  type StyleValue,
} from 'vue';
import type { ClassValue } from 'clsx';
import {
  cn,
  ColorExtensions,
  composeEventHandlers,
  ButtonType,
  CssExtensions,
  HtmlElement,
  IS_DEV,
  Key,
  OptionalExtensions,
  PressExtensions,
  type BoxSizeOverrides,
  type PressEvent,
} from '../../../foundation/utils';
import { Primitive } from '../../../foundation/primitives';
import { useFormControl } from '../../../foundation/primitives/formControlContext/FormControlContext';
import { Spinner } from '../../../foundation/icons';
import { useDebounceHandler } from '../../../foundation/hooks';
import { buttonVariants } from './Button.variants';

const COMPONENT_NAME = 'Button';

const BUTTON_SIZE_PRESETS: ReadonlySet<string> = new Set<ButtonSizePreset>([
  'xs',
  'sm',
  'md',
  'lg',
  'xl',
]);

/* Observable state surfaced via the `data-state` DOM attribute. */
const ButtonDataState = {
  Loading: 'loading',
  Skeleton: 'skeleton',
  Disabled: 'disabled',
} as const;
type ButtonDataState = (typeof ButtonDataState)[keyof typeof ButtonDataState];

/* `inheritAttrs: false` because three attrs are *owned*, not forwarded: `class` and `style` fold
   into the component's own `cn()` / style resolution so consumer values still win last (plain
   fallthrough would append outside `cn()`, losing tailwind-merge conflict resolution), and
   `onClick` is intercepted so loading / skeleton / long-press / the debounce window can swallow a
   click before the consumer's handler sees it. Everything else passes straight through. */
/* The name is spelled out, not `COMPONENT_NAME`: `defineOptions()` is hoisted out of `setup()`,
   so it cannot reference a locally declared const. */
defineOptions({ name: 'Button', inheritAttrs: false });

const props = withDefaults(defineProps<ButtonProps>(), {
  type: ButtonType.Button,
  longPressDelay: PressExtensions.longPressDelay.default,
  /* Explicit `undefined` defaults keep Vue's boolean casting from turning an absent prop into
     `false` — `isDisabled` must stay undefined to inherit from an enclosing `Field`. */
  isDisabled: undefined,
  isLoading: undefined,
  isSkeleton: undefined,
  isFullWidth: undefined,
  isMultiline: undefined,
  asChild: false,
  /* `VNodeChild` includes `boolean`, so Vue's boolean casting turns an absent node-valued prop
     into `false` rather than `undefined` — which reads as "supplied" at every `!== undefined`
     check. An explicit `undefined` default suppresses the cast. */
  leadingSlot: undefined,
  trailingSlot: undefined,
  hoverSlot: undefined,
  loadingSlot: undefined,
});

const emit = defineEmits<{
  /** Fires when the press begins — pointer-down OR Space/Enter keydown (first event in a gesture). */
  'press-start': [event: PressEvent<HTMLButtonElement>];

  /** Fires when the press ends — pointer-up/cancel OR Space/Enter keyup. */
  'press-end': [event: PressEvent<HTMLButtonElement>];

  /** Fires when the pointer is held for `longPressDelay` ms. Suppresses the next click. */
  'long-press': [event: PressEvent<HTMLButtonElement>];
}>();

const attrs = useAttrs();
const slots = useSlots();

/* Stable render-only wrappers for the node-valued props, so each can render as the fallback of its
   named-slot twin. Stable identity (created once) keeps them from remounting on every render. */
const nodeProp = (read: () => VNodeChild) => defineComponent({ render: read });
const LeadingSlotProp = nodeProp(() => props.leadingSlot);
const TrailingSlotProp = nodeProp(() => props.trailingSlot);
const HoverSlotProp = nodeProp(() => props.hoverSlot);
const LoadingSlotProp = nodeProp(() => props.loadingSlot);

/* Inherit disabled-state from an enclosing `Field` when the local prop is omitted; standalone when
   no context. Bound to the object, never destructured — every field on it is a live getter. */
const formControl = useFormControl();
const resolvedDisabled = computed(() => props.isDisabled ?? formControl?.isDisabled ?? false);

const skeletonActive = computed(() => !!props.isSkeleton);
const loadingActive = computed(() => !skeletonActive.value && !!props.isLoading);
const isInactive = computed(
  () => loadingActive.value || skeletonActive.value || resolvedDisabled.value,
);

const dataState = computed<ButtonDataState | undefined>(() =>
  skeletonActive.value
    ? ButtonDataState.Skeleton
    : loadingActive.value
      ? ButtonDataState.Loading
      : resolvedDisabled.value
        ? ButtonDataState.Disabled
        : undefined,
);

const safeLongPressDelay = computed(() =>
  props.longPressDelay < PressExtensions.longPressDelay.min ||
  props.longPressDelay > PressExtensions.longPressDelay.max
    ? PressExtensions.longPressDelay.default
    : props.longPressDelay,
);

watchEffect(() => {
  if (!IS_DEV) return;
  if (props.isLoading && props.isSkeleton) {
    console.warn(
      `[${COMPONENT_NAME}] \`isLoading\` and \`isSkeleton\` are mutually exclusive — \`isSkeleton\` takes precedence.`,
    );
  }
  if (safeLongPressDelay.value !== props.longPressDelay) {
    console.warn(
      `[${COMPONENT_NAME}] longPressDelay=${props.longPressDelay}ms is outside reasonable range (${PressExtensions.longPressDelay.min}–${PressExtensions.longPressDelay.max}ms). Falling back to ${PressExtensions.longPressDelay.default}ms.`,
    );
  }
  if (
    slots.default === undefined &&
    attrs['aria-label'] === undefined &&
    attrs['aria-labelledby'] === undefined
  ) {
    console.warn(
      `[${COMPONENT_NAME}] icon-only button (no text children) is missing an accessible name — pass \`aria-label\` or \`aria-labelledby\` (Button.standard.md rule 12).`,
    );
  }
});

/* Parse the union-typed `size` prop into preset (for variant lookup) + box overrides (for inline dims). */
const parsedSize = computed(() =>
  CssExtensions.parseSizeUnion<ButtonSizePreset>(props.size, BUTTON_SIZE_PRESETS),
);

const rootClass = computed(() =>
  cn(
    buttonVariants({
      variant: props.variant,
      tone: props.tone,
      size: parsedSize.value.preset,
      shape: props.shape,
      fullWidth: props.isFullWidth,
      wrap: props.isMultiline,
    }),
    attrs.class as ClassValue,
  ),
);

const overrideStyle = computed<StyleValue | undefined>(() => {
  const padStyle = CssExtensions.resolvePadding(props.padding);
  const radStyle = CssExtensions.resolveRadius(props.radius);
  /* Box overrides — `size` (object form or raw value) is the base; flat width/height/minWidth/minHeight/boxSize props win when both are set. */
  const composedBox: BoxSizeOverrides = {
    ...(parsedSize.value.box ?? {}),
    ...(props.width !== undefined ? { width: props.width } : {}),
    ...(props.height !== undefined ? { height: props.height } : {}),
    ...(props.minWidth !== undefined ? { minWidth: props.minWidth } : {}),
    ...(props.minHeight !== undefined ? { minHeight: props.minHeight } : {}),
    ...(props.boxSize !== undefined ? { boxSize: props.boxSize } : {}),
  };
  const boxStyle = CssExtensions.resolveBoxSize(composedBox);
  /* Per-instance color override → sets CSS vars on element, scoped locally. */
  const colorStyle = ColorExtensions.toneColorOverride(props.color, props.tone);
  const consumerStyle = attrs.style as StyleValue | undefined;
  if (!padStyle && !radStyle && !boxStyle && !colorStyle && !consumerStyle) return undefined;
  return normalizeStyle([colorStyle, padStyle, radStyle, boxStyle, consumerStyle]);
});

// ---------------------------------------------------------------------------
// Press / long-press / debounce wiring.
// ---------------------------------------------------------------------------

let isPressing = false;
let longPressTimer: ReturnType<typeof setTimeout> | undefined;
let longPressFired = false;

const instance = getCurrentInstance();

/* React armed the long-press timer only when an `onLongPress` prop was passed. A declared emit has
   no such signal — `emit()` on an unlistened event is a silent no-op, but the fired flag would
   still swallow the following click on every long hold. The listener is read off the incoming
   vnode props at event time (declared-emit listeners are stripped from `attrs`), so an unlistened
   button never arms the timer at all. */
function hasLongPressListener(): boolean {
  return instance?.vnode.props?.onLongPress !== undefined;
}

onBeforeUnmount(() => {
  if (longPressTimer !== undefined) clearTimeout(longPressTimer);
});

function cancelLongPress(): void {
  if (longPressTimer !== undefined) {
    clearTimeout(longPressTimer);
    longPressTimer = undefined;
  }
}

function endPress(event: PressEvent<HTMLButtonElement>): void {
  if (isPressing) {
    isPressing = false;
    emit('press-end', event);
  }
}

function handlePointerDown(event: PointerEvent): void {
  if (isInactive.value) return;
  // Cancel any pending timer, then arm only on the first pointer of a gesture — a second
  // pointer-down must not stack a second long-press timer.
  cancelLongPress();
  if (!isPressing) {
    const pressEvent = event as PressEvent<HTMLButtonElement>;
    isPressing = true;
    longPressFired = false;
    emit('press-start', pressEvent);
    if (hasLongPressListener()) {
      longPressTimer = setTimeout(() => {
        longPressFired = true;
        emit('long-press', pressEvent);
        longPressTimer = undefined;
      }, safeLongPressDelay.value);
    }
  }
}

function handlePointerUp(event: PointerEvent): void {
  cancelLongPress();
  endPress(event as PressEvent<HTMLButtonElement>);
}

function handlePointerCancel(event: PointerEvent): void {
  cancelLongPress();
  endPress(event as PressEvent<HTMLButtonElement>);
}

function handlePointerLeave(): void {
  // Pointer leaving cancels a pending long-press but does NOT end the press itself —
  // pointer-up/cancel handlers do that. Matches React Aria.
  cancelLongPress();
}

const isActivationKey = (event: KeyboardEvent) =>
  event.key === Key.Space || event.key === Key.Enter;

function handleKeyDown(event: KeyboardEvent): void {
  if (isInactive.value) return;
  if (isActivationKey(event) && !event.repeat && !isPressing) {
    isPressing = true;
    longPressFired = false;
    emit('press-start', event as PressEvent<HTMLButtonElement>);
  }
}

function handleKeyUp(event: KeyboardEvent): void {
  if (isActivationKey(event) && isPressing) {
    isPressing = false;
    emit('press-end', event as PressEvent<HTMLButtonElement>);
  }
}

/**
 * The consumer's listener for one attr, normalised. Vue merges several listeners for the same
 * event into an array (a wrapper component that binds `@click` on top of a forwarded `onClick`
 * produces exactly that), so the raw attr is not always callable.
 */
function toHandler<E extends Event>(value: unknown): ((event: E) => void) | undefined {
  if (typeof value === 'function') return value as (event: E) => void;
  if (!Array.isArray(value)) return undefined;
  const handlers = value.filter(
    (entry): entry is (event: E) => void => typeof entry === 'function',
  );
  if (handlers.length === 0) return undefined;
  return (event) => {
    for (const handler of handlers) handler(event);
  };
}

// Long-press suppression happens BEFORE this — a suppressed click does NOT advance the throttle window.
const debouncedOnClick = useDebounceHandler(
  (event: MouseEvent) => toHandler<MouseEvent>(attrs.onClick)?.(event),
  () => props.debounceMs,
);

function handleClick(event: MouseEvent): void {
  if (loadingActive.value || skeletonActive.value) {
    // Block native activation too — e.g. `type="submit"` must not submit while loading.
    event.preventDefault();
    return;
  }
  if (longPressFired) {
    longPressFired = false;
    event.preventDefault();
    return;
  }
  debouncedOnClick(event);
}

/* The attrs the component owns rather than forwards — see the `inheritAttrs: false` note above.
   Event names carry the single casing Vue's runtime understands (`on` + the event name with only
   its first letter capitalised); `onPointerDown` would bind a `pointer-down` listener. */
const OWNED_ATTRS: ReadonlySet<string> = new Set([
  'class',
  'style',
  'onClick',
  'onPointerdown',
  'onPointerup',
  'onPointercancel',
  'onPointerleave',
  'onKeydown',
  'onKeyup',
]);

const passthroughAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))),
);

/** The consumer's own listener for an owned event, so it can be chained ahead of the component's. */
function consumerHandler<E extends Event>(name: string): ((event: E) => void) | undefined {
  return toHandler<E>(attrs[name]);
}

/* Assembled in the React original's spread order: the component's own attributes first, its event
   chain next, consumer attrs last so they still win. */
const rootProps = computed(() => ({
  type: props.asChild ? undefined : props.type,
  class: rootClass.value,
  style: overrideStyle.value,
  disabled: OptionalExtensions.from(resolvedDisabled.value, true),
  'aria-busy': OptionalExtensions.from(loadingActive.value || skeletonActive.value, true),
  'aria-disabled': OptionalExtensions.from(loadingActive.value || skeletonActive.value, true),
  tabindex: OptionalExtensions.from(skeletonActive.value, -1),
  'data-state': dataState.value,
  onClick: handleClick,
  onPointerdown: composeEventHandlers(consumerHandler<PointerEvent>('onPointerdown'), handlePointerDown),
  onPointerup: composeEventHandlers(consumerHandler<PointerEvent>('onPointerup'), handlePointerUp),
  onPointercancel: composeEventHandlers(
    consumerHandler<PointerEvent>('onPointercancel'),
    handlePointerCancel,
  ),
  onPointerleave: composeEventHandlers(
    consumerHandler<PointerEvent>('onPointerleave'),
    handlePointerLeave,
  ),
  onKeydown: composeEventHandlers(consumerHandler<KeyboardEvent>('onKeydown'), handleKeyDown),
  onKeyup: composeEventHandlers(consumerHandler<KeyboardEvent>('onKeyup'), handleKeyUp),
  ...passthroughAttrs.value,
}));

const root = useTemplateRef<ComponentPublicInstance>('root');

/** The rendered element — the Vue stand-in for the React original's forwarded ref. */
const el = computed<HTMLElement | null>(() => {
  const node = root.value?.$el;
  return node instanceof HTMLElement ? node : null;
});

defineExpose({ el });
</script>

<template>
  <!-- Renders an action button — for text and/or icon content. -->
  <Primitive ref="root" :as="HtmlElement.Button" :as-child="asChild" v-bind="rootProps">
    <!-- asChild → the merge target owns its children; leading/trailing/loading chrome is not rendered. -->
    <slot v-if="asChild" />

    <template v-else-if="loadingActive">
      <slot name="loading">
        <LoadingSlotProp v-if="loadingSlot !== undefined" />
        <Spinner v-else />
      </slot>
      <span v-if="loadingText !== undefined">{{ loadingText }}</span>
      <!-- No loadingText: keep children in sr-only so the accessible name survives (Spinner is aria-hidden). -->
      <span v-else class="sr-only"><slot /></span>
    </template>

    <template v-else-if="hoverSlot !== undefined || $slots.hover">
      <slot name="leading"><LeadingSlotProp v-if="leadingSlot !== undefined" /></slot>
      <!-- CSS-only hover/focus-visible swap: children occupy the box and reserve its size;
           the hover content overlays it centered. Toggle via `group-hover`/`group-focus-visible`
           on the root `group` — no JS hover state. `aria-hidden` on the hidden layer so AT
           reads one label. -->
      <span class="relative inline-flex items-center justify-center">
        <span
          class="inline-flex items-center justify-center group-hover:invisible group-focus-visible:invisible"
        >
          <slot />
        </span>
        <span
          aria-hidden="true"
          class="invisible absolute inset-0 inline-flex items-center justify-center group-hover:visible group-focus-visible:visible"
        >
          <slot name="hover"><HoverSlotProp v-if="hoverSlot !== undefined" /></slot>
        </span>
      </span>
      <slot name="trailing"><TrailingSlotProp v-if="trailingSlot !== undefined" /></slot>
    </template>

    <template v-else>
      <slot name="leading"><LeadingSlotProp v-if="leadingSlot !== undefined" /></slot>
      <slot />
      <slot name="trailing"><TrailingSlotProp v-if="trailingSlot !== undefined" /></slot>
    </template>
  </Primitive>
</template>
