// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/highlight/Highlight.vue
<script lang="ts">
export interface HighlightProps {
  /**
   * The source text to render.
   *
   * React took this as `children: string` and split it. A Vue slot renders
   * opaque vnodes that cannot be tokenised, so the text has to arrive as a
   * prop — named `text`, matching the sibling `Snippet`, which faced the same
   * "string consumed by logic, not rendered as a node" case.
   */
  text: string;

  /** The substring(s) to highlight. Match is case-insensitive. */
  query: string | ReadonlyArray<string>;

  /** The whole-word-only matching mode. Default `false`. */
  isWholeWord?: boolean;
}

/** One run of the source text, flagged for `Mark` wrapping. */
interface HighlightSegment {
  text: string;
  isMatch: boolean;
}

function escapeRegExp(re: string): string {
  return re.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';
import Mark from '../mark/Mark.vue';

/**
 * Wraps each occurrence of `query` (or any of `query[]`) inside the `text`
 * in a `<Mark>`. Case-insensitive; pass `isWholeWord` to avoid partial
 * matches.
 */
defineOptions({ name: 'Highlight', inheritAttrs: false });

const props = defineProps<HighlightProps>();

const attrs = useAttrs();
const el = useTemplateRef<HTMLSpanElement>('el');

/* `typeof` rather than `Array.isArray` — the latter does not narrow a
   `ReadonlyArray` cleanly, and the two branches are equivalent here. */
const queries = computed<Array<string>>(() =>
  (typeof props.query === 'string' ? [props.query] : [...props.query]).filter(Boolean),
);

/**
 * With no usable query React returned the raw text in a bare span; that is the
 * single non-matching segment below, so both paths share one root element.
 */
const segments = computed<Array<HighlightSegment>>(() => {
  const list = queries.value;
  if (list.length === 0) return [{ text: props.text, isMatch: false }];

  const pattern = list.map(escapeRegExp).join('|');
  const regex = new RegExp(props.isWholeWord ? `\\b(${pattern})\\b` : `(${pattern})`, 'gi');

  return props.text
    .split(regex)
    .filter((part) => part !== '')
    .map((part) => ({
      text: part,
      isMatch: list.some((q) => part.toLowerCase() === q.toLowerCase()),
    }));
});

const classes = computed(() => cn(attrs.class as string | undefined));

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <span ref="el" v-bind="rest" :class="classes">
    <template v-for="(segment, i) in segments" :key="i">
      <Mark v-if="segment.isMatch">{{ segment.text }}</Mark>
      <template v-else>{{ segment.text }}</template>
    </template>
  </span>
</template>

// src/display/highlight/Highlight.tsx
import { Fragment, forwardRef, type ComponentPropsWithoutRef, type ReactNode } from 'react';
import { cn } from '../../utils';
import { Mark } from '../mark/Mark';

export interface HighlightProps extends Omit<ComponentPropsWithoutRef<'span'>, 'children'> {
  /** Source text to render. */
  children: string;
  /** Substring(s) to highlight. Match is case-insensitive. */
  query: string | string[];
  /** When `true`, only highlights whole-word matches. Default `false`. */
  wholeWord?: boolean;
}

function escape(re: string) {
  return re.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Wraps each occurrence of `query` (or any of `query[]`) inside the
 * `children` text in a `<Mark>`. Case-insensitive; pass `wholeWord` to
 * avoid partial matches.
 */
export const Highlight = forwardRef<HTMLSpanElement, HighlightProps>(
  ({ children, query, wholeWord, className, ...props }, ref) => {
    const queries = (Array.isArray(query) ? query : [query]).filter(Boolean);
    if (queries.length === 0) return <span ref={ref} className={cn(className)} {...props}>{children}</span>;
    const pattern = queries.map(escape).join('|');
    const regex = new RegExp(wholeWord ? `\\b(${pattern})\\b` : `(${pattern})`, 'gi');
    const parts = children.split(regex);

    const nodes: ReactNode[] = [];
    parts.forEach((part, i) => {
      if (queries.some((q) => part.toLowerCase() === q.toLowerCase())) {
        nodes.push(<Mark key={i}>{part}</Mark>);
      } else if (part) {
        nodes.push(<Fragment key={i}>{part}</Fragment>);
      }
    });

    return (
      <span ref={ref} className={cn(className)} {...props}>
        {nodes}
      </span>
    );
  },
);
Highlight.displayName = 'Highlight';
