// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/nav/menubar/Menubar.vue
<script lang="ts">
/**
 * The prop surface of `Menubar`.
 *
 * React declared `extends Omit<HTMLAttributes<HTMLDivElement>, 'defaultValue' | 'onChange'>`;
 * attributes reach the root through `useAttrs` here, which leaves the active-menu
 * value pair. React's `onValueChange` is the `value-change` emit.
 */
export interface MenubarProps {
  /** The id of the currently-open menu, or `null` if none. Controlled. */
  value?: string | null;

  /** The initially-open menu id when uncontrolled. Default `null`. */
  defaultValue?: string | null;
}
</script>

<script setup lang="ts">
import { computed, provide, useAttrs, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';
import { useControlled } from '../../../foundation/hooks';
import { RovingFocusGroup } from '../../../foundation/primitives';
import { menubarContextKey, type MenubarTriggerEntry } from './MenubarContext';
import { menubarVariants } from './Menubar.variants';

/** The application menu bar — a single composite tab stop holding one menu open at a time. */
defineOptions({ name: 'Menubar', inheritAttrs: false });

/** The `MenubarMenu` children — React's `children`. */
defineSlots<{ default(): unknown }>();

/** `value` defaults to `undefined` — the tri-state that separates "controlled to null" from "uncontrolled". */
const props = withDefaults(defineProps<MenubarProps>(), {
  value: undefined,
  defaultValue: null,
});

const emit = defineEmits<{
  /** Replaces React's `onValueChange` — fires with the newly-open menu id, or `null`. */
  'value-change': [value: string | null];
}>();

const attrs = useAttrs();
const el = useTemplateRef<InstanceType<typeof RovingFocusGroup>>('el');

const { value: activeId, setValue: setActiveId } = useControlled<string | null>({
  controlled: () => props.value,
  default: () => props.defaultValue,
  onChange: (next) => emit('value-change', next),
});

/** Plain array, not reactive — the ordering is read imperatively, exactly as React's `useRef` list was. */
const triggers: Array<MenubarTriggerEntry> = [];

function registerTrigger(id: string, triggerEl: HTMLButtonElement | null): void {
  const index = triggers.findIndex((t) => t.id === id);
  if (index >= 0) triggers[index] = { id, el: triggerEl };
  else triggers.push({ id, el: triggerEl });
}

function unregisterTrigger(id: string): void {
  const index = triggers.findIndex((t) => t.id === id);
  if (index >= 0) triggers.splice(index, 1);
}

function moveAcross(fromId: string, direction: 1 | -1): void {
  const index = triggers.findIndex((t) => t.id === fromId);
  if (index === -1) return;
  let nextIndex = index + direction;
  if (nextIndex < 0) nextIndex = triggers.length - 1;
  if (nextIndex >= triggers.length) nextIndex = 0;
  const next = triggers[nextIndex];
  if (!next) return;
  next.el?.focus();
  // If a menu is already open, switch the open menu to follow focus.
  if (activeId.value !== null) setActiveId(next.id);
}

provide(menubarContextKey, {
  activeId,
  setActiveId,
  registerTrigger,
  unregisterTrigger,
  moveAcross,
});

const classes = computed(() => cn(menubarVariants(), attrs.class as string | undefined));

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <!-- Roving tabindex (APG): the menubar is a single composite tab stop — one
       trigger holds tabindex 0, arrows / Home / End rove focus. `role` falls
       through and replaces the primitive's own `role="group"`. -->
  <RovingFocusGroup ref="el" orientation="horizontal" can-loop role="menubar" v-bind="rest" :class="classes">
    <slot />
  </RovingFocusGroup>
</template>

// src/presentation/nav/menubar/Menubar.tsx
import {
  createContext,
  forwardRef,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ButtonHTMLAttributes,
  type HTMLAttributes,
  type ReactNode,
} from 'react';
import { cn, composeRefs } from '../../../foundation/utils';
import { useControlled } from '../../../foundation/hooks';
import { RovingFocusGroup, useRovingFocusItem } from '../../../foundation/primitives';
import {
  Menu,
  MenuItem,
  MenuGroup,
  MenuLabel,
  MenuSeparator,
  type MenuProps,
} from '../menu';
import { menubarTriggerVariants, menubarVariants } from './Menubar.variants';

interface MenubarContextValue {
  activeId: string | null;
  setActiveId: (id: string | null) => void;
  registerTrigger: (id: string, ref: HTMLButtonElement | null) => void;
  unregisterTrigger: (id: string) => void;
  triggersRef: React.MutableRefObject<{ id: string; ref: HTMLButtonElement | null }[]>;
  /** Focuses the trigger adjacent to `fromId`; switches the open menu when one is open. */
  moveAcross: (fromId: string, direction: 1 | -1) => void;
}

const MenubarContext = createContext<MenubarContextValue | null>(null);

function useMenubarContext() {
  const ctx = useContext(MenubarContext);
  if (!ctx) throw new Error('Menubar.* must be used inside <Menubar>');
  return ctx;
}

interface MenubarMenuContextValue {
  id: string;
  open: boolean;
  setOpen: (open: boolean) => void;
  triggerRef: React.MutableRefObject<HTMLButtonElement | null>;
  /** Trigger node kept in state so anchored content re-renders once the ref attaches. */
  triggerNode: HTMLButtonElement | null;
  setTriggerNode: (node: HTMLButtonElement | null) => void;
}

const MenubarMenuContext = createContext<MenubarMenuContextValue | null>(null);

function useMenubarMenuContext() {
  const ctx = useContext(MenubarMenuContext);
  if (!ctx) throw new Error('Menubar.Trigger / Content must be used inside <Menubar.Menu>');
  return ctx;
}

export interface MenubarProps
  extends Omit<HTMLAttributes<HTMLDivElement>, 'defaultValue' | 'onChange'> {
  /** Id of the currently-open menu, or `null` if none. */
  value?: string | null;
  defaultValue?: string | null;
  onValueChange?: (value: string | null) => void;
  children: ReactNode;
}

const MenubarRoot = forwardRef<HTMLDivElement, MenubarProps>(function Menubar(
  { value, defaultValue = null, onValueChange, className, children, ...rest },
  ref,
) {
  const [activeId, setActiveId] = useControlled<string | null>({
    controlled: value,
    default: defaultValue,
    onChange: onValueChange,
  });

  const triggersRef = useRef<{ id: string; ref: HTMLButtonElement | null }[]>([]);

  const registerTrigger = useCallback((id: string, triggerRef: HTMLButtonElement | null) => {
    const idx = triggersRef.current.findIndex((t) => t.id === id);
    if (idx >= 0) triggersRef.current[idx] = { id, ref: triggerRef };
    else triggersRef.current.push({ id, ref: triggerRef });
  }, []);
  const unregisterTrigger = useCallback((id: string) => {
    triggersRef.current = triggersRef.current.filter((t) => t.id !== id);
  }, []);

  const moveAcross = useCallback(
    (fromId: string, direction: 1 | -1) => {
      const list = triggersRef.current;
      const idx = list.findIndex((t) => t.id === fromId);
      if (idx === -1) return;
      let nextIdx = idx + direction;
      if (nextIdx < 0) nextIdx = list.length - 1;
      if (nextIdx >= list.length) nextIdx = 0;
      const next = list[nextIdx];
      if (!next) return;
      next.ref?.focus();
      // If a menu is already open, switch the open menu to follow focus.
      if (activeId !== null) setActiveId(next.id);
    },
    [activeId, setActiveId],
  );

  const ctx = useMemo<MenubarContextValue>(
    () => ({ activeId, setActiveId, registerTrigger, unregisterTrigger, triggersRef, moveAcross }),
    [activeId, setActiveId, registerTrigger, unregisterTrigger, moveAcross],
  );

  return (
    <MenubarContext.Provider value={ctx}>
      {/* Roving tabindex (APG): the menubar is a single composite tab stop —
          one trigger holds tabIndex 0, arrows / Home / End rove focus. */}
      <RovingFocusGroup
        ref={ref}
        orientation="horizontal"
        canLoop
        role="menubar"
        className={cn(menubarVariants(), className)}
        {...rest}
      >
        {children}
      </RovingFocusGroup>
    </MenubarContext.Provider>
  );
});

export interface MenubarMenuProps {
  /** Stable id for this menu — used for active-menu tracking. */
  value: string;
  children: ReactNode;
}

export function MenubarMenu({ value, children }: MenubarMenuProps) {
  const ctx = useMenubarContext();
  const triggerRef = useRef<HTMLButtonElement | null>(null);
  const [triggerNode, setTriggerNode] = useState<HTMLButtonElement | null>(null);

  const open = ctx.activeId === value;
  const setOpen = useCallback(
    (next: boolean) => {
      ctx.setActiveId(next ? value : null);
    },
    [ctx, value],
  );

  const menuCtx = useMemo<MenubarMenuContextValue>(
    () => ({ id: value, open, setOpen, triggerRef, triggerNode, setTriggerNode }),
    [value, open, setOpen, triggerNode],
  );

  return <MenubarMenuContext.Provider value={menuCtx}>{children}</MenubarMenuContext.Provider>;
}

export interface MenubarTriggerProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'children'> {
  children: ReactNode;
}

export const MenubarTrigger = forwardRef<HTMLButtonElement, MenubarTriggerProps>(
  function MenubarTrigger(
    { className, onClick, onKeyDown, onPointerEnter, onFocus, children, ...rest },
    forwardedRef,
  ) {
    const bar = useMenubarContext();
    const menu = useMenubarMenuContext();
    // Roving tab stop — one trigger is tabbable; the stop follows focus.
    const roving = useRovingFocusItem();

    useEffect(() => {
      bar.registerTrigger(menu.id, menu.triggerRef.current);
      return () => bar.unregisterTrigger(menu.id);
    }, [bar, menu.id, menu.triggerRef]);

    return (
      <button
        ref={composeRefs(forwardedRef, menu.triggerRef, menu.setTriggerNode, roving.ref)}
        type="button"
        role="menuitem"
        aria-haspopup="menu"
        aria-expanded={menu.open}
        data-state={menu.open ? 'open' : 'closed'}
        tabIndex={roving.tabIndex}
        onClick={(e) => {
          onClick?.(e);
          if (e.defaultPrevented) return;
          menu.setOpen(!menu.open);
        }}
        onPointerEnter={(e) => {
          onPointerEnter?.(e);
          // If any menu is open, switching the trigger pointer-over switches the active menu.
          if (bar.activeId !== null && bar.activeId !== menu.id) {
            bar.setActiveId(menu.id);
          }
        }}
        onFocus={(e) => {
          onFocus?.(e);
          // The roving stop follows focus — however it arrived (arrows,
          // moveAcross from an open popup, focus return on close).
          roving.onFocus();
        }}
        onKeyDown={(e) => {
          onKeyDown?.(e);
          if (e.defaultPrevented) return;
          switch (e.key) {
            case 'ArrowDown':
            case 'Enter':
            case ' ':
              e.preventDefault();
              menu.setOpen(true);
              return;
            case 'ArrowRight':
            case 'ArrowLeft':
              // A menu is open → switching semantics: focus AND open state
              // move to the adjacent menu together.
              if (bar.activeId !== null) {
                e.preventDefault();
                bar.moveAcross(menu.id, e.key === 'ArrowRight' ? 1 : -1);
                return;
              }
              break;
          }
          // Closed menubar: arrows / Home / End rove the single tab stop
          // (disabled triggers skipped, RTL-aware).
          roving.onKeyDown(e);
        }}
        className={cn(menubarTriggerVariants(), className)}
        {...rest}
      >
        {children}
      </button>
    );
  },
);

export interface MenubarContentProps {
  className?: string;
  placement?: MenuProps['placement'];
  offset?: number;
  'aria-label'?: string;
  children: ReactNode;
}

export function MenubarContent({
  className,
  placement = 'bottom-start',
  offset = 4,
  'aria-label': ariaLabel,
  children,
}: MenubarContentProps) {
  const bar = useMenubarContext();
  const menu = useMenubarMenuContext();
  return (
    <Menu
      open={menu.open}
      anchor={menu.triggerNode}
      onClose={() => {
        menu.setOpen(false);
        requestAnimationFrame(() => menu.triggerRef.current?.focus());
      }}
      onKeyDown={(e) => {
        // Arrow across menus while a popup is open — close current, open adjacent.
        switch (e.key) {
          case 'ArrowRight':
            e.preventDefault();
            bar.moveAcross(menu.id, 1);
            break;
          case 'ArrowLeft':
            e.preventDefault();
            bar.moveAcross(menu.id, -1);
            break;
        }
      }}
      placement={placement}
      offset={offset}
      aria-label={ariaLabel}
      className={className}
    >
      {children}
    </Menu>
  );
}

export const Menubar = Object.assign(MenubarRoot, {
  Menu: MenubarMenu,
  Trigger: MenubarTrigger,
  Content: MenubarContent,
  Item: MenuItem,
  Group: MenuGroup,
  Label: MenuLabel,
  Separator: MenuSeparator,
});

export default Menubar;
