// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/list/List.vue
<script lang="ts">
import type { ListMarker, ListSpacing } from './List.variants';

export interface ListProps {
  /** The ordered mode — renders `<ol>` instead of `<ul>`. */
  isOrdered?: boolean;

  /** The item marker style. */
  marker?: ListMarker;

  /** The vertical spacing between items. */
  spacing?: ListSpacing;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';
import { listVariants } from './List.variants';

/**
 * Bulleted / numbered / check list container. Pair with `ListItem` for the
 * leading-trailing row shape; a bare `<li>` works too.
 */
defineOptions({ name: 'List', inheritAttrs: false });

/** The list items — React's required `children`. */
defineSlots<{ default(): unknown }>();

const props = withDefaults(defineProps<ListProps>(), { isOrdered: undefined });

const attrs = useAttrs();
const el = useTemplateRef<HTMLElement>('el');

const tag = computed(() => (props.isOrdered ? 'ol' : 'ul'));

const classes = computed(() =>
  cn(
    listVariants({ marker: props.marker, spacing: props.spacing }),
    attrs.class as string | undefined,
  ),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <component :is="tag" ref="el" v-bind="rest" :class="classes"><slot /></component>
</template>

// engineering/codebase/wow-two-front-beta-sdk/src/presentation/display/list/List.tsx
import { forwardRef, type HTMLAttributes, type LiHTMLAttributes, type ReactNode } from 'react';
import { Check } from 'lucide-react';
import { cn } from '../../../foundation/utils';
import {
  listItemVariants,
  listVariants,
  type ListMarker,
  type ListSpacing,
  type ListVariants,
} from './List.variants';

export interface ListProps
  extends Omit<HTMLAttributes<HTMLUListElement | HTMLOListElement>, 'type'>,
    Omit<ListVariants, 'marker' | 'spacing'> {
  isOrdered?: boolean;
  /** The item marker style. */
  marker?: ListMarker;
  /** The vertical spacing between items. */
  spacing?: ListSpacing;
  children: ReactNode;
}

const ListRoot = forwardRef<HTMLUListElement | HTMLOListElement, ListProps>(function List(
  { isOrdered, marker, spacing, className, children, ...rest },
  ref,
) {
  const Component = (isOrdered ? 'ol' : 'ul') as 'ol';
  return (
    <Component
      ref={ref as React.Ref<HTMLOListElement>}
      className={cn(listVariants({ marker, spacing }), className)}
      {...(rest as HTMLAttributes<HTMLOListElement>)}
    >
      {children}
    </Component>
  );
});

export interface ListItemProps extends LiHTMLAttributes<HTMLLIElement> {
  /** The leading slot — icon, avatar, marker. */
  leading?: ReactNode;

  /** The trailing slot — badge, chevron, status. */
  trailing?: ReactNode;

  /** The auto-check-marker mode — renders a check marker if the parent List uses `marker="check"`. */
  hasCheckMarker?: boolean;
  children: ReactNode;
}

export const ListItem = forwardRef<HTMLLIElement, ListItemProps>(function ListItem(
  { leading, trailing, hasCheckMarker, className, children, ...rest },
  ref,
) {
  return (
    <li ref={ref} className={cn(listItemVariants(), className)} {...rest}>
      {hasCheckMarker && (
        <span aria-hidden="true" className="mt-0.5 shrink-0 text-primary">
          <Check className="h-4 w-4" />
        </span>
      )}
      {leading && (
        <span aria-hidden="true" className="mt-0.5 shrink-0 text-muted-foreground">
          {leading}
        </span>
      )}
      <span className="flex-1">{children}</span>
      {trailing && <span className="shrink-0 text-muted-foreground">{trailing}</span>}
    </li>
  );
});

export const List = Object.assign(ListRoot, {
  Item: ListItem,
});

export default List;
