// src/nav/menu/Menu.tsx
import {
  createContext,
  forwardRef,
  useCallback,
  useContext,
  useEffect,
  useId,
  useMemo,
  useRef,
  type ButtonHTMLAttributes,
  type HTMLAttributes,
  type KeyboardEvent,
  type ReactNode,
} from 'react';
import { FocusScope } from '@radix-ui/react-focus-scope';
import { cn, composeRefs, surfaceVariants, type SurfaceVariants } from '../../utils';
import { AnchoredPositioner, DismissableLayer, Portal, Presence } from '../../primitives';
import {
  menuItemVariants,
  menuLabelVariants,
  menuSeparatorVariants,
  menuVariants,
  type MenuItemVariants,
} from './Menu.variants';

interface MenuItemEntry {
  id: string;
  ref: HTMLButtonElement | null;
  disabled: boolean;
}

interface MenuContextValue {
  registerItem: (entry: MenuItemEntry) => void;
  unregisterItem: (id: string) => void;
  itemsRef: React.MutableRefObject<MenuItemEntry[]>;
  onClose: () => void;
}

const MenuContext = createContext<MenuContextValue | null>(null);

function useMenuContext() {
  const ctx = useContext(MenuContext);
  if (!ctx) throw new Error('Menu.Item / Group / Label / Separator must be used inside <Menu>');
  return ctx;
}

/** Represents the prop surface of `Menu`. */
export interface MenuProps extends SurfaceVariants {
  open: boolean;
  anchor: HTMLElement | null;
  onClose: () => void;
  placement?: React.ComponentProps<typeof AnchoredPositioner>['placement'];
  offset?: number;
  /** Keydown observed on the menu container — lets wrappers (e.g. Menubar) add navigation. */
  onKeyDown?: (e: KeyboardEvent<HTMLDivElement>) => void;
  /** Labels the menu for screen readers. */
  'aria-label'?: string;
  className?: string;
  children: ReactNode;
}

function MenuRoot({
  open,
  anchor,
  onClose,
  placement = 'bottom-start',
  offset = 6,
  onKeyDown,
  'aria-label': ariaLabel,
  variant,
  tone,
  radius,
  padding,
  elevation,
  className,
  children,
}: MenuProps) {
  const itemsRef = useRef<MenuItemEntry[]>([]);

  const registerItem = useCallback((entry: MenuItemEntry) => {
    const idx = itemsRef.current.findIndex((i) => i.id === entry.id);
    if (idx >= 0) itemsRef.current[idx] = entry;
    else itemsRef.current.push(entry);
  }, []);
  const unregisterItem = useCallback((id: string) => {
    itemsRef.current = itemsRef.current.filter((i) => i.id !== id);
  }, []);

  const ctx = useMemo<MenuContextValue>(
    () => ({ registerItem, unregisterItem, itemsRef, onClose }),
    [registerItem, unregisterItem, onClose],
  );

  // No hard `if (!open) return null` — Presence (below) keeps the surface
  // mounted through its pop-out exit, flipping data-state to "closed" and
  // deferring unmount until the animation ends.
  return (
    <MenuContext.Provider value={ctx}>
      <Portal>
        <AnchoredPositioner
          anchor={anchor}
          placement={placement}
          offset={offset}
          className="z-dropdown"
        >
          {/* Presence drives data-state on the menu surface and defers unmount until the
              pop-out finishes. FocusScope `asChild` + DismissableLayer (forwardRef, spreads
              props) relay Presence's ref + data-state down onto the surface div. */}
          <Presence isPresent={open}>
            <FocusScope asChild trapped loop>
              <DismissableLayer
                role="menu"
                aria-label={ariaLabel}
                onEscape={onClose}
                onOutsidePointerDown={(e) => {
                  if (anchor?.contains(e.target as Node)) return;
                  onClose();
                }}
                className={cn(
                  surfaceVariants({
                    variant: variant ?? 'surface',
                    tone,
                    radius: radius ?? 'md',
                    padding: padding ?? 'xs',
                    elevation,
                  }),
                  menuVariants(),
                  'motion-safe:data-[state=open]:animate-(--animate-pop-in)',
                  'motion-safe:data-[state=closed]:animate-(--animate-pop-out)',
                  'motion-reduce:animate-none',
                  className,
                )}
                onKeyDown={(e) => {
                  onKeyDown?.(e);
                  if (e.defaultPrevented) return;
                  if (e.key === 'Tab') {
                    e.preventDefault();
                    onClose();
                  }
                }}
              >
                {children}
              </DismissableLayer>
            </FocusScope>
          </Presence>
        </AnchoredPositioner>
      </Portal>
    </MenuContext.Provider>
  );
}
MenuRoot.displayName = 'Menu';

export interface MenuItemProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'onSelect'>,
    MenuItemVariants {
  /** Fired when the item is activated (Enter / Space / click). Menu closes after. */
  onSelect?: () => void;
  /** Disable activation. */
  isDisabled?: boolean;
}

export const MenuItem = forwardRef<HTMLButtonElement, MenuItemProps>(function MenuItem(
  { onSelect, isDisabled = false, state, className, onClick, onKeyDown, children, ...rest },
  forwardedRef,
) {
  const ctx = useMenuContext();
  const id = useId();
  const ref = useRef<HTMLButtonElement | null>(null);

  useEffect(() => {
    ctx.registerItem({ id, ref: ref.current, disabled: isDisabled });
    return () => ctx.unregisterItem(id);
  }, [ctx, id, isDisabled]);

  const moveFocus = useCallback(
    (target: 1 | -1 | 'first' | 'last') => {
      const list = ctx.itemsRef.current.filter((i) => !i.disabled);
      if (list.length === 0) return;
      if (target === 'first' || target === 'last') {
        list[target === 'first' ? 0 : list.length - 1]?.ref?.focus();
        return;
      }
      const idx = list.findIndex((i) => i.id === id);
      let nextIdx = idx + target;
      if (idx === -1) nextIdx = target === 1 ? 0 : list.length - 1;
      if (nextIdx < 0) nextIdx = list.length - 1;
      if (nextIdx >= list.length) nextIdx = 0;
      list[nextIdx]?.ref?.focus();
    },
    [ctx, id],
  );

  const handleKeyDown = (e: KeyboardEvent<HTMLButtonElement>) => {
    onKeyDown?.(e);
    if (e.defaultPrevented || isDisabled) return;
    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault();
        moveFocus(1);
        break;
      case 'ArrowUp':
        e.preventDefault();
        moveFocus(-1);
        break;
      case 'Home':
        e.preventDefault();
        moveFocus('first');
        break;
      case 'End':
        e.preventDefault();
        moveFocus('last');
        break;
      case 'Enter':
      case ' ':
        e.preventDefault();
        onSelect?.();
        ctx.onClose();
        break;
    }
  };

  const itemState = state ?? (isDisabled ? 'disabled' : 'default');
  return (
    <button
      ref={composeRefs(forwardedRef, ref)}
      type="button"
      role="menuitem"
      disabled={isDisabled}
      aria-disabled={isDisabled || undefined}
      data-disabled={isDisabled ? '' : undefined}
      onClick={(e) => {
        onClick?.(e);
        if (e.defaultPrevented || isDisabled) return;
        onSelect?.();
        ctx.onClose();
      }}
      onKeyDown={handleKeyDown}
      className={cn(menuItemVariants({ state: itemState }), className)}
      {...rest}
    >
      {children}
    </button>
  );
});

export interface MenuGroupProps extends HTMLAttributes<HTMLDivElement> {
  label?: ReactNode;
  children: ReactNode;
}

export function MenuGroup({ label, children, className, ...rest }: MenuGroupProps) {
  const labelId = useId();
  return (
    <div
      role="group"
      aria-labelledby={label ? labelId : undefined}
      className={className}
      {...rest}
    >
      {label && (
        <div id={labelId} className={menuLabelVariants()}>
          {label}
        </div>
      )}
      {children}
    </div>
  );
}

export function MenuLabel({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLDivElement>) {
  return (
    <div className={cn(menuLabelVariants(), className)} {...rest}>
      {children}
    </div>
  );
}

export function MenuSeparator(props: HTMLAttributes<HTMLDivElement>) {
  return <div role="separator" className={menuSeparatorVariants()} {...props} />;
}

export const Menu = Object.assign(MenuRoot, {
  Item: MenuItem,
  Group: MenuGroup,
  Label: MenuLabel,
  Separator: MenuSeparator,
});

export default Menu;

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/nav/menu/Menu.vue
<script lang="ts">
import type { Placement } from '@floating-ui/vue';
import type {
  SurfaceElevation,
  SurfacePadding,
  SurfaceRadius,
  SurfaceTone,
  SurfaceVariant,
} from '../../../foundation/utils';

/**
 * Represents the prop surface of `Menu`.
 *
 * React declared the surface axes by `extends SurfaceVariants`; they are
 * spelled out here because the SFC compiler's type resolver cannot follow a
 * `VariantProps<typeof …>` base and fails the build on it. The aliases below
 * are the canonical ones from `foundation/utils`, already locked against the
 * `surfaceVariants` config there, so the two cannot drift. `placement` is
 * `Placement` for the same reason — React read it back off `AnchoredPositioner`
 * with an indexed access, which the resolver cannot follow either.
 *
 * The accessible label is *not* a prop: a declared `'aria-label'` arrives as
 * `props.ariaLabel` and never renders. It stays a fallthrough attr and lands on
 * the menu surface through `v-bind="rest"` below.
 */
export interface MenuProps {
  /** The open state, controlled. The React name; `isOpen` is the house spelling and `open` wins when both are set. */
  open?: boolean;

  /** The open state, controlled — the house spelling of `open`. */
  isOpen?: boolean;

  /** The element the surface anchors to. */
  anchor: HTMLElement | null;

  /** The Floating UI placement. Default `bottom-start`. */
  placement?: Placement;

  /** The distance between anchor and surface in px. Default 6. */
  offset?: number;

  /** The visual recipe. Default `surface`. */
  variant?: SurfaceVariant;

  /** The color tone the recipe is tinted with. */
  tone?: SurfaceTone;

  /** The corner rounding. Default `md`. */
  radius?: SurfaceRadius;

  /** The inner spacing step. Default `xs`. */
  padding?: SurfacePadding;

  /** The shadow depth. */
  elevation?: SurfaceElevation;
}
</script>

<script setup lang="ts">
import { computed, provide, useAttrs } from 'vue';
import { cn, surfaceVariants } from '../../../foundation/utils';
import {
  AnchoredPositioner,
  DismissableLayer,
  FocusScope,
  Portal,
  Presence,
} from '../../../foundation/primitives';
import { MenuKey, type MenuItemEntry } from './MenuContext';
import { menuVariants } from './Menu.variants';

/** The anchored, focus-trapped menu surface. */
defineOptions({ name: 'Menu', inheritAttrs: false });

/** The menu contents — `MenuItem` / `MenuGroup` / `MenuLabel` / `MenuSeparator`. React's `children`. */
defineSlots<{ default(): unknown }>();

/** `open` / `isOpen` default to `undefined` so an absent prop cannot read as an explicit `false`. */
const props = withDefaults(defineProps<MenuProps>(), {
  open: undefined,
  isOpen: undefined,
  placement: 'bottom-start',
  offset: 6,
  variant: undefined,
  tone: undefined,
  radius: undefined,
  padding: undefined,
  elevation: undefined,
});

const emit = defineEmits<{
  /** Replaces React's `onClose` — Escape, an outside pointerdown, Tab, or an item selection. */
  close: [];

  /**
   * Replaces React's `onKeyDown` — fires for every keydown on the menu container,
   * ahead of the menu's own Tab handling, so a wrapper (Menubar) can add navigation
   * and opt out with `preventDefault()`.
   */
  keydown: [event: KeyboardEvent];
}>();

const attrs = useAttrs();

const isMenuOpen = computed(() => props.open ?? props.isOpen ?? false);

/** The live item registry — a plain array, not reactive: the ordering is read imperatively. */
const items: Array<MenuItemEntry> = [];

function registerItem(entry: MenuItemEntry): void {
  const index = items.findIndex((i) => i.id === entry.id);
  if (index >= 0) items[index] = entry;
  else items.push(entry);
}

function unregisterItem(id: string): void {
  const index = items.findIndex((i) => i.id === id);
  if (index >= 0) items.splice(index, 1);
}

provide(MenuKey, { registerItem, unregisterItem, items, close: () => emit('close') });

const classes = computed(() =>
  cn(
    surfaceVariants({
      variant: props.variant ?? 'surface',
      tone: props.tone,
      radius: props.radius ?? 'md',
      padding: props.padding ?? 'xs',
      elevation: props.elevation,
    }),
    menuVariants(),
    'motion-safe:data-[state=open]:animate-(--animate-pop-in)',
    'motion-safe:data-[state=closed]:animate-(--animate-pop-out)',
    'motion-reduce:animate-none',
    attrs.class as string | undefined,
  ),
);

/** Everything but `class`, which is re-applied through `cn` above. Carries `aria-label` onto the surface. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

function handleEscape(): void {
  emit('close');
}

function handleOutsidePointerDown(event: PointerEvent): void {
  if (props.anchor?.contains(event.target as Node)) return;
  emit('close');
}

function handleKeydown(event: KeyboardEvent): void {
  emit('keydown', event);
  if (event.defaultPrevented) return;
  if (event.key === 'Tab') {
    event.preventDefault();
    emit('close');
  }
}
</script>

<template>
  <!-- No hard `v-if="isMenuOpen"` — Presence keeps the surface mounted through its
       pop-out exit, flipping data-state to "closed" and deferring unmount until the
       animation ends. `FocusScope as-child` relays Presence's cloned `ref` +
       `data-state` down onto the DismissableLayer's div, which *is* the surface. -->
  <Portal>
    <AnchoredPositioner
      :anchor="props.anchor"
      :placement="props.placement"
      :offset="props.offset"
      class="z-dropdown"
    >
      <Presence :is-present="isMenuOpen">
        <FocusScope as-child trapped loop>
          <DismissableLayer
            role="menu"
            :on-escape="handleEscape"
            :on-outside-pointer-down="handleOutsidePointerDown"
            v-bind="rest"
            :class="classes"
            @keydown="handleKeydown"
          >
            <slot />
          </DismissableLayer>
        </FocusScope>
      </Presence>
    </AnchoredPositioner>
  </Portal>
</template>
