// engineering/codebase/wow-two-front-beta-sdk/src/presentation/forms/formErrorMessage/FormErrorMessage.tsx
import { forwardRef, type ComponentPropsWithoutRef } from 'react';
import { cn } from '../../../foundation/utils';
import {
  useFormControl,
  useFormControlChrome,
} from '../../../foundation/primitives/formControlContext/FormControlContext';

export type FormErrorMessageProps = ComponentPropsWithoutRef<'p'>;

/**
 * Error copy under a form control. Renders only when the surrounding
 * `FormControl` is `isInvalid` AND there is something to show. `id={errorId}`
 * for `aria-describedby` wiring — the node registers itself with the context,
 * so controls reference the id only while the message actually renders.
 *
 * Without `children` it renders the context's `errors` (fed by the forms-engine
 * `form.Field` glue) — ALL of them, client + server merged. Pass `children` to
 * override with a single hand-written message.
 */
export const FormErrorMessage = forwardRef<HTMLParagraphElement, FormErrorMessageProps>(
  ({ className, id, children, ...props }, ref) => {
    const ctx = useFormControl();
    // Booleans/empty strings are render-nothing JSX (`{cond && 'msg'}`) — fall through to ctx errors.
    const hasChildren = children != null && children !== false && children !== '';
    const messages = hasChildren ? [] : (ctx?.errors ?? []);
    const isShown = (hasChildren || messages.length > 0) && (ctx ? ctx.isInvalid : true);
    // Register only while rendering under the context id — an explicit `id` prop
    // means the context's errorId is NOT in the DOM and must stay unreferenced.
    useFormControlChrome('error', isShown && id == null);
    if (!isShown) return null;
    return (
      <p
        ref={ref}
        id={id ?? ctx?.errorId}
        role="alert"
        className={cn('text-sm text-destructive', className)}
        {...props}
      >
        {hasChildren
          ? children
          : messages.length === 1
            ? messages[0]
            : messages.map((message, index) => (
                <span key={index} className="block">
                  {message}
                </span>
              ))}
      </p>
    );
  },
);
FormErrorMessage.displayName = 'FormErrorMessage';

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/forms/formErrorMessage/FormErrorMessage.vue
<script lang="ts">
export interface FormErrorMessageProps {
  /**
   * The node's own id. An explicit id detaches it from the context's `errorId`,
   * so the control's `aria-describedby` stops referencing it.
   */
  id?: string;

  /**
   * The single hand-written message — the scalar half of React's `children`.
   * Set it (or fill the default slot) to override the context's `errors`.
   */
  message?: string | number;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useSlots, useTemplateRef } from 'vue';
import type { ClassValue } from 'clsx';
import { cn } from '../../../foundation/utils';
import { useFormControl, useFormControlChrome } from '../../../foundation/primitives';

/**
 * Error copy under a form control. Renders only when the surrounding
 * `FormControl` is `isInvalid` AND there is something to show. `id={errorId}`
 * for `aria-describedby` wiring — the node registers itself with the context,
 * so controls reference the id only while the message actually renders.
 *
 * Without an override it renders the context's `errors` (fed by the forms-engine
 * `Field` glue) — ALL of them, client + server merged. Pass `message`, or fill
 * the default slot, to override with a single hand-written message.
 */
/* `inheritAttrs: false` so `class` folds into the component's own `cn()` call — plain fallthrough
   appends outside it and loses tailwind-merge conflict resolution. */
defineOptions({ name: 'FormErrorMessage', inheritAttrs: false });

const props = defineProps<FormErrorMessageProps>();

const attrs = useAttrs();
const slots = useSlots();

/* `ctx` is a live-getter object — read fields off it, never destructure. */
const ctx = useFormControl();

/* React tested `children != null && children !== false && children !== ''` because
   `{cond && 'msg'}` renders nothing; the Vue counterpart is an empty `message` or an
   absent slot, both of which must fall through to the context's errors. */
const hasChildren = computed(() => (props.message != null && props.message !== '') || Boolean(slots.default));

const messages = computed<readonly string[]>(() => (hasChildren.value ? [] : (ctx?.errors ?? [])));

const isShown = computed(() => (hasChildren.value || messages.value.length > 0) && (ctx ? ctx.isInvalid : true));

/* Register only while rendering under the context id — an explicit `id` prop
   means the context's errorId is NOT in the DOM and must stay unreferenced. */
useFormControlChrome('error', () => isShown.value && props.id == null);

const errorId = computed(() => props.id ?? ctx?.errorId);

const OWNED_ATTRS: ReadonlySet<string> = new Set(['class']);
const passthroughAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))),
);

const rootClass = computed(() => cn('text-sm text-destructive', attrs.class as ClassValue));

const root = useTemplateRef<HTMLParagraphElement>('root');

/** The rendered element — the Vue stand-in for the React original's forwarded ref. */
defineExpose({ el: root });
</script>

<template>
  <p v-if="isShown" ref="root" :id="errorId" role="alert" :class="rootClass" v-bind="passthroughAttrs">
    <template v-if="hasChildren">
      <slot>{{ message }}</slot>
    </template>
    <template v-else-if="messages.length === 1">{{ messages[0] }}</template>
    <template v-else>
      <span v-for="(entry, index) in messages" :key="index" class="block">{{ entry }}</span>
    </template>
  </p>
</template>
