// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/metricChip/MetricChip.vue
<script lang="ts">
/** Defines the MetricChip icon tint tone. */
export const MetricChipTone = {
  /** Refers to the neutral tint. */
  Neutral: 'neutral',
  /** Refers to the positive / confirmation tint. */
  Success: 'success',
  /** Refers to the caution tint. */
  Warning: 'warning',
  /** Refers to the destructive / error tint. */
  Danger: 'danger',
  /** Refers to the informational tint. */
  Info: 'info',
} as const;

export type MetricChipTone = (typeof MetricChipTone)[keyof typeof MetricChipTone];

/** Defines the MetricChip visual size. */
export const MetricChipSize = {
  /** Refers to the extra-small chip. */
  Xs: 'xs',
  /** Refers to the small chip. */
  Sm: 'sm',
  /** Refers to the medium chip. */
  Md: 'md',
} as const;

export type MetricChipSize = (typeof MetricChipSize)[keyof typeof MetricChipSize];

export interface MetricChipProps {
  /** The uppercase mini-LABEL rendered after the icon. Rich content goes through the `label` slot. */
  label: string | number;

  /** The value rendered after the label, tabular-nums. Rich content goes through the `value` slot. */
  value: string | number;

  /** The tone tinting for the icon. Default `neutral`. */
  tone?: MetricChipTone;

  /** The visual size — drives gap + text-size token. Default `sm`. */
  size?: MetricChipSize;
}

const TONE: Record<MetricChipTone, string> = {
  neutral: 'text-muted-foreground',
  success: 'text-success',
  warning: 'text-warning',
  danger: 'text-destructive',
  info: 'text-info',
};

const SIZE: Record<MetricChipSize, { wrapper: string; label: string; value: string }> = {
  xs: { wrapper: 'gap-1 text-[10px]', label: 'text-[10px]', value: 'text-xs' },
  sm: { wrapper: 'gap-1.5 text-xs', label: 'text-xs', value: 'text-xs' },
  md: { wrapper: 'gap-2 text-sm', label: 'text-xs', value: 'text-sm' },
};
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';

/**
 * Horizontal label-value chip with a leading tone-tinted icon and an
 * uppercase mini-LABEL. Used for stat strips. Distinct from `Stat` (large
 * KPI tile), `InfoRow` (justify-between two-column row), and `Status`
 * (dot+text). Renders inline-flex.
 */
defineOptions({ name: 'MetricChip', inheritAttrs: false });

defineSlots<{
  /** The optional leading icon (tone-tinted via the `tone` prop) — React's `icon` node prop. */
  icon?(): unknown;
  /** The rich override for the `label` prop. */
  label?(): unknown;
  /** The rich override for the `value` prop. */
  value?(): unknown;
}>();

const props = withDefaults(defineProps<MetricChipProps>(), {
  tone: 'neutral',
  size: 'sm',
});

const attrs = useAttrs();
const el = useTemplateRef<HTMLSpanElement>('el');

const size = computed(() => SIZE[props.size]);

const classes = computed(() =>
  cn('inline-flex items-center', size.value.wrapper, attrs.class as string | undefined),
);

const iconClasses = computed(() =>
  cn('inline-flex shrink-0 items-center', TONE[props.tone]),
);

const labelClasses = computed(() =>
  cn('font-medium uppercase tracking-wide text-muted-foreground', size.value.label),
);

const valueClasses = computed(() => cn('tabular-nums text-foreground', size.value.value));

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <span ref="el" v-bind="rest" :class="classes">
    <span v-if="$slots.icon" :class="iconClasses"><slot name="icon" /></span>
    <span :class="labelClasses"><slot name="label">{{ props.label }}</slot></span>
    <span :class="valueClasses"><slot name="value">{{ props.value }}</slot></span>
  </span>
</template>

// src/presentation/display/metricChip/MetricChip.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from 'react';
import { cn } from '../../../foundation/utils';

export interface MetricChipProps extends Omit<ComponentPropsWithoutRef<'span'>, 'children'> {
  /** Optional leading icon (tone-tinted via the `tone` prop). */
  icon?: ReactNode;
  /** Uppercase mini-LABEL rendered after the icon. */
  label: ReactNode;
  /** Value rendered after the label, tabular-nums. */
  value: ReactNode;
  /** Tone tinting for the icon. Default `neutral`. */
  tone?: 'neutral' | 'success' | 'warning' | 'danger' | 'info';
  /** Visual size — drives gap + text-size token. Default `sm`. */
  size?: 'xs' | 'sm' | 'md';
}

const TONE: Record<NonNullable<MetricChipProps['tone']>, string> = {
  neutral: 'text-muted-foreground',
  success: 'text-success',
  warning: 'text-warning',
  danger: 'text-destructive',
  info: 'text-info',
};

const SIZE: Record<
  NonNullable<MetricChipProps['size']>,
  { wrapper: string; label: string; value: string }
> = {
  xs: { wrapper: 'gap-1 text-[10px]', label: 'text-[10px]', value: 'text-xs' },
  sm: { wrapper: 'gap-1.5 text-xs', label: 'text-xs', value: 'text-xs' },
  md: { wrapper: 'gap-2 text-sm', label: 'text-xs', value: 'text-sm' },
};

/**
 * Horizontal label-value chip with a leading tone-tinted icon and an
 * uppercase mini-LABEL. Used for stat strips. Distinct from `Stat` (large
 * KPI tile), `InfoRow` (justify-between two-column row), and `Status`
 * (dot+text). Renders inline-flex.
 */
export const MetricChip = forwardRef<HTMLSpanElement, MetricChipProps>(
  ({ icon, label, value, tone = 'neutral', size = 'sm', className, ...props }, ref) => {
    const sz = SIZE[size];
    return (
      <span
        ref={ref}
        className={cn('inline-flex items-center', sz.wrapper, className)}
        {...props}
      >
        {icon && <span className={cn('inline-flex shrink-0 items-center', TONE[tone])}>{icon}</span>}
        <span className={cn('font-medium uppercase tracking-wide text-muted-foreground', sz.label)}>
          {label}
        </span>
        <span className={cn('tabular-nums text-foreground', sz.value)}>{value}</span>
      </span>
    );
  },
);
MetricChip.displayName = 'MetricChip';
