// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/forms/reactionPicker/ReactionPicker.vue
<script lang="ts">
import type { Size } from '../../../foundation/utils';

export interface ReactionPickerProps {
  /** The list of emoji shortcuts shown as quick-pick buttons. */
  emojis?: ReadonlyArray<string>;

  /** The currently active emoji keys (highlighted). */
  selected?: ReadonlyArray<string>;

  /**
   * Fires when the trailing "more" button is clicked (open full picker).
   *
   * Kept a PROP, not an emit: its presence is what renders the button at all, and Vue
   * strips a declared emit's listener out of `useAttrs()` — an emit could never be
   * detected, so the button would either always or never render.
   */
  onMore?: () => void;

  /** The hidden state for the trailing "more" button. */
  isMoreHidden?: boolean;

  /** The compact button size. */
  size?: Size;
}

const DEFAULT_REACTIONS = ['👍', '❤️', '😂', '🎉', '😮', '😢', '🚀'];

/* Sizes not listed fall back to the `md` row at the call site. */
const SIZE: Partial<Record<Size, string>> = {
  sm: 'h-7 w-7 text-base',
  md: 'h-8 w-8 text-lg',
};
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import type { ClassValue } from 'clsx';
import { Plus } from 'lucide-vue-next';
import { cn, Size as SizeValue } from '../../../foundation/utils';

/**
 * Quick-pick row of common emoji reactions. Pair with `overlays/Popover`
 * to surface as a hover/long-press affordance on a `ChatBubble`. Click
 * `+` to fall through to a fuller `forms/EmojiPicker`.
 */
/* `inheritAttrs: false` so `class` folds into the component's own `cn()` call — plain fallthrough
   appends outside it and loses tailwind-merge conflict resolution. */
defineOptions({ name: 'ReactionPicker', inheritAttrs: false });

const props = withDefaults(defineProps<ReactionPickerProps>(), {
  emojis: () => DEFAULT_REACTIONS,
  size: SizeValue.Md,
  /* Explicit `undefined` default: Vue casts an absent `boolean` prop to `false`, keeping the
     prop a genuine tri-state for consumers reading it. */
  isMoreHidden: undefined,
});

const emit = defineEmits<{
  /** Fires when an emoji is picked. Replaces React's `onSelect`. */
  select: [emoji: string];
}>();

const attrs = useAttrs();

function isActive(emoji: string): boolean {
  return props.selected?.includes(emoji) ?? false;
}

function emojiClass(emoji: string): string {
  return cn(
    'inline-flex items-center justify-center rounded-full leading-none transition-transform',
    'hover:scale-125 hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
    isActive(emoji) && 'bg-primary-soft',
    SIZE[props.size] ?? SIZE.md,
  );
}

const moreClass = computed(() =>
  cn(
    'inline-flex items-center justify-center rounded-full text-muted-foreground transition-colors',
    'hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
    SIZE[props.size],
  ),
);

const isMoreShown = computed(() => !props.isMoreHidden && Boolean(props.onMore));

const OWNED_ATTRS: ReadonlySet<string> = new Set(['class']);
const passthroughAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))),
);

const rootClass = computed(() =>
  cn(
    'inline-flex items-center gap-1 rounded-full border border-border bg-popover p-1 shadow-sm',
    attrs.class as ClassValue,
  ),
);

const root = useTemplateRef<HTMLDivElement>('root');

/** The rendered element — the Vue stand-in for the React original's forwarded ref. */
defineExpose({ el: root });
</script>

<template>
  <div ref="root" role="toolbar" aria-label="Reaction picker" :class="rootClass" v-bind="passthroughAttrs">
    <button
      v-for="emoji in emojis"
      :key="emoji"
      type="button"
      :data-active="isActive(emoji) ? '' : undefined"
      :aria-pressed="isActive(emoji)"
      :aria-label="`React with ${emoji}`"
      :class="emojiClass(emoji)"
      @click="emit('select', emoji)"
    >
      <span aria-hidden="true">{{ emoji }}</span>
    </button>
    <button v-if="isMoreShown" type="button" aria-label="More reactions" :class="moreClass" @click="props.onMore?.()">
      <Plus class="h-4 w-4" />
    </button>
  </div>
</template>

// src/presentation/forms/reactionPicker/ReactionPicker.tsx
import { forwardRef, type HTMLAttributes } from 'react';
import { Plus } from 'lucide-react';
import { cn } from '../../../foundation/utils';

export interface ReactionPickerProps extends Omit<HTMLAttributes<HTMLDivElement>, 'onSelect'> {
  /** List of emoji shortcuts shown as quick-pick buttons. */
  emojis?: string[];
  /** Currently active emoji keys (highlighted). */
  selected?: string[];
  /** Fires when an emoji is picked. */
  onSelect?: (emoji: string) => void;
  /** Fires when the trailing "more" button is clicked (open full picker). */
  onMore?: () => void;
  /** Hide the trailing "more" button. */
  isMoreHidden?: boolean;
  /** Compact button size. */
  size?: 'sm' | 'md';
}

const DEFAULT_REACTIONS = ['👍', '❤️', '😂', '🎉', '😮', '😢', '🚀'];

const SIZE: Record<NonNullable<ReactionPickerProps['size']>, string> = {
  sm: 'h-7 w-7 text-base',
  md: 'h-8 w-8 text-lg',
};

/**
 * Quick-pick row of common emoji reactions. Pair with `overlays/Popover`
 * to surface as a hover/long-press affordance on a `ChatBubble`. Click
 * `+` to fall through to a fuller `forms/EmojiPicker`.
 */
export const ReactionPicker = forwardRef<HTMLDivElement, ReactionPickerProps>(
  (
    {
      emojis = DEFAULT_REACTIONS,
      selected,
      onSelect,
      onMore,
      isMoreHidden,
      size = 'md',
      className,
      ...props
    },
    ref,
  ) => (
    <div
      ref={ref}
      role="toolbar"
      aria-label="Reaction picker"
      className={cn(
        'inline-flex items-center gap-1 rounded-full border border-border bg-popover p-1 shadow-sm',
        className,
      )}
      {...props}
    >
      {emojis.map((emoji) => {
        const active = selected?.includes(emoji);
        return (
          <button
            key={emoji}
            type="button"
            data-active={active ? '' : undefined}
            aria-pressed={active}
            aria-label={`React with ${emoji}`}
            onClick={() => onSelect?.(emoji)}
            className={cn(
              'inline-flex items-center justify-center rounded-full leading-none transition-transform',
              'hover:scale-125 hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
              active && 'bg-primary-soft',
              SIZE[size],
            )}
          >
            <span aria-hidden="true">{emoji}</span>
          </button>
        );
      })}
      {!isMoreHidden && onMore && (
        <button
          type="button"
          aria-label="More reactions"
          onClick={onMore}
          className={cn(
            'inline-flex items-center justify-center rounded-full text-muted-foreground transition-colors',
            'hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
            SIZE[size],
          )}
        >
          <Plus className="h-4 w-4" />
        </button>
      )}
    </div>
  ),
);
ReactionPicker.displayName = 'ReactionPicker';
