// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/layout/center/Center.vue
<script lang="ts">
import type { HTMLAttributes } from 'vue';

export type CenterProps = HTMLAttributes;
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';

/** Flex shorthand that centers its children both axes. */
/* `<center>` is a deprecated HTML element. This is a library component — imported,
   never globally registered — so the name cannot shadow the tag, and renaming it
   would break parity with the React package. */
defineOptions({ name: 'Center', inheritAttrs: false });

const attrs = useAttrs();
const el = useTemplateRef<HTMLDivElement>('el');

const classes = computed(() =>
  cn('flex items-center justify-center', attrs.class as string | undefined),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <div ref="el" v-bind="rest" :class="classes"><slot /></div>
</template>

// src/layout/center/Center.tsx
import { forwardRef, type ComponentPropsWithoutRef } from 'react';
import { cn } from '../../utils';

export type CenterProps = ComponentPropsWithoutRef<'div'>;

/** Flex shorthand that centers its children both axes. */
export const Center = forwardRef<HTMLDivElement, CenterProps>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={cn('flex items-center justify-center', className)}
      {...props}
    />
  ),
);
Center.displayName = 'Center';
