// src/forms/knob/Knob.tsx
import {
  forwardRef,
  useCallback,
  useRef,
  type HTMLAttributes,
  type KeyboardEvent,
  type PointerEvent as ReactPointerEvent,
  type ReactNode,
} from 'react';
import { cn } from '../../utils';
import { useControlled } from '../../hooks';

export type KnobTone = 'brand' | 'success' | 'warning' | 'danger' | 'muted';

const TONE_CLASS: Record<KnobTone, string> = {
  brand: 'text-primary',
  success: 'text-success',
  warning: 'text-warning',
  danger: 'text-destructive',
  muted: 'text-muted-foreground',
};

export interface KnobProps extends Omit<HTMLAttributes<HTMLDivElement>, 'defaultValue' | 'onChange'> {
  value?: number;
  defaultValue?: number;
  onValueChange?: (value: number) => void;
  min?: number;
  max?: number;
  step?: number;
  largeStep?: number;
  size?: number;
  arcDegrees?: number;
  tone?: KnobTone;
  format?: (value: number) => ReactNode;
  showValue?: boolean;
  disabled?: boolean;
  name?: string;
  'aria-label'?: string;
}

function clamp(v: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, v));
}

/**
 * Rotational dial input. Pointer drag rotates over `arcDegrees` (default 270°
 * from -135° to +135°). Wheel + arrow keys step; Home/End → min/max.
 */
export const Knob = forwardRef<HTMLDivElement, KnobProps>(function Knob(
  {
    value: valueProp,
    defaultValue,
    onValueChange,
    min = 0,
    max = 1,
    step = 0.01,
    largeStep = 0.1,
    size = 64,
    arcDegrees = 270,
    tone = 'brand',
    format = (v) => v.toFixed(2),
    showValue = true,
    disabled,
    name,
    className,
    'aria-label': ariaLabel = 'Knob',
    ...rest
  },
  ref,
) {
  const [value, setValue] = useControlled({
    controlled: valueProp,
    default: defaultValue ?? min,
    onChange: onValueChange,
  });
  const containerRef = useRef<HTMLDivElement | null>(null);
  const dragStateRef = useRef<{ startY: number; startValue: number } | null>(null);

  const fraction = (clamp(value, min, max) - min) / (max - min);
  const halfArc = arcDegrees / 2;
  const startAngle = -halfArc - 90; // -90 puts 0° at top
  const endAngle = halfArc - 90;
  const angle = startAngle + fraction * arcDegrees;

  const setClamped = useCallback(
    (v: number) => setValue(clamp(v, min, max)),
    [min, max, setValue],
  );

  const handlePointerDown = (e: ReactPointerEvent<HTMLDivElement>) => {
    if (disabled || e.button !== 0) return;
    dragStateRef.current = { startY: e.clientY, startValue: value };
    (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
  };

  const handlePointerMove = (e: ReactPointerEvent<HTMLDivElement>) => {
    if (disabled || !dragStateRef.current) return;
    const dy = dragStateRef.current.startY - e.clientY; // up = increase
    const range = max - min;
    const sensitivity = range / 200; // 200px drag = full range
    setClamped(dragStateRef.current.startValue + dy * sensitivity);
  };

  const handlePointerUp = (e: ReactPointerEvent<HTMLDivElement>) => {
    if (!dragStateRef.current) return;
    dragStateRef.current = null;
    (e.currentTarget as HTMLElement).releasePointerCapture?.(e.pointerId);
  };

  const handleWheel = (e: React.WheelEvent<HTMLDivElement>) => {
    if (disabled) return;
    e.preventDefault();
    const delta = e.deltaY < 0 ? step : -step;
    setClamped(value + delta);
  };

  const handleKey = (e: KeyboardEvent<HTMLDivElement>) => {
    if (disabled) return;
    const s = e.shiftKey ? largeStep : step;
    switch (e.key) {
      case 'ArrowUp':
      case 'ArrowRight':
        e.preventDefault();
        setClamped(value + s);
        break;
      case 'ArrowDown':
      case 'ArrowLeft':
        e.preventDefault();
        setClamped(value - s);
        break;
      case 'Home':
        e.preventDefault();
        setClamped(min);
        break;
      case 'End':
        e.preventDefault();
        setClamped(max);
        break;
    }
  };

  // SVG arc path math.
  const radius = size / 2 - 4;
  const center = size / 2;
  const polar = (deg: number, r: number) => {
    const rad = (deg * Math.PI) / 180;
    return [center + r * Math.cos(rad), center + r * Math.sin(rad)] as const;
  };
  const [trackStartX, trackStartY] = polar(startAngle, radius);
  const [trackEndX, trackEndY] = polar(endAngle, radius);
  const largeArc = arcDegrees > 180 ? 1 : 0;
  const trackPath = `M ${trackStartX} ${trackStartY} A ${radius} ${radius} 0 ${largeArc} 1 ${trackEndX} ${trackEndY}`;

  const [valueEndX, valueEndY] = polar(angle, radius);
  const valueLargeArc = fraction * arcDegrees > 180 ? 1 : 0;
  const valuePath = `M ${trackStartX} ${trackStartY} A ${radius} ${radius} 0 ${valueLargeArc} 1 ${valueEndX} ${valueEndY}`;

  const [pointerInnerX, pointerInnerY] = polar(angle, radius * 0.45);
  const [pointerOuterX, pointerOuterY] = polar(angle, radius * 0.85);

  return (
    <div
      ref={(el) => {
        containerRef.current = el;
        if (typeof ref === 'function') ref(el);
        else if (ref) (ref as React.MutableRefObject<HTMLDivElement | null>).current = el;
      }}
      role="slider"
      aria-label={ariaLabel}
      aria-valuenow={value}
      aria-valuemin={min}
      aria-valuemax={max}
      aria-orientation="vertical"
      aria-disabled={disabled || undefined}
      tabIndex={disabled ? -1 : 0}
      onPointerDown={handlePointerDown}
      onPointerMove={handlePointerMove}
      onPointerUp={handlePointerUp}
      onPointerCancel={handlePointerUp}
      onWheel={handleWheel}
      onKeyDown={handleKey}
      style={{ width: size, height: size, touchAction: 'none' }}
      className={cn(
        'relative inline-flex select-none items-center justify-center rounded-full focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
        TONE_CLASS[tone],
        disabled ? 'cursor-not-allowed opacity-50' : 'cursor-grab active:cursor-grabbing',
        className,
      )}
      {...rest}
    >
      <svg width={size} height={size} className="overflow-visible">
        <path
          d={trackPath}
          fill="none"
          stroke="currentColor"
          strokeWidth={4}
          strokeLinecap="round"
          className="opacity-20"
        />
        <path
          d={valuePath}
          fill="none"
          stroke="currentColor"
          strokeWidth={4}
          strokeLinecap="round"
        />
        <line
          x1={pointerInnerX}
          y1={pointerInnerY}
          x2={pointerOuterX}
          y2={pointerOuterY}
          stroke="currentColor"
          strokeWidth={2.5}
          strokeLinecap="round"
        />
      </svg>
      {showValue && (
        <span
          aria-hidden="true"
          className="absolute inset-0 grid place-items-center text-[10px] font-medium tabular-nums text-foreground"
        >
          {format(value)}
        </span>
      )}
      {name && <input type="hidden" name={name} value={value} />}
    </div>
  );
});

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/forms/knob/Knob.vue
<script lang="ts">
/** Defines the accent palette of a knob's value arc. */
export const KnobTone = {
  /** Refers to the primary brand accent. */
  Brand: 'brand',
  /** Refers to the positive/confirmation accent. */
  Success: 'success',
  /** Refers to the caution accent. */
  Warning: 'warning',
  /** Refers to the destructive/error accent. */
  Danger: 'danger',
  /** Refers to the muted/neutral accent. */
  Muted: 'muted',
} as const;

export type KnobTone = (typeof KnobTone)[keyof typeof KnobTone];

const TONE_CLASS: Record<KnobTone, string> = {
  brand: 'text-primary',
  success: 'text-success',
  warning: 'text-warning',
  danger: 'text-destructive',
  muted: 'text-muted-foreground',
};

export interface KnobProps {
  /** The value, controlled — React's spelling, which wins when both are set. */
  value?: number;

  /** The value, controlled. The `v-model` binding target. */
  modelValue?: number;

  /** The initial value when uncontrolled. Defaults to `min`. */
  defaultValue?: number;

  /** The lower bound. Default `0`. */
  min?: number;

  /** The upper bound. Default `1`. */
  max?: number;

  /** The arrow-key / wheel step. Default `0.01`. */
  step?: number;

  /** The Shift+arrow step. Default `0.1`. */
  largeStep?: number;

  /** The knob's pixel diameter. Default `64`. */
  size?: number;

  /** The sweep of the value arc in degrees. Default `270`. */
  arcDegrees?: number;

  /** The accent palette. Default `brand`. */
  tone?: KnobTone;

  /**
   * The readout formatter. Default `(v) => v.toFixed(2)`.
   *
   * Kept a PROP, not an emit: it RETURNS the rendered text, which an emit cannot do.
   */
  format?: (value: number) => string | number;

  /** Whether the formatted readout renders in the centre. Default `true`. */
  isValueShown?: boolean;

  /** The disabled state. Falls back to the surrounding form control's `isDisabled`. */
  isDisabled?: boolean;

  /** The hidden input name; the hidden input emits the numeric value. */
  name?: string;

  /** The control's id. Auto-filled from `FormControl` context when omitted. */
  id?: string;
}

function clamp(v: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, v));
}
</script>

<script setup lang="ts">
import { computed, ref, useAttrs, useTemplateRef } from 'vue';
import type { ClassValue } from 'clsx';
import { cn } from '../../../foundation/utils';
import { useControlled, useEventListener } from '../../../foundation/hooks';
import { useFormControl } from '../../../foundation/primitives';

/**
 * Rotational dial input. Pointer drag rotates over `arcDegrees` (default 270°
 * from -135° to +135°). Wheel + arrow keys step; Home/End → min/max.
 */
/* `inheritAttrs: false` so `class` folds into the root's own `cn()` call — plain fallthrough
   appends outside it and loses tailwind-merge conflict resolution. */
defineOptions({ name: 'Knob', inheritAttrs: false });

const props = withDefaults(defineProps<KnobProps>(), {
  min: 0,
  max: 1,
  step: 0.01,
  largeStep: 0.1,
  size: 64,
  arcDegrees: 270,
  tone: 'brand',
  format: (v: number) => v.toFixed(2),
  isValueShown: true,
  /* Explicit `undefined` defaults: `useControlled` keys on `=== undefined`, and Vue casts an
     absent `boolean` prop to `false` — which would shadow the form control context. */
  value: undefined,
  modelValue: undefined,
  defaultValue: undefined,
  isDisabled: undefined,
});

const emit = defineEmits<{
  /** The `v-model` half. */
  'update:modelValue': [value: number];
  /** Replaces React's `onValueChange`. */
  'value-change': [value: number];
}>();

const attrs = useAttrs();

const controlled = useControlled<number>({
  controlled: () => (props.value !== undefined ? props.value : props.modelValue),
  default: () => props.defaultValue ?? props.min,
  onChange: (next) => {
    emit('update:modelValue', next);
    emit('value-change', next);
  },
});

const current = controlled.value;

/* Inherits id/disabled/invalid/labelling from a surrounding <Field>; explicit props win. */
const ctx = useFormControl();
const disabled = computed(() => props.isDisabled ?? ctx?.isDisabled ?? false);

/* Never a declared prop — a declared `'aria-label'` would arrive as `props.ariaLabel`, so
   `props['aria-label']` is always undefined and no accessible name renders. */
const ariaLabel = computed(() => attrs['aria-label'] as string | undefined);
/* Names the knob from the Field label when present; an explicit aria-label always wins. */
const labelledBy = computed(() => (!ariaLabel.value ? ctx?.labelledBy : undefined));

const container = useTemplateRef<HTMLDivElement>('container');
const dragState = ref<{ startY: number; startValue: number } | null>(null);

const fraction = computed(() => (clamp(current.value, props.min, props.max) - props.min) / (props.max - props.min));
const halfArc = computed(() => props.arcDegrees / 2);
const startAngle = computed(() => -halfArc.value - 90); // -90 puts 0° at top
const endAngle = computed(() => halfArc.value - 90);
const angle = computed(() => startAngle.value + fraction.value * props.arcDegrees);

function setClamped(v: number): void {
  controlled.setValue(clamp(v, props.min, props.max));
}

function onPointerDown(event: PointerEvent): void {
  if (disabled.value || event.button !== 0) return;
  dragState.value = { startY: event.clientY, startValue: current.value };
  (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId);
}

function onPointerMove(event: PointerEvent): void {
  const drag = dragState.value;
  if (disabled.value || !drag) return;
  const dy = drag.startY - event.clientY; // up = increase
  const range = props.max - props.min;
  const sensitivity = range / 200; // 200px drag = full range
  setClamped(drag.startValue + dy * sensitivity);
}

function onPointerUp(event: PointerEvent): void {
  if (!dragState.value) return;
  dragState.value = null;
  (event.currentTarget as HTMLElement).releasePointerCapture?.(event.pointerId);
}

/* Wheel through a non-passive listener attached to the element — Vue's `@wheel` lands as a
   passive listener on some engines, and `preventDefault` inside it cannot stop the page scroll.
   `useEventListener` is post-flush and re-attaches when the ref resolves, so nothing here runs
   during SSR; the handler reads state live rather than capturing it. */
useEventListener(
  'wheel',
  (event) => {
    if (disabled.value) return;
    event.preventDefault();
    const delta = (event as WheelEvent).deltaY < 0 ? props.step : -props.step;
    setClamped(current.value + delta);
  },
  container,
  { passive: false },
);

function onKeydown(event: KeyboardEvent): void {
  if (disabled.value) return;
  const s = event.shiftKey ? props.largeStep : props.step;
  switch (event.key) {
    case 'ArrowUp':
    case 'ArrowRight':
      event.preventDefault();
      setClamped(current.value + s);
      break;
    case 'ArrowDown':
    case 'ArrowLeft':
      event.preventDefault();
      setClamped(current.value - s);
      break;
    case 'Home':
      event.preventDefault();
      setClamped(props.min);
      break;
    case 'End':
      event.preventDefault();
      setClamped(props.max);
      break;
  }
}

// SVG arc path math.
const radius = computed(() => props.size / 2 - 4);
const center = computed(() => props.size / 2);

function polar(deg: number, r: number): readonly [number, number] {
  const rad = (deg * Math.PI) / 180;
  return [center.value + r * Math.cos(rad), center.value + r * Math.sin(rad)] as const;
}

const trackStart = computed(() => polar(startAngle.value, radius.value));
const trackEnd = computed(() => polar(endAngle.value, radius.value));
const largeArc = computed(() => (props.arcDegrees > 180 ? 1 : 0));

const trackPath = computed(
  () =>
    `M ${trackStart.value[0]} ${trackStart.value[1]} A ${radius.value} ${radius.value} 0 ${largeArc.value} 1 ${trackEnd.value[0]} ${trackEnd.value[1]}`,
);

const valueEnd = computed(() => polar(angle.value, radius.value));
const valueLargeArc = computed(() => (fraction.value * props.arcDegrees > 180 ? 1 : 0));

const valuePath = computed(
  () =>
    `M ${trackStart.value[0]} ${trackStart.value[1]} A ${radius.value} ${radius.value} 0 ${valueLargeArc.value} 1 ${valueEnd.value[0]} ${valueEnd.value[1]}`,
);

const pointerInner = computed(() => polar(angle.value, radius.value * 0.45));
const pointerOuter = computed(() => polar(angle.value, radius.value * 0.85));

const knobId = computed(() => props.id ?? ctx?.id);
const readout = computed(() => props.format(current.value));

const OWNED_ATTRS: ReadonlySet<string> = new Set(['class']);
const passthroughAttrs = computed(() =>
  Object.fromEntries(Object.entries(attrs).filter(([key]) => !OWNED_ATTRS.has(key))),
);

const rootStyle = computed(() => ({
  width: `${props.size}px`,
  height: `${props.size}px`,
  touchAction: 'none',
}));

const rootClass = computed(() =>
  cn(
    'relative inline-flex select-none items-center justify-center rounded-full focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
    TONE_CLASS[props.tone],
    disabled.value ? 'cursor-not-allowed opacity-50' : 'cursor-grab active:cursor-grabbing',
    attrs.class as ClassValue,
  ),
);

/** The rendered root `<div>` — the Vue stand-in for the React original's forwarded ref. */
defineExpose({ el: container });
</script>

<template>
  <div
    ref="container"
    role="slider"
    :id="knobId"
    :aria-label="ariaLabel ?? (labelledBy ? undefined : 'Knob')"
    :aria-labelledby="labelledBy"
    :aria-valuenow="current"
    :aria-valuemin="min"
    :aria-valuemax="max"
    aria-orientation="vertical"
    :aria-invalid="ctx?.isInvalid || undefined"
    :aria-describedby="ctx?.describedBy"
    :aria-disabled="disabled || undefined"
    :tabindex="disabled ? -1 : 0"
    :style="rootStyle"
    :class="rootClass"
    v-bind="passthroughAttrs"
    @pointerdown="onPointerDown"
    @pointermove="onPointerMove"
    @pointerup="onPointerUp"
    @pointercancel="onPointerUp"
    @keydown="onKeydown"
  >
    <svg :width="size" :height="size" class="overflow-visible">
      <path
        :d="trackPath"
        fill="none"
        stroke="currentColor"
        :stroke-width="4"
        stroke-linecap="round"
        class="opacity-20"
      />
      <path :d="valuePath" fill="none" stroke="currentColor" :stroke-width="4" stroke-linecap="round" />
      <line
        :x1="pointerInner[0]"
        :y1="pointerInner[1]"
        :x2="pointerOuter[0]"
        :y2="pointerOuter[1]"
        stroke="currentColor"
        :stroke-width="2.5"
        stroke-linecap="round"
      />
    </svg>
    <span
      v-if="isValueShown"
      aria-hidden="true"
      class="absolute inset-0 grid place-items-center text-[10px] font-medium tabular-nums text-foreground"
    >
      {{ readout }}
    </span>
    <input v-if="name" type="hidden" :name="name" :value="current" />
  </div>
</template>
