// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/messageList/MessageList.vue
<script lang="ts">
/** The imperative surface exposed on a `MessageList` template ref. */
export interface MessageListHandle {
  scrollToBottom: (behavior?: ScrollBehavior) => void;
  isAtBottom: () => boolean;
}

export interface MessageListProps {
  /** The sticky auto-scroll mode — scrolls to bottom when children change *and* the viewer is near the bottom. Default true. */
  isSticky?: boolean;

  /** The threshold (px) considered "at bottom" for stickiness. Default 32. */
  bottomThreshold?: number;

  /** The floating "jump to bottom" button's visibility when scrolled away. Default true. */
  hasJumpToBottom?: boolean;

  /** The reversed render order (newest at top). v1 keeps natural top→bottom. */
  isReversed?: boolean;
}
</script>

<script setup lang="ts">
import {
  computed,
  onBeforeUnmount,
  onMounted,
  onUpdated,
  ref,
  useAttrs,
  useTemplateRef,
} from 'vue';
import { ChevronDown } from 'lucide-vue-next';
import { cn } from '../../../foundation/utils';

/**
 * Scrolling message stream with sticky auto-scroll and a jump-to-latest
 * affordance. Messages stay in the default slot — `MessageList` owns the
 * viewport, not the rows.
 *
 * React's `header` / `footer` were structural `ReactNode` props with no string
 * form worth keeping; they are slots only.
 */
defineOptions({ name: 'MessageList', inheritAttrs: false });

defineSlots<{
  /** The region above the message stream (e.g. "load older"). */
  header(): unknown;

  /** The message rows — React's required `children`. */
  default(): unknown;

  /** The region below the message stream (e.g. typing indicator). */
  footer(): unknown;
}>();

const props = withDefaults(defineProps<MessageListProps>(), {
  isSticky: true,
  bottomThreshold: 32,
  hasJumpToBottom: true,
  isReversed: undefined,
});

const attrs = useAttrs();
const el = useTemplateRef<HTMLDivElement>('el');
const scroller = useTemplateRef<HTMLDivElement>('scroller');

/**
 * Near-bottom state recorded *before* a new message commits (in the scroll
 * handler). Measuring inside the post-update hook would see the just-committed
 * message, so anything taller than `bottomThreshold` would defeat stickiness.
 * Plain `let`, not a `ref` — nothing renders off it, exactly like React's ref.
 */
let nearBottom = true;

const atBottom = ref(true);

const isNearBottom = (): boolean => {
  const node = scroller.value;
  if (!node) return true;
  return node.scrollHeight - node.clientHeight - node.scrollTop <= props.bottomThreshold;
};

const scrollToBottom = (behavior: ScrollBehavior = 'smooth'): void => {
  const node = scroller.value;
  if (!node) return;
  node.scrollTo({ top: node.scrollHeight, behavior });
};

const onScroll = (): void => {
  nearBottom = isNearBottom();
  atBottom.value = nearBottom;
};

/**
 * React ran the sticky scroll in a layout effect keyed on `children`, *before*
 * the effect that attached the listener — so the first paint lands at the
 * bottom while `nearBottom` is still its initial `true`. The mount order below
 * preserves that: scroll first, then attach and take the first measurement.
 */
onMounted(() => {
  if (props.isSticky && nearBottom) scrollToBottom('auto');
  const node = scroller.value;
  if (!node) return;
  node.addEventListener('scroll', onScroll, { passive: true });
  onScroll();
});

onBeforeUnmount(() => {
  scroller.value?.removeEventListener('scroll', onScroll);
});

/**
 * Stands in for React's `useLayoutEffect(…, [children])`. A slot's content is
 * not a reactive dependency Vue can watch, but any new message re-renders this
 * component, and `onUpdated` is the hook that fires after that commit.
 */
onUpdated(() => {
  if (props.isSticky && nearBottom) scrollToBottom('auto');
});

const classes = computed(() =>
  cn('relative flex h-full min-h-0 flex-col', attrs.class as string | undefined),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

/** React's `useImperativeHandle` surface (`MessageListHandle`), plus the root element. */
defineExpose({ el, scrollToBottom, isAtBottom: isNearBottom });
</script>

<template>
  <div ref="el" v-bind="rest" :class="classes">
    <div v-if="$slots.header" class="shrink-0"><slot name="header" /></div>
    <div
      ref="scroller"
      class="flex-1 min-h-0 overflow-y-auto px-3 py-3"
      role="log"
      aria-live="polite"
      aria-relevant="additions"
    >
      <div class="flex flex-col gap-2"><slot /></div>
    </div>
    <div v-if="$slots.footer" class="shrink-0 border-t border-border px-3 py-2">
      <slot name="footer" />
    </div>
    <button
      v-if="props.hasJumpToBottom && !atBottom"
      type="button"
      aria-label="Jump to latest"
      class="absolute bottom-3 right-3 inline-flex h-9 w-9 items-center justify-center rounded-full border border-border bg-background text-foreground shadow-md hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
      @click="scrollToBottom('smooth')"
    >
      <ChevronDown class="h-4 w-4" />
    </button>
  </div>
</template>

// src/presentation/display/messageList/MessageList.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useLayoutEffect,
  useRef,
  useState,
  type HTMLAttributes,
  type ReactNode,
} from 'react';
import { ChevronDown } from 'lucide-react';
import { cn } from '../../../foundation/utils';

export interface MessageListHandle {
  scrollToBottom: (behavior?: ScrollBehavior) => void;
  isAtBottom: () => boolean;
}

export interface MessageListProps extends HTMLAttributes<HTMLDivElement> {
  /** The slot rendered above the message stream (e.g. "load older"). */
  header?: ReactNode;

  /** The slot rendered below the message stream (e.g. typing indicator). */
  footer?: ReactNode;

  /** The sticky auto-scroll mode — scrolls to bottom when children change *and* the viewer is near the bottom. Default true. */
  isSticky?: boolean;

  /** The threshold (px) considered "at bottom" for stickiness. Default 32. */
  bottomThreshold?: number;

  /** The floating "jump to bottom" button's visibility when scrolled away. Default true. */
  hasJumpToBottom?: boolean;

  /** The reversed render order (newest at top). v1 keeps natural top→bottom. */
  isReversed?: boolean;
  children: ReactNode;
}

export interface DaySeparatorProps extends HTMLAttributes<HTMLDivElement> {
  /** The label (e.g. "Today", "Yesterday", "Mar 5"). */
  label: ReactNode;
}

export const DaySeparator = forwardRef<HTMLDivElement, DaySeparatorProps>(
  ({ label, className, ...props }, ref) => (
    <div
      ref={ref}
      role="separator"
      className={cn('flex items-center gap-3 py-2', className)}
      {...props}
    >
      <span className="h-px flex-1 bg-border" aria-hidden="true" />
      <span className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
        {label}
      </span>
      <span className="h-px flex-1 bg-border" aria-hidden="true" />
    </div>
  ),
);
DaySeparator.displayName = 'MessageList.DaySeparator';

const MessageListInner = forwardRef<MessageListHandle, MessageListProps>(
  (
    {
      header,
      footer,
      isSticky = true,
      bottomThreshold = 32,
      hasJumpToBottom = true,
      isReversed: _isReversed,
      children,
      className,
      ...props
    },
    ref,
  ) => {
    void _isReversed;
    const scrollerRef = useRef<HTMLDivElement | null>(null);
    // Near-bottom state recorded *before* a new message commits (in onScroll).
    // Measuring inside the layout effect would see the just-committed message,
    // so anything taller than bottomThreshold would defeat stickiness.
    const nearBottomRef = useRef(true);
    const [atBottom, setAtBottom] = useState(true);

    const isNearBottom = useCallback(() => {
      const el = scrollerRef.current;
      if (!el) return true;
      return el.scrollHeight - el.clientHeight - el.scrollTop <= bottomThreshold;
    }, [bottomThreshold]);

    const scrollToBottom = useCallback((behavior: ScrollBehavior = 'smooth') => {
      const el = scrollerRef.current;
      if (!el) return;
      el.scrollTo({ top: el.scrollHeight, behavior });
    }, []);

    useImperativeHandle(
      ref,
      () => ({ scrollToBottom, isAtBottom: isNearBottom }),
      [scrollToBottom, isNearBottom],
    );

    useLayoutEffect(() => {
      if (isSticky && nearBottomRef.current) scrollToBottom('auto');
    }, [children, isSticky, scrollToBottom]);

    useEffect(() => {
      const el = scrollerRef.current;
      if (!el) return;
      const onScroll = () => {
        nearBottomRef.current = isNearBottom();
        setAtBottom(nearBottomRef.current);
      };
      el.addEventListener('scroll', onScroll, { passive: true });
      onScroll();
      return () => el.removeEventListener('scroll', onScroll);
    }, [isNearBottom]);

    return (
      <div className={cn('relative flex h-full min-h-0 flex-col', className)} {...props}>
        {header && <div className="shrink-0">{header}</div>}
        <div
          ref={scrollerRef}
          className="flex-1 min-h-0 overflow-y-auto px-3 py-3"
          role="log"
          aria-live="polite"
          aria-relevant="additions"
        >
          <div className="flex flex-col gap-2">{children}</div>
        </div>
        {footer && <div className="shrink-0 border-t border-border px-3 py-2">{footer}</div>}
        {hasJumpToBottom && !atBottom && (
          <button
            type="button"
            onClick={() => scrollToBottom('smooth')}
            aria-label="Jump to latest"
            className={cn(
              'absolute bottom-3 right-3 inline-flex h-9 w-9 items-center justify-center rounded-full',
              'border border-border bg-background text-foreground shadow-md',
              'hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
            )}
          >
            <ChevronDown className="h-4 w-4" />
          </button>
        )}
      </div>
    );
  },
);
MessageListInner.displayName = 'MessageList';

type MessageListComponent = typeof MessageListInner & {
  DaySeparator: typeof DaySeparator;
};

export const MessageList = MessageListInner as MessageListComponent;
MessageList.DaySeparator = DaySeparator;

export default MessageList;
