// src/display/nodeEditor/NodeEditor.tsx
import {
  forwardRef,
  useCallback,
  useMemo,
  useRef,
  useState,
  type HTMLAttributes,
  type PointerEvent as ReactPointerEvent,
  type ReactNode,
} from 'react';
import { Maximize, Minus, Plus } from 'lucide-react';
import { cn } from '../../utils';
import { Icon } from '../../icons';

export interface NodeEditorNode {
  id: string;
  x: number;
  y: number;
  data?: Record<string, unknown>;
  label?: ReactNode;
}

export interface NodeEditorEdge {
  id: string;
  source: string;
  target: string;
  label?: ReactNode;
}

export interface NodeEditorProps extends HTMLAttributes<HTMLDivElement> {
  nodes: NodeEditorNode[];
  edges?: NodeEditorEdge[];
  onNodesChange?: (nodes: NodeEditorNode[]) => void;
  onEdgeClick?: (edge: NodeEditorEdge) => void;
  renderNode?: (node: NodeEditorNode) => ReactNode;
  nodeWidth?: number;
  nodeHeight?: number;
  minZoom?: number;
  maxZoom?: number;
}

interface Viewport {
  x: number;
  y: number;
  zoom: number;
}

/**
 * First-generation node graph editor. Drag nodes to reposition; pan the
 * viewport on background drag; wheel-zoom. Drag-to-connect ports + minimap
 * + auto-layout deferred.
 */
export const NodeEditor = forwardRef<HTMLDivElement, NodeEditorProps>(function NodeEditor(
  {
    nodes,
    edges = [],
    onNodesChange,
    onEdgeClick,
    renderNode,
    nodeWidth = 160,
    nodeHeight = 60,
    minZoom = 0.25,
    maxZoom = 2,
    className,
    ...rest
  },
  ref,
) {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const [viewport, setViewport] = useState<Viewport>({ x: 0, y: 0, zoom: 1 });
  const dragStateRef = useRef<
    | { kind: 'pan'; startX: number; startY: number; viewportX: number; viewportY: number }
    | { kind: 'node'; nodeId: string; startX: number; startY: number; nodeStartX: number; nodeStartY: number }
    | null
  >(null);

  const nodeIndex = useMemo(() => new Map(nodes.map((n) => [n.id, n])), [nodes]);

  const onContainerPointerDown = (e: ReactPointerEvent<HTMLDivElement>) => {
    if (e.button !== 0) return;
    if ((e.target as HTMLElement).closest('[data-node]')) return;
    dragStateRef.current = {
      kind: 'pan',
      startX: e.clientX,
      startY: e.clientY,
      viewportX: viewport.x,
      viewportY: viewport.y,
    };
    (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
  };

  const onContainerPointerMove = (e: ReactPointerEvent<HTMLDivElement>) => {
    const drag = dragStateRef.current;
    if (!drag) return;
    if (drag.kind === 'pan') {
      const dx = e.clientX - drag.startX;
      const dy = e.clientY - drag.startY;
      setViewport((v) => ({ ...v, x: drag.viewportX + dx, y: drag.viewportY + dy }));
    } else if (drag.kind === 'node') {
      const dx = (e.clientX - drag.startX) / viewport.zoom;
      const dy = (e.clientY - drag.startY) / viewport.zoom;
      const next = nodes.map((n) =>
        n.id === drag.nodeId ? { ...n, x: drag.nodeStartX + dx, y: drag.nodeStartY + dy } : n,
      );
      onNodesChange?.(next);
    }
  };

  const onContainerPointerUp = (e: ReactPointerEvent<HTMLDivElement>) => {
    dragStateRef.current = null;
    (e.currentTarget as HTMLElement).releasePointerCapture?.(e.pointerId);
  };

  const onWheel = useCallback(
    (e: React.WheelEvent<HTMLDivElement>) => {
      e.preventDefault();
      const rect = containerRef.current?.getBoundingClientRect();
      if (!rect) return;
      // Zoom centered on the cursor.
      const cx = e.clientX - rect.left;
      const cy = e.clientY - rect.top;
      const factor = e.deltaY < 0 ? 1.1 : 1 / 1.1;
      setViewport((v) => {
        const nextZoom = Math.max(minZoom, Math.min(maxZoom, v.zoom * factor));
        const ratio = nextZoom / v.zoom;
        return {
          zoom: nextZoom,
          x: cx - (cx - v.x) * ratio,
          y: cy - (cy - v.y) * ratio,
        };
      });
    },
    [minZoom, maxZoom],
  );

  const beginNodeDrag = (e: ReactPointerEvent<HTMLDivElement>, node: NodeEditorNode) => {
    e.stopPropagation();
    dragStateRef.current = {
      kind: 'node',
      nodeId: node.id,
      startX: e.clientX,
      startY: e.clientY,
      nodeStartX: node.x,
      nodeStartY: node.y,
    };
    (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
  };

  const fitView = () => {
    if (nodes.length === 0) {
      setViewport({ x: 0, y: 0, zoom: 1 });
      return;
    }
    const minX = Math.min(...nodes.map((n) => n.x));
    const minY = Math.min(...nodes.map((n) => n.y));
    const maxX = Math.max(...nodes.map((n) => n.x + nodeWidth));
    const maxY = Math.max(...nodes.map((n) => n.y + nodeHeight));
    const w = maxX - minX;
    const h = maxY - minY;
    const rect = containerRef.current?.getBoundingClientRect();
    if (!rect) return;
    const padding = 40;
    const zoomX = (rect.width - padding * 2) / w;
    const zoomY = (rect.height - padding * 2) / h;
    const zoom = Math.max(minZoom, Math.min(maxZoom, Math.min(zoomX, zoomY, 1)));
    setViewport({
      zoom,
      x: padding - minX * zoom + (rect.width - padding * 2 - w * zoom) / 2,
      y: padding - minY * zoom + (rect.height - padding * 2 - h * zoom) / 2,
    });
  };

  return (
    <div
      ref={(el) => {
        containerRef.current = el;
        if (typeof ref === 'function') ref(el);
        else if (ref) (ref as React.MutableRefObject<HTMLDivElement | null>).current = el;
      }}
      onPointerDown={onContainerPointerDown}
      onPointerMove={onContainerPointerMove}
      onPointerUp={onContainerPointerUp}
      onPointerCancel={onContainerPointerUp}
      onWheel={onWheel}
      className={cn(
        'relative h-96 w-full overflow-hidden rounded-md border border-border bg-muted/30 select-none',
        className,
      )}
      {...rest}
    >
      {/* Pan/zoom transform */}
      <div
        className="absolute inset-0 origin-top-left"
        style={{ transform: `translate(${viewport.x}px, ${viewport.y}px) scale(${viewport.zoom})` }}
      >
        <svg
          className="absolute pointer-events-none"
          style={{ overflow: 'visible', width: '100%', height: '100%' }}
        >
          {edges.map((edge) => {
            const a = nodeIndex.get(edge.source);
            const b = nodeIndex.get(edge.target);
            if (!a || !b) return null;
            const x1 = a.x + nodeWidth;
            const y1 = a.y + nodeHeight / 2;
            const x2 = b.x;
            const y2 = b.y + nodeHeight / 2;
            const mid = (x1 + x2) / 2;
            const path = `M${x1},${y1} C${mid},${y1} ${mid},${y2} ${x2},${y2}`;
            return (
              <g key={edge.id} className="pointer-events-auto cursor-pointer" onClick={() => onEdgeClick?.(edge)}>
                <path
                  d={path}
                  fill="none"
                  stroke="currentColor"
                  strokeWidth={2 / viewport.zoom}
                  className="text-border-strong hover:text-primary"
                />
                {edge.label && (
                  <text
                    x={mid}
                    y={(y1 + y2) / 2 - 6}
                    textAnchor="middle"
                    className="fill-muted-foreground text-[10px]"
                    style={{ fontSize: 10 / viewport.zoom }}
                  >
                    {edge.label}
                  </text>
                )}
              </g>
            );
          })}
        </svg>
        {nodes.map((node) => (
          <div
            key={node.id}
            data-node
            role="group"
            aria-label={typeof node.label === 'string' ? node.label : node.id}
            onPointerDown={(e) => beginNodeDrag(e, node)}
            style={{
              position: 'absolute',
              left: node.x,
              top: node.y,
              width: nodeWidth,
              height: nodeHeight,
            }}
            className="cursor-grab active:cursor-grabbing"
          >
            {renderNode ? (
              renderNode(node)
            ) : (
              <div className="flex h-full w-full items-center justify-center rounded-md border border-border bg-card px-3 text-sm font-medium shadow-sm">
                {node.label ?? node.id}
              </div>
            )}
          </div>
        ))}
      </div>
      {/* Controls */}
      <div className="absolute bottom-3 right-3 flex flex-col gap-1 rounded-md border border-border bg-card p-1 shadow-sm">
        <button
          type="button"
          aria-label="Zoom in"
          onClick={() =>
            setViewport((v) => ({ ...v, zoom: Math.min(maxZoom, v.zoom * 1.2) }))
          }
          className="inline-flex h-7 w-7 items-center justify-center rounded text-muted-foreground hover:bg-muted hover:text-foreground"
        >
          <Icon icon={Plus} size={14} />
        </button>
        <button
          type="button"
          aria-label="Zoom out"
          onClick={() =>
            setViewport((v) => ({ ...v, zoom: Math.max(minZoom, v.zoom / 1.2) }))
          }
          className="inline-flex h-7 w-7 items-center justify-center rounded text-muted-foreground hover:bg-muted hover:text-foreground"
        >
          <Icon icon={Minus} size={14} />
        </button>
        <button
          type="button"
          aria-label="Fit view"
          onClick={fitView}
          className="inline-flex h-7 w-7 items-center justify-center rounded text-muted-foreground hover:bg-muted hover:text-foreground"
        >
          <Icon icon={Maximize} size={12} />
        </button>
      </div>
    </div>
  );
});

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/nodeEditor/NodeEditor.vue
<script lang="ts">
export interface NodeEditorNode {
  id: string;
  x: number;
  y: number;
  data?: Record<string, unknown>;
  /**
   * The node caption. React took a `ReactNode`; a node is an array entry and
   * cannot become its own slot, so the scalar stays here and the `node` scoped
   * slot (React's `renderNode`) is the rich override.
   */
  label?: string | number;
}

export interface NodeEditorEdge {
  id: string;
  source: string;
  target: string;
  /** The edge caption, drawn as SVG `<text>` at the curve midpoint. */
  label?: string | number;
}

export interface NodeEditorProps {
  nodes: ReadonlyArray<NodeEditorNode>;
  edges?: ReadonlyArray<NodeEditorEdge>;
  /** The node box width in px. Default `160`. */
  nodeWidth?: number;
  /** The node box height in px. Default `60`. */
  nodeHeight?: number;
  /** The lower zoom bound. Default `0.25`. */
  minZoom?: number;
  /** The upper zoom bound. Default `2`. */
  maxZoom?: number;
}

interface Viewport {
  x: number;
  y: number;
  zoom: number;
}

type DragState =
  | { kind: 'pan'; startX: number; startY: number; viewportX: number; viewportY: number }
  | {
      kind: 'node';
      nodeId: string;
      startX: number;
      startY: number;
      nodeStartX: number;
      nodeStartY: number;
    }
  | null;
</script>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, useAttrs, useTemplateRef } from 'vue';
import { Maximize, Minus, Plus } from 'lucide-vue-next';
import { cn } from '../../../foundation/utils';
import { Icon } from '../../../foundation/icons';

/**
 * First-generation node graph editor. Drag nodes to reposition; pan the
 * viewport on background drag; wheel-zoom. Drag-to-connect ports + minimap
 * + auto-layout deferred.
 */
defineOptions({ name: 'NodeEditor', inheritAttrs: false });

const props = withDefaults(defineProps<NodeEditorProps>(), {
  edges: () => [],
  nodeWidth: 160,
  nodeHeight: 60,
  minZoom: 0.25,
  maxZoom: 2,
});

const emit = defineEmits<{
  /** Fires with the full node list after a drag moves one of them. */
  'nodes-change': [nodes: ReadonlyArray<NodeEditorNode>];
  /** Fires with the clicked edge. */
  'edge-click': [edge: NodeEditorEdge];
}>();

defineSlots<{
  /** Replaces a node's box. Falls back to the default card with its `label` / `id`. */
  node(props: { node: NodeEditorNode }): unknown;
}>();

const attrs = useAttrs();
const el = useTemplateRef<HTMLDivElement>('el');

const viewport = ref<Viewport>({ x: 0, y: 0, zoom: 1 });

/** Plain variable, not a ref — React held this in `useRef`; nothing renders off it. */
let dragState: DragState = null;

const nodeIndex = computed(() => new Map(props.nodes.map((node) => [node.id, node])));

function onContainerPointerDown(event: PointerEvent): void {
  if (event.button !== 0) return;
  if ((event.target as HTMLElement).closest('[data-node]')) return;
  dragState = {
    kind: 'pan',
    startX: event.clientX,
    startY: event.clientY,
    viewportX: viewport.value.x,
    viewportY: viewport.value.y,
  };
  (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId);
}

function onContainerPointerMove(event: PointerEvent): void {
  const drag = dragState;
  if (!drag) return;
  if (drag.kind === 'pan') {
    const dx = event.clientX - drag.startX;
    const dy = event.clientY - drag.startY;
    viewport.value = { ...viewport.value, x: drag.viewportX + dx, y: drag.viewportY + dy };
  } else {
    const dx = (event.clientX - drag.startX) / viewport.value.zoom;
    const dy = (event.clientY - drag.startY) / viewport.value.zoom;
    const next = props.nodes.map((node) =>
      node.id === drag.nodeId
        ? { ...node, x: drag.nodeStartX + dx, y: drag.nodeStartY + dy }
        : node,
    );
    emit('nodes-change', next);
  }
}

function onContainerPointerUp(event: PointerEvent): void {
  dragState = null;
  (event.currentTarget as HTMLElement).releasePointerCapture?.(event.pointerId);
}

// Wheel-zoom must be a non-passive native listener — a template `@wheel` binding
// is attached passively, so `preventDefault` inside it cannot stop the page from
// scrolling. Registered once and reading `minZoom` / `maxZoom` live, which is
// what React's `[minZoom, maxZoom]` dependency array re-registered for.
function onWheel(event: WheelEvent): void {
  const node = el.value;
  if (!node) return;
  event.preventDefault();
  const rect = node.getBoundingClientRect();
  // Zoom centered on the cursor.
  const cx = event.clientX - rect.left;
  const cy = event.clientY - rect.top;
  const factor = event.deltaY < 0 ? 1.1 : 1 / 1.1;
  const current = viewport.value;
  const nextZoom = Math.max(props.minZoom, Math.min(props.maxZoom, current.zoom * factor));
  const ratio = nextZoom / current.zoom;
  viewport.value = {
    zoom: nextZoom,
    x: cx - (cx - current.x) * ratio,
    y: cy - (cy - current.y) * ratio,
  };
}

onMounted(() => {
  el.value?.addEventListener('wheel', onWheel, { passive: false });
});

onBeforeUnmount(() => {
  el.value?.removeEventListener('wheel', onWheel);
});

function beginNodeDrag(event: PointerEvent, node: NodeEditorNode): void {
  event.stopPropagation();
  dragState = {
    kind: 'node',
    nodeId: node.id,
    startX: event.clientX,
    startY: event.clientY,
    nodeStartX: node.x,
    nodeStartY: node.y,
  };
  (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId);
}

function fitView(): void {
  if (props.nodes.length === 0) {
    viewport.value = { x: 0, y: 0, zoom: 1 };
    return;
  }
  const minX = Math.min(...props.nodes.map((node) => node.x));
  const minY = Math.min(...props.nodes.map((node) => node.y));
  const maxX = Math.max(...props.nodes.map((node) => node.x + props.nodeWidth));
  const maxY = Math.max(...props.nodes.map((node) => node.y + props.nodeHeight));
  const width = maxX - minX;
  const height = maxY - minY;
  const rect = el.value?.getBoundingClientRect();
  if (!rect) return;
  const padding = 40;
  const zoomX = (rect.width - padding * 2) / width;
  const zoomY = (rect.height - padding * 2) / height;
  const zoom = Math.max(props.minZoom, Math.min(props.maxZoom, Math.min(zoomX, zoomY, 1)));
  viewport.value = {
    zoom,
    x: padding - minX * zoom + (rect.width - padding * 2 - width * zoom) / 2,
    y: padding - minY * zoom + (rect.height - padding * 2 - height * zoom) / 2,
  };
}

function zoomIn(): void {
  viewport.value = {
    ...viewport.value,
    zoom: Math.min(props.maxZoom, viewport.value.zoom * 1.2),
  };
}

function zoomOut(): void {
  viewport.value = {
    ...viewport.value,
    zoom: Math.max(props.minZoom, viewport.value.zoom / 1.2),
  };
}

/** Edges resolved to a cubic path; endpoints that name a missing node are dropped. */
const renderEdges = computed(() =>
  props.edges.flatMap((edge) => {
    const a = nodeIndex.value.get(edge.source);
    const b = nodeIndex.value.get(edge.target);
    if (!a || !b) return [];
    const x1 = a.x + props.nodeWidth;
    const y1 = a.y + props.nodeHeight / 2;
    const x2 = b.x;
    const y2 = b.y + props.nodeHeight / 2;
    const mid = (x1 + x2) / 2;
    return [
      {
        edge,
        path: `M${x1},${y1} C${mid},${y1} ${mid},${y2} ${x2},${y2}`,
        labelX: mid,
        labelY: (y1 + y2) / 2 - 6,
      },
    ];
  }),
);

const strokeWidth = computed(() => 2 / viewport.value.zoom);

/** Vue does not append `px` to a numeric `:style` value the way React does — every length is spelled out. */
const edgeLabelStyle = computed(() => ({ fontSize: `${10 / viewport.value.zoom}px` }));

const transformStyle = computed(() => ({
  transform: `translate(${viewport.value.x}px, ${viewport.value.y}px) scale(${viewport.value.zoom})`,
}));

function nodeStyle(node: NodeEditorNode): Record<string, string> {
  return {
    position: 'absolute',
    left: `${node.x}px`,
    top: `${node.y}px`,
    width: `${props.nodeWidth}px`,
    height: `${props.nodeHeight}px`,
  };
}

const SVG_STYLE = { overflow: 'visible', width: '100%', height: '100%' } as const;

const classes = computed(() =>
  cn(
    'relative h-96 w-full overflow-hidden rounded-md border border-border bg-muted/30 select-none',
    attrs.class as string | undefined,
  ),
);

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <div
    ref="el"
    v-bind="rest"
    :class="classes"
    @pointerdown="onContainerPointerDown"
    @pointermove="onContainerPointerMove"
    @pointerup="onContainerPointerUp"
    @pointercancel="onContainerPointerUp"
  >
    <!-- Pan/zoom transform -->
    <div class="absolute inset-0 origin-top-left" :style="transformStyle">
      <svg class="absolute pointer-events-none" :style="SVG_STYLE">
        <g
          v-for="entry in renderEdges"
          :key="entry.edge.id"
          class="pointer-events-auto cursor-pointer"
          @click="emit('edge-click', entry.edge)"
        >
          <path
            :d="entry.path"
            fill="none"
            stroke="currentColor"
            :stroke-width="strokeWidth"
            class="text-border-strong hover:text-primary"
          />
          <text
            v-if="entry.edge.label"
            :x="entry.labelX"
            :y="entry.labelY"
            text-anchor="middle"
            class="fill-muted-foreground text-[10px]"
            :style="edgeLabelStyle"
          >
            {{ entry.edge.label }}
          </text>
        </g>
      </svg>
      <div
        v-for="node in nodes"
        :key="node.id"
        data-node="true"
        role="group"
        :aria-label="typeof node.label === 'string' ? node.label : node.id"
        :style="nodeStyle(node)"
        class="cursor-grab active:cursor-grabbing"
        @pointerdown="beginNodeDrag($event, node)"
      >
        <slot name="node" :node="node">
          <div
            class="flex h-full w-full items-center justify-center rounded-md border border-border bg-card px-3 text-sm font-medium shadow-sm"
          >
            {{ node.label ?? node.id }}
          </div>
        </slot>
      </div>
    </div>
    <!-- Controls -->
    <div
      class="absolute bottom-3 right-3 flex flex-col gap-1 rounded-md border border-border bg-card p-1 shadow-sm"
    >
      <button
        type="button"
        aria-label="Zoom in"
        class="inline-flex h-7 w-7 items-center justify-center rounded text-muted-foreground hover:bg-muted hover:text-foreground"
        @click="zoomIn"
      >
        <Icon :icon="Plus" :size="14" />
      </button>
      <button
        type="button"
        aria-label="Zoom out"
        class="inline-flex h-7 w-7 items-center justify-center rounded text-muted-foreground hover:bg-muted hover:text-foreground"
        @click="zoomOut"
      >
        <Icon :icon="Minus" :size="14" />
      </button>
      <button
        type="button"
        aria-label="Fit view"
        class="inline-flex h-7 w-7 items-center justify-center rounded text-muted-foreground hover:bg-muted hover:text-foreground"
        @click="fitView"
      >
        <Icon :icon="Maximize" :size="12" />
      </button>
    </div>
  </div>
</template>
