// src/overlays/actionSheet/ActionSheet.tsx
import {
  createContext,
  forwardRef,
  useContext,
  useMemo,
  type ButtonHTMLAttributes,
  type ReactNode,
} from 'react';
import { cn } from '../../utils';
import { useControlled } from '../../hooks';
import { Drawer, DrawerContent, DrawerDescription, DrawerTitle } from '../drawer';

interface ActionSheetContextValue {
  setOpen: (open: boolean) => void;
}

const ActionSheetContext = createContext<ActionSheetContextValue | null>(null);

function useActionSheetContext() {
  const ctx = useContext(ActionSheetContext);
  if (!ctx) throw new Error('ActionSheet.* must be used inside <ActionSheet>');
  return ctx;
}

export interface ActionSheetProps {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  title?: ReactNode;
  description?: ReactNode;
  className?: string;
  children: ReactNode;
}

/**
 * iOS-style action sheet — opinionated bottom Drawer with stacked button rows
 * and a separated Cancel.
 */
function ActionSheetRoot({
  open,
  defaultOpen,
  onOpenChange,
  title,
  description,
  className,
  children,
}: ActionSheetProps) {
  // ActionSheet owns open state + drives Drawer fully controlled, so `ctx.setOpen`
  // works in both controlled and uncontrolled modes (Drawer's context isn't interceptable).
  const [resolvedOpen, setOpen] = useControlled({
    controlled: open,
    default: defaultOpen ?? false,
    onChange: onOpenChange,
  });

  const ctx = useMemo<ActionSheetContextValue>(() => ({ setOpen }), [setOpen]);

  return (
    <ActionSheetContext.Provider value={ctx}>
      <Drawer open={resolvedOpen} onOpenChange={setOpen} side="bottom">
        <DrawerContent
          className={cn(
            'mx-auto max-w-md rounded-t-xl bg-card p-2 text-card-foreground',
            className,
          )}
        >
          {(title || description) && (
            <div className="px-3 py-2 text-center">
              {title && (
                <DrawerTitle className="text-sm font-medium text-muted-foreground">
                  {title}
                </DrawerTitle>
              )}
              {description && (
                <DrawerDescription className="mt-1 text-xs text-muted-foreground">
                  {description}
                </DrawerDescription>
              )}
            </div>
          )}
          <div className="flex flex-col gap-px overflow-hidden rounded-lg bg-border">
            {children}
          </div>
        </DrawerContent>
      </Drawer>
    </ActionSheetContext.Provider>
  );
}
ActionSheetRoot.displayName = 'ActionSheet';

export interface ActionSheetActionProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  onSelect?: () => void;
  isDestructive?: boolean;
}

export const ActionSheetAction = forwardRef<HTMLButtonElement, ActionSheetActionProps>(
  function ActionSheetAction(
    { className, onSelect, isDestructive, onClick, children, type = 'button', ...rest },
    ref,
  ) {
    const ctx = useActionSheetContext();
    return (
      <button
        ref={ref}
        type={type}
        onClick={(e) => {
          onClick?.(e);
          if (e.defaultPrevented) return;
          onSelect?.();
          ctx.setOpen(false);
        }}
        className={cn(
          'flex h-12 w-full items-center justify-center bg-card px-4 text-base font-medium transition-colors hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50',
          isDestructive ? 'text-destructive' : 'text-foreground',
          className,
        )}
        {...rest}
      >
        {children}
      </button>
    );
  },
);

export type ActionSheetCancelProps = ButtonHTMLAttributes<HTMLButtonElement>;

export const ActionSheetCancel = forwardRef<HTMLButtonElement, ActionSheetCancelProps>(
  function ActionSheetCancel({ className, onClick, children = 'Cancel', type = 'button', ...rest }, ref) {
    const ctx = useActionSheetContext();
    return (
      <button
        ref={ref}
        type={type}
        onClick={(e) => {
          onClick?.(e);
          if (e.defaultPrevented) return;
          ctx.setOpen(false);
        }}
        className={cn(
          'mt-2 flex h-12 w-full items-center justify-center rounded-lg bg-card text-base font-semibold text-foreground shadow-sm transition-colors hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
          className,
        )}
        {...rest}
      >
        {children}
      </button>
    );
  },
);

export const ActionSheet = Object.assign(ActionSheetRoot, {
  Action: ActionSheetAction,
  Cancel: ActionSheetCancel,
});

export default ActionSheet;

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/overlays/actionSheet/ActionSheet.vue
<script lang="ts">
import { inject, type InjectionKey } from 'vue';

/** The value shared with `ActionSheetAction` / `ActionSheetCancel`. */
export interface ActionSheetContextValue {
  setOpen: (open: boolean) => void;
}

export const actionSheetContextKey: InjectionKey<ActionSheetContextValue> = Symbol(
  'wow-two.actionSheet',
);

export function useActionSheetContext(): ActionSheetContextValue {
  const context = inject(actionSheetContextKey, null);
  if (!context) throw new Error('ActionSheet.* must be used inside <ActionSheet>');
  return context;
}

/**
 * The prop surface of `ActionSheet`.
 *
 * React's `title` / `description` were `ReactNode`; they are `string` props here
 * with matching named slots for rich content. React's `className` is the `class`
 * attr, forwarded to the panel exactly as React forwarded it.
 */
export interface ActionSheetProps {
  /** The open state, controlled. The `v-model:open` binding target. */
  open?: boolean;

  /** The open state, controlled — the house spelling of `open`; `open` wins when both are set. */
  isOpen?: boolean;

  /** The initial open state when uncontrolled. Default `false`. */
  defaultOpen?: boolean;

  /** The heading above the action rows. Use the `title` slot for rich content. */
  title?: string;

  /** The supporting line under the heading. Use the `description` slot for rich content. */
  description?: string;
}
</script>

<script setup lang="ts">
import { computed, provide, useAttrs, useSlots } from 'vue';
import { cn } from '../../../foundation/utils';
import { useControlled } from '../../../foundation/hooks';
import Drawer from '../drawer/Drawer.vue';
import DrawerContent from '../drawer/DrawerContent.vue';
import OverlayTitle from '../OverlayTitle.vue';
import OverlayDescription from '../OverlayDescription.vue';

/**
 * iOS-style action sheet — opinionated bottom Drawer with stacked button rows
 * and a separated Cancel.
 */
defineOptions({ name: 'ActionSheet', inheritAttrs: false });

defineSlots<{
  /** The action rows — `ActionSheetAction` / `ActionSheetCancel`. React's `children`. */
  default(): unknown;
  /** The heading, when it is richer than the `title` string prop. */
  title?(): unknown;
  /** The supporting line, when it is richer than the `description` string prop. */
  description?(): unknown;
}>();

/** `open` / `isOpen` / the node-ish props default to `undefined` so an absent prop cannot read as a set one. */
const props = withDefaults(defineProps<ActionSheetProps>(), {
  open: undefined,
  isOpen: undefined,
  defaultOpen: false,
  title: undefined,
  description: undefined,
});

const emit = defineEmits<{
  /** The `v-model:open` half. */
  'update:open': [open: boolean];
  /** Replaces React's `onOpenChange`. */
  'open-change': [open: boolean];
}>();

const attrs = useAttrs();
const slots = useSlots();

/*
 * ActionSheet owns open state and drives Drawer fully controlled, so `setOpen`
 * works in both controlled and uncontrolled modes (Drawer's context isn't
 * interceptable).
 */
const controlled = useControlled<boolean>({
  controlled: () => (props.open !== undefined ? props.open : props.isOpen),
  default: () => props.defaultOpen,
  onChange: (value) => {
    emit('update:open', value);
    emit('open-change', value);
  },
});

const resolvedOpen = controlled.value;

provide(actionSheetContextKey, { setOpen: controlled.setValue });

const hasTitle = computed(() => props.title !== undefined || slots.title !== undefined);
const hasDescription = computed(
  () => props.description !== undefined || slots.description !== undefined,
);

const classes = computed(() =>
  cn(
    'mx-auto max-w-md rounded-t-xl bg-card p-2 text-card-foreground',
    attrs.class as string | undefined,
  ),
);
</script>

<template>
  <Drawer :open="resolvedOpen" side="bottom" @open-change="controlled.setValue">
    <DrawerContent :class="classes">
      <div v-if="hasTitle || hasDescription" class="px-3 py-2 text-center">
        <OverlayTitle v-if="hasTitle" class="text-sm font-medium text-muted-foreground">
          <slot name="title">{{ props.title }}</slot>
        </OverlayTitle>
        <OverlayDescription
          v-if="hasDescription"
          class="mt-1 text-xs text-muted-foreground"
        >
          <slot name="description">{{ props.description }}</slot>
        </OverlayDescription>
      </div>
      <div class="flex flex-col gap-px overflow-hidden rounded-lg bg-border">
        <slot />
      </div>
    </DrawerContent>
  </Drawer>
</template>
