// src/presentation/display/stepCard/StepCard.tsx
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from 'react';
import { cn } from '../../../foundation/utils';
import { Card } from '../card/Card';
import { Heading } from '../heading/Heading';
import { Text } from '../text/Text';

export interface StepCardProps extends Omit<ComponentPropsWithoutRef<'div'>, 'title'> {
  /** The step number — rendered as a large faint overlay top-right. */
  step: number;

  /** The icon node rendered inside a tinted badge (`bg-primary-soft text-primary`). Size it yourself. */
  icon?: ReactNode;

  /** The step title. */
  title: ReactNode;

  /** The optional supporting copy below the title. Falls back to `children` when omitted. */
  description?: ReactNode;

  /** The body content — used when `description` is not provided. */
  children?: ReactNode;
}

/**
 * Numbered "how it works" step — large faint step number overlay + tinted icon
 * badge + title + description. Outlined card; content-only (no baked routing).
 */
export const StepCard = forwardRef<HTMLDivElement, StepCardProps>(
  ({ step, icon, title, description, children, className, ...props }, ref) => (
    <Card
      ref={ref}
      variant="outline"
      radius="xl"
      elevation={0}
      className={cn('relative overflow-hidden bg-card p-6', className)}
      {...props}
    >
      <span className="absolute right-4 top-3 text-5xl font-bold text-foreground/5">{step}</span>
      {icon && (
        <span className="grid size-11 place-items-center rounded-lg bg-primary-soft text-primary">
          {icon}
        </span>
      )}
      <Heading level={3} size="md" className={cn('tracking-normal', icon && 'mt-4')}>
        {title}
      </Heading>
      {(description ?? children) && (
        <Text size="sm" color="muted" className="mt-2">
          {description ?? children}
        </Text>
      )}
    </Card>
  ),
);
StepCard.displayName = 'StepCard';

// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/display/stepCard/StepCard.vue
<script lang="ts">
export interface StepCardProps {
  /** The step number — rendered as a large faint overlay top-right. */
  step: number;

  /**
   * The step title. React typed this `ReactNode`; a scalar stays a prop so it
   * remains the discriminator, and the same-named slot is the rich override.
   */
  title: string | number;

  /** The optional supporting copy below the title. Falls back to the default slot when omitted. */
  description?: string | number;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useSlots, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';
import Card from '../card/Card.vue';
import Heading from '../heading/Heading.vue';
import Text from '../text/Text.vue';

/**
 * Numbered "how it works" step — large faint step number overlay + tinted icon
 * badge + title + description. Outlined card; content-only (no baked routing).
 */
defineOptions({ name: 'StepCard', inheritAttrs: false });

/**
 * React's `icon` was a structural `ReactNode` prop — a region with no prop
 * equivalent in Vue, so it becomes a slot. `title` / `description` stay props
 * (scalars) with a same-named slot as the rich override; the default slot is
 * the body fallback React spelled `description ?? children`.
 */
defineSlots<{
  /** The icon node rendered inside a tinted badge (`bg-primary-soft text-primary`). Size it yourself. */
  icon(): unknown;
  /** The step title — overrides the `title` prop's rendering. */
  title(): unknown;
  /** The supporting copy — overrides the `description` prop's rendering. */
  description(): unknown;
  /** The body content — used when neither `description` nor its slot is provided. */
  default(): unknown;
}>();

const props = withDefaults(defineProps<StepCardProps>(), { description: undefined });

const attrs = useAttrs();
const slots = useSlots();
const el = useTemplateRef<InstanceType<typeof Card>>('el');

const hasBody = computed(
  () => props.description !== undefined || !!slots.description || !!slots.default,
);

const classes = computed(() =>
  cn('relative overflow-hidden bg-card p-6', attrs.class as string | undefined),
);

const headingClasses = computed(() => cn('tracking-normal', !!slots.icon && 'mt-4'));

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <Card ref="el" variant="outline" radius="xl" :elevation="0" v-bind="rest" :class="classes">
    <span class="absolute right-4 top-3 text-5xl font-bold text-foreground/5">{{ props.step }}</span>
    <span
      v-if="$slots.icon"
      class="grid size-11 place-items-center rounded-lg bg-primary-soft text-primary"
    >
      <slot name="icon" />
    </span>
    <Heading :level="3" size="md" :class="headingClasses">
      <slot name="title">{{ props.title }}</slot>
    </Heading>
    <Text v-if="hasBody" size="sm" color="muted" class="mt-2">
      <slot name="description">
        <template v-if="props.description !== undefined">{{ props.description }}</template>
        <slot v-else />
      </slot>
    </Text>
  </Card>
</template>
