// engineering/codebase/wow-two-front-vue-beta-sdk/src/presentation/layout/container/Container.vue
<script lang="ts">
import type { ElementType } from '../../../foundation/utils';
import type { ContainerSize } from './Container.variants';

export interface ContainerProps {
  as?: ElementType;
  /** The max-width preset. Default `lg`. */
  size?: ContainerSize;
}
</script>

<script setup lang="ts">
import { computed, useAttrs, useTemplateRef } from 'vue';
import { cn } from '../../../foundation/utils';
import { containerVariants } from './Container.variants';

/**
 * Centered max-width wrapper with horizontal padding. Use at page-level to
 * constrain content width.
 */
defineOptions({ name: 'Container', inheritAttrs: false });

const props = withDefaults(defineProps<ContainerProps>(), { as: 'div' });

const attrs = useAttrs();
const el = useTemplateRef<HTMLElement>('el');

const classes = computed(() => cn(containerVariants({ size: props.size }), attrs.class as string | undefined));

/** Everything but `class`, which is re-applied through `cn` above. */
const rest = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

defineExpose({ el });
</script>

<template>
  <component :is="props.as" ref="el" v-bind="rest" :class="classes"><slot /></component>
</template>

// src/layout/container/Container.tsx
import {
  forwardRef,
  type ComponentPropsWithoutRef,
  type ElementType,
  type Ref,
} from 'react';
import { cn } from '../../utils';
import { containerVariants, type ContainerVariants } from './Container.variants';

export interface ContainerProps
  extends Omit<ComponentPropsWithoutRef<'div'>, 'as'>,
    ContainerVariants {
  as?: ElementType;
}

/**
 * Centered max-width wrapper with horizontal padding. Use at page-level to
 * constrain content width.
 */
export const Container = forwardRef<HTMLElement, ContainerProps>(
  ({ as: Component = 'div', className, size, ...props }, ref) => (
    <Component
      ref={ref as Ref<HTMLElement>}
      className={cn(containerVariants({ size }), className)}
      {...props}
    />
  ),
);
Container.displayName = 'Container';
